### ISSUE TITLE
Ventus W132

### ISSUE THREAD

**Issue by df7nf** [merbanan/rtl_433#1008]
Hello,

i use your Programm to record the Ventus W132 Speedsensor Data.
It works but can i change the time between recieving data. Actually the period is round about 30Seconds. But i will use it on an raspberry on my sailing boot, so i try to get faster informations about windspeed and direction - less then 30Seconds. 

How can i refresh data faster?

Thank you for your help

**Comment by merbanan** [comment]
Not possible I would guess. There are limits on how much air time you can use on the ISM bands. Anyway this does not matter for rtl_433, it will decode as often as there is a signal transmitted. Ask the manufacturer of the device or seller.

**Comment by df7nf** [comment]
okay thanks
