### ISSUE TITLE
Help Decoding TS-FT 002 water level sensor

### ISSUE THREAD

**Issue by effort10** [merbanan/rtl_433#1011]
Good Day,

I am struggling to get the binary data for this hex string.
I have ran the below command:

rtl_433 -A -a -X "n=name,m=OOK_PPM,s=464,l=948,g=956,r=956" -Mbits

![image](https://user-images.githubusercontent.com/48510263/54473362-984d6980-47df-11e9-98a0-5e207f7df1ab.png)

Please could someone help me, do i need to use an Oscillator to get the correct flex decoder paramaters?

Thank you

**Comment by zuckschwerdt** [comment]
The code is in #1025 -- please test.
