### ISSUE TITLE
Honeywell 5890PI motion sensor

### ISSUE THREAD

**Issue by fanlessfan** [merbanan/rtl_433#1012]
Hello,

I am wondering the Honeywell 5890PI motion sensor is supported or not. I can receive/decode Honeywell window/door sensor 5816. Here is the link to 5890. 

http://library.ademconet.com/MWT/fs2/5890PI/5890PI-Data-Sheet.PDF

Thx

**Comment by merbanan** [comment]
Most likely, one of the protocol decoders for Honeywell mentions PIR sensors.

https://github.com/merbanan/rtl_433/blob/master/src/devices/honeywell_wdb.c

But as always no guarantees. Try and report back if it works or not.

**Comment by fanlessfan** [comment]
Hi @merbanan ,

Thank you for your fantastic work. I will compile and try the latest.

**Comment by pbendersky** [comment]
@fanlessfan are you able to decode those sensors? Do you know what frequency should I use?

**Comment by zuckschwerdt** [comment]
see #1013
