### ISSUE TITLE
Segmentation fault with -S option without argument

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1027]
### Version

rtl_433 version 18.12-175-g897f9db branch master at 201903290959 inputs file rtl_tcp RTL-SDR

### Expected behaviour

Graceful shutdown with an error message explaining what I did wrong.

### Actual behaviour

```
user@homeserver:~/$ rtl_433 -S
rtl_433 version 18.12-175-g897f9db branch master at 201903290959 inputs file rtl_tcp RTL-SDR
rtl_433: option requires an argument -- 'S'
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/pi/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl_433: option requires an argument -- 'S'
Segmentation fault
```

Not sure what causes this but it's reproducible on both my main machine and on my raspberry pi 1.

**Comment by zuckschwerdt** [comment]
Thanks, fixed with 4256075 now.
