### ISSUE TITLE
Streamline sensor id keys

### ISSUE THREAD

**Issue by helgew** [merbanan/rtl_433#1032]
Related to https://github.com/merbanan/rtl_433/pull/986, I noticed that many sensors report IDs in some form or the other. However, the keys for those IDs are a mix of "sensor_id", "id", "device", etc.

I am happy to tackle this in my ample spare time, but wanted to first elicit some feedback on whether a) it should be done, and b) what the best approach should be?

For b) `_X("sensor_id", "id")` seems to be the obvious answer.

**Comment by zuckschwerdt** [comment]
It should be `_X("id","device")` so users can switch that mit newmodel. I think I already looked for those id-like keys. Maybe I missed some?
