### ISSUE TITLE
how to know the details of the cpatured signals

### ISSUE THREAD

**Issue by sidhu037** [merbanan/rtl_433#1039]
Hi,

I am using RTL-SDR and I was able to capture few signals. Let me know how I can know the detail about the signal I am capturing. Is there any specific command for it.

**Comment by merbanan** [comment]
Use -A to invoke the analyzer. It will tell you alot about the signal. And then you can use tests/sigrok-open.sh to get a good visualization.

**Comment by sidhu037** [comment]
hi,
Could you please let me know how i can execute the sigrok-open.sh. while executing I am going through this error. I have edited the .sh file and added the destination of my captured signal.
![test](https://user-images.githubusercontent.com/46221606/55683041-a9aa1180-5958-11e9-9d47-5a424b996c12.png).

**Comment by merbanan** [comment]
You need to install sigrok also. Then you just use tests/sigrok-open.sh gfile.cu8 and it should be fine.

**Comment by zuckschwerdt** [comment]
also no `sudo` needed.

@merbanan in current master the sigrok-*.sh moved to examples with all the other scripts.

**Comment by sidhu037** [comment]
Thank You
