### ISSUE TITLE
Honda remote triggers on long preamble

### ISSUE THREAD

**Issue by merbanan** [merbanan/rtl_433#1041]
I am getting lots of the following messages:

model     : Honda Remote device id : 65535         code      : unknown

This is caused by weak rejection logic.
[g086_868.8M_1000k.cu8.zip](https://github.com/merbanan/rtl_433/files/3051971/g086_868.8M_1000k.cu8.zip)

**Comment by zuckschwerdt** [comment]
I don't think anybody would mind if we default disable this. Shall I?

**Comment by merbanan** [comment]
Sure

**Comment by zuckschwerdt** [comment]
Addressed with 0974aca.
