### ISSUE TITLE
Incorrect text field in MQTT option parsing

### ISSUE THREAD

**Issue by aabaker** [merbanan/rtl_433#1074]
In src/r_api.c, line 806 it says "Publishing MQTT UDP datagrams to %s port %s\n"

By default it uses TCP (it looks as though mongoose will send it as UDP if the hostname is prefixed with udp:// but it isn't obvious if it will actually be sending MQTT-SN in that case as plain MQTT over UDP doesn't appear to be standardised)

I think the fix is just to remove the text "UDP datagrams " unless there is some reason UDP is mentioned.

**Comment by zuckschwerdt** [comment]
Yeah, that's an copy and paste error I made. Thanks, fixed with e5a6083.
