### ISSUE TITLE
Change receiver / tuner (DVB-T stick or 433MHz Receiver)

### ISSUE THREAD

**Issue by matthiaaas** [merbanan/rtl_433#1084]
I have an USB DVB-T stick and a simple 433MHz Receiver via GPIO connected to my Raspberry Pi.
The 433MHz Receiver is already in use, so I want rtl_433 to select my DVB-T stick instead.
But the program is trying to get data from the Receiver by default.
So my question: How to change the input device?

Thank you in advance!

**Comment by zuckschwerdt** [comment]
rtl_433 has no input driver for GPIO. There must be another reason RTL-SDR isn't selected. Paste your full output here, please.

**Comment by zuckschwerdt** [comment]
Closing as this is likely not an issue we need to track. Feel free to continue this issue, we just don't need to track progress ;)
