### ISSUE TITLE
undefined reference to `template' 

### ISSUE THREAD

**Issue by fme34** [merbanan/rtl_433#1100]
Hi Falks,
Looking for help on compiling rtl_433 on Rapsberry Pi 3b+ running Raspbian Buster fresh install. I got the following error at make step:

/usr/bin/ld: rtl_433.o: in function `main':
/home/pi/rtl_433/src/rtl_433.c:1120: undefined reference to `template'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:931: rtl_433] Error 1
make[2]: Leaving directory '/home/pi/rtl_433/src'
make[1]: *** [Makefile:497: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/rtl_433'
make: *** [Makefile:383: all] Error 2

Any Idea ?
Regards

**Comment by zuckschwerdt** [comment]
Yes, sorry, the last commit was incomplete. Please `git reset --hard HEAD^ ; git pull`

**Comment by fme34** [comment]
Worked, thanks !!
