### ISSUE TITLE
CurrentCost EnviR Help

### ISSUE THREAD

**Issue by neilco** [merbanan/rtl_433#1104]
I've started looking into adding support for the CurrentCost EnviR transmitter (as per #247), but I could do with some guidance. 

I've captured transmissions with the CT clamp sensor in each of the three sensor ports on the bottom on the transmitter. The signals seems to be quite clean, as you can see below:

<img width="1792" alt="EnviR - Sensors 1-3 - FM demod" src="https://user-images.githubusercontent.com/59509/61154330-bdc85680-a4e5-11e9-8087-2c16c8f4cd85.png">

Next, I eyeballed the first 32 bits of the reading from Sensor 1:

![EnviR-first-32-bits](https://user-images.githubusercontent.com/59509/61154438-07b13c80-a4e6-11e9-8a56-6900ea57de8e.png)

Unfortunately, this were I've hit a roadblock. According to [this site](https://github.com/JackKelly/rfm_edf_ecomanager/wiki/Technical-details-of-Current-Cost-RF-protocol) linked from #247, I should expect to see either:

![0x552DD4](https://user-images.githubusercontent.com/59509/61154660-aa69bb00-a4e6-11e9-8e35-7d8cd66deab5.png)

or

![0xAA2DD4](https://user-images.githubusercontent.com/59509/61154791-f4eb3780-a4e6-11e9-9708-eb86a371d8d7.png)

However, that's not what I'm receiving. You can also see that the first 45 bits are the same for all three sensors. This got me thinking it could be [the init pattern](https://github.com/merbanan/rtl_433/blob/8fdaf27d6562b4c01682fceec5e49a6c256e990c/src/devices/current_cost.c#L10) but the first 24 bits of that are:

![0xCCCCCC](https://user-images.githubusercontent.com/59509/61155021-b1dd9400-a4e7-11e9-83fa-df4fb7c4ad4a.png)

So that doesn't fit either. 

What am I doing wrong?

**Comment by zuckschwerdt** [comment]
That looks like Manchester code. If you can get IQ sample data then use rtl_433 to decode the stream using the flex decoder. First try PCM to get the data you have above. Then try the MC or decode further by hand: `01` is a 0-bit, `10` is a 1-bit.

**Comment by neilco** [comment]
```shell
$ rtl_433 -X 'm=FSK_PCM'
rtl_433 version 18.12-235-g8bae8c8 branch master at 201907080940 inputs file rtl_tcp RTL-SDR
Trying conf file at "rtl_433.conf"...
Trying conf file at "/Users/neil/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Bad flex spec, missing modulation!
Use -X <spec> to add a general purpose decoder. For usage use -X help
```

> Bad flex spec, missing modulation!

But…. but… isn’t `m` modulation?!

**Comment by neilco** [comment]
Also, if `01` is a 0-bit and `10` is a 1-bit, doesn’t that mean the data I’ve captured is junk because of that string of nine `1`s?

**Comment by zuckschwerdt** [comment]
For flex, the names always goes first (compat to the old positional format).
Ah ok, you already did a Manchester decode, sorry missed that. But 0xCC is 0x55 after MC decode.

**Comment by neilco** [comment]
> compat to the old positional format

You assume I know what that means when I don’t. 

> But 0xCC is 0x55 after MC decode.

So either I’m doing something wrong or the data is junk. There is no 0x55, 0xAA, or 0xCC in the signals I’ve captured above. What am I doing wrong?

**Comment by zuckschwerdt** [comment]
> You assume I know what that means when I don’t.

The original flex spec format was positional, thus the name field always needs to be first. Simply, always start a flex spec with `n=myname,m=…`

> What am I doing wrong?

Your decoding looks right. Could be that the data is a different protocol (Though using `000…` as a preamble is a poor choice for a protocol as the MC `101010…` is ambiguous). Try to acquire more data, put it in a [BitBench](http://triq.net/bitbench?c=y0000000000000000110100011111111101&f=8h%20) and then play with shift and invert to see if some pattern emerges.

**Comment by neilco** [comment]
Yes! 

<img width="1164" alt="rtl_433 receiving data from the CurrentCost EnvirR transmitter" src="https://user-images.githubusercontent.com/59509/61498167-1bfbaa80-a9ba-11e9-9b08-80d68ed9ac62.png">

**Comment by zuckschwerdt** [comment]
Support now has been added, thanks!
