### ISSUE TITLE
-X vs. -R 0

### ISSUE THREAD

**Issue by winterrace** [merbanan/rtl_433#1116]
If you use a flex decoder via -X, help states "-R 0 to disable all other decoders".

This only works when specifying rtl_433 -R 0 -X '...'. Then rtl_433 outputs flex messages but no other ones from regular decoders.

However, most users will specify rtl_433 -X '...' -R 0, i.e simply attach this to the end. In this case rtl_433 outputs no messages at all. Should be fixed...

**Comment by zuckschwerdt** [comment]
The text is now `(prepend -R 0 to disable all decoders)` which hopefully helps somewhat.
