### ISSUE TITLE
Acurite Atlas 8 in 1

### ISSUE THREAD

**Issue by K2AAE** [merbanan/rtl_433#1123]
I thought my 5 in 1 was broken so I ordered the latest AcuRite Atlas with a Lighting module. Attached is rtl_433 -S all -T 120 Tared and giped
[acurite-a.tar.gz](https://github.com/merbanan/rtl_433/files/3503752/acurite-a.tar.gz)

**Comment by zuckschwerdt** [comment]
Thanks for the samples! Data bytes with #1124 below, now we need to decode the fields ;)

| File | Message |
| --- | --- |
| g001_433.92M_250k.cu8 |  {80} 82 f3 65 00 88 72 22 00 9f 95 |
| | {80} 86 f3 65 00 88 72 22 00 9f 99 |
| | {80} 8a f3 65 00 88 72 22 00 9f 9d |
| g002_433.92M_250k.cu8 |  {80} 82 f3 66 00 05 e4 81 00 9f e4 |
| | {80} 86 f3 66 00 05 e4 81 00 9f e8 |
| | {80} 8a f3 66 00 05 e4 81 00 9f ec |
| g003_433.92M_250k.cu8 |  {80} 82 f3 e7 00 00 00 96 00 9f 91 |
| | {80} 86 f3 e7 00 00 00 96 00 9f 95 |
| | {80} 8a f3 e7 00 00 00 96 00 9f 99 |
| g004_433.92M_250k.cu8 |  {80} 82 f3 65 00 88 72 22 00 9f 95 |
| | {80} 86 f3 65 00 88 72 22 00 9f 99 |
| | {80} 8a f3 65 00 88 72 22 00 9f 9d |
| g005_433.92M_250k.cu8 |  {80} 82 f3 66 00 05 60 81 00 9f 60 |
| | {80} 86 f3 66 00 05 60 81 00 9f 64 |
| | {80} 8a f3 66 00 05 60 81 00 9f 68 |
| g006_433.92M_250k.cu8 |  {80} 82 f3 e7 00 00 00 96 00 9f 91 |
| | {80} 86 f3 e7 00 00 00 96 00 9f 95 |
| | {80} 8a f3 e7 00 00 00 96 00 9f 99 |
| g007_433.92M_250k.cu8 |  {80} 82 f3 65 00 88 71 24 00 9f 96 |
| | {80} 86 f3 65 00 88 71 24 00 9f 9a |
| | {80} 8a f3 65 00 88 71 24 00 9f 9e |
| g008_433.92M_250k.cu8 |  {80} 82 f3 66 00 05 60 81 00 9f 60 |
| | {80} 86 f3 66 00 05 60 81 00 9f 64 |
| | {80} 8a f3 66 00 05 60 81 00 9f 68 |
| g009_433.92M_250k.cu8 |  {80} 82 f3 e7 00 00 00 96 00 9f 91 |
| | {80} 86 f3 e7 00 00 00 96 00 9f 95 |
| | {80} 8a f3 e7 00 00 00 96 00 9f 99 |
| g010_433.92M_250k.cu8 |  {80} 82 f3 65 00 88 71 a5 00 9f 17 |
| | {80} 86 f3 65 00 88 71 a5 00 9f 1b |
| | {80} 8a f3 65 00 88 71 a5 00 9f 1f |
| g011_433.92M_250k.cu8 |  {80} 82 f3 66 00 05 e4 81 00 9f e4 |
| | {80} 86 f3 66 00 05 e4 81 00 9f e8 |
| | {80} 8a f3 66 00 05 e4 81 00 9f ec |
