### ISSUE TITLE
inFactory protocoll channel number.

### ISSUE THREAD

**Issue by ind03** [merbanan/rtl_433#1133]
Please add the channel number to the inFactory protocoll. Ist encoded in the last 2 bits.
* 0000 1111 | 0011 0000 | 0101 1100 | 1110 0111 | 0110 0001
 * xxxx xxxx | cccc cccc | tttt tttt | tttt hhhh | hhhh ??nn
 *
 * x - ID // changes on battery switch
 * c - Unknown Checksum (changes on every transmit if the other values are different)
 * h - Humidity // BCD-encoded, each nibble is one digit
 * t - Temperature   // in °F as binary number with one decimal place + 90 °F offset
 * n - Channel	// Channel number 1 - 3

**Comment by zuckschwerdt** [comment]
Thanks. Implemented now with ae53759.
