### ISSUE TITLE
TX35DTH-IT not decoded with sample rate <> 250 kHz

### ISSUE THREAD

**Issue by f1oat** [merbanan/rtl_433#1135]
With "-s 1024k", all my 868 MHz devices are decoded, except the TX35 sensors.
When using "-s 250k", TX35 decoding is ok.

**Comment by zuckschwerdt** [comment]
Can you grab TX35 samples at 1024k? (`-S all`, then filter through those and upload a zip here)

**Comment by f1oat** [comment]
Here are 3 samples.
Thank you for your help.
[TX35DTH-IT 1024k.zip](https://github.com/merbanan/rtl_433/files/3571166/TX35DTH-IT.1024k.zip)

**Comment by zuckschwerdt** [comment]
Thanks. The samples look good, but the demod won't pick up the FSK.
(Try `sigrok-open.sh g001_868.35M_1024k.cu8 1024` to see that.)
We need to refine the current demod with these samples and use them as baseline for the new demod.

**Comment by f1oat** [comment]
I have been able to demodulate @1024k by scaling following sampling rate dependent constants by a factor of 4:
#define PD_MIN_PULSE_SAMPLES (4*10)
#define FSK_DEFAULT_FM_DELTA (6000/4) 
#define FSK_EST_SLOW         (4*64)
#define FSK_EST_FAST         (4*16)  

Now I need to figure out a clean implementation for that.

**Comment by f1oat** [comment]
Done, I will push a PR

**Comment by merbanan** [comment]
This is superseded by the minmax demodulator.
