### ISSUE TITLE
possible to send "rtl_433 -a -R 0" output to MQTT?

### ISSUE THREAD

**Issue by vampywiz17** [merbanan/rtl_433#1140]
Hello there,

I would like to send a doorbell button push to mqtt. The rtl_433 is not decode it(the Pulse Analyzer not find it), but to be honest, it not required to me, because it is a simple button, it need only if it pushed.

with `rtl_433 -a -R 0` i able to catch the button with {25}... code. It is enough to me. I try to use `rtl_433 -a -R 0 -F "mqtt://localhost:1883,retain=0"` but it dont send the code...

What the correct way to send the raw data to mqtt?

**Comment by zuckschwerdt** [comment]
Use `-A` and note the `-X` line. Then use that to write a flex decoder. See e.g. https://github.com/merbanan/rtl_433/blob/master/conf/EV1527-PIR-Sgooway.conf
