### ISSUE TITLE
Bresser Weather Center 5-in-1 wrong rain_mm value?

### ISSUE THREAD

**Issue by iMarkus** [merbanan/rtl_433#1144]
Hi all,
I am using the latest version of rtl_433 and a Bresser 5in1 weather station. Everything looks fine but the value for rain_mm seems to be not correct (at least for me).

Command: rtl_433 -f 868.3M -s 1000k -R 119 -F json
Output JSON: {"time" : "2019-09-02 22:26:03", "model" : "Bresser-5in1", "id" : 206, "temperature_C" : 16.700, "humidity" : 96, "wind_max_m_s" : 0.800, "wind_avg_m_s" : 0.600, "wind_dir_deg" : 292.500, "rain_mm" : 94.400, "mic" : "CHECKSUM"}

time: 2019-09-02 22:28:03
model: Bresser-5in1
id: 206
Temperature: 16.8 C
Humidity: 96
Wind Gust : 0.0 m/s
Wind Speed: 0.2 m/s
Direction : 292.5 °
Rain: 94.4 mm
Integrity : CHECKSUM

But the station itself says:
15.2mm daily
16.0mm weekly
16.0mm monthly

0.60in daily
0.63in weekly
0.63in monthly

What does "rain_mm" : 94.400 mean?

Thanks in advance!

**Comment by zuckschwerdt** [comment]
Most sensors will output an accumulated counter since the last reset (battery change) only. You need to derive the value. I.e. you need two measurements and the difference is the new rainfall.
