### ISSUE TITLE
Anything to learn from the tellstick-code code?

### ISSUE THREAD

**Issue by petterreinholdtsen** [merbanan/rtl_433#1145]
I've just tested the https://github.com/telldus/telldus/tree/master/telldus-core code with the original Tellstick USB dongle, and noticed that rtl_433 could not tell the difference between the arctech protocol and the waveman protocol.  Looking at the code in service/ProtocolNexa.cpp and service/ProtocolWaveman.cpp, I see the protocols are implemented in different files and seem to be slightly different.

Perhaps there is something to learn from the tellstick-code source regarding the various protocols?

**Comment by zuckschwerdt** [comment]
Waveman is a simpe EV1527 protocol which is best implemented with a flex decoder nowadays.
Proove/Nexa/Kaku are similar but with 32 bits. And there is sometimes 36 bits with an additional dimmer value. Arctech seems to be the same with maybe some added quirks.
The Telldus code is GPL, feel free to PR interesting bits or reopen with a protocol description.
