### ISSUE TITLE
Inconsistent and confusing battery / battery_ok / battery_low keys

### ISSUE THREAD

**Issue by JeanVEGA** [merbanan/rtl_433#1157]
I was running an older version https://github.com/merbanan/rtl_433/blob/ca16cd6c487ab9b34a585dc5d896896bed7b5bef/src/devices/acurite.c#L537, where Accurite sensors simply used a `bool` `"battery"` flag. Exampe JSON output:

Current state uses 3 possible keys for the same `bool` (depending on a device): `"battery"`, `"battery_low"` and `"battery_ok"` https://github.com/merbanan/rtl_433/blob/8eecdbbad975ac024ecc0407cc7cbd9e8f457c8b/src/devices/acurite.c#L511

Can this be reverted back or consolidated into a single key? It is unclear which key to expect when and for which device.

**Comment by zuckschwerdt** [comment]
Please use `-M newmodel`. S.a. https://triq.org/rtl_433/DATA_FORMAT.html#common-device-data
