### ISSUE TITLE
Support for LaCrosse TX37U-IT

### ISSUE THREAD

**Issue by CharlesGodwin** [merbanan/rtl_433#1162]
This is a 915Mhz unit.
I tried this but get no result
`rtl_433 -R 8 -R 34 -R 73 -R 75 -R 76 -R 124 -f 915M`

I also tried with only -R 8 and only-R 76, the most likely candidates. Nothing
I am using on a Raspberry Pi
`rtl_433 version 19.08-23-gdc4440b branch master at 201910051118 inputs file rtl_tcp RTL-SDR SoapySDR`

Any suggestions for what to try next?

**Comment by CharlesGodwin** [comment]
Should have read the help files first. https://triq.org/

**Comment by zuckschwerdt** [comment]
I don't think we have support specific to this device. If it isn't working with one of the other LaCrosse decoders (better to try all decoders or even `-G`) then upload some sample files as zip here. (Check in https://triq.org/iqs before.) We'll take a look.

**Comment by CharlesGodwin** [comment]
I tried and failed to figure out a pull request in https://github.com/merbanan/rtl_433_tests. i'm not that skilled.

The TX37U is described [here ](https://www.lacrossetechnology.com/tx37u-it?type=parts)
The attached zip file was taken when the air temperature was about 13 C
[2019-10-07_0800.zip](https://github.com/merbanan/rtl_433/files/3698079/2019-10-07_0800.zip)

**Comment by zuckschwerdt** [comment]
A zip also works, no need for a PR. The signals are present but distorted. Can you try again with a higher sample rate (`-s 1024k`)?

**Comment by merbanan** [comment]
We should default a higher sample rate for >433MHz.

**Comment by zuckschwerdt** [comment]
The samples vaguely looked like FSK. Is FSK common on 915, like on 868? What about 315?

**Comment by CharlesGodwin** [comment]
Here is the new file. current temperature about 16 C
[2019-10-07_1120.zip](https://github.com/merbanan/rtl_433/files/3698185/2019-10-07_1120.zip)

**Comment by merbanan** [comment]
@zuckschwerdt FSK is common at 868, 915. 315 probably uses OOK.

**Comment by zuckschwerdt** [comment]
That's GFSK (gaussian filtered FSK) at about 33 µs bit width. Looks like minimum shift width -- the 101010… preamble is a neat sine in FM.
Our current demodulator can't automatically pick this up :/

**Comment by merbanan** [comment]
:( I still have a few projects I need to finish before I can look into this

**Comment by CharlesGodwin** [comment]
Take your time. Thanks for the help

**Comment by merbanan** [comment]
@zuckschwerdt I took a look at this signal in I/Q Spectrogram and I see 4 clear levels.

**Comment by merbanan** [comment]
Or when I also look at the signal in octave.
[signal_demod.pdf](https://github.com/merbanan/rtl_433/files/3698729/signal_demod.pdf)

**Comment by merbanan** [comment]
First the signal preamble uses 2 alternating symbols (mid-hi and mid-low), then you can see that the hi-hi symbol is present and then even lots of low-low symbols.

**Comment by zuckschwerdt** [comment]
I think multiple f levels are an artifact. Pulseview shows the PCM as expected:
![signal](https://user-images.githubusercontent.com/12833/66336089-b544b800-e93c-11e9-993b-7b10f112c49e.png)

**Comment by merbanan** [comment]
What sample are you looking at?

**Comment by merbanan** [comment]
Hmm, ok that makes more sense, what I see is then a filtering artifact

**Comment by merbanan** [comment]
With a tweaked butterworth filter I am able to recover the frequency transitions.

[signal_demod2.pdf](https://github.com/merbanan/rtl_433/files/3699063/signal_demod2.pdf)

So it should be doable. Just need run time switching of filter coeffs or some heuristics that can figure out what is needed.

**Comment by zuckschwerdt** [comment]
We already untangled both analyzers from the sample processing and now have a (configurable) choice of four steps for sample data: two analyzers, ook demod, fsk demod. It's possible to add more (optional) steps and choose them on demand/startup. Like the fsk demod we could enable a specific demod only if a decoder needs that.
It'll take some more coding to properly abstract it but that's on my list, and we are nearly there.

**Comment by CharlesGodwin** [comment]
Any luck on this?
Thanks

**Comment by CharlesGodwin** [comment]
you can close this issue. I've moved on to an alternative solution. Thanks for your  efforts.

**Comment by gdt** [comment]
This issue has been abandoned by the submitter, and it doesn't seem like we should leave it open.   Before closing, is there information we should capture, and if so where?
