### ISSUE TITLE
rtl_433 -S gives me segmentation fault

### ISSUE THREAD

**Issue by jcarduino** [merbanan/rtl_433#119]
Playing with the parameters when starting rtl_433 -S causes a segmentation error right at the startup.

Any thoughts?

**Comment by jcarduino** [comment]
still active and current with build on today...

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000.
Bit detection level set to 8000.
Tuner gain set to Auto.
Reading samples in sync mode...
Segmentation fault (core dumped)

**Comment by LuccoJ** [comment]
Yep, this happens to me as well.

**Comment by robho** [comment]
sync mode writes samples to an output file. If no output file is specified rtl_433 will crash.

**Comment by jcarduino** [comment]
Clear. Can this be updated in documentation? This can be closed afaik. 

Mvg Johan Corstjens

Verstuurd via mobile

**Comment by merbanan** [comment]
Option -S is no longer a valid option and thus no longer crash. Closing issue.
