### ISSUE TITLE
Centos 8 build notes

### ISSUE THREAD

**Issue by toroa** [merbanan/rtl_433#1197]
The libusb-devel package in Centos 7 has been renamed to libusbx-devel in Centos 8 so you need to use "sudo dnf install libusbx-devel" if you get a cmake error

**Comment by zuckschwerdt** [comment]
Thanks! There also was a PR (#1259) to update our docs recently. Was that really a change from libusb to libusbx? The later is a fork but now merged if I read that correctly.
