### ISSUE TITLE
LaCrosse TX29-IT/TX37U-IT no longer detected on 915000000

### ISSUE THREAD

**Issue by bronze51** [merbanan/rtl_433#1204]
EDIT: I checked and the thermometer is actually a TX37U-IT. It was recognized as a TX29-IT by rtl_433.

The version back in May (or prior), when running "rtl_433 -a -f 915000000", would detect a thermometer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2019-11-22 18:06:56                    brand     : LaCrosse
model     : TX29-IT      id        : 8
Battery   : OK           NewBattery: 0             Temperature: 7.3 C
Integrity : CRC

However, this evening I re-built rtl_433 (version 19.08-102-g6b7f066) and it no longer seems to detect the above thermometer. I.e. I don't get the above output.

**Comment by Mindavi** [comment]
You could try if the -Y classic flag helps. See also #1198 for information.

**Comment by bronze51** [comment]
Adding "-Y classic" got it back! However the model I have states TX37Y-IT on the back (as I found out yesterday).
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2019-11-24 10:07:29                    brand     : LaCrosse
model     : TX29-IT      id        : 8
Battery   : OK           NewBattery: 0             Temperature: 11.7 C
Integrity : CRC

**Comment by Mindavi** [comment]
If the protocol is the same it could just be an annotation in the documentation, otherwise it would be good to fix it. Also, some samples could help @merbanan improve the new decoder to also work for this device.

**Comment by bronze51** [comment]
Noob question: how do I create a a file with some useful samples? I run "rtl_433 -f 915M -Y classic".

**Comment by steepleian** [comment]
One way is to use the WeeWX SDR recipe.

Find it here: -

https://github.com/weewx/weewx/wiki/sdr-rpi-recipe

**Comment by zuckschwerdt** [comment]
Likely you are looking for the `-S ` option:
```
  [-S none | all | unknown | known] Signal auto save. Creates one file per signal.
```

**Comment by bronze51** [comment]
I used "rtl_433 -f 915M -R 76 -Y classic -S all" to capture signals from my TX37U-IT. 
The TX37U-IT is decoded by rtl_433 as TX29-IT.
[g00x_915M_1000k.tar.gz](https://github.com/merbanan/rtl_433/files/4007242/g00x_915M_1000k.tar.gz)

**Comment by evilpete** [comment]
I have a TX29IT   (FCC ID OMO-TX29U) and detect it fine,

In fact it reports as both  LaCrosse-TX35DTHIT and LaCrosse-TX29IT
which is odd since the TX29IT uses a pause width of 55 and the TX35DTHIT uses a pause width of 105

Also note that the modulation is reported incorrectly ( I suspect is a side effect of one of the two FSK demodulators, but that is another issue)

```
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-02-03 20:40:51                    Protocol  : 75            brand     : LaCrosse
model     : LaCrosse-TX35DTHIT                     id        : 8
Battery   : 1            NewBattery: 0             Temperature: 2.6 C        Integrity : CRC
Modulation: ASK          Freq      : 0.0 MHz
RSSI      : 0.0 dB       SNR       : 0.0 dB        Noise     : 0.0 dB
pulse_demod_pcm(): LaCrosse TX35DTH-IT, TFA Dostmann 30.3155 Temperature/Humidity sensor
bitbuffer:: Number of rows: 1
[00] {80} aa aa a8 b7 52 48 10 99 a8 04
LaCrosse TX29/35 detected, buffer is 80 bits length, device is TX29
{80} aa aa a8 b7 52 48 10 99 a8 04 : 10101010 10101010 10101000 10110111 01010010 01001000 00010000 10011001 10101000 00000100
lacrosse_it	buffer from 38	{40} 92 04 26 6a 01 : 10010010 00000100 00100110 01101010 00000001
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-02-03 20:40:51                    Protocol  : 76            brand     : LaCrosse
model     : LaCrosse-TX29IT                        id        : 8
Battery   : 1            NewBattery: 0             Temperature: 2.6 C        Integrity : CRC
Modulation: ASK          Freq      : 0.0 MHz
RSSI      : 0.0 dB       SNR       : 0.0 dB        Noise     : 0.0 dB
pulse_demod_pcm(): LaCrosse TX29IT Temperature sensor
bitbuffer:: Number of rows: 1
[00] {80} aa aa a8 b7 52 48 10 99 a8 04
LaCrosse TX29/35 detected, buffer is 80 bits length, device is TX35
{80} aa aa a8 b7 52 48 10 99 a8 04 : 10101010 10101010 10101000 10110111 01010010 01001000 00010000 10011001 10101000 00000100
```

**Comment by zuckschwerdt** [comment]
They are both the same protocol but with a different PCM width. But the new PCM code locks onto the transmission anyway -- it's too good ;) I'll look into that, thanks.
Strange that it says ASK. It's FSK for sure.

**Comment by evilpete** [comment]
@zuckschwerdt  it's not *that* good :-)  I am having a hell of a time trying to get it to accept Transmissions from my YardStick 1.  mostly false translations resulting in pulses having drops lasting only one or two samples 
![SS2](https://user-images.githubusercontent.com/2381225/73878292-2757db80-480f-11ea-9acc-aacd1eab02ee.png)

![SS1](https://user-images.githubusercontent.com/2381225/73878267-1f983700-480f-11ea-904d-5e88b20a0ce3.png)

Should I open a separate issue for this ?

**Comment by zuckschwerdt** [comment]
I meant the PCM pulse to bitbuffer (it's not reliant on an exact bit rate anymore) "demod" -- perhaps that should be called "slicer". Those drops are in the FSK demod. @merbanan knows the minmax FSK demod better. You could try the older `-Y classic` demod.

**Comment by zuckschwerdt** [comment]
The slicers are the first point where we known the expected mark/space widths, in principle we could low-pass filter there.

**Comment by merbanan** [comment]
@evilpete IIRC when using sigrok-open scripts I think it always uses the classic demod.

**Comment by zuckschwerdt** [comment]
Ah, yes. The script doesn't care about the frequency and thus the classic demod.

**Comment by merbanan** [comment]
And yes the terminology is wrong, it should be the bit slicers. The actual demodulation is a frequency discriminator (arctan based). Depending on the chosen mode the classic code is used. This classic one is not suitable for "fast" bitrate protocols. The new min/max based one works better for that.

**Comment by merbanan** [comment]
I think we should add one option to the script to force fsk demod (bitslicer).

**Comment by merbanan** [comment]
@evilpete regarding short pulses, the classic version had code to remove them. We could introduce the same logic in the min/max version. But I need sample signals that trigger this. Generic fsk demod turned out to be a not so easy problem.

**Comment by merbanan** [comment]
@evilpete and yes, open another issue for it.

**Comment by merbanan** [comment]
The original issue has been explained and command line output has been added to inform users about there options. Closing issue.
