### ISSUE TITLE
ISO-8601 shows no time zone

### ISSUE THREAD

**Issue by LiberationFrequency** [merbanan/rtl_433#1206]
Is it possible to implement the time zone for -M time:iso . This way you cannot see at what time the dataset was created. You may want to display the local time, but still use the data across different time zones. The best format would be time+/-hh:mm and timeZ for UTC. If this is not possible due to portability, then it would be nice if at least the Z is written behind for UTC.
Thanks in advance.

**Comment by zuckschwerdt** [comment]
Checkout and discuss in #1207
