### ISSUE TITLE
Command with multiple frequencies results in OOB read

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1211]
Running a command with multiple frequencies, e.g. `rtl_433 -r g038_915M_1000k.cu8 -f 914980000 -f 915000000` will result in `int hop_index` in `rtl_433.c` being -1. With ASAN compiled in this gives an error like this: `/rtl_433/src/rtl_433.c:570:87: runtime error: index -1 out of bounds for type 'int [32]'`

**Comment by zuckschwerdt** [comment]
Good find. The default hop time is only set after the read-file block, thus not reliable in that line mentioned.
