### ISSUE TITLE
cd build && cmake .. is throwing an error

### ISSUE THREAD

**Issue by juergenschubert** [merbanan/rtl_433#1238]
- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found Git version: refs/heads/master commit 2b6d5fded418d21195438909c7839abdf1c935d7 from 2019-12-16T22:34:30+0100
-- Using Git version tag: 19.08-113-g2b6d5fd on master at 201912162234
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Found LibRTLSDR: /usr/local/lib/librtlsdr.so
-- Found LibUSB: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
-- RTL-SDR device input will be compiled.
CMake Warning at CMakeLists.txt:116 (find_package):
  Could not find a package configuration file provided by "SoapySDR"
  (requested version 0.6) with any of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.

-- SoapySDR development files not found, SoapySDR device input won't be possible.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/rtl_433/build

**Comment by zuckschwerdt** [comment]
Just a warning, not an error. Use -DENABLE_SOAPYSDR=OFF to get rid of the test.
See https://triq.org/rtl_433/BUILDING.html#cmake
