### ISSUE TITLE
Decoding WS0232

### ISSUE THREAD

**Issue by Hormold** [merbanan/rtl_433#1241]
Hello. I have a small weather station (WS0232) from Aliexpress - https://aliexpress.com/item/32294810058.html
They have a few versions with a rain sensor and with connection to PC via USB.
My station had only 433 transmitter, wind direction+speed, and Temp.+Hum.
The station works on 433.690, and now detecting as "Smoke detector GS 558".

I record a few samples with data and record real values from the indoor display.
They send data every ~48 seconds, but I receive some other data in another 48sec interval. I don't know what is data, in this moment's display not updating.

> g002_433.69M_250k.cu8
> C = 5.3
> H = 74%
> Wind (N) 6.1 ms
> 
> g004_433.69M_250k.cu8
> C = 5.1
> H = 75%
> Wind (N) 4.0 ms
> 
> C = 4.9
> H = 76%
> Wind (N) 4.4ms
> g006_433.69M_250k.cu8
> 
> C =4.7
> H = 77%
> Wind (N) 6.1ms
> g008_433.69M_250k.cu8
> 
> C = 4.6
> H = 77%
> Wind (N) 6.1 ms
> g010_433.69M_250k.cu8

Archive: [rec1.zip](https://github.com/merbanan/rtl_433/files/4005797/rec1.zip)

Can someone help me decode the data?

**Comment by Hormold** [comment]
This set is recorded in 10cm, without an antenna.

> 
> g018_433.69M_250k.cu8
> T=5.6C, H=70%
> Wind (N) 6.6 ms
> 
> g020_433.69M_250k.cu8
> T=5.6 C, H= 71%
> Wind (N) 5.7 ms
> 
> g022_433.69M_250k.cu8
> T= 5.7 C, H = 71%
> Wine (N) 7.9 m/s
> 
> g024_433.69M_250k.cu8
> T=5.7C, H=70%
> Wind (W) 6,6 ms
[rec2.zip](https://github.com/merbanan/rtl_433/files/4005833/rec2.zip)

**Comment by Hormold** [comment]
Oops, see #1200 
Closing this duplicate.

**Comment by M66B** [comment]
If somebody else is looking for this information: rtl_433 works with the more recent AliExpress WS0232 weather station. It checks in as WS2032, but it works fine.
