### ISSUE TITLE
Improvement suggestion: add frequency to output (optionally)

### ISSUE THREAD

**Issue by giddyhup** [merbanan/rtl_433#1244]
I cycle through frequencies using the -H option. Would it be possible to add the frequency where something was found and decoded to the output, e.g. to the JSON object (`{"frequency": 433920000,...}`)?

**Comment by zuckschwerdt** [comment]
You are looking for `-M level`:
```
{... "mod" : "ASK", "freq" : 433.895, "rssi" : -0.133, "snr" : 18.357, "noise" : -18.489}
```
