### ISSUE TITLE
OMS device types

### ISSUE THREAD

**Issue by antonmeyer** [merbanan/rtl_433#1245]
my QDS meter reports device type 0x37 and no device type string
if you have some spare time, you might add the OMS device types
https://oms-group.org/fileadmin/files/download4all/specification/Vol2/4.1.2/OMS-Spec_Vol2_Primary_v412.pdf (page 16 and 17)

**Comment by merbanan** [comment]
Care to send a patch?

The code is here:

https://github.com/merbanan/rtl_433/blob/master/src/devices/m_bus.c#L87

**Comment by antonmeyer** [comment]
done and created a pull request. thx

**Comment by merbanan** [comment]
tnx
