### ISSUE TITLE
BUG ? some csv output fields seems to be not part of the CSV output 

### ISSUE THREAD

**Issue by dgrostoto** [merbanan/rtl_433#1249]
During my tests i found out that :
When manually selecting a decoding protocol disabled by default. The corresponding output csv fields  does not seems to be reported in the output.
My try was (ikea sparnas decoder)
rtl_433  -R 130  -F csv
Part of the ouput is 
"Registered 1 out of 141 device decoding protocols [ 130 ]
time,msg,codes"
but i expected the output to inclure other fields 
such as "sequence"  and so on (fields mentionned in ikea_sparsnas.c file.
Maybe this could be a bug, and csv -at least headers- fields should be included in csv output ? 
PS : when setting disable to 0 in ikea_sparsnas.c file in r_device ikea_sparsnas structure, everything comes OK.
PS2 : i can't tell about csv data (i just saw it for the headers) for this decoder since i don't own any and thus can test it.

**Comment by zuckschwerdt** [comment]
Thanks! Fixed with 195ec6e
