### ISSUE TITLE
Oregon scientific variant

### ISSUE THREAD

**Issue by fnarfbargle** [merbanan/rtl_433#1258]
While I'm here, one of my neighbours has a weather station that seems to be a variant or revision of an oregon scientfic model. I've used this patch since January and it gives sane outputs that correlate pretty well with my local measurements.

[oregon.patch.txt](https://github.com/merbanan/rtl_433/files/4038470/oregon.patch.txt)

Don't know if it's useful or not.

**Comment by zuckschwerdt** [comment]
Interesting. I'll just put that in there with an "unconfirmed" note.
