### ISSUE TITLE
-M option frequencies

### ISSUE THREAD

**Issue by JSMSolns** [merbanan/rtl_433#1267]
Would it be possible to change the frequency reporting for the -M option from 1 decimal place to 3decimal places please? 
This would help with identifying the centre and deviation frequencies more accurately (assuming this is appropriate).

I believe this should simply be a matter of changing the following lines in r_api.c from %.1f MHz to %.3f MHz:
664
665
674

**Comment by zuckschwerdt** [comment]
Sorry, the frequency report is just a very rough estimation. We are currently modularizing the demodulator step and we might add a true dominate frequency (likely FFT) someday.

**Comment by merbanan** [comment]
Currently it should only be used to identify what band the signal is in. We would need new dsp code for this. And it is unlikely that something like that will ever be written. At least by me.

**Comment by JSMSolns** [comment]
Understood - thanks for the quick response
