### ISSUE TITLE
Flex decoder requires long_width setting for FSK_MC_ZEROBIT 

### ISSUE THREAD

**Issue by evilpete** [merbanan/rtl_433#1273]
when using the OOK_MC_ZEROBIT the 'long' setting is ignored 
but when using FSK_MC_ZEROBIT  you get an error requiring  long is set although with value is ignored for both OOK_MC_ZEROBIT and FSK_MC_ZEROBIT modulations

**Comment by zuckschwerdt** [comment]
Thanks!
