### ISSUE TITLE
Signal auto save. not not work as expected with Flex decoder 

### ISSUE THREAD

**Issue by evilpete** [merbanan/rtl_433#1280]
When the Signal auto save option  '-S known'  is used  with Flex decoder samples are not saved when an identified signal is received 

the command 

rtl_433 -X "n=doorbell,m=OOK_PWM,s=400,l=800,r=7000,g=1000,match={24}0xa9878c"  -S known

**Comment by zuckschwerdt** [comment]
The flex decode doesn't count as successful ouput. But I guess it reasonably could.
Changed with 74c527b, should work now.
