### ISSUE TITLE
protocol_num is reset for fineoffset-wh5

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1288]
## Expected behavior

Fineoffset-wh5 protocol_num is set and can be used to stream bitbuffers, like this one: `[18]{47} fe 8b 30 04 a7 44`.

## Actual behavior

`Unknown protocol number 18.`

## Step to reproduce

1. Create a file `fineoffset-wh5.bb` with the bitbuffer listed above
2. Run `rtl_433 -y - < fineoffset-wh5.bb`

## Research done

It seems like this has to do with some initialization for the fineoffset-wh5 decoder.
That decoder is the only one with a `create_fn`, which creates an `r_device`.

The numbering is done in the following lines: https://github.com/merbanan/rtl_433/blob/71f86a4a29b37aa7b20f2c05066163b27dbf23a0/src/rtl_433.c#L1160-L1164

However, the `create_fn` is called in `register_all_protocols`:

https://github.com/merbanan/rtl_433/blob/71f86a4a29b37aa7b20f2c05066163b27dbf23a0/src/rtl_433.c#L1219-L1220

Which is called later. It seems like this resets the protocol number back to 0. I'm not sure if the `protocol_num` must be set for something else to work, otherwise the fix would be to just move the setting of the `protocol_num` to a later moment (after `register_all_protocols`).

It might also be possible that the `create_fn` is not needed anymore, or is obsolete. Removing it would fix the issue as well, but then the whole feature should be removed, I guess.

## Related issues/PRs

https://github.com/merbanan/rtl_433/issues/955#issuecomment-457840536

(it seems like this is the only decoder using such a parametric decoder)

https://github.com/merbanan/rtl_433/pull/960

**Comment by zuckschwerdt** [comment]
All dynamic decoders (currently this and flex) don't get a fixed number. This is because those decoders might be registered multiple times with different arguments.
I don't much like this, but I can't see how we could manage fixed numbers for dynamic, parameterized decoders? Maybe I'll rethink this once we have the library abstraction and parallel demods done.
