### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1292]
Hi, I was wondering if a release is planned or if it possibly should be planned. I'm not sure about the distribution of users, but I assume there might be some users that use the version distributed by their package manager, e.g. ubuntu (https://packages.ubuntu.com/eoan/rtl-433). Because their repositories only contain releases, those users might miss out on some recently added features and decoders.

Would it be good to make a release and if so, are there any issues that need to be solved before doing so? Or is releasing something that's considered non-important/not needed?

Honestly, I really can't tell if there are users that just use the version provided by the package repositories, because this is a niche tool mostly used by enthousiasts, I'd assume.

**Comment by merbanan** [comment]
My idea was to make a release before February 10. @zuckschwerdt any comments on that?

**Comment by zuckschwerdt** [comment]
I don't have any short term feature PRs, just "someday" stuff. (And decoders will always be evolving.) I'd say we are good for a release tag. However:

I would be really interested about the user base, what platforms and if it's precompiled or from git. I've been playing with static builds and CI for armhf/64, i686/amd64 to help users just download a binary. But I'm not too sure if that's a thing for SDR hackers ;)

Maybe we could output a prominent link with some encoded but visible stats? Allthough I'm not one for automatic usage stats in background, I'd click a simple link. E.g.

> Click this link to let the developers know what system is most used:
> https:// foo /stats?platfom=foo&ver=foo

**Comment by merbanan** [comment]
Things before release:
Fix Thermopro 11 and 12 integrity check.

**Comment by merbanan** [comment]
I'd like to get the release out soon. Do we have any nice to have stuff that we want in the release ? Some of the long gone PR's would be nice.

**Comment by Mindavi** [comment]
Maybe we could do a sweep through all decoders to fill in any missing return code for the diagnostic mode. I'm not sure what else is important, but according to the bug reports something about the minmax vs classic decoder should definitely be mentioned indeed.

**Comment by merbanan** [comment]
@Mindavi I'm like 25% through all decoder regarding that.

**Comment by alexmyczko** [comment]
@mindavi https://github.com/merbanan/rtl_433/issues/1095 

https://qa.debian.org/popcon.php?package=rtl-433

**Comment by Mindavi** [comment]
Shall I pick up a part of the error code implementation? If so, maybe we should track progress somewhere?

**Comment by merbanan** [comment]
@Mindavi I did it alphabetically, last file was holman_ws5029.c in feat-error-codes2 branch. I mixed some other stuff in there so it can't be applied yet. Anyway if you continue and only do the error codes we can merge those quickly. Anyway that would be very helpful.

**Comment by merbanan** [comment]
@Mindavi just push the return code fixes directly. Simple fixes can be pushed directly without a PR. More complex changes can go as a PR.

**Comment by Mindavi** [comment]
Most devices have correct(ish) return codes now. #1314 lists some missing ones, which use the 'event pattern'.

Notably, I've skipped `m_bus.c`, which needs a good look.

You can find all non-implemented decoders using `grep -R "return 0" -l | sort | less`.

This gives the following list, of which most should be mentioned in #1314.

```
acurite.c
brennenstuhl_rcs_2044.c
current_cost.c
digitech_xc0324.c
dsc.c
flex.c
gt_wt_02.c
hondaremote.c
ht680.c
ikea_sparsnas.c
m_bus.c
new_template.c
oil_standard.c
oregon_scientific.c
oregon_scientific_sl109h.c
radiohead_ask.c
tpms_ford.c
tpms_pmv107j.c
tpms_renault.c
tpms_toyota.c
ttx201.c
```

**Comment by merbanan** [comment]
I'd say it's enough return codes for the release. The ones left needs a more in-depth look.

**Comment by merbanan** [comment]
I have added the output information. I have no further things I think is vital before a release. @zuckschwerdt do you have something you want to add? If not can you create a release tomorrow?

**Comment by zuckschwerdt** [comment]
Ok, I'll compile the changelog and tag a release tomorrow.

**Comment by alexmyczko** [comment]
how am i supposed to build the docs? ./build-docs.sh ? and the tarball release spits out
```
$ rtl_433 -V
rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
```

**Comment by zuckschwerdt** [comment]
The Doxygen stuff is just for the maintainers. It's really not used but a style check for now.
Use `cmake -DBUILD_DOCUMENTATION:BOOL=OFF ..` if you accidentally turned it on.

Yes, we need a solution to insert a version number when not building from Git with CMake. Not sure if we really want to put a version number (and keep it up to date) somewhere.

**Comment by alexmyczko** [comment]
> The Doxygen stuff is just for the maintainers. It's really not used but a style check for now.
> Use `cmake -DBUILD_DOCUMENTATION:BOOL=OFF ..` if you accidentally turned it on.

I maintain the debian package, and fail to build the docs?

**Comment by zuckschwerdt** [comment]
As for distrib docs, that's just the plain .md files.
Those docs (not doxygen source code docs) can be found at https://triq.org/rtl_433/

The doxygen docs are not used. I guess you can build them, but they are not distributed or available anywhere. There is no useful index or intro page.

I'm not aware of an error in the troff man page. What checker is that?

**Comment by alexmyczko** [comment]
something from https://salsa.debian.org/lintian/lintian

**Comment by zuckschwerdt** [comment]
Probably https://salsa.debian.org/lintian/lintian/blob/master/checks/documentation/man.pm then. Let's see if we can spot what's wrong.

**Comment by alexmyczko** [comment]
I fixed the -doc thing by dropping the package for now.

**Comment by merbanan** [comment]
@alexmyczko can you sponsor a patch to the debian rtl-sdr package for me?

**Comment by merbanan** [comment]
https://github.com/osmocom/rtl-sdr/pull/9

**Comment by alexmyczko** [comment]
guess so well i can put that in the source package and a DD might sponsor it, i can not ;)

**Comment by zuckschwerdt** [comment]
For the troff checking the script runs `man --warnings -E UTF-8 -l -Tutf8 -Z rtl_433.1`.
I don't get the warning with man 2.7.6.1 here. But it looks like an overlong line warning.
