### ISSUE TITLE
Add Pulseview demod tracing tool

### ISSUE THREAD

**Issue by evilpete** [merbanan/rtl_433#1295]
If possible, include output of  both FSK demodulators

**Comment by zuckschwerdt** [comment]
I like the idea. I already have some kind of enhanced "debugging" version, will adapt that.

**Comment by merbanan** [comment]
@evilpete of course output from both bit slicers are the obvious solution.

**Comment by zuckschwerdt** [comment]
I will add more options for the SR ouput later, please test the prototype code in #1297
