### ISSUE TITLE
switch fallthrough warning in rtl_433/src/devices/m_bus.c

### ISSUE THREAD

**Issue by jcwren** [merbanan/rtl_433#1298]
Got this warning compiling the latest pull from the master branch. Looks like there should be a `break` at line 226? Or perhaps a `__attribute__ ((fallthrough))`, if that's really what is intended.

This is with gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)

```
/home/zzz/rtl_433/src/devices/m_bus.c: In function ‘m_bus_decode_records’:
/home/zzz/rtl_433/src/devices/m_bus.c:219:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             switch(vif_uam>>1) {
             ^~~~~~
/home/zzz/rtl_433/src/devices/m_bus.c:226:9: note: here
         case 0x7D:
         ^~~~
```

**Comment by merbanan** [comment]
Should be fixed now.

**Comment by jcwren** [comment]
The `break` needs to go after the closing brace for the `case 0x7B:`. You added a default for the switch statement that's inside the `case 0x7B`.

**Comment by jcwren** [comment]
That got it :)  Thanks!

**Comment by merbanan** [comment]
Send a PR next time you need something to be done properly ;)
