### ISSUE TITLE
Oregon support

### ISSUE THREAD

**Issue by dwery** [merbanan/rtl_433#13]
It would be nice to add support for Oregon sensors.
You can find some code here: https://github.com/kevinmehall/rtlsdr-433m-sensor

Here's some output:

Tuned to 433920000 Hz.
*** signal_start = 5066203, signal_end = 5184028
signal_len = 117825,  pulses = 82
Iteration 1. t: 916    min: 432 (80)    max: 1401 (2)    delta 1685
Iteration 2. t: 916    min: 432 (80)    max: 1401 (2)    delta 0
Pulse coding: Short pulse length 432 - Long pulse length 1401

Short distance: 337, long distance: 935, packet distance: 26308

p_limit: 916

[00] {41} 00 08 00 00 00 00 : 00000000 00001000 00000000 00000000 00000000 00000000 
[01] {41} 00 08 00 00 00 00 : 00000000 00001000 00000000 00000000 00000000 00000000

**Comment by merbanan** [comment]
I think Oregon is fairly supported now. Reopen if that is not the case.

**Comment by ygator** [comment]
His output above looks to be version 1 of the Protocol which is not (yet) supported.
