### ISSUE TITLE
sample rate too low for protocol 150 "Klimalogg"

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1326]
`rtl_433 -y "{25}fb2dd58" -F json -G 4` yields this error.

https://github.com/merbanan/rtl_433/blob/31a3248a7f6967182d6ba0c7cb07403d3f830364/src/r_api.c#L154-L161

**Comment by merbanan** [comment]
Add -s 2000k first. The order matters.

**Comment by Mindavi** [comment]
Does this mean the `-G 4` testing mode should always require the sample rate? Is this intended? Do other devices still decode correctly in that case?

**Comment by merbanan** [comment]
The tolerance gets rounded towards 0. Just an unknown effect.

**Comment by merbanan** [comment]
Ok, fixed.
