### ISSUE TITLE
gcc compile warning

### ISSUE THREAD

**Issue by merbanan** [merbanan/rtl_433#1329]
write_sigrok.c: In function ‘write_sigrok’:
write_sigrok.c:97:15: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
         (void)asprintf(&argv[arg++], "analog-1-%u-1", i);
               ^~~~~~~~
               vsprintf

Running the clang tests emits lots of warnings to in that code.

**Comment by zuckschwerdt** [comment]
I was lazy there, asprintf isn't portable. Fixed with 02e8d32.
