### ISSUE TITLE
TPMS Device Emitting Particular Values

### ISSUE THREAD

**Issue by AlexKusnezov** [merbanan/rtl_433#1334]
Hey guys, 

I was wondering, if there's a way to program a device, let's say a TPMS sensor which will send a spoofed signal to the car's TPMS ECU module?

E.g. I would program in to send 37psi all the time.

Is this possible, for testing purposes of course?

**Comment by zuckschwerdt** [comment]
Transmitting signals is not our scope. There are programmable TPMS, sure. But either you need to write a new firmware for that or take a stock one, spin it to send signals and fix the value by glueing the pressure sensor.
