### ISSUE TITLE
Please implement  gracefull exit when usb stick becomes inactive/removed/whatever

### ISSUE THREAD

**Issue by jcarduino** [merbanan/rtl_433#136]
When the stick is removed rtl_433 does not exit.

keeps repeating:

rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
r82xx_write: i2c wr failed=-4 reg=17 len=1
r82xx_set_freq: failed=-4
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
WARNING: Failed to set center freq.
Failed to submit transfer 0!

in stead of gracefull exit or better try reinit/reconnect to stick

**Comment by killerbees19** [comment]
+1 for this! 🤓

It's using 100% CPU…

**Comment by zuckschwerdt** [comment]
What are the exact command line options you use, and what specific OS?

**Comment by killerbees19** [comment]
OS: Debian Jessie
Command: `rtl_433 -R 19 -R 50 -R 55 -g 50 -l 1 -F json -T 900`

But I think I've found a simple fix: https://github.com/froonix/rtl_433/commit/8e606bde58269578fdb6e51c13cb07a2e73d7423

```
cb transfer status: 1, canceling...
WARNING: async read failed.

Library error -5, exiting...
```

**Comment by killerbees19** [comment]
Thanks for merging! :-)

I think this issue could be closed now, what do you think?
