### ISSUE TITLE
RSSI, SNR, Noise, and Freq all 0

### ISSUE THREAD

**Issue by ALEEF02** [merbanan/rtl_433#1363]
Hey guys,
I'm trying to use rtl_433 to intercept the packets from my weather devices. I am trying to best position my antenna, so I activated the `-M level` to see the SNR. But, all the SNRs are 0, along with RSSI, Noise, and Freq. Is this an issue on my end? Thanks 👍 
![image](https://user-images.githubusercontent.com/12904259/80178997-71519180-85b4-11ea-9790-11caf99573c2.png)

**Comment by zuckschwerdt** [comment]
There should be no code path where all those values are `0`. What version are you running?

**Comment by ALEEF02** [comment]
I am on commit https://github.com/merbanan/rtl_433/commit/c47bef0815e5240253236c023f21deeff5979058

**Comment by ALEEF02** [comment]
Further testing shows that this seems to only be happening with 915MHz, not 433.92MHz @zuckschwerdt 
![image](https://user-images.githubusercontent.com/12904259/80247972-e1e3c700-8623-11ea-8596-6d315641f107.png)

**Comment by merbanan** [comment]
Can you try adding -Y classic -s 1000k ?

**Comment by ALEEF02** [comment]
@merbanan That's working!
![image](https://user-images.githubusercontent.com/12904259/80253742-aa2e4c80-862e-11ea-84fb-71fcfef0f149.png)

**Comment by merbanan** [comment]
The new fsk demod code is missing some calculations.

**Comment by ALEEF02** [comment]
Is there a fix on the way, or should I continue to use `-Y classic -s 1000k` and close this issue?

**Comment by zuckschwerdt** [comment]
We do want to have this fixed ;)

**Comment by zuckschwerdt** [comment]
It's fixed. Thanks for the detailed report!
