### ISSUE TITLE
Manual gain settings unable to find signals that work fine in "auto"

### ISSUE THREAD

**Issue by courtarro** [merbanan/rtl_433#1366]
I have several strong signals nearby from a weather station at 915M. With auto gain, I have no trouble receiving them:

    rtl_433 -M level -Y classic -f 915000000 -s 250000

I use classic mode because I want the SNR levels. This works fine and yields packets with an SNR of about 30dB. However, when I manually set the gain to any value:

    rtl_433 -M level -Y classic -f 915000000 -s 250000 -g 15

I receive **no packets**. I tried gains `[1.4, 8.7, 15.7, 20.7, 25.4, 32.8, 36.4, 42.1, 49.6]`. Is there something about auto gain mode that changes when the gain is manually set? I notice that the RTL-SDR architecture often includes multiple gain levels and AGCs. Are these possibly the reason I'm having this problem?

My main reason for wanting to set the gain manually is avoiding variation in when and how the signals are received, since the transmitter and receiver have fixed position. I don't want other nearby signals to affect the gain levels and potentially disrupt my signal of interest.

**Comment by zuckschwerdt** [comment]
AFAIK, it should work. Maybe you can record short samples with auto and some other gains and compare. Use e.g. `rtl_433 -M level -Y classic -f 915M -s 250k -g 15 -w test-gain15.cu8 -T 10s` and https://triq.org/iqs/

**Comment by theasp** [comment]
Neat site!  I also can't capture anything when setting the gain. I've captured 0db, 15db and 40db and 49.6db here:
https://industrial.gt0.ca/~asp/rtl_443/

0db is quite a bit stronger than 49.6db, so perhaps it turns the AGC on?

**Comment by merbanan** [comment]
0=auto

**Comment by theasp** [comment]
Yes, but then how do you control the gain independently of having AGC turned on?

**Comment by merbanan** [comment]
By using any values beside 0.

**Comment by merbanan** [comment]
The gain used is written in the command line output.

**Comment by theasp** [comment]
Ok, if I want a gain of 20, and AGC turned on, how can I do that?

**Comment by merbanan** [comment]
You can't. Either fixed gain or AGC.

**Comment by theasp** [comment]
With AGC on, what gain will be used?

**Comment by theasp** [comment]
I'm asking, because they can be set independently in other software.

**Comment by merbanan** [comment]
AGC = automatic gain control. So the actual gain used is unknown.

**Comment by merbanan** [comment]
Well the AGC is a property of the Realtek chip. The gain is a property of the tuner chip. AFAIK the AGC will override the manual gain but that might not correlate well with reality.

Exactly how all the gain stages work and how the AGC interacts with them is unknown to me. We have had this logic since the start of the project I think.

**Comment by theasp** [comment]
With sdrangel, this is what the waterfall looks like with the gain set to 25db:
![image](https://user-images.githubusercontent.com/7775024/81502514-ca0f7280-92b4-11ea-8dda-4a1f0f07c480.png)

25db with AGC:
![image](https://user-images.githubusercontent.com/7775024/81502585-37230800-92b5-11ea-8640-4cb8305f7c54.png)

40db with AGC:
![image](https://user-images.githubusercontent.com/7775024/81502640-78b3b300-92b5-11ea-9f48-6e9b82c4c4b3.png)

There may be a way to control them independently using using a SoapySDR device, which should do what @courtarro was looking for.

**Comment by theasp** [comment]
This should do it if rtl_443 is compiled with SoapySDR support:
```
rtl_433 -d driver=rtlsdr -t digital_agc=true -g TUNER=30
```

**Comment by gdt** [comment]
What's the status of this issue?  Is there a bug?

**Comment by ksaye** [comment]
I see the same issue.  When using autogain, it sees packets just fine.  When setting the gain "-g 1" through "-g 50", I do not see packets.

I think I am seeing autogain change, as I guess it should, in normal operation.  When autogain is set, over time it stops picking up wanted packets (reading the water meter, protocol 149) and I have to restart rtl_433 to see them again.  My hopes are that I can find a desired setting and force it and not have to restart.

**Comment by gdt** [comment]
@ksaye Are you using recent git master?  What kind of tuner?   Have you tried -20 through 0 (not really sure; there is apparently negative gain, and running with lots of -v and all -M options is advisable).

**Comment by ksaye** [comment]
> @ksaye Are you using recent git master? What kind of tuner? Have you tried -20 through 0 (not really sure; there is apparently negative gain, and running with lots of -v and all -M options is advisable).

I am running version 20.11-1, from the package store on a Pi3:

      apt list --installed | grep rtl
      
      WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
      
      librtlsdr0/stable,now 0.6.0-3 armhf [installed,automatic]
      rtl-433/stable,now 20.11-1 armhf [installed]
      soapysdr0.7-module-rtlsdr/stable,now 0.3.0-2 armhf [installed,automatic]

The tuner is just an inexpensive USB RTL2838:

      trying device  0:  Realtek, RTL2838UHIDIR, SN: 915

Trying the command: "rtl_433 -g -20 -F json -M level -R 149 -f 914M" I get no messages.

      rtl_433 -g -20 -F json -M level -R 149 -f 914M
      rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
      Use -h for usage help and see https://triq.org/ for documentation.
      Trying conf file at "rtl_433.conf"...
      Trying conf file at "/home/ksaye/.config/rtl_433/rtl_433.conf"...
      Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
      Trying conf file at "/etc/rtl_433/rtl_433.conf"...
      
      New defaults active, use "-Y classic -s 250k" for the old defaults!
      
      Registered 1 out of 175 device decoding protocols [ 149 ]
      Found Rafael Micro R820T tuner
      Exact sample rate is: 1000000.026491 Hz
      [R82XX] PLL not locked!
      Sample rate set to 1000000 S/s.
      Tuner gain set to 0.000000 dB.
      Tuned to 914.000MHz.
      Allocating 15 zero-copy buffers

Based on your comments, I have tried (in Docker) to build it from GitHub and running the command:

      rtl_433 version nightly-1-g72c0f21b branch master at 202309292256 inputs file rtl_tcp RTL-SDR with TLS
      rtl_433 -F json -g 20 -M level -R 149 -f 914M

I am able to see some messages, so perhaps the issue is only with the build in the package store?

      2023-10-02 11:36:26.157750 Running command rtl_433 -F json -g 20 -M level -R 149 -f 914M
      2023-10-02 11:37:34.043721 {"time" : "2023-10-02 11:37:33", "model" : "ERT-SCM", "id" : 26732440, "physical_tamper" : 0, "ert_type" : 13, "encoder_tamper" : 2, "consumption_data" : 126575, "mic" : "CRC", "mod" : "ASK", "freq" : 914.017, "rssi" : -11.392, "snr" : 21.209, "noise" : -32.602}

I will continue to monitor it with the "-g 20" setting, and assuming all goes well, I will withdrawal my question.

**Comment by gdt** [comment]
Thanks.  20.11 is too old and how it behaves is out of scope for the tracker, so building and testing with recent is indeed the right approach.

**Comment by ksaye** [comment]
@gdt, when using autogain, is there anyway to read the current gain setting from the R820T?

**Comment by gdt** [comment]
I don't know.  I'd suggest reading the pgogramming documention for the R820T.

**Comment by zuckschwerdt** [comment]
> when using autogain, is there anyway to read the current gain setting from the R820T?

Solid no.

If you get to try a newer version of rtl_433 note that there is now also `-Y autolevel` which will help to read signals at what would usually be too low gain settings.

We can't really help with RTL-SDR gain settings. But note that automatic gain (gain=0) is not the same as AGC (automatic gain control), which might additionally be needed (`-t digital_agc=1`).

If you try different gains then record samples (`-S all)` or better the channel (e.g. `-w myfile_433.92M_250k.cu8 -T 20`) and compare the waterfall on https://triq.org/pdv/

**Comment by ksaye** [comment]
> > when using autogain, is there anyway to read the current gain setting from the R820T?
> 
> Solid no.
> 
> If you get to try a newer version of rtl_433 note that there is now also `-Y autolevel` which will help to read signals at what would usually be too low gain settings.
> 
> We can't really help with RTL-SDR gain settings. But note that automatic gain (gain=0) is not the same as AGC (automatic gain control), which might additionally be needed (`-t digital_agc=1`).
> 
> If you try different gains then record samples (`-S all)` or better the channel (e.g. `-w myfile_433.92M_250k.cu8 -T 20`) and compare the waterfall on https://triq.org/pdv/

Thanks for the clarity and I do agree that this issue should be closed, since it has been proven that when using the '-g 20' switch I can see messages when using a build from this repo.

**Comment by eigenphase** [comment]
Hi @zuckschwerdt you closed this issue but reading through it I can't find a conclusion on what's going on. I am still seeing the same issue.

I have written this simple script in an attempt to find the optimum gain setting from a distant weather station:

```
#!/bin/bash

# valid gain settings
# output from rtl_test -t
gains="0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6"

for g in $gains
do
    echo "*** GAIN $g"

    timeout --kill-after=15 20 /usr/local/bin/rtl_433 -f 433940000 -F mqtt://**** -F kv -M time:unix:usec:utc -M level -M noise -M stats -C si  -R 213 -g $g 2>&1 | grep -E "RSSI|SNR"

done
```

The output is:

```
# ./test_gain.sh 
*** GAIN 0.0
RSSI      : -11.0 dB     SNR       : 9.4 dB        Noise     : -20.4 dB
RSSI      : -10.9 dB     SNR       : 13.7 dB       Noise     : -24.7 dB
*** GAIN 0.9
*** GAIN 1.4
*** GAIN 2.7
*** GAIN 3.7
*** GAIN 7.7
*** GAIN 8.7
*** GAIN 12.5
*** GAIN 14.4
*** GAIN 15.7
*** GAIN 16.6
*** GAIN 19.7
*** GAIN 20.7
*** GAIN 22.9
*** GAIN 25.4
*** GAIN 28.0
*** GAIN 29.7
*** GAIN 32.8
*** GAIN 33.8
*** GAIN 36.4
*** GAIN 37.2
*** GAIN 38.6
*** GAIN 40.2
*** GAIN 42.1
*** GAIN 43.4
*** GAIN 43.9
*** GAIN 44.5
*** GAIN 48.0
*** GAIN 49.6
```

So, as some people report here, I am getting a signal with `-g 0` but with no other gain setting. This doesn't make sense.

**Comment by DennisKehrig** [comment]
@eigenphase Note that `-g 0` and `-g 0.0` set the gain to auto, if you want no gain, use a negative number, for example `-g -1` (might be a side effect of arguments bounds checking).
Also add `-v` as the first parameter if you want to get confirmation that the expected gain level is set.

```
rtl_433 -v -g 0
...
[SDR] Tuner gain set to Auto.
```

```
rtl_433 -v -g -1
...
[SDR] Tuner gain set to 0.000000 dB.
```

Edit: I haven't read the whole thread, maybe this doesn't apply to SoapySDR, please ignore if that's the case.

**Comment by eigenphase** [comment]
@DennisKehrig but I do want gain, I just want it to be statically set. With `-g 0` there will still be a gain, it's just not known. This must correspond to one of the manual gain settings.

> Also add -v as the first parameter if you want to get confirmation that the expected gain level is set.

Yep, it is:

> [SDR] Tuner gain set to Auto.
> [...]
> [SDR] Tuner gain set to 22.900000 dB.

> Edit: I haven't read the whole thread, maybe this doesn't apply to SoapySDR, 

It's RTL-SDR for me, not SoapySDR

**Comment by zuckschwerdt** [comment]
If the input signal is not in the optimal range of at least -12 dB then you'll need `-Y autolevel` to accept lower level signals given the noise floor is lower still.
