### ISSUE TITLE
Honeywell-Security devices ignore reed switch.

### ISSUE THREAD

**Issue by thetic** [merbanan/rtl_433#1383]
At least some models (eg Honeywell 5816, 2GIG DW10) support both wired contact switches and magnetic reed switches. On cursory inspection, reed switch state is encoded in bit 5 of the event field, but is ignored in decoding. State is [currently assigned](https://github.com/merbanan/rtl_433/blob/master/src/devices/honeywell.c#L98) as `(event & 0x80) >> 7`, but I think it should be `(event & 0x80) && (event & 0x20)`. I'm not sure whether this would be considered a breaking change or if there is a means to support both sensors discretely.

**Comment by gdt** [comment]
Looks like this was fixed with #1384.  Please comment if that's wrong.
