### ISSUE TITLE
Not able to update to version 20.02 on Ubuntu 18.04

### ISSUE THREAD

**Issue by taylormia** [merbanan/rtl_433#1408]
I am on rtl_433 v.19.08 on Ubuntu 18.04. I would like to update to version 20.02 but its not available in the repos. I'm looking to use a Sonoff RM433 which was added in v. 20.02. Is there any way to get support for this device without upgrading to 20.02 or upgrade to v. 20.02 without upgrading Ubuntu to 20.04?

**Comment by zuckschwerdt** [comment]
Perhaps someone else can explain how to override PPA selection?

But good news: The Sonoff RM433 is supported as flex config: https://github.com/merbanan/rtl_433/blob/master/conf/sonoff_rm433.conf
Just include that in your config file (use `config_file` in your rtl_433.conf or copy and paste).
