### ISSUE TITLE
sigrok / pulseview issue 

### ISSUE THREAD

**Issue by evilpete** [merbanan/rtl_433#1409]
While working with a yardstick one I was using rtl_443 to validate transmissions.
(was trying to spoof a LaCrosse sensor as an exercise) 

when I used rtl_433 to view saved data file it rtl_443 fails with out error, 
I am able to view the data in audacity  and see the iq waveforms so I assume the recorded data is valid

sampled with:
`rtl_433 -f 914.9M -R 75 -R 76 -s 2048k  -vv -S unknown`

View command:
`rtl_433 -f 914.9M -R 75 -R 76 -s 2048k -W output.sr -r g003_914.9M_2048k.cu8`

[g003_914.9M_2048k.cu8.gz](https://github.com/merbanan/rtl_433/files/4796864/g003_914.9M_2048k.cu8.gz)
[g015_915M_2048k.cu8.gz](https://github.com/merbanan/rtl_433/files/4796865/g015_915M_2048k.cu8.gz)

**Comment by zuckschwerdt** [comment]
Fixed with 0da03c3. Thanks!
