### ISSUE TITLE
Support for headerless Radiohead raw data

### ISSUE THREAD

**Issue by hisnameishb** [merbanan/rtl_433#1419]
rlt_433 missinterprets the packet length:
The real payload length ist 8 bytes with this content (dezimal code) of the payload:
50, 48, 46,54,56, 56, 0, 0

rtl_433 shows this:
model: RadioHead-ASK         Data len: 4    To: 50   From: 48   Id: 46
Flags: 54    Payload: 56, 56, 0, 0        Integrity : CRC

It missinterpretes the first 4 bytes of the payload as the fields "To", "From", "ID", "Flags"
Radiohead ASK has not such fields. It has iirc a meaningless preamble, a magicbyte, the payloadlength, the payload and two crc16 bytes

So it should show:
model: RadioHead-ASK     Data len: 8    To: -   From: -   Id: -
Payload: 50, 48, 46, 54, 56, 56, 0, 0    Integrity : CRC

**Comment by zuckschwerdt** [comment]
The decoder is about "RadioHead Datagrams". Maybe we can add a raw RadioHead option, but I'd need links to the documention about that mode.

**Comment by gdt** [comment]
@hisnameishb Are you still working on this?  Would you want to propose a specific change?
