### ISSUE TITLE
Sensor causes rtl_433 to exit.

### ISSUE THREAD

**Issue by fyvfy** [merbanan/rtl_433#1436]
After running for about 8-40 hours rtl_433 aborts with these error messages:
>rtl_433 -M protocol -M level

>Decoder "Abarth 124 Spider TPMS" gave invalid return value -6: notify maintainer

>pulse_FSK_detect(): Maximum number of pulses reached!
>Decoder "Abarth 124 Spider TPMS" gave invalid return value -6: notify maintainer

>Decoder "Abarth 124 Spider TPMS" gave invalid return value -9: notify maintainer

**Comment by merbanan** [comment]
Found an issue with the code. Should be fixed.
