### ISSUE TITLE
Unknown keyword when option put in .conf file  

### ISSUE THREAD

**Issue by GHSTUDIO1** [merbanan/rtl_433#1453]
If I start rtl_433 with the following command, it starts normally:

rtl_433 -V

if I create a rtl_433.conf file containing

-V

and I start rtl_433, I get the following:

rtl_433 version 20.02-108-ge64d3e5 branch master at 202007291509 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Reading conf from "rtl_433.conf".
Unknown keyword "-V"

I have tried this with various options in the .conf file and I always get the same "unknown keyword" message. Is there some format for the .conf file...I'm just entering a single line containing -V.    I've also tried "-V" with the same result.

Running headless Debian on Raspberry Pi 0 W.

**Comment by zuckschwerdt** [comment]
The config file uses a more verbose syntax, see https://github.com/merbanan/rtl_433/blob/master/conf/rtl_433.example.conf for reference.
