### ISSUE TITLE
No SoapySDR support in Windows binary builds

### ISSUE THREAD

**Issue by bluegizmo83** [merbanan/rtl_433#1456]
I'm using the newest July 2020 RTL_433 windows binary and I cannot get the SoapySDR driver to work. 

SoapySDR is installed and working properly. SoapySDRUtil finds my HackRF just fine. However, when I try to use the `-d driver=hackrf` command with RTL_433 it just doesn't seem to do anything and immediately drops back to the command prompt. The RX light on the HackRF also never lights up. See image of command prompt below.
![rtl_433](https://user-images.githubusercontent.com/1000998/89358199-f2bec280-d67f-11ea-953f-83c4e6b52f77.jpg)

EDIT: It appears that none of the compiled Windows binaries that are linked to in the Readme actually contain SoapySDR support, is that true? Why on earth would they be compiled without support for SoapySDR?

**Comment by zuckschwerdt** [comment]
The provided Windows binaries are compiled without SoapySDR support.
PR on https://github.com/merbanan/rtl_433/blob/master/do_sysroot.sh appreciated.
