### ISSUE TITLE
AlectoV1 wrong field names

### ISSUE THREAD

**Issue by marki555** [merbanan/rtl_433#1457]
It seems that AlectoV1 has wrong field names defined, which causes the wind speed to be ommited from csv data, but is displayed in default KV output.

```
root@rpi5:/home/pi/new433/rtl_433/build/src# ./rtl_433 -d 1 -F csv -F kv -R 16
Registered 1 out of 163 device decoding protocols [ 16 ]
time,msg,codes,model,id,channel,battery_ok,temperature_C,humidity,rain_total,rain_mm,wind_speed,wind_gust,wind_direction,wind_avg_km_h,wind_max_km_h,wind_dir_deg,mic
2020-08-06 23:07:44,,,AlectoV1-Wind,33,1,0,,,,,,,,,,315,CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-08-06 23:07:44
model     : AlectoV1-Wind House Code: 33
Channel   : 1            Battery   : 0             Wind speed: 0.40 m/s      Wind gust : 0.60 m/s      Wind Direction: 315
Integrity : CHECKSUM
```
In https://github.com/merbanan/rtl_433/blob/9c117521f0570c86eda651c1237c3d796bfbb62d/src/devices/alecto.c#L166 it data_make()s "wind_avg_m_s" and "wind_max_m_s", but later https://github.com/merbanan/rtl_433/blob/9c117521f0570c86eda651c1237c3d796bfbb62d/src/devices/alecto.c#L236 in `output_fields` it is "wind_avg_km_h" and "wind_max_km_h".
After changing it to m_s names in the  `output_fields` it outputs the values also in csv.

**Comment by merbanan** [comment]
Please send a PR and we will merge the change.
