### ISSUE TITLE
ook to pulseview conversion gives empty file

### ISSUE THREAD

**Issue by merbanan** [merbanan/rtl_433#1463]
Command line example.

rtl_433 -r g001_433.92M_250k.ook -W test.sr

**Comment by zuckschwerdt** [comment]
This would need special handling as the OOK data doesn't contain the raw data we need for SR. I'd say it isn't even useful as we would ever only get the OOK pulses as (graphical) output. https://triq.org/pdv/ can do that more versatile.
I guess I'll just add an error message for this case.
