### ISSUE TITLE
rflink No supported devices found

### ISSUE THREAD

**Issue by mpuff** [merbanan/rtl_433#1472]
Hello,

i have installed rflink with an Arduino SA Mega 2560 R3.
it is plugged via usb, its /dev/ttyACM0.

when i try to strat rtl_433 i get the text:

tl_433 version 20.02-125-g57c924d branch master at 202008102239 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/pi/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 134 out of 163 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163 ]
**No supported devices found.**

what can i do that the rflink is supportet or can i create a config that rflink_433 use /dev/ttyACM0?

**Comment by zuckschwerdt** [comment]
rflink is not an SDR source, the output of rflink should already be something like the output of rtl_433. You'll only want rtl_433 if you have an SDR device like RTL-SDR or some SoapySDR supported device like HackRF, LimeSDR, Pluto, SDRplay, …
