### ISSUE TITLE
SCM+ duplicate devices

### ISSUE THREAD

**Issue by JonGilmore** [merbanan/rtl_433#1503]
I'm running rtl_433 with the following: 
```
/usr/local/bin/rtl_433 -d 1 -f 915M -F "mqtt://192.168.45.249:1883,user=username,pass=password,retain=1,events=rtl_915[/model][/id]"
```
this works well for an `ERT-SCM` device, but doesn't work well for my SCM+ water meter. The SDR picks up multiple water meters from around the neighborhood and values jump all over the place because it doesn't have an `id`. Can I filter this differently so this doesn't happen? I've shown a screenshot from MQTT Explorer below

![image](https://user-images.githubusercontent.com/7232986/94760374-f6ad4f00-0367-11eb-8f42-989d1c02f703.png)

**Comment by zuckschwerdt** [comment]
Is the "EndpointID" field unique to the different meters? Perhaps we should map that to "id"? Also "PacketCRC" should likely be dropped, keys lowercased, and the "+"...

**Comment by JonGilmore** [comment]
> Is the "EndpointID" field unique to the different meters? Perhaps we should map that to "id"? Also "PacketCRC" should likely be dropped, keys lowercased, and the "+"...

Yes, `EndpointID` is unique for the different meters near me. I think it would make sense to map to `id`, that would seem to follow standards of other devices that I have observed using this. I'm happy to help contribute with what is necessary to upstream these changes, but I'm no C developer and SDR's are brand new to me :/ 
Let me know what you need from me, I'm happy to help!

**Comment by merbanan** [comment]
> s the "EndpointID" field unique to the different meters? Perhaps we should map that to "id"? Also "PacketCRC" should likely be dropped, keys lowercased, and the "+"...

The reason for the naming is to keep compatibility with rtlamr IIRC. Maybe add a duplicate id key?

**Comment by JonGilmore** [comment]
> The reason for the naming is to keep compatibility with rtlamr IIRC. Maybe add a duplicate id key?

Ahh yeah, that would make sense. I think a duplicate key would solve my issue

**Comment by zuckschwerdt** [comment]
`id` and some notes added, esp. "SCM+" is a bad MQTT topic name.

**Comment by JonGilmore** [comment]
thanks @zuckschwerdt - I just confirmed this fixed my issues :D
