### ISSUE TITLE
HackRF and Windows problem ?

### ISSUE THREAD

**Issue by schmiernippel** [merbanan/rtl_433#1530]
Is it possible to use my hackrf with rtl_433 on windows with this soapy drivers ? I dont get it howto...?

When its possible, can someone please write a quick tutorial ?

greets

**Comment by zuckschwerdt** [comment]
Yes, you need to compile or install SoapySDR and drivers, then build rtl_433 with `-DENABLE_SOAPYSDR=ON `.
There are some hints in https://github.com/merbanan/rtl_433/blob/master/docs/BUILDING.md

**Comment by schmiernippel** [comment]
I have installed soapySDR(photosSDR)but my knowledge is to less to build rtl_433 by myself... but thanks for your answer !

**Comment by zuckschwerdt** [comment]
It is somewhat involved to get the drivers included. Basically some trial and error to get all paths setup. Do you have any experience with either MinGW or Visual Studio?
We currently don't provide binaries with SoapySDR support as getting all dependencies setup is tricky. I might take a look at that, would you be interested in testing some builds? It could be some back and forth until we get it right though.

**Comment by schmiernippel** [comment]
I have no experience in MinGW or visual studio. But i would like to test some builds, this would be nice !

**Comment by zuckschwerdt** [comment]
Can you try rtl_433-20.02-195-gc92751e-win-x64.zip from https://bintray.com/beta/#/chzu/dist/rtl_433/20.02-195-gc92751e?tab=files
Then not-static version should include support for SoapySDR.

**Comment by schmiernippel** [comment]
I have installed PhotosSDR with the SoapySDR drivers and have run rtl_433.exe. No supportet device found....
CubicSDR, GQRX SDR, SDR# are working nice.
Any workaround what should i do ?

**Comment by zuckschwerdt** [comment]
That is the first line in the output of `rtl_433.exe`?

**Comment by schmiernippel** [comment]
Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\schmiernippel>C:\Daten\Downloads\SDR\rtl_433\Soapy_support\rtl_433.exe
rtl_433 version 20.02-195-gc92751e branch  at 202010231657 inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "C:\Daten\Downloads\SDR\rtl_433\Soapy_support\rtl_433.conf"...
Trying conf file at "C:\Users\schmiernippel\AppData\Local\rtl_433\rtl_433.conf"...
Trying conf file at "C:\ProgramData\rtl_433\rtl_433.conf"...
Registered 139 out of 168 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 ]
No supported devices found.

C:\Users\schmiernippel>



Thats the output!

**Comment by zuckschwerdt** [comment]
Great! That looks fine.
`rtl_433 version 20.02-195-gc92751e branch at 202010231657 inputs file rtl_tcp RTL-SDR SoapySDR` <-
And selecting your HackRF doesn't work? I.e. `rtl_433 -d driver=hackrf`

**Comment by schmiernippel** [comment]
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\schmiernippel>C:\Daten\Downloads\SDR\rtl_433\Soapy_support\rtl_433.exe -d driver=hackrf
rtl_433 version 20.02-195-gc92751e branch  at 202010231657 inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "C:\Daten\Downloads\SDR\rtl_433\Soapy_support\rtl_433.conf"...
Trying conf file at "C:\Users\schmiernippel\AppData\Local\rtl_433\rtl_433.conf"...
Trying conf file at "C:\ProgramData\rtl_433\rtl_433.conf"...
Registered 139 out of 168 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 ]

C:\Users\schmiernippel>

The same output, without "No supportet devices found."

**Comment by zuckschwerdt** [comment]
The build includes the SoapySDR.dll from the https://downloads.myriadrf.org/builds/PothosSDR/PothosSDR-2020.01.26-vc14-x64.exe version found on https://downloads.myriadrf.org/builds/PothosSDR/
Is that the same version you have installed?
Perhaps just copy `rtl_433.exe` to the directory where PothosSDR installed all the .exe and .dll, do not copy `SoapySDR.dll` so your version is used --  it should already be in that directory along with `libusb-1.0.dll`.
Running `SoapySDRUtil.exe --info` does list the HackRF module, right? And `--probe` or `--make` show the HackRF?

**Comment by schmiernippel** [comment]
"libusb-1.0.dll" was not in the folder "C:\Program Files\PothosSDR\bin". So i copied it.

C:\Users\schmiernippel>"C:\Program Files\PothosSDR\bin\rtl_433.exe" -d driver=hackrf
rtl_433 version 20.02-195-gc92751e branch  at 202010231657 inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "C:\Program Files\PothosSDR\bin\rtl_433.conf"...
Trying conf file at "C:\Users\schmiernippel\AppData\Local\rtl_433\rtl_433.conf"...
Trying conf file at "C:\ProgramData\rtl_433\rtl_433.conf"...
Registered 139 out of 168 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 ]
[INFO] Opening HackRF One #0 17c467dc2154bbc3...

C:\Users\schmiernippel>

And here is the SoapySDRUtil.exe Output:

C:\Users\schmiernippel>"C:\Program Files\PothosSDR\bin\SoapySDRUtil.exe" --info
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Lib Version: v0.8.0-PothosSDR-2020.01.26-vc14-x64
API Version: v0.8.0
ABI Version: v0.8
Install root: C:\Program Files\PothosSDR
Search path:  C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/airspyhfSupport.dll (0.1.1-81ca737)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/airspySupport.dll   (0.1.2-10d697b)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/audioSupport.dll    (0.1.1-2ae84e3)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/bladeRFSupport.dll  (0.4.1-1c1e8aa)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/HackRFSupport.dll   (0.3.3-3c514ce)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/IrisSupport.dll     (2019.07.0.1-423a351)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/LMS7Support.dll     (19.04.1-538e186b)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/miriSupport.dll     (0.2.6-5a9674c)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/netSDRSupport.dll   (0.1.0-dc4e579)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/osmosdrSupport.dll  (0.2.6-5a9674c)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/PlutoSDRSupport.dll (0.2.0-e28e4f5)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/RedPitaya.dll       (0.1.1-3d576f8)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/remoteSupport.dll   (0.5.2-6d9bd82)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/rtlsdrSupport.dll   (0.3.1-8ba18f1)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/sdrPlaySupport.dll  (0.3.0-14ec39e)
Module found: C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/uhdSupport.dll      (0.3.6-47972ba)
Available factories... airspy, airspyhf, audio, bladerf, hackrf, iris, lime, miri, netsdr, osmosdr, plutosdr, redpitaya, remote, rtlsdr, sdrplay, uhd
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8]

C:\Users\schmiernippel>"C:\Program Files\PothosSDR\bin\SoapySDRUtil.exe" --probe
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Probe device
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.15.0.0-0-gaea0e2de

----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=Audio
  hardware=Audio
  device_id=0
  origin=https://github.com/pothosware/SoapyAudio

----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 0 Tx
  Timestamps: NO
  Other Settings:
     * Stereo Sample Offset - Offset stereo samples for off-by-one audio inputs.
       [key=sample_offset, default=0, type=string, options=(-2, -1, 0, 1, 2)]

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: NO
  Supports AGC: YES
  Stream formats: CS8, CS16, CF32
  Native format: CS16 [full-scale=65536]
  Stream args:
     * Channel Setup - Input channel configuration.
       [key=chan, default=mono_l, type=string, options=(mono_l, mono_r, stereo_iq, stereo_qi)]
  Antennas: RX
  Full gain range: [0, 0] dB
  Full freq range: [0, 6000] MHz
    RF freq range: [0, 6000] MHz
  Sample rates: 0.004, 0.005512, 0.008, 0.0096, 0.011025, 0.048, 0.0882, 0.096, 0.1764, 0.192 MSps



C:\Users\schmiernippel>"C:\Program Files\PothosSDR\bin\SoapySDRUtil.exe" --make
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Make device
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.15.0.0-0-gaea0e2de
  driver=Audio
  hardware=Audio
  device_id=0
  origin=https://github.com/pothosware/SoapyAudio


C:\Users\schmiernippel>


I see no hackrf ? But in windows device manager its listed under "USB-devices" as "HackRF One"

**Comment by zuckschwerdt** [comment]
At least it does say ` [INFO] Opening HackRF One #0 17c467dc2154bbc3...` now. But immediatly stops? This could be the hackrf driver looking for a device but not finding it.
Does adding `-vv` get more useful info?
I suspect that the device is not available, perhaps blocked/in-use by another program? Some other user reported something about outdated firmware he had to update.

**Comment by schmiernippel** [comment]
This is with -vv 

C:\Users\schmiernippel>"C:\Program Files\PothosSDR\bin\rtl_433.exe" -d driver=hackrf -vv
rtl_433 version 20.02-195-gc92751e branch  at 202010231657 inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "C:\Program Files\PothosSDR\bin\rtl_433.conf"...
Trying conf file at "C:\Users\schmiernippel\AppData\Local\rtl_433\rtl_433.conf"...
Trying conf file at "C:\ProgramData\rtl_433\rtl_433.conf"...
Registering protocol [1] "Silvercrest Remote Control"
Registering protocol [2] "Rubicson Temperature Sensor"
Registering protocol [3] "Prologue, FreeTec NC-7104, NC-7159-675 temperature sensor"
Registering protocol [4] "Waveman Switch Transmitter"
Registering protocol [8] "LaCrosse TX Temperature / Humidity Sensor"
Registering protocol [11] "Acurite 609TXC Temperature and Humidity Sensor"
Registering protocol [12] "Oregon Scientific Weather Sensor"
Registering protocol [15] "KlikAanKlikUit Wireless Switch"
Registering protocol [16] "AlectoV1 Weather Sensor (Alecto WS3500 WS4500 Ventus W155/W044 Oregon)"
Registering protocol [17] "Cardin S466-TX2"
Registering protocol [18] "Fine Offset Electronics, WH2, WH5, Telldus Temperature/Humidity/Rain Sensor"
Registering protocol [19] "Nexus, FreeTec NC-7345, NX-3980, Solight TE82S, TFA 30.3209 temperature/humidity sensor"
Registering protocol [20] "Ambient Weather Temperature Sensor"
Registering protocol [21] "Calibeur RF-104 Sensor"
Registering protocol [23] "DSC Security Contact"
Registering protocol [25] "Globaltronics GT-WT-02 Sensor"
Registering protocol [26] "Danfoss CFR Thermostat"
Registering protocol [29] "Chuango Security Technology"
Registering protocol [30] "Generic Remote SC226x EV1527"
Registering protocol [31] "TFA-Twin-Plus-30.3049, Conrad KW9010, Ea2 BL999"
Registering protocol [32] "Fine Offset Electronics WH1080/WH3080 Weather Station"
Registering protocol [33] "WT450, WT260H, WT405H"
Registering protocol [34] "LaCrosse WS-2310 / WS-3600 Weather Station"
Registering protocol [35] "Esperanza EWS"
Registering protocol [36] "Efergy e2 classic"
Registering protocol [38] "Generic temperature sensor 1"
Registering protocol [39] "WG-PB12V1 Temperature Sensor"
Registering protocol [40] "Acurite 592TXR Temp/Humidity, 5n1 Weather Station, 6045 Lightning, 3N1, Atlas"
Registering protocol [41] "Acurite 986 Refrigerator / Freezer Thermometer"
Registering protocol [42] "HIDEKI TS04 Temperature, Humidity, Wind and Rain Sensor"
Registering protocol [43] "Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor"
Registering protocol [44] "CurrentCost Current Sensor"
Registering protocol [45] "emonTx OpenEnergyMonitor"
Registering protocol [46] "HT680 Remote control"
Registering protocol [47] "Conrad S3318P, FreeTec NC-5849-913 temperature humidity sensor"
Registering protocol [48] "Akhan 100F14 remote keyless entry"
Registering protocol [49] "Quhwa"
Registering protocol [50] "OSv1 Temperature Sensor"
Registering protocol [51] "Proove / Nexa / KlikAanKlikUit Wireless Switch"
Registering protocol [52] "Bresser Thermo-/Hygro-Sensor 3CH"
Registering protocol [53] "Springfield Temperature and Soil Moisture"
Registering protocol [54] "Oregon Scientific SL109H Remote Thermal Hygro Sensor"
Registering protocol [55] "Acurite 606TX Temperature Sensor"
Registering protocol [56] "TFA pool temperature sensor"
Registering protocol [57] "Kedsum Temperature & Humidity Sensor, Pearl NC-7415"
Registering protocol [58] "Blyss DC5-UK-WH"
Registering protocol [59] "Steelmate TPMS"
Registering protocol [60] "Schrader TPMS"
Registering protocol [63] "Efergy Optical"
Registering protocol [67] "Radiohead ASK"
Registering protocol [68] "Kerui PIR / Contact Sensor"
Registering protocol [69] "Fine Offset WH1050 Weather Station"
Registering protocol [70] "Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater"
Registering protocol [71] "Maverick ET-732/733 BBQ Sensor"
Registering protocol [73] "LaCrosse TX141-Bv2, TX141TH-Bv2, TX141-Bv3, TX141W, TX145wsdth sensor"
Registering protocol [74] "Acurite 00275rm,00276rm Temp/Humidity with optional probe"
Registering protocol [75] "LaCrosse TX35DTH-IT, TFA Dostmann 30.3155 Temperature/Humidity sensor"
Registering protocol [76] "LaCrosse TX29IT Temperature sensor"
Registering protocol [77] "Vaillant calorMatic VRT340f Central Heating Control"
Registering protocol [78] "Fine Offset Electronics, WH25, WH32B, WH24, WH65B, HP1000 Temperature/Humidity/Pressure Sensor"
Registering protocol [79] "Fine Offset Electronics, WH0530 Temperature/Rain Sensor"
Registering protocol [80] "IBIS beacon"
Registering protocol [81] "Oil Ultrasonic STANDARD FSK"
Registering protocol [82] "Citroen TPMS"
Registering protocol [83] "Oil Ultrasonic STANDARD ASK"
Registering protocol [84] "Thermopro TP11 Thermometer"
Registering protocol [85] "Solight TE44/TE66, EMOS E0107T, NX-6876-917"
Registering protocol [86] "Wireless Smoke and Heat Detector GS 558"
Registering protocol [87] "Generic wireless motion sensor"
Registering protocol [88] "Toyota TPMS"
Registering protocol [89] "Ford TPMS"
Registering protocol [90] "Renault TPMS"
Registering protocol [91] "inFactory, nor-tec, FreeTec NC-3982-913 temperature humidity sensor"
Registering protocol [92] "FT-004-B Temperature Sensor"
Registering protocol [93] "Ford Car Key"
Registering protocol [94] "Philips outdoor temperature sensor (type AJ3650)"
Registering protocol [95] "Schrader TPMS EG53MA4, PA66GF35"
Registering protocol [96] "Nexa"
Registering protocol [97] "Thermopro TP08/TP12/TP20 thermometer"
Registering protocol [98] "GE Color Effects"
Registering protocol [99] "X10 Security"
Registering protocol [100] "Interlogix GE UTC Security Devices"
Registering protocol [102] "SimpliSafe Home Security System (May require disabling automatic gain for KeyPad decodes)"
Registering protocol [103] "Sensible Living Mini-Plant Moisture Sensor"
Registering protocol [104] "Wireless M-Bus, Mode C&T, 100kbps (-f 868950000 -s 1200000)"
Registering protocol [105] "Wireless M-Bus, Mode S, 32.768kbps (-f 868300000 -s 1000000)"
Registering protocol [108] "Hyundai WS SENZOR Remote Temperature Sensor"
Registering protocol [109] "WT0124 Pool Thermometer"
Registering protocol [110] "PMV-107J (Toyota) TPMS"
Registering protocol [111] "Emos TTX201 Temperature Sensor"
Registering protocol [112] "Ambient Weather TX-8300 Temperature/Humidity Sensor"
Registering protocol [113] "Ambient Weather WH31E Thermo-Hygrometer Sensor, EcoWitt WH40 rain gauge"
Registering protocol [114] "Maverick et73"
Registering protocol [115] "Honeywell ActivLink, Wireless Doorbell"
Registering protocol [116] "Honeywell ActivLink, Wireless Doorbell (FSK)"
Registering protocol [119] "Bresser Weather Center 5-in-1"
Registering protocol [121] "Opus/Imagintronix XT300 Soil Moisture"
Registering protocol [124] "LaCrosse/ELV/Conrad WS7000/WS2500 weather sensors"
Registering protocol [125] "TS-FT002 Wireless Ultrasonic Tank Liquid Level Meter With Temperature Sensor"
Registering protocol [126] "Companion WTR001 Temperature Sensor"
Registering protocol [127] "Ecowitt Wireless Outdoor Thermometer WH53/WH0280/WH0281A"
Registering protocol [128] "DirecTV RC66RX Remote Control"
Registering protocol [130] "IKEA Sparsnas Energy Meter Monitor"
Registering protocol [131] "Microchip HCS200 KeeLoq Hopping Encoder based remotes"
Registering protocol [132] "TFA Dostmann 30.3196 T/H outdoor sensor"
Registering protocol [133] "Rubicson 48659 Thermometer"
Registering protocol [134] "Holman Industries iWeather WS5029 weather station (newer PCM)"
Registering protocol [135] "Philips outdoor temperature sensor (type AJ7010)"
Registering protocol [136] "ESIC EMT7110 power meter"
Registering protocol [137] "Globaltronics QUIGG GT-TMBBQ-05"
Registering protocol [138] "Globaltronics GT-WT-03 Sensor"
Registering protocol [139] "Norgo NGE101"
Registering protocol [140] "Elantra2012 TPMS"
Registering protocol [141] "Auriol HG02832, HG05124A-DCF, Rubicson 48957 temperature/humidity sensor"
Registering protocol [142] "Fine Offset Electronics/ECOWITT WH51 Soil Moisture Sensor"
Registering protocol [143] "Holman Industries iWeather WS5029 weather station (older PWM)"
Registering protocol [144] "TBH weather sensor"
Registering protocol [145] "WS2032 weather station"
Registering protocol [146] "Auriol AFW2A1 temperature/humidity sensor"
Registering protocol [147] "TFA Drop Rain Gauge 30.3233.01"
Registering protocol [148] "DSC Security Contact (WS4945)"
Registering protocol [149] "ERT"
Registering protocol [151] "Visonic powercode"
Registering protocol [152] "Eurochron EFTH-800 temperature and humidity sensor"
Registering protocol [153] "Cotech 36-7959 wireless weather station with USB"
Registering protocol [154] "Standard Consumption Message Plus (SCMplus)"
Registering protocol [155] "Fine Offset Electronics WH1080/WH3080 Weather Station (FSK)"
Registering protocol [156] "Abarth 124 Spider TPMS"
Registering protocol [157] "Missil ML0757 weather station"
Registering protocol [158] "Sharp SPC775 weather station"
Registering protocol [159] "Insteon"
Registering protocol [160] "Interval Data Message (IDM)"
Registering protocol [161] "Interval Data Message (IDM) for Net Meters"
Registering protocol [163] "Acurite 590TX Temperature with optional Humidity"
Registering protocol [164] "Security+ 2.0 (Keyfob)"
Registering protocol [165] "TFA Dostmann 30.3221.02 T/H Outdoor Sensor"
Registering protocol [166] "LaCrosse Technology View LTV-WSDTH01 Breeze Pro Wind Sensor"
Registering protocol [167] "Somfy RTS"
Registering protocol [168] "Schrader TPMS SMD3MA4 (Subaru)"
Registered 139 out of 168 device decoding protocols
[INFO] Opening HackRF One #0 17c467dc2154bbc3...
Using device HackRF One:
C:\Users\schmiernippel>


Is it possible that i must ad a line with settings for the hackrf ? Like gain and so on ??? 
Firmware is the newest for HackRF.

**Comment by zuckschwerdt** [comment]
Looks like rtl_433 is able to acquire a handle to the driver but the device isn't initializing or working.
You need to try things until `SoapySDRUtil.exe --make` works, then continue with rtl_433.

**Comment by schmiernippel** [comment]
Ok, thanks.I will google some stuff :-)

**Comment by merbanan** [comment]
No update in a long time, closing issue.
