### ISSUE TITLE
Measuring unit of the TFA-Dostmann rain-sensor 30.3161

### ISSUE THREAD

**Issue by rtega** [merbanan/rtl_433#1531]
According to this page https://forum.fhem.de/index.php?topic=85746.0 the TFA-Dostmann rain sensor 30.3161 has as measuring unit 0.45mm. This seems to fit my observations. Could somebody add this to the code here?
https://github.com/merbanan/rtl_433/blob/master/src/devices/inovalley-kw9015b.c

**Comment by zuckschwerdt** [comment]
Thanks, done.
