### ISSUE TITLE
Prologue-TH missing subtype in instance definition in rtl_433_mqtt_hass.py 

### ISSUE THREAD

**Issue by rotragit** [merbanan/rtl_433#1540]
Prologue-TH sensors have a subtype attribute:
```
{
    "time": "2020-10-29 04:32:58",
    "model": "Prologue-TH",
    "subtype": 5,
    "id": 37,
    "channel": 3,
    "battery_ok": 1,
    "temperature_C": 19.8,
    "humidity": 66,
    "button": 0
}
```

so the states are published in `rtl_433/[hostname]/devices/Prologue-TH/[subtype]/[channel]/[id]/humidity`

Adding the following lines between 394 and 395 solves the problem:

```
   if "subtype" in data:
        subtype = str(data["subtype"])
        instance = subtype + "/" + instance
```

**Comment by zuckschwerdt** [comment]
@rct is working on this in #1510 with some deeper analysis, please coordinate changes there.

**Comment by rct** [comment]
@rotragit - What does subtype: 5 represent for Prologue sensors?  Is that a message type?  Does the device only send a single value for that field?  If so the field name should probably be changed to `message_type` - see #1520 

@zuckschwerdt mentioned in @1510 `subtype` is intended to be used when there are somewhat distinct sub-devices that it makes sense to break out. This is why I believe it 

I'll also publish the fixes I have so far for the MQTT discovery script.

**Comment by zuckschwerdt** [comment]
For Prologue the first nibble really is a (hardware version?) type. We only ever see 9 and 5 and the value is fixed (i.e. "a Prologue9" or a "Prologue5" device), it could be seen as part of the ID though, https://github.com/merbanan/rtl_433/blob/master/src/devices/prologue.c#L19

**Comment by rct** [comment]
That does seem more like part of device identification rather than identifying a discrete sub-device.

**Comment by rotragit** [comment]
@zuckschwerdt I own only 3 Prologue sensors and all of them have number 5 as subtype. As I see there exists a "prologue IW007 weather station", I think the answer should be related to that: if the protocol is the same and the data are marked as subtypes then - probably - the subtype sholud be part of the id, if not than the subtype is some kind of hardware model and Prologue9, Prologue5 make sense.
I don't own that station, of course :-)
If you have no experience with that weather station, and because there is not a significant difference in the case of Prologue-TH sensors, I suggest to pass the subtype ias part of the id in the discovery script. And because the suggested version is general for any device that has a subtype, it probably will solve other problems with other sensors where the difference is not so important :-)

**Comment by zuckschwerdt** [comment]
When the Prologue decoder was written den first nibble was fixed to `9` and just seen/used as a check. Then later `5` was also seen.
So maybe we should have added the subtype to the ID back then. It is a breaking change and will invalidate ID for existing users, so we need to consider carefully if we want to break this :/

**Comment by rotragit** [comment]
> So maybe we should have added the subtype to the ID back then. It is a breaking change and will invalidate ID for existing users, so we need to consider carefully if we want to break this :/

I agree

**Comment by merbanan** [comment]
Well the id is randomly generated anyway so people will have to reconfigure anyway on battery replacement. If people use this sensor I think they will only care about the model. I'd say do the change after the new release.

**Comment by zuckschwerdt** [comment]
Good point, let's do that.

**Comment by rotragit** [comment]
I never have seen the id changed after a battery replacement on the Prologue-TH. I have also four Nexus-TH and yes, they have id changed after battery replacement (and that's very annoying...)

**Comment by merbanan** [comment]
@rotragit get wmbus sensors. Unique ids and 10+ years of battery.

**Comment by zuckschwerdt** [comment]
Uhh, nice. Can we get a list of tested and well behaving hardware?

**Comment by rotragit** [comment]
Never seen wmbus devices "affordable" :-)
Prologue-TH are not so bad for me, considering that I've got them for less than 10€ each....

**Comment by gdt** [comment]
Where are we on this?   Has the bugfix  been made?  If not, is @rotragit able to make a PR?

**Comment by gdt** [comment]
abandoned
