### ISSUE TITLE
Mqtt secure credentials

### ISSUE THREAD

**Issue by insipiens** [merbanan/rtl_433#1563]
I cannot see how I can parse the data to mqtt without exposing the username and password via the process. Can the configuration file contain the credentials? If so how....?

**Comment by zuckschwerdt** [comment]
Just copy the example. https://github.com/merbanan/rtl_433/blob/master/conf/rtl_433.example.conf#L171
I.e. `output mqtt://localhost:1883,user=USERNAME,pass=PASSWORD`
