### ISSUE TITLE
Interoperability with CS8 RF-dump format (HackRF)

### ISSUE THREAD

**Issue by iDoka** [merbanan/rtl_433#1567]
Hi again and thanks again for that great work.

AFAIK, CU8 using for RTLSDR as native format.

My case are: 
I dump RF by RTLSDR and try to replay on HackRF multiple time to debug my own RX-hardware.

My question are:
Google give me info that HackRF use own RF-dump format known as CS8 which unsupported on `rtl_433`. 
Unfortunately for `-r` and `-w` possible options are: 'cu8', 'cs16', 'cf32'

Strange things, I see mention CS8 format in src: https://github.com/merbanan/rtl_433/blob/master/src/rtl_433.c#L497

Any chances to supports CS8 in `rtl_433` (at least for `-w` option)?

**Comment by zuckschwerdt** [comment]
The help text is somewhat conservative. `.cs8` is supported when writing (`-w`) but not when reading (`-r`).
