### ISSUE TITLE
Bonjour au développeur web qui a créé le logiciel

### ISSUE THREAD

**Issue by gaspar1987** [merbanan/rtl_433#1568]
Bonjour au développeur web qui a créé le logiciel j'ai vu que vous avez écrit ce logiciel je l'ai utilisé il fonctionne à merveille mais il faut utiliser un amplificateur de fréquence et c'est ce qui permet d'avoir plus et j'ai pu capter des chauffage numérique partout dans ma ville j'ai eu les véhicules certains étaient des maisons avec des météo à distance je voudrais que vous me faites aussi un logiciel sur comment on écoute le compteur en France de de l'eau et du gaz c'est pour ça que je le sais que c'est impossible mais ça serait marrant d'écouter et savoir combien j'ai utilisé de gaz la journée ou des tricité avec les nouveaux compteurs c'est pour cela que ça qu'il existe des logiciels mais c'est ce n'est pas si c'est autorisé ou non autorisé bonne journée

**Google Translate**:
Hello to the web developer who created the software I saw that you wrote this software I used it it works wonderfully but you have to use a frequency amplifier and that's what allows you to have more and I I was able to collect digital heating everywhere in my city I had the vehicles some were houses with remote weather forecast I would like you to also make me a software on how we listen to the water and gas meter in France that's why I know it is impossible but it would be fun to listen and know how much gas I used during the day or tricity with the new meters that's why it exists software but it's not whether it's allowed or not allowed good day

**Comment by merbanan** [comment]
Bonjour, I think those meters are using 169MHz wmbus. If you are able to record signals we might be able to add support. You need to research this a lot more for this to be a possibility.
