### ISSUE TITLE
Protocol 19 (model Nexus-T) - no data reported when temperature is 0 degrees

### ISSUE THREAD

**Issue by badrpc** [merbanan/rtl_433#1576]
Hello,

I use rtl_433 to decode data from a couple of sensors and noticed that data from one of the sensors disappear when temperature crosses value of 0 degrees Celsius (see graph below). Temperature station is Auriol HG00073B and internal module will keep showing correct temperature even when it reaches 0. The model reported by rtl_433 is Nexus-T and the protocol number is 19. What can I do to help debug this problem further?

![image](https://user-images.githubusercontent.com/46691416/101292119-7262c680-3805-11eb-8625-7ed5da326f0e.png)

**Comment by zuckschwerdt** [comment]
Thanks for analyzing this so spot on. There was a bug with false positive detection at 0 degrees. Fixed!

**Comment by badrpc** [comment]
Wow! This was a very fast response with a fix. Thank you! I can confirm it works: 
![image](https://user-images.githubusercontent.com/46691416/101343083-5e59ac00-387b-11eb-89a7-50d8f353b347.png)
