### ISSUE TITLE
Support Cotech Wireless Rain Gauge E0013TRF-A1V-YX (Clas Ohlson art.no. 36-7900)

### ISSUE THREAD

**Issue by robinsmidsrod** [merbanan/rtl_433#1591]
I recently got this device, and I'd like to use it with rtl_433. Any chance of supporting it?

Here is the technical information I could gleam from the stickers and manual:

Cotech Wireless Rain Gauge
Clas Ohlson Art. no. 36-7900
Model no. E0330WST2 (Indoor unit)
Model no. E0013TRF-A1V-YX (Rain gauge)
433.92 MHz

https://www.manualslib.de/manual/559395/Cotech-E0330Wst2.html

What can I do to help this along?

**Comment by zuckschwerdt** [comment]
Verify the frequency with CubicSDR, Gqrx, or SDRangel.
Capture packets with `-S unknown`.
Check for a good signal with https://triq.org/pdv/ 
Run the analyzer mode `-A`
Post findings and a zipped packet sample here for more help.

**Comment by merbanan** [comment]
No update for a long time and no signal samples upload. Closing issue.

**Comment by robinsmidsrod** [comment]
@merbanan Sorry about that. Life has gotten in the way. I'll reopen once I have time to generate the required files.
