### ISSUE TITLE
How to output timestamps to MQTT in 12 hour format with "Day - 12:00 AM/PM" date code?

### ISSUE THREAD

**Issue by lucifudge** [merbanan/rtl_433#1601]
Saw the -time parameter, but don't understand what flags are needed to achieve this.

Or even simply "12:00 AM" output.

**Comment by zuckschwerdt** [comment]
The timestamp, and generally rtl_433's output is machine readable and not for immediate display purpose.
Best to use ISO format, which is a established and well supported standard, then format as wanted in your output/display.
