### ISSUE TITLE
Support Ardunino Nano with 433MHZ Transmitter

### ISSUE THREAD

**Issue by tiego-007** [merbanan/rtl_433#1607]
Hello, is it possible to transmit some sensors which are read out via an Arduini Nano with a 433Mhz Trasmitter so that it is possible to receive them with RTL_433?

Does anyone already have this running and could provide the Arduino project?
Many Thanks

**Comment by zuckschwerdt** [comment]
Look for RadioHead https://www.airspayce.com/mikem/arduino/RadioHead/ sample decoder https://github.com/merbanan/rtl_433/blob/master/src/devices/radiohead_ask.c

**Comment by merbanan** [comment]
Issue answered.
