### ISSUE TITLE
 question about rtl_433/src/devices/generic_temperature_sensor.c 

### ISSUE THREAD

**Issue by zillawilli** [merbanan/rtl_433#1613]
Hello
I have a question about rtl_433/src/devices/generic_temperature_sensor.c

The code says that 24 bits are received:
IIIIIIII BBTTTTTT TTTTTTTT
- I: 8 bit ID
- B: 2 bit? Battery?
- T: 12 bit temp
Is it possible that 2 bits are still missing, or is the temperature 14 bits or something else?

Thanks for your great work!
William

**Comment by zuckschwerdt** [comment]
That device was added in 1541670. Compared to other sensors I'd say 12 bit temperature is normal. The extra bits are more likely battery low and maybe a pairing / manual activation flag.
Best to connect a variable power supply or known flat batteries and investigate!
