### ISSUE TITLE
TFA 30.3208.02 recognized as Ambientweather-F007TH

### ISSUE THREAD

**Issue by fsasm** [merbanan/rtl_433#1622]
The TFA senders 30.3208.02 from the TFA "Klima-Monitor" 30.3054 are recognized as Ambientweather-F007TH by rtl_433. The packets are correctly decoded and show the correct values for channels, temperature and humidity. 

It would be nice to add the TFA product name and/or the product number to the documentation, i.e. Readme.md.

**Comment by zuckschwerdt** [comment]
Thanks!
