### ISSUE TITLE
owl 180 i 

### ISSUE THREAD

**Issue by lavileric** [merbanan/rtl_433#1623]
[oregon_scientific.c.txt](https://github.com/merbanan/rtl_433/files/5862162/oregon_scientific.c.txt)

owl 180 intuition are not recognized in current version of rtl_433. 

It is not possible attach as .c so I changed the suffix and attached proposed modified file as oregon_scentific.c.txt

lavileric

**Comment by zuckschwerdt** [comment]
Can you explain what is different betwenn `OWL 180` <-> `OWL 180 intuition`?

**Comment by lavileric** [comment]
OWL 180i, changes its identifier (0x25 instead of 0x26) and gives three measurement instead of 1 (one measurement per sensor). I was not able to compute the CRC.

There is also the measurement of total energy from time to time but it should be similar to OWL180.

**Comment by merbanan** [comment]
@lavileric you should upload some signal samples from the Owl 180i. I merged your code manually.
