### ISSUE TITLE
wmbus: Kamstrup Multical 21 water meter

### ISSUE THREAD

**Issue by xenos1984** [merbanan/rtl_433#1632]
**Update**: I realized that I had been using an old version (apparently the git version I compiled got installed alongside the one from the Ubuntu 20.04 repo, and the latter was given preference). With the current git version I get a lot more decoded data, even though it does not seem to make sense. I updated the issue below.

---

I recorded a few samples from two [Kamstrup Multical 21](http://optimatic.ee/en/products/ultrasonic-water-meters/kamstrup-multical-21/) water meters (cold and warm water), which are only partially decoded. The device sends data every 16 seconds, and I took samples while using water, so that the meter reading - if it is in the data - should change. There is quite a bit of information in [the datasheet](http://optimatic.ee/wp-content/uploads/2018/02/MULTICAL%C2%AE-21-Data-Sheet-English.pdf).

Command line: `rtl_433 -f 868950000 -s 1200000 -g 15 -R 104 -M hires -M level -S known`

Sample output:
```
time      : 2021-01-29 00:11:26.795651
model     : Wireless-MBus Mode      : C            Manufacturer: KAM         ID        : 76522329
Version   : 27           Device Type: 0x16         Device Type String: Cold Water                      Control   : 0x44          Data Length: 32           Data      : 21442d2c292352761b168d207fe2189c20e134e8e1577543a97d60942ae5c07f2d37
Integrity : CRC
Min Volume flow[0]: 2698.285 m3/min                Min Mass flow[0]: 144882.203 kg/h                   Unknown   : none
Modulation: FSK          Freq1     : 869.0 MHz     Freq2     : 869.1 MHz
RSSI      : -12.1 dB     SNR       : 18.2 dB       Noise     : -30.4 dB
```
Recorded data: [wmbus.zip](https://github.com/merbanan/rtl_433/files/5890307/wmbus.zip)

Related issue: #1626

**Comment by merbanan** [comment]
Compare the output with the decoded parameters from the https://github.com/weetmuts/wmbusmeters/ project. You can use rtl_433 decoding as input to wmbusmeters. I sort of aim to cover the OMS spec for rtl_433. Covering all the different proprietary wmbus devices would mean I would have to re-implement all the decoding that wmbusmeters has which would be redundant.

**Comment by xenos1984** [comment]
Thanks, that worked out!

Also as a comment to future readers of this issue, it turned out that I had forgotten to use the AES keys, since the meter data is encrypted.

**Comment by merbanan** [comment]
Yeah, aes support might come in the future. But I think my time is better served in other areas. Right now wmbusmeters is much better for wmbus support.
