### ISSUE TITLE
 rtl_433 -C si -F csv Parameters seem incompatible, drops to 'usage'

### ISSUE THREAD

**Issue by barjac** [merbanan/rtl_433#1634]
All in the summary.
csv works fine but adding the conversion to deg C breaks it.

**Comment by zuckschwerdt** [comment]
Can't reproduce.

**Comment by barjac** [comment]
OK problem resolved here. I was expecting the conversion to appear in field 46 of the csv but it is in field 9.
Thanks for checking.
