### ISSUE TITLE
GPLv3 licensing

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1645]
Maybe we should ask all authors to relicense (and hope they don't mind) to GPLv2+. Because some parts are licensed GPLv3-only, which makes the whole tool GPLv3 because the rest is GPLv2+. Or we should make clear that the result of linking is GPLv3 in the README / LICENSE.

We should also check if no GPLv2-only code is in the repo, as that would be incompatible with GPLv3-only.

For initial discussion see https://github.com/merbanan/rtl_433/pull/1642

- [ ] List of authors to ping
- [ ] Add Github action for checking licenses

- [x] fs20.c, should be removed and implemented as a conf
- [x] brennenstuhl_rcs_2044.c, should be removed and implemented as a conf
- [x] tfa_twin_plus_30.3049.c, one line of code is left from the initial commit
- [x] gt_wt_02.c, no main code from the initial implementation is left, can be re-licensed IMO
- [x] cardin.c : GPL2-only
- [x] newkaku.c : copyright missing
- [x] oregon_scientific_sl109h.c : copyright missing
- [x] prologue.c : copyright missing
- [x] git-version-gen, not part of rtl_433 binary so it should be fine with a gplv3 license

The author with gplv3 code is Paul Ortyl so if we ask him we should be fine for most of the code. fs20 had another.

**Comment by merbanan** [comment]
I have now asked Paul Ortyl.

**Comment by Mindavi** [comment]
I think it's acceptable to assume that any files without license information are fine with the the license that was in the project root folder at the time of creation.

**Comment by merbanan** [comment]
I emailed the fs20 author but did not get any response yet.

**Comment by merbanan** [comment]
Reimplement the Cardin stuff as a config file and then close the issue.

**Comment by zuckschwerdt** [comment]
I've touched every line on cardin and it was originally PPM which I rewrote to PWM, taking authorship. Also Authorship clarified on others I took over with 48157f6 now.

**Comment by Mindavi** [comment]
Great to see this resolved ✨
