### ISSUE TITLE
Fineoffset-WHx080 allocate station id 

### ISSUE THREAD

**Issue by Ellis-EPA** [merbanan/rtl_433#1649]
I am using a number of Digitec xc-0348 met stations and reading them with python/bash with an SDR on a raspi.
Is there a way to manually allocate a station id number to a met station output? I am finding that when the batteries in the met stations lose power the station id is reset when power is restored.

**Comment by merbanan** [comment]
Some stations generate a random id. How it does that is mostly unknown. We try to make the device output as unique as possible. You should use model in this case. If you have 2 devices with the same model you might be able to separate them by signal strength. But the logic for that will be quite messy.
