### ISSUE TITLE
Misidentified temperature sensor: TFA not Lacrosse

### ISSUE THREAD

**Issue by migurski** [merbanan/rtl_433#1652]
I am running rtl_433 built from source and I have a LaCrosse TX141TH-Bv3 temperature sensor. I expect it to show up in the output with the name "LaCrosse TX141TH-Bv3". Instead, I see its output misidentified as a TFA-303221:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2021-02-14 19:08:25
model     : TFA-303221   Sensor ID : 53
Channel   : 1            Battery   : 1             Temperature: 8.30 C       Humidity  : 71 %          Test mode : 0             Integrity : CRC
```

When running `rtl_433 -R 73` to pick out just the LaCrosse device, no output is generated.

We don’t have a TFA and I’ve checked that the temperature readings are consistent with the device we do own. Is it possible that this device ID is being mislabeled?

**Comment by migurski** [comment]
Here are two sample pulses from the LaCrosse device:

* https://triq.org/pdv/#AAB00B0404034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1928055+AAB00B0403034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1928055+AAB00B0403034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1928055+AAB00B0403034400F001E827148055+AAB0330401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1A355
* https://triq.org/pdv/#AAB00B0404034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1A18055+AAB00B0403034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1928055+AAB00B0403034400F001E827148055+AAB0340401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A1A18055+AAB00B0403034400F001E827148055+AAB0330401034400F001E827149292A1A192A192A1929292929292A19292A19292A192929292A19292A192929292A192A1929292A19355

**Comment by zuckschwerdt** [comment]
Interesting find. They appear to be the same protocol indeed. Strange that we didn't pick this up before.
https://github.com/merbanan/rtl_433/blob/master/src/devices/tfa_30_3221.c#L12
https://github.com/merbanan/rtl_433/blob/master/src/devices/lacrosse_tx141x.c#L48
(the digest is uncommon enough (init f4) that this isn't likely coincidence.

I'd say the TFA 30.3221.02 is a rebranded LaCrosse TX141TH. I'll investigate and maybe delete one.

**Comment by migurski** [comment]
Thanks for looking into this!

**Comment by merbanan** [comment]
Any update on this ?

**Comment by on4cg** [comment]
I bought a TFA 35.1140 with a sensor 30.3222.02. I read LaCrosse-TX141W.

**Comment by zuckschwerdt** [comment]
Does the TFA  30.3222.02 show the correct values as LaCrosse-TX141W?

**Comment by on4cg** [comment]
On first view, yes ...
But I have to view this for a longer period...

**Comment by Domifry** [comment]
I have the same behavior. I own two TFA 30.3221.02 and it shows: LaCrosse-TX141THBv2 - works with the code: sudo rtl_433 -R 73

The data are correct so I will just use it.

**Comment by zuckschwerdt** [comment]
Thanks for the report. TFA is just a reseller, your sensor is very likely an original LaCrosse ;)

Still todo: remove the TFA-303221 protocol someday.

**Comment by Domifry** [comment]
Just a short Update - if you have the TFA it currently identify both. You can see from my 2 Sensors sometimes it tells me: I am a TFA and sometimes I am a Lacrosse.
![image](https://user-images.githubusercontent.com/897506/136653526-c3094428-114a-4be2-a7a3-a53cc2047d6e.png)

**Comment by zuckschwerdt** [comment]
Decoder priority stages have been introduced with #1895 and the TFA 30.3221 is now only a last resort fallback, you should see LaCrosse-TX141THBv2 usually, and never both.

**Comment by TheSecurityDev** [comment]
I'm seeing the same thing:

<img width="1080" height="189" alt="Image" src="https://github.com/user-attachments/assets/0a4fc5eb-5400-4a3b-b4a6-1cf6ac440988" />
