### ISSUE TITLE
Multiple Kerui Door Sensors not detecting reliably 

### ISSUE THREAD

**Issue by y2kdread** [merbanan/rtl_433#1659]
Hi -

There are a couple of different Kerui Door sensors I have been trying to use with rtl_433. They will detect, but not very often. Is this normal?

**Comment by zuckschwerdt** [comment]
Perhaps the signal is at the edge of the watched frequency. Check with CubisSDR, Gqrx, or SDRangel if you center frequency is optimal or try to increase the frequency window with `-s 1024k`

**Comment by merbanan** [comment]
Try to adjust the frequency also. A slight change will probably help.
