### ISSUE TITLE
Auto-discovery script uses invalid device_class "moisture" for Ecowitt WH51

### ISSUE THREAD

**Issue by Jonkieber** [merbanan/rtl_433#1681]
I'm getting a "voluptuous.error.MultipleInvalid: value must be one of..." error due to the device class "moisture" being used.

Can we change this to humidity or something that homeassistant accepts?

**Comment by merbanan** [comment]
Ecowitt WH51 is a moisture sensor. So the output is not humidity.

**Comment by Jonkieber** [comment]
You are correct that it is a moisture sensor, I'm wondering how to resolve this so the device can be used with homeassistant though, as of now moisture is not an accepted device class.

**Comment by merbanan** [comment]
I guess homeassistant needs a change maybe?

**Comment by Jonkieber** [comment]
I've been in contact with the Hass addon creator and he's working on this, thanks @merbanan .
