### ISSUE TITLE
Ecowitt WH51(B): doesn't work with fc = 915 MHz

### ISSUE THREAD

**Issue by roger-** [merbanan/rtl_433#1684]
For some reason it doesn't recognize my WH51B  when run with `rtl_433 -f 915000000` (with default 1 Msps) but it does decode  some data (see [here](https://github.com/merbanan/rtl_433/files/6245948/wh.zip)).

From #1404 I saw someone had better luck with 250 ksps but that didn't work either.

I then tried lowering the center frequency by 85 kHz to 914915000 Hz with `rtl_433 -f 914915000` and *that* works.

Not sure what's going on.

**Comment by ecowitness** [comment]
This works for me. Thanks. frequency 914915000 sample_rate 250000

You saved my WH51B from the garbage can. I was giving it one last try before moving on when I found your post.

**Comment by merbanan** [comment]
@roger- Hi you are probably hitting the base frequency perfectly. Try adjusting it a little bit. And you have to submit some signal samples for us to be able to help better. rtl_433 -f 915000000 -S unknown should give good files.

**Comment by roger-** [comment]
Thought I attached a file — did it work?
