### ISSUE TITLE
Ecowitt WH51(B): weird noise in ADC values

### ISSUE THREAD

**Issue by roger-** [merbanan/rtl_433#1685]
This plot shows the values of the `ad_raw` field of a WH51 moisture sensor (@ 915 MHz):

![Figure 8](https://user-images.githubusercontent.com/1389709/113482915-d1141600-946e-11eb-9f29-7e704f27e66d.png)

The spike is where I watered the plant. Notice the weird noise at t=300 where the values jump by ~8-9. Here's a zoomed in view:

![Figure 7 (1)](https://user-images.githubusercontent.com/1389709/113482953-f4d75c00-946e-11eb-8a6c-512907e12752.png)

Does this seem like a decoding issue or just a sensor issue?

**Comment by merbanan** [comment]
Any post-processing needs to be done in the consumer/presentation layer.
