### ISSUE TITLE
Acurite 5-n-1 rain gauge reading incorrect (all 0)

### ISSUE THREAD

**Issue by rct** [merbanan/rtl_433#169]
The Acurite 5-n-1 rain gauge decoding isn't working.  I get values of all zeros. 

I made some -a -t recordings during a heavy rain.   The wind speed and direction all seem within plausible range.  

I will start digging into it, but wanted to check if anyone else is seeing incorrect or correct readings.

**Comment by ygator** [comment]
I believe I get false AcuRite Rain Gauge messages from my Oregon Scientific THC138 Temperature Sensors.  They are version 1.0 protocol which rtl_433 does not decode.

**Comment by rct** [comment]
Closing this issue.  I was incorrect.  Due to signal level differences, my 5n1 rain messages weren't being decoded and I was getting false positives with bizarre results from the  Acurite 896 range gauge device decodings.

@ygator, the acurite 896 rain gauge decoder should be tightened up to not give false reports, but there aren't any test signals in the rtl_433_tests repository to work with.
