### ISSUE TITLE
Oregon-BHTR968 Forecast

### ISSUE THREAD

**Issue by tiego-007** [merbanan/rtl_433#1696]
Hello,

its possible to recive with the rtl_433 the Forcast of the Oregon-BHTR968?
i thing this is sendet by the sensor, but not trasmittet over mqtt?

thanks
Markus

**Comment by zuckschwerdt** [comment]
Something is perhaps available in the data, but I guess it was never properly analyzed and would just be a fixed map of Temp/Hum/Pressure anyway. https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c#L301

**Comment by tiego-007** [comment]
Hello, 
thanks, but i have make some tests, but i am not abel tu print out the recived values.
i have remove the // on line 301 - 314.
but if i start rtl_433 i dont recive this Output
can you help me please

**Comment by zuckschwerdt** [comment]
Yes, remove the `//` then add in the list below something like this:
```
"comfort", "Comfort", DATA_STRING, comfort_str,
"forecast", "Forecast", DATA_STRING, forecast_str,
```

**Comment by gdt** [comment]
@tiego-007 Have you made progress?  What's the status of this issue and next steps?

**Comment by gdt** [comment]
@tiego-007 Can you submit a draft PR?

**Comment by zuckschwerdt** [comment]
The conclusion here is not to print a fixed map of Temp/Hum/Pressure to comfort / forecast fields, even if some devices offer that. It should be done with a general mapping for all weather devices in the downstream processing. E.g. something like the hass script could offer this. Closing as not-planned.
