### ISSUE TITLE
Windows binary download

### ISSUE THREAD

**Issue by TTIMLB06** [merbanan/rtl_433#1709]
Windows binary download link is broken

**Comment by zuckschwerdt** [comment]
Travis and Bintray now removed with 491f735. New builds will be available shortly (see branch feat-relact).

**Comment by LukePrior** [comment]
Ahh cool I was wondering where the link had gone.

**Comment by zuckschwerdt** [comment]
Looks like we release tomorrow.

**Comment by zuckschwerdt** [comment]
A new release and build is now at https://github.com/merbanan/rtl_433/releases/tag/21.05

**Comment by LukePrior** [comment]
Do you plan on releasing windows binary for testing versions?

**Comment by zuckschwerdt** [comment]
Perhaps we can add a rolling dev release. I need to look into that.
