### ISSUE TITLE
11.5 Gig txt file

### ISSUE THREAD

**Issue by krill074** [merbanan/rtl_433#1716]
Hello Im new to this software and only recently got it running during daytime only, nitetime seems to stop weather beacons.
(Do they stop transmitting when lux hits a certain limit, I stopped getting signals when the sun set)

I left this to record overnight and write the information to a txt file using -w
6 to 7 hours later the program had exited.
The txt file was so large I couldnt open it, it was over 11Gig in size.
Im using the windows compiled version too..

Why does it do this?

rtl_433 -w -
âzü}é⌂Ç{é|ä{ä~⌂⌂}}Ç~üÇü⌂|⌂Ç~~~âü⌂{|}ü{⌂⌂⌂åzé{Ç}⌂Ç{ü|{}~Ç~⌂yz~üÇ⌂~}üÇé}|Ç}Çé|⌂üüâ~~Çz|{}Çé|Ç}~~üàÇüüâ~â|ä}ü⌂⌂⌂}~Ç⌂}Ç⌂~äézü{é~⌂âÇéééüÇéÇÇü}|~ü~üÇü}ÇâàÇéüÇ}{{Çü|ü~⌂ÇäÇééå~éÇâ~~ Times a Billion.

Is this because its not process through Demodulator option?

How do I record what it finds to a txt file?

Grant

RTL-SDR BLOG V3
https://github.com/winterrace/rtl_433_win/releases
(Nitetime I get an overbearing pulse and no other signals and usually a trail of these)
pulse_FSK_detect(): Maximum number of pulses reached!

**Comment by zuckschwerdt** [comment]
Record a text format to file with `-F`, e.g. for the human-readable format `-F kv:myfile.txt`
Other text formats are `csv` and `json`.

Using `-w` you are recording the raw sample data, will be at at high rate...
(0.5M per second at the default 250k sample rate, 2M/s at the higher sample rate for 868M freq.)...

**Comment by krill074** [comment]
Thanks but why remove thread?Sent from SpaceOn 16 May 2021 8:37 pm, "Christian W. Zuckschwerdt" ***@***.***> wrote:
Closed #1716.

**Comment by zuckschwerdt** [comment]
We close issues that are not a todo item for rtl_433. Feel free to discuss further anyway.

Note that winterrace' builds are merged into rtl_433, current builds are found at https://github.com/merbanan/rtl_433/releases
