### ISSUE TITLE
running it with hackrf via soapysdr cause type overflow. 

### ISSUE THREAD

**Issue by MHL3060** [merbanan/rtl_433#1717]
it throws overflow exception when using the cs16 sampling size.

I am seeing this with hackrf device.
`rtl_433 -d driver=hackrf`
here is the stacktrace.

signed integer overflow: 1431655765 + 2147483646 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/bl/workspaces/rtl_433/src/baseband.c:327:50 in

**Comment by Mindavi** [comment]
Ubsan is not enabled by default, right? Anyhow, would be nice to solve this.

**Comment by zuckschwerdt** [comment]
The baseband for cs16 has some possible overflows in the fast int calculations for cs16 -- shouldn't be a problem as it's only I/Q data points, but I'll look further into it.
