### ISSUE TITLE
different amount of output -F mqtt and -F json

### ISSUE THREAD

**Issue by tbone4711** [merbanan/rtl_433#1720]
Hi.
I'm receiving my temp/hum-sensors from all over my house and publish them via MQTT. The different output modes seem to produce different amount of data.

Output wit -G 4
time      : 2021-05-21 18:25:24.270993
model     : Fineoffset-WH2A                        ID        : 11
Temperature: 24.3 C      Humidity  : 38 %          Integrity : CRC
Modulation: ASK          Freq      : 433.9 MHz
RSSI      : -0.1 dB      SNR       : 22.5 dB       Noise     : -22.7 dB

Output with -F json
{"time" : "2021-05-21 18:37:27.002657", "model" : "Fineoffset-WH2A", "id" : 11, "temperature_C" : 24.300, "humidity" : 38, "mic" : "CRC", "mod" : "ASK", "freq" : 433.914, "rssi" : -0.124, "snr" : 6.288, "noise" : -6.412}

Topics via rtl_433 -d 0 -C si -F "mqtt://broker:1883,devices=rtl_433[/model][/id],retain=0"
rtl_433/Fineoffset-WH2A/11/humidity
rtl_433/Fineoffset-WH2A/11/id
rtl_433/Fineoffset-WH2A/11/mic
rtl_433/Fineoffset-WH2A/11/temperature_C
rtl_433/Fineoffset-WH2A/11/time

Did I miss any parameter to get mod, freq, rssi, snr, noise also published via MQTT?
Why are the values at "-G 4" truncated/rounded? e.g. freq

Thanx in advance,
Tbone

**Comment by zuckschwerdt** [comment]
You need `-M level` to get levels. You get the same fields on `-F mqtt` as with `-F json`.

Only consider two decimals on the freq and a single decimal on the levels to be somewhat accurate.
