### ISSUE TITLE
rtl_433 does not see hackrf (2021.03.1)

### ISSUE THREAD

**Issue by straw1low** [merbanan/rtl_433#1745]
┌──(root💀*)-[*]
└─# hackrf_info                                                         2 ⨯
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000081c69dc370c611b
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x00664772
                                                                            
┌──(root💀*)-[*]
└─# rtl_433    
rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 145 out of 175 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 ]
No supported devices found.

**Comment by zuckschwerdt** [comment]
The default is to scan for RTLSDR receivers only. Use `-d ""` to open the default SoapySDR device.
