### ISSUE TITLE
Fine Offset WN5300 weather station support

### ISSUE THREAD

**Issue by thtro** [merbanan/rtl_433#1750]
Hello,

It seems there are a few days now since triq.org is down. Any chance of getting it up again?

I am trying to decode the Fine Offset WN5300 weather station, but no luck so far. I've analysed the signal and attached it below.
Here is the -A output:
https://gist.github.com/thtro/f2ea4e41b0b270cdd9414f9b1ab9555e

and here is with the suggested -X params:
https://gist.github.com/thtro/fbff44489f916646aba8839a928393d3

Thanks a lot!

**Comment by zuckschwerdt** [comment]
Thanks for the note, it's not down but there is some filtering. If your netblock is relocated from originally APNIC or LACNIC there is some chance it's blocked. Can you give your ip-range, just the first three numbers?

The signal you are getting looks like noise. Lots of pulses or gaps below say 20 µs is not good. Can you grab a sample with `-S unknown`?

**Comment by thtro** [comment]
Hi, thanks for getting back so fast. 

My ip starts with 79.114

I moved the Pi with my homemade antenna on the roof and it seems to pick up the signal rather than the noise as before. (the chinese guys forgot to send the 868 antenna in the package)

I used -S and attached the zip with the samples (the station sends the signal every 48s, so at least one of the files should contain the data)

https://drive.google.com/file/d/148HPmi5nF5IY2M5rIbBFKfRtrOwWCFjm/view?usp=sharing

Thanks again, regards!

**Comment by zuckschwerdt** [comment]
RO-Telecom is unblocked now.

Most 433M antennas should work well with 868M too.

But the real problem could be the "pilot tone" at 868.00M.
It can be seen in g001 (use https://triq.org/pdv/ ).
With the current position your weather sensor is stronger (see g005) but automatic gain will not work with that interference around.
It might work better with just `-s 250k` or if you tune up to exclude the tone, `-f 868.5M`.

I'll have a closer look at the signals. E.g. this should work:
`rtl_433 -s 1M -R 0 -X 'n=WN5300,m=OOK_PWM,s=500,l=1500,r=9000'` g005_868.3M_1000k.cu8
The codes you got so far look somewhat ok in [this BitBench](https://triq.net/bitbench#c=%7B95%7D3fd0294f9384060036872ffe&c=%7B90%7D1fe814a8ca0101801b43304&c=%7B94%7Dffa052a3280406006d0cc1fc&c=%7B110%7D15397fa052a427060b006d0e0efc&c=%7B92%7D07fa052a924050c006d01ce&c=%7B94%7Dffa052a924050c006d01cefc&f=SYNC%3A8h%20TYPE%3A4h%20ID%3A8h%20FLAGS%3A2b%20TEMP%3A10d%20HUM%3A8d%20WAVG%3A8d%20GUST%3A8d%20RAIN%3A16d%20CRC%3F8h%208h%208h%0A&a=Sync&m=ff).
And the format matches the WH1050/WH1080.

**Comment by zuckschwerdt** [comment]
The name WN5300 is for the base station / head unit only.
The actual sensor you have is a FineOffset WH1080/3080 I guess?

**Comment by thtro** [comment]
Triq.org is working fine, thanks!

Now that you're saying I suppose it could be wh1080, this their link ( Mine is actually a German branded version -  Waldbeck	
Kopernikus, I had a really hard time finding the producer because there is absolutely no clue inside or outside the case, found it by pure mistake on YouTube) 
http://www.foshk.com/Weather_Professional/WN5300.html is the link on FineOffset's website
and looking at their product list it seems they are using the same weather station with diferent base units.

Will check the config provided by you.

Later edit:
Here is some info regarding wn5300, footnote 23 especially:
https://www.wxforum.net/index.php?PHPSESSID=tn3vhckua93vnsbl618anh5e4o&topic=40730.0

will get back after testing more, thanks again, you're amazing!

**Comment by thtro** [comment]
rtl_433 -a 4 -f 868.3M -R 32 
worked fine for my Waldbeck Kopernikus aka WH1080, I just need to improve my antenna further.
Thanks!

**Comment by zuckschwerdt** [comment]
Great to hear. I meant either
- limit the bandwidth to exclude 868.00M: `-f 868.3M -s 250k`
- or tune higher to exclude 868.00M: `-f 868.55M`

Either one (not both) should work better.

**Comment by zuckschwerdt** [comment]
That link is full of good information. Fine Offset has so many resellers and rebrands!

**Comment by thtro** [comment]
Yeah that link is nice, it took me a while to find that forum. Maybe add Waldbeck it in the readme or accepted devices so people can spare their time looking for it :), it drove me crazy not finding any info about my Waldbeck.
