### ISSUE TITLE
Help Request: Understanding GET in flex

### ISSUE THREAD

**Issue by ideal2545** [merbanan/rtl_433#1755]
Hi All, my apologies, I'm a newb at this. I'm trying to better understand the get= for reading content from DATA

If I do get=@0:{20}:id from a1750e0 I get 661328 which corresponds to the decimal conversion of the hex: a1750 but I'm trying to understand how @0:{20} corresponds basically to the first 5 characters of the "data" stream. 

help is appreciated, sorry if I posted this question in the wrong spot!

Jon

**Comment by zuckschwerdt** [comment]
No worries, that syntax is pretty dusty and cryptic ;)
The `@0` marks the fist bit you want, the `{20}` marks how many bits, i.e. the 20 bits (5 hex chars) 0-19 will be extracted.
