### ISSUE TITLE
QOS Level For mqtt

### ISSUE THREAD

**Issue by ssmoss** [merbanan/rtl_433#1769]
Thanks for making such a great library.

I have one tiny question, it seems that the messages get sent with QOS 0. Is there a way to set the QOS level for the messages to either 1 or 2?

**Comment by zuckschwerdt** [comment]
Well… there is now ;)

**Comment by ssmoss** [comment]
Holy crap dude. Thanks!

**Comment by ssmoss** [comment]
One other quick question, what does the `retain` parameter do? Does that tell mqtt to keep the last sent message?

**Comment by zuckschwerdt** [comment]
Yes, "retain" sets the MQTT retain behaviour to keep the last message persistent.

**Comment by rct** [comment]
If you use retain and have per device topics, any false positive device decodes will hang around permanently.  A periodic clean up might be necessary
