### ISSUE TITLE
Support for Orion Endpoints (water meters)

### ISSUE THREAD

**Issue by nijhawank** [merbanan/rtl_433#1779]
I came searching to read my water meter which uses an Orion SE Endpoint FCC-ID https://fccid.io/GIF2014W-OSE

I found a thread at https://github.com/bemasher/rtlamr/discussions/196 that pointed here with the information that Orion supposedly uses M-Bus Mode T but with a different logical format. Is there a possibility to support meters like these?

**Comment by MidwestTechnologies** [comment]
I have an Orion endpoint about 150’ from my antenna and also have interest in adding these sensors.  I have made some recordings at 915 MHz and analyzed them but see no useful data.

**Comment by zuckschwerdt** [comment]
Closed with #2089
