### ISSUE TITLE
Alpine package missing libressl

### ISSUE THREAD

**Issue by cjd** [merbanan/rtl_433#1786]
In current master the libressl package is missing and so rtl433 fails to start with messages such as:

Error relocating /usr/local/bin/rtl_433: BIO_new_file: symbol not found                           
Error loading shared library libssl.so.48: No such file or directory (needed by /usr/local/bin/rtl
_433)                                                                                             
Error loading shared library libcrypto.so.46: No such file or directory (needed by /usr/local/bin/rtl_433)
Error relocating /usr/local/bin/rtl_433: SSL_get_error: symbol not found
Error relocating /usr/local/bin/rtl_433: SSL_get_fd: symbol not found
Error relocating /usr/local/bin/rtl_433: SSL_write: symbol not found

**Comment by cjd** [comment]
I've created a quick pull request to fix this up as https://github.com/hertzg/rtl_433_docker/pull/22

**Comment by zuckschwerdt** [comment]
Thanks for the info! Hopefully this will point users looking at the same problem in the right direction.
Closing, since there is nothing we can do here. But feel free to add more info and discuss further.
