### ISSUE TITLE
How to enable bias-t?

### ISSUE THREAD

**Issue by vistalba** [merbanan/rtl_433#1787]
Hi

I use a LNA to get the signal. When I use rtl_tcp and SDR Console on Windows I can see a good signal on 868.34M.
As soon as I start `rtl433 -f 868.34M -d2 -R 32` I do not see anything :( 

Any idea why this happens? Is there a way to enable bias-t with rtl433? Do I miss something?

**Comment by zuckschwerdt** [comment]
You have to add `rtlsdr_set_bias_tee(dev, 1);` in e.g. https://github.com/merbanan/rtl_433/blob/master/src/sdr.c#L429
and then recompile. It's not an option any user seemed to want.

**Comment by vistalba** [comment]
Ok, will try. I know that this wouldn't fit for everyone but why not make it available as an option like others?

**Comment by merbanan** [comment]
Patch is welcome.

**Comment by vistalba** [comment]
@zuckschwerdt I tested it and it doesn't work as now it ends with the error "Speicherzugriffsfehler". May it is the wrong place or I have to do other things too?

@merbanan I would love that too... but I'm not familiar with coding :(

**Comment by merbanan** [comment]
Well, it is hard to develop anything without a way to test it.

**Comment by vistalba** [comment]
I understand. 

Normally I use this driver with `rtl_eeprom -b y` to enable bias-t in eeprom but it looks like rtl_433 doesn't support it that way :(
For other tools like flightaware it works fine.

Any idea what I could do to help/test?

**Comment by zuckschwerdt** [comment]
Oops, sorry, it's `rtlsdr_set_bias_tee(dev->rtlsdr_dev, 1);`

**Comment by zuckschwerdt** [comment]
We could maybe add something to 
`  [-t <settings>] apply a list of keyword=value settings for SoapySDR devices`

SoapySDR already supports "biastee=true", e.g. `-d driver=rtlsdr -t biastee=true`

Also `rtlsdr_set_bias_tee()` is a recent addition to rtlsdr, we should use it only after a feature check.

**Comment by zuckschwerdt** [comment]
I guess something like https://github.com/merbanan/rtl_433/tree/feat-biastee
94fd235

**Comment by vistalba** [comment]
Just compiled master and for me it looks like it works. Will do a test with a multimeter later.
