### ISSUE TITLE
BeClose sensors

### ISSUE THREAD

**Issue by ifuchs** [merbanan/rtl_433#1794]
I have some BeClose sensors (monitoring system- often used to monitor seniors in their home) that operate at 319Mhz. Is there a way I can use rtl_433 to get sensor information (mostly motion or door open/close, and gas)?

**Comment by zuckschwerdt** [comment]
Sure. `-f 319M` to set the freq. Then watch for data with `-A` and also capture a few sample signals with `-S unknown` to check with https://triq.org/pdv/
