### ISSUE TITLE
Is it possible to set the retain flag on some devices or decoders but not others?

### ISSUE THREAD

**Issue by ponchohoncho** [merbanan/rtl_433#1796]
I have a handful of 433mhz devices in the home that I'm using with rtl_433 > MQTT > HASS. One issue I'm having is that HASS doesn't remember the door sensor state and defaults to "closed" on restart. I can't use the retain flag globally because I'm also using some buttons to trigger automations, and when I restart with the retain flag set, all those automations fire as well.

Is there a way to set the MQTT retain flag for certain decoders/devices, but not others? that way the door state could be retained, but the button state wouldn't be.

**Comment by zuckschwerdt** [comment]
Sorry, the MQTT support in rtl_433 is for the basic cases only. You need to run a relay or bridge script with your custom logic. Some examples are in the https://github.com/merbanan/rtl_433/tree/master/examples folder.
