### ISSUE TITLE
How to disable a protocol and set it up myself with changes? [141=Auriol-HG02832]

### ISSUE THREAD

**Issue by HolgerAusB** [merbanan/rtl_433#1797]
One of my neigbours sensors is recognized as Auriol-HG02832, which is protol 141. But this sensor spams all its data 10 times within 0.5 seconds and this is done every ~30 seconds.  I want to use the sensor data but want to cut the flooding.

So I want to disable protocol 141 in the conf file. But I do not know which parameters to user in the decoder-directive to re-build the protocol there. I want to try, if a 'unique' will help inside there.

Could that help?

Here is a short excerpt of a single mqtt-sensor-topic and Unix-timestamps with nanoseconds:

```
pi@xxx:~ $ mosquitto_sub -F '%U \e[92m%t \e[96m%p\e[0m' -q 2 -t rtl_433/sensors/141/46/Auriol-HG02832/temperature_C
1631023759.837498634 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023759.837922149 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023759.838392535 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023759.838849421 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023759.839306325 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023759.839775488 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023760.363650881 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023760.367753056 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023760.370916738 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023760.373436647 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4

1631023790.772782748 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023790.775694543 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023790.779935365 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023790.784044837 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023790.788103124 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023791.293736457 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023791.295391057 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023791.296968360 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023791.298545905 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
1631023791.299800378 rtl_433/sensors/141/46/Auriol-HG02832/temperature_C 27.4
```

And it is not on mosquito. As i did my first tries with `rtl_433 -G 4` to find my doorbell, this Auriol sensor spamed the same way.

**Comment by zuckschwerdt** [comment]
A flex decoder will only give you the raw data. There is a CRC checksum and some decoding to get the temperature value.
If you need to filter output it's best to use the syslog output and read that from a custom script with your filtering logic. E.g. https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_custom.py
Or if you want to push to MQTT after filtering https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_mqtt_relay.py
