### ISSUE TITLE
SoapySDR_free build error on SoapySDR prior to 0.8

### ISSUE THREAD

**Issue by x31415926** [merbanan/rtl_433#1804]
Adding SoapySDR_free seems to require SoapySDR 0.8+. The build dependency references 0.6 though.

With 0.7
$ cmake ..
[...]
-- SoapySDR device input will be compiled. Found version 0.7.2-1
[...]
$ make
-- Build type not specified: defaulting to release.
[...]
/usr/bin/ld: libr_433.a(sdr.c.o):sdr.c:(.text+0x14a5): more undefined references to `SoapySDR_free' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rtl_433.dir/build.make:88: src/rtl_433] Error 1
make[1]: *** [CMakeFiles/Makefile2:1012: src/CMakeFiles/rtl_433.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

With 0.8
cmake ..
[...]
-- SoapySDR device input will be compiled. Found version 0.8.1-g1cf5a539
[...]
$ make
[ 93%] Built target data
[ 93%] Built target r_433
[ 93%] Building C object src/CMakeFiles/rtl_433.dir/rtl_433.c.o
cc1: warning: command line option ‘-Wnon-virtual-dtor’ is valid for C++/ObjC++ but not for C
[ 93%] Linking C executable rtl_433
[ 93%] Built target rtl_433
[ 93%] Built target data-test
[...]

**Comment by gvanem** [comment]
This can easily be patched like this:
```diff
--- a/src/sdr.c 2021-09-10 11:24:05
+++ b/src/sdr.c 2021-09-11 09:35:35
@@ -31,6 +31,10 @@
 #include <SoapySDR/Device.h>
 #include <SoapySDR/Formats.h>
 #include <SoapySDR/Logger.h>
+
+#if (SOAPY_SDR_API_VERSION < 0x00080000)
+#define SoapySDR_free(ptr) free(ptr)
+#endif
 #endif
```
