### ISSUE TITLE
Parameters order with multiple RTL-SDR devices

### ISSUE THREAD

**Issue by kao73** [merbanan/rtl_433#1806]
Found an interesting behavior with setup two RTL-SDR devices on the same host. I think it can be useful and probably should be fixed.

I have two devices with different serial numbers. Use the following to start them separately:
```bash
rtl_433 -v -c /usr/local/etc/rtl_433/rtl_433.F.conf -f 915M -f 433.92M -s 250k -H 90 -F "mqtt://192.168.20.20:1883,user=xxx,pass=xxx,devices=rtl_433[/model][/id]" -d 0
```
and 
```bash
rtl_433 -v -c /usr/local/etc/rtl_433/rtl_433.F.conf -f 915M -f 433.92M -s 250k -H 90 -F "mqtt://192.168.20.20:1883,user=xxx,pass=xxx,devices=rtl_433[/model][/id]" -d 1
```

When both processes started, I see in the console error messages from MQTT:
```
MQTT Connection failed...
MQTT Connected...
MQTT Connection established.
MQTT Connection failed...
MQTT Connected...
MQTT Connection established.
MQTT Connection failed...
```

According to my investigation, the rtl_433 uses the same client_id for both processes.
I tried to use serial number instead of device indexes without success.

My solution is to place `-d` option before `-F` in the command line. Found by source code analysis. Looks like command line parameters read from left to right, and option `-d` used by `-F` to generate MQTT `client_id`. Thus, if the last one comes first, the `client_id` will not include device index/serial when calculated.

Working example:
```bash
rtl_433 -v -c /usr/local/etc/rtl_433/rtl_433.F.conf -f 915M -f 433.92M -s 250k -H 90 -d 0 -F "mqtt://192.168.20.20:1883,user=xxx,pass=xxx,devices=rtl_433[/model][/id]"
```
and 
```bash
rtl_433 -v -c /usr/local/etc/rtl_433/rtl_433.F.conf -f 915M -f 433.92M -s 250k -H 90 -d 1 -F "mqtt://192.168.20.20:1883,user=xxx,pass=xxx,devices=rtl_433[/model][/id]"
```

Hope that will save someone's time.

**Comment by peteakalad** [comment]
Same findings as #1129
