### ISSUE TITLE
Add support for FineOffset WH57 lighting sensor

### ISSUE THREAD

**Issue by hadeshimself** [merbanan/rtl_433#1818]
This device transmits every 79 seconds and according to the specs ([here](http://www.foshk.com/Other_sensors/WH57.html)) it detects strikes at distances up to 40km.

Preamble seems to be 5516ea (confirmed that it's the correct device from the 79-second xmit timer).

rtl_433 -R 0 -X 'n=WH57,m=FSK_PCM,s=60,l=60,r=1800'
{"model" : "WH57", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 146, "data" : "5555555555516ea2b806342011f8047381010"}], "codes" : ["{146}5555555555516ea2b806342011f8047381010"]}
{"model" : "WH57", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 146, "data" : "5555555555516ea2b806342011f8047381014"}], "codes" : ["{146}5555555555516ea2b806342011f8047381014"]}

Last nibble changes between 0, 2 and 4 with no specific order.

Unfortunately I don't have the wifi gateway for this device and can't cross check the actual readings and the captured data. I'm looking at fineoffset_wh31l.c for reference.

**Comment by zuckschwerdt** [comment]
Actually the preamble is `aa..` with a sync word of `2dd4`. That will then also align the data.
Here those two [codes as BitBench](https://triq.net/bitbench#c=%7B146%7D5555555555516ea2b806342011f8047381010&c=%7B146%7D5555555555516ea2b806342011f8047381014&f=8h&a=Preamble&m=aa2dd4).
