### ISSUE TITLE
Incorrect values for 6059M - AcuRite Atlas 5-in-1 Weather Station

### ISSUE THREAD

**Issue by danielgoepp** [merbanan/rtl_433#1819]
I have tried to look through the various threads here and in the google group discussions, but I don't see anyone mention the specific thing I'm seeing. I do see that there was a feature branch that appears to have been merged in, so I'm assuming that the developers feel this should be working now. Most, I think it works, but I have some issues with the data I'm seeing. First is that I don't get any pressure reading, but I know the device is reporting it since it shows on the display inside. Also, the lightning data is off. On the display it shows 0 count 0 distance, we haven't had any in a while, but rtl_433 is showing 2 count 15 distance. Also, rain is off, display is showing 0 rain inches, but rtl_433 is showing 1.07 inches. I'm happy to provide any further details on this. Here are the three messages I'm currently getting:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-09-29 06:20:20
model     : Acurite-Atlas id        : 36
channel   : C            sequence_num: 0           Battery   : 1             message_type: 38          Wind Speed: 0.0 mi/h      wind_dir_deg: 165.0       Rainfall Accumulation: 1.07 in                      strike_count: 2
strike_distance: 15      data_exception: 0         raw_message: 002466000514eb00cf5d
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-09-29 06:20:30
model     : Acurite-Atlas id        : 36
channel   : C            sequence_num: 0           Battery   : 1             message_type: 39          Wind Speed: 0.0 mi/h      uv        : 0             lux       : 0             strike_count: 2           strike_distance: 15
data_exception: 0        raw_message: 0024e70000000000cfda
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-09-29 06:20:40
model     : Acurite-Atlas id        : 36
channel   : C            sequence_num: 0           Battery   : 1             message_type: 37          Wind Speed: 0.0 mi/h      temperature: 41.3 F       humidity  : 98 %          strike_count: 2           strike_distance: 15
data_exception: 0        raw_message: 00246500062de200cf6d
```

**Comment by zuckschwerdt** [comment]
- Atmospheric pressure is like built into the display unit, there is no need to have that on a remote sensor.
- Lightning strike values are historic, you should see "active" a the time of the detection.
- Rain is cumulative. You need to derive the time based counts (per hour, per day) yourself.
