### ISSUE TITLE
bitbuffer_add_row: Warning: row count limit (50 rows) reached error

### ISSUE THREAD

**Issue by mjwellhacks** [merbanan/rtl_433#1822]
I recently set up rtl_433 on my raspberry pi 4, whenever I start the program I get the error "bitbuffer_add_row: Warning: row count limit (50 rows) reached". The data also comes through delayed and some are never received.

**Comment by zuckschwerdt** [comment]
Thanks. That diagnostic warning slipped in, removed now.
