### ISSUE TITLE
TFA Dostmann 30.3222.02 maybe the same like LACrosse TX141W?

### ISSUE THREAD

**Issue by Domifry** [merbanan/rtl_433#1827]
Hello,

I own the TFA Dostmann 30.3222.02 Windsensor and the temperature Sensors 30.3221.02. The temperature sensors works awesome. Looks like they use the same protocol like LaCrosse-TX141THBv2 because it shows this as model. This is fine for me. I was wondering if maybe we can also use this code from [lacrosse_tx141x.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/lacrosse_tx141x.c) for this Model? I think it can work. If you check both models also look the same. Is there any option how to rewrite this code and tell it to try it for the TFA Dostmann 30.3222.02? 

I am also open for a suggestion for another Wind Sensor if you have a tip. Thanks!

**Comment by Domifry** [comment]
Update: I was waiting now a bit and it showed me same values. But it do not comes always. Can you give me some hints how do debug or which wind sensor is working
![wind-sensor](https://user-images.githubusercontent.com/897506/136578769-43e8dd28-a01e-4d29-8613-9059aaa77f94.png)
?

**Comment by Domifry** [comment]
Hi @zuckschwerdt - I tried now with new Antenna (the sensor is just 5cm away from the Antenna) and my problem is that it shows nothing. The Output in normal Mode is nothing and with this parameters I can receive the data you see in the picture. 

sudo rtl_433 -X 'n=name,m=OOK_PWM,s=290,l=560,r=1160,g=0,t=0,y=835'

Can you give me some help? 

![image](https://user-images.githubusercontent.com/897506/136670042-d625388e-5643-449e-ac07-5205c0d5c76b.png)
![image](https://user-images.githubusercontent.com/897506/136670086-244473fd-4761-41c7-8058-4228fac717b6.png)

**Comment by zuckschwerdt** [comment]
It's 65 like seen above as `{65}`.

5 cm distance is not enough, it will overload the receiver. With a good antenna try 5 meters. Or remove the antenna and use 10-20cm.

**Comment by Domifry** [comment]
All Right - 65 is more then 64 - so normally it should go in this function. U putted it now 5 and 10 Meters away. Nothing happened. Do you have any idea what I can do otherwise I need to order the ventus W132.

**Comment by Domifry** [comment]
You are right! sudo rtl_433 -f 433.8M delivers always a result!
![image](https://user-images.githubusercontent.com/897506/136671030-423aff87-d64c-4577-ad49-6a6d101f413b.png)

**Comment by zuckschwerdt** [comment]
Happy to help.

**Comment by fthiery** [comment]
> -Y autolevel -Y minmax -Y magest

Just wanted to chime in to say thanks for this suggestion which allowed me to improve sensitivity for my TFA Dostmann 30.3251.10
