### ISSUE TITLE
SQL Connection for RTL_433

### ISSUE THREAD

**Issue by Domifry** [merbanan/rtl_433#1828]
Hello,

because I found a request in this Repo and also in other Websites I did a SQL Connect for the RTL_433.
This Script use the Code of rtl_433 This Script helps you to push every 15 Minutes the current Data of Sensors to a SQL Database. The Script starts the RTL-SDR Stick and reads out for a certain time until it receives one value of every sensor. If it successful it puts the JSON Data in a SQL Table and sleeps for 15 Minutes. 

You can find it here - maybe it can be part of your great work if you want!
<a href="https://github.com/Domifry/RTL_433_SQL_Connection/tree/main">https://github.com/Domifry/RTL_433_SQL_Connection/tree/main </a>

**Comment by zuckschwerdt** [comment]
Thanks, this might be a good starting point for other users interested in SQL storage.

Some quick notes: we recommend starting rtl_433 as it's own service and getting the output by UDP, see e.g. https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_custom.py
Generally we recommend a time-series DB, like RRD, Graphite, or InfluxDB, using maybe Statsd, or Collectd, Prometheus, ... protocols. Frontends like Grafana can make good use of that data then.

**Comment by zuckschwerdt** [comment]
Todo: put this example in the docs, somewhere.

**Comment by Domifry** [comment]
Thanks! Thats so great and a big honor!
