### ISSUE TITLE
Support for Rain Sensor TFA 3233 or 3161

### ISSUE THREAD

**Issue by Domifry** [merbanan/rtl_433#1831]
Hello,

I buyed the Rain Sensor from TFA. To test I buyed two models and will send one back. I want to share some information with you that you know how to implement it:

- TFA 3233: sudo rtl_433 -R 147 delivers nothing
- TFA 3161 delivers something with sudo rtl_433 -R 37

TFA 3233: What is the issue with TFA 3233 that is delivers nothing? Because the other sensor is working - I will send this one back.

For people with more sensors:
TFA 3161: I have more sensors and want to read all out - so I used: sudo rtl_433 -R 37 -R73

Output:
{"time" : "2021-10-11 17:10:00", "model" : "Inovalley-kw9015b", "id" : 3, "temperature_C" : 24.000, "rain" : 512, "rain_mm" : 230.400}

Maybe you can help me: rain_mm is the value I want - but what means: rain: 512? Is this the rain in total?

**Comment by zuckschwerdt** [comment]
Inovalley kw9015b is also sold as TFA-Dostmann 30.3161. The `*` notes that this protocol is *disabled*  by default as it would produce false positives. Just enable if you need it. It's `rain * 0.45 = rain_mm` -- don't use `rain`.

For the TFA 3233, record a sample (`-s 1M -S unknown`) then check what you got with https://triq.org/pdv/ and upload a few verified good cu8 files here as zip, also write down the expected values (temp, and maybe click the rain bucket a few times by hand).
If in doubt what a "good file" is: remove the antenna and place only the TFA 3233 at 10cm to the receiver. All recorded samples should look somewhat the same.

**Comment by zuckschwerdt** [comment]
Ah, wait, I see. We already support the TFA 30.3233.01 as "TFA Drop". Maybe it's just the frequency. Try like mentioned: record samples (at 1M) look at them, note freq.

**Comment by Domifry** [comment]
I succeded now with the TFA 3161  and my Wheater station works now. I uploaded the code in my [GitHub](https://github.com/Domifry/Wetterstation-Funk-RaspberryPi) - it is in German. 
Thanks for this great software and I had much fun! Thanks to your support it worked!
