### ISSUE TITLE
No decoding only on Raspberry Pi 4

### ISSUE THREAD

**Issue by FantaGhost** [merbanan/rtl_433#1833]
Hi! I'm getting crazy with a strange behaviour decoding an Oregon Scientific THN132n sensor via Raspberry Pi 4.
My hardware is based on Raspberry Pi 4 + Noolec NESDR Smart stick + 433MHz SMA antenna, powered up by 5V/3A DC power supply. I compiled latest rtl_433 git release this morning via "cmake .. && make && sudo make install" without any -D switches. I tested the stick via "rtl_test" and everything is working fine.
But even if everything seems to be ok I'm not able to decode any data running the command "rtl_433 -d 0 -g 48" on Raspberry Pi (gain value has shown by rtl_test and sensor is placed about 1 meter away from receiver).
BUT: if I plug the same USB stick, with the same antenna  in my old MacBook Pro (placed at the same distance from the sensor)  and run "rtl_433 -d 0 -g 48" on rtl_433 installed via brew (version 21.05), everything is working fine and I'm also able to decode data coming from other sensors in range.
As latest counter-test, running adsbdecoder on the raspberry with the same stick and the same antenna, produce tons of ADSB decoded data flawless.

**Comment by zuckschwerdt** [comment]
Please update if there is some news on this. Closing as there is nothing we can do right now.
