### ISSUE TITLE
no rtl_433 directory to cd into to perform building process

### ISSUE THREAD

**Issue by KonTiki1957** [merbanan/rtl_433#1848]
Hi there I was trying to build this software on a Beagle Bone Black today with Ubuntu 18.04 installed but I was not able to find the rtl_433 directory mentioned in the building guide which seems to be very simple and which I followed. Did I miss something?
Thank you for any help,
Federico

**Comment by peteakalad** [comment]
You need to git clone or download this repo.

**Comment by zuckschwerdt** [comment]
note added with 3da5dd2

**Comment by KonTiki1957** [comment]
thank you very helpfull :-)
