### ISSUE TITLE
How to update decoding protocols and where are the *.conf files?

### ISSUE THREAD

**Issue by Nemokando** [merbanan/rtl_433#1852]
Good day @all,

Info: my setup: RPi4 - Dragon OS (installed 1 week ago) - Noelec USB-Stick DVB-T on extension

********

Startup-log:

rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/ubuntu/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 122 out of 149 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 ]
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
Allocating 15 zero-copy buffers
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-09 08:09:43
model     : Acurite-606TX id        : 158
Battery   : 1            Temperature: 8.1 C        Integrity : CHECKSUM
******
Fine! It works! Now I'd like to update the supported device protocols.

What happened so far:
I cd-ed into the 4 "Trying..." directories not finding any *.conf files.
1, 2 and 4 dont seem to extist
3 seems to be empty

Question(s):
There should be more than 149 decoding protocols, how do I update them? The manual is at #187.
Where does it find the named 149 protocols if all 4 locations have no *.conf files?

If my questions are the result of my goofyness give it a smile when having your next afterwork beer, cheers and
thanks!
Greetings,
Alex

**Comment by zuckschwerdt** [comment]
That version looks old. More recent versions will output the realease tag (current 21.05) and we are now up to 200 protocols. Either wait for the dragon OS team to update, or compile from source: https://github.com/merbanan/rtl_433/blob/master/docs/BUILDING.md#cmake
Conf files are mainly for settings and very simple (doorbell-style) protocols.
