### ISSUE TITLE
undefined reference to `SoapySDR_free'

### ISSUE THREAD

**Issue by loewal** [merbanan/rtl_433#1853]
Can anyone help please?

/usr/bin/cc -O3 -DNDEBUG  -rdynamic CMakeFiles/rtl_433.dir/rtl_433.c.o  -o rtl_433 -Wl,-rpath,/usr/local/lib: libr_433.a -lssl -lcrypto /usr/local/lib/librtlsdr.so -lusb-1.0 /usr/local/lib/libSoapySDR.so.0.8.0 -lm
/usr/bin/ld: libr_433.a(sdr.c.o): in function `sdr_open':
sdr.c:(.text+0x5f0): undefined reference to `SoapySDR_free'
/usr/bin/ld: sdr.c:(.text+0x6f2): undefined reference to `SoapySDR_free'
/usr/bin/ld: sdr.c:(.text+0x8a8): undefined reference to `SoapySDR_free'
/usr/bin/ld: sdr.c:(.text+0x912): undefined reference to `SoapySDR_free'
/usr/bin/ld: sdr.c:(.text+0x972): undefined reference to `SoapySDR_free'
/usr/bin/ld: libr_433.a(sdr.c.o):sdr.c:(.text+0xa00): more undefined references to `SoapySDR_free' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rtl_433.dir/build.make:93: src/rtl_433] Fout 1
make[2]: Map '/root/Downloads/rtl_433/build' wordt verlaten
make[1]: *** [CMakeFiles/Makefile2:1044: src/CMakeFiles/rtl_433.dir/all] Fout 2
make[1]: Map '/root/Downloads/rtl_433/build' wordt verlaten
make: *** [Makefile:144: all] Fout 2

**Comment by zuckschwerdt** [comment]
That's strange. SoapySDR 0.8+ should have SoapySDR_free().
https://github.com/pothosware/SoapySDR/blob/soapy-sdr-0.8.0/lib/TypesC.cpp#L26
From what sources did you compile that lib? Or is it may a pre 0.8 lib installed wrong?

Anyway, delete `#if (SOAPY_SDR_API_VERSION < 0x00080000)` and `#endif` in our sdr.c line 38,40, so you get
`#define SoapySDR_free(ptr) free(ptr)` unconditionally.
