### ISSUE TITLE
Home Assistant template rounding does not work

### ISSUE THREAD

**Issue by realthk** [merbanan/rtl_433#1888]
Recently I started to use [RTL433 addon](https://github.com/pbkhrv/rtl_433-hass-addons) (which is based on this repo) to integrate my 433 MHz sensors to Home Assistant.
This mostly works fine, but windspeeds often have BCD errors like this:
![](https://user-images.githubusercontent.com/5654575/142902794-d6664f97-e582-4c92-b60a-d596b769c953.png)
The reason is in the way HA templates used in examples/rtl_433_mqtt_hass.py. For example, [this conversion](https://github.com/merbanan/rtl_433/blob/c85279804c8231a49da64a0820c37657b39f1b27/examples/rtl_433_mqtt_hass.py#L269) is wrong:
`"value_template": "{{ float(value|float) * 3.6 | round(2) }}"`

Because in Jinja templating of HA, the order of execution is not guaranteed to be left-to-right, only if you use parentheses around everything before the last filter like this:
`"value_template": "{{ (float(value|float) * 3.6) | round(2) }}"`

For example, copy this into the template editor of developer tools in HA, and get the same 1.4400000000000002:
`{{ float(0.4|float) * 3.6 | round(2) }}`
while this results the correct 1.44:
`{{ (float(0.4|float) * 3.6) | round(2) }}`

**Comment by zuckschwerdt** [comment]
Thanks!
