### ISSUE TITLE
Update device IDs to reflect device model in Inkbird decoder

### ISSUE THREAD

**Issue by snicker** [merbanan/rtl_433#1891]
As others have noted, the Inkbird decoder supports the IBS-P01R Pool Thermometer as well.
https://www.amazon.com/gp/product/B08GFZS475/

Currently, the decoder assumes everything is a ITH20R (functionally, it doesn't matter) other than reporting the device ID

I just thought I would share the "unknown values" determined by running the decoder in verbose mode for the IBS-P01R:

```
inkbird_ith20r_callback dword0-3= 0x000F91D3
inkbird_ith20r_callback word5-6= 0x0100
inkbird_ith20r_callback byte18= 0x00
```

I am not certain if the ITH20R reports a different or the same value, but if they are different, these values could be used to map to device models.

Super low priority. @heffer86

**Comment by zuckschwerdt** [comment]
> inkbird_ith20r_callback dword0-3= 0x000F91D3
> inkbird_ith20r_callback byte18= 0x00

These values are the same as seen on the Inkbird devices.

> inkbird_ith20r_callback word5-6= 0x0100

That's interesting, the Inkbird would have 0x0103 or 0x0102 (little endian).

I'm adding these findings to the decoder notes.
