### ISSUE TITLE
Nice work, but I want more. :-)

### ISSUE THREAD

**Issue by johanadler** [merbanan/rtl_433#19]
Hi!

Thanks for the nice work!

I am trying to comprehend the source, since I want to try to make it do more. One thing I lack is units (and more info) on the output from -a. I will keep digging through the code and try to decipher it,but for me, having reverse analyzed wireless ISM protocols with a logic analyzer and writing code to make an Arduino decode it, times in µs or ms is essential, and I would really love a graphical representation of the signal train (not necessarily from your code, could be optional output to file for visualization by other software.)

When working on your code I already replaced most of the output to stderr with the proper output to stdout, since I noticed that a simple output redirection would just give me an empty file.

I would like the decoders and all related code to be in either one file or maybe each decoder should have a file of its own.

I too am looking forward to decoding and implementing the Efergy protocoll, Elite in my case. My Arduino code already handles two different temperature sensors, one with humidity sensing too, but I never got around to the Efergy stuff.

What unit are the values for signal_start, signal_end, signal_len and so on?

The source mentions some different PWM protocols, but many of the simple wireless ISM protocols use some kind of Manchester encoding (that your software seems to be able to decode, non the less).

Timing is vital if you want to implement a transmitter. Consider the TellStick project, for example.

I am not sure whether to fork this project or try to contribute. (Another thing I do not understand/approve of is the inclusion of the entire rtl_sdr source tree, when rtl-sdr.h should be available after a successful installation of that part.)

**Comment by merbanan** [comment]
I think everything you asked for is implemented now.
