### ISSUE TITLE
Implement own Protocol

### ISSUE THREAD

**Issue by SaschaMuehl** [merbanan/rtl_433#1907]
Hallo folks,
I sniffed my own 433MHz 
- remote and 
- weather station 
via universal radio hacker and a RTL-SDR-Dongle.
  
For the remote I wrote my own Python script for sending on/off signals via the 433MHz transmitter. Now I want not just send the signals I also want to read those via an RTL-SDR-Dongle or the cheap wired transceiver. 

I do have the sniffed protocols (long and short signals with different puls widths).

How can I implement a new or rather my own sniff protocol? Is there a prepared template or an manual?

Thanks.

**Comment by zuckschwerdt** [comment]
A decoder template is in https://github.com/merbanan/rtl_433/blob/master/src/devices/new_template.c
Copy to a new file, add to https://github.com/merbanan/rtl_433/blob/master/include/rtl_433_devices.h
the run ./maintainer_update.py (needs a clean git stage or commit).
There is also an older guide on the wiki: https://github.com/merbanan/rtl_433/wiki/digitech_xc0324.README

For simple remotes a flex conf (see conf dir) is prefered.
