### ISSUE TITLE
Sonoff wall switch T2EU3C-RF

### ISSUE THREAD

**Issue by tgeorgiop** [merbanan/rtl_433#1921]
Hello, I run rtl_433 for the wall switch T2EU3C-RF. 

1. When I press the buttons with `rtl_433` I see no response.
2. When I press the buttons with `rtl-433 -G 4` I see 
![Screen Shot 2021-12-29 at 00 12 44](https://user-images.githubusercontent.com/18070734/147610887-a56c1b14-7d47-4c7f-9eb2-075603fb3f6d.png)

I would like to publish mqtt decoded messages to home assistant broker. Is this possible?

**Comment by zuckschwerdt** [comment]
https://triq.org/rtl_433/ANALYZE.html to get started. A few examples for simple push buttons are in our conf directory.
If you like, post a working and documented .conf here or by PR.

**Comment by tgeorgiop** [comment]
Thanks for the answer.

- I ran `rtl_433 -S unknown` and the 3 signals were saved.
- I analyzed 1 of them with `rtl_433 -A g001_433.92M_250k.cs16` and the output was
![Screen Shot 2021-12-29 at 15 37 02](https://user-images.githubusercontent.com/18070734/147667863-1cbc79c3-7565-4f5a-b9da-1077badc7a83.png)

- I ran rtl_433 with the suggested decoder `rtl_433 'n=sonoff_T2EU3C-RF,m=OOK_PWM,s=188,l=588,r=6212,g=724,t=160,y=0'` and the output was
![Screen Shot 2021-12-29 at 15 40 01](https://user-images.githubusercontent.com/18070734/147668104-22e6cef0-1ac6-436a-a17c-f19b23a20449.png)

- I created a conf file 

> decoder {
    n=sonoff_T2EU3C_RF,
    m=OOK_PWM,
    s=188,
    l=588,
    y=6212,
    g=724,
    t=160,
    y=0,
    match={25}11e2f78
}
and I got the error "Bad flex spec, missing reset limit!". So, I entered the r with value 700 (bigger than l). Is it correct? Now, I see the signals from 1 button, which seems reasonable. I will enter 2 decoders more in the config file.

Now, I run `rtl_433 -c sonoff_T2EU3C-RF.conf -F "mqtt://192.168.2.178:1883,user=user,pass=pass,events=rtl_433"` and I get the messages in the mqtt broker. 
![Screen Shot 2021-12-29 at 16 23 32](https://user-images.githubusercontent.com/18070734/147671912-a182a8f8-ddd0-4f8d-be2d-e454b975a383.png)

Are they useful now? Can I decode them more? I see responses of other sensors and the format is very different.

**Comment by zuckschwerdt** [comment]
Change the suggestion to:
- s=200,
- l=600,
- g=1000,
- r=7000,
- no y= or t=

Those 25 bit (actually 24 plus sync bit) codes are the very common EV1527. It's just a unique number.

**Comment by tgeorgiop** [comment]
Thank you. Now, with `rtl_433 'n=sonoff_T2EU3C-RF,m=OOK_PWM,s=200,l=600,r=7000,g=1000'` the response is
![Screen Shot 2021-12-29 at 16 34 31](https://user-images.githubusercontent.com/18070734/147672933-10ac27ae-3ef6-4bc7-a248-b177c47244c2.png)

**Comment by zuckschwerdt** [comment]
You can add `unique` or `countonly` to get less data. Otherwise you are done!

**Comment by tgeorgiop** [comment]
Thank you very much! Can this button be supported by rtl_433 natively, without running the decoder?

**Comment by zuckschwerdt** [comment]
That's pretty much native support. Too much false positives if we add EV1527 decoders. The `match=` you use is essential.
