### ISSUE TITLE
Multiple sensors and one RTL_SDR receiver

### ISSUE THREAD

**Issue by garudaonekh** [merbanan/rtl_433#1925]
Hi,
Is it possible for a single RTL_SDR receiver listen for multiple sensors of different types? For example, I have a weather station, 4 soil sensors(RainPoint).

**Comment by zuckschwerdt** [comment]
If they are in the same band (e.g. 868 MHz), then yes.

The band covered is equal to the sample rate. At the default 433.92M and 250k sample rate that's 433.67 MHz to 434.17 MHz. For the 868M default sample rate of 1024k that's 867.5 MHz to 868.5 MHz. For the 868M it's like good to pick 868.3M for a band of 867.8 MHz to 868.8 MHz.

Use `-M level` and look at the frequency reported.
