### ISSUE TITLE
Support for solar powered weather station WH-SP-WS03

### ISSUE THREAD

**Issue by garudaonekh** [merbanan/rtl_433#1926]
Please add support for this model WH-SP-WS03

https://www.amazon.co.uk/MISOL-outdoor-Professional-Wireless-Weather/dp/B078JKYK24

**Comment by garudaonekh** [comment]
I use this one and it works:
[32]  Fine Offset Electronics WH1080/WH3080 Weather Station

**Comment by zuckschwerdt** [comment]
Fine Offset resellers/rebrands everywhere!
