### ISSUE TITLE
how to convert a raw / bin file form rtl_sdr to rtl_433 .cu8 files?

### ISSUE THREAD

**Issue by MaxPeal** [merbanan/rtl_433#1932]
how can i convert a raw / bin file form rtl_sdr to rtl_433 .cu8 files?
the rtl_sdr is created this way:
```
rtl_sdr -d 10smartV5 -f 868.625M -s 1600000 - | tee techem_data4_f868.625M_s1.6M.bin | rtl_wmbus -s
```
is it also possible to tag | filter the files for a specific wmbus device id?

**Comment by zuckschwerdt** [comment]
The default output format of `rtl_sdr` is already .cu8 (native RTL-SDR format).

**Comment by zuckschwerdt** [comment]
For the name you should use `techem_data4_868.625M_1600k.cu8`

**Comment by MaxPeal** [comment]
thank you for the fast answer.

do you have also a tipp for the filtering need?

**Comment by zuckschwerdt** [comment]
Sorry, I don't know what you mean.

**Comment by MaxPeal** [comment]
hope this is easier to understand:
with a rtl_sdr pipechain i can do a filtering like this (inc saving the "raw telegrams":
```
rtl_sdr -f 868.625M -s 1600000 - | rtl_wmbus -s |  grep -E ';03719685;' | tee -a rtl_wmbus.decode | $wmbusmeters --format=json stdin:rtlwmbus
```
can i make this also with rtl_433?

**Comment by zuckschwerdt** [comment]
You can save any output from rtl_433 to text files, e.g. `-F json:myfile.json` or `-F kv:myfile.txt` (see  `rtl_433 -F`).
If you want raw .cu8 data then use just the mbus protocol and saving:  `-R 104 -S known`

**Comment by gdt** [comment]
answered question
