### ISSUE TITLE
lora devices

### ISSUE THREAD

**Issue by opabert** [merbanan/rtl_433#1939]
Hi,
Wil it be possible to decode LORA devices in future?

**Comment by merbanan** [comment]
Well if you have a time machine that can be answered. Time machines aside I do have the logic for a lora demodulator. But right now I don't have the time to work on it. And then there is the question if it ever will be performing well enough to be useful.

So the most likely answer is no. And maybe it needs to run on its own and not side by side with a OOK/ASK and FSK demodulator.

**Comment by opabert** [comment]
Oke understand,  a standalone lora decoder that be nice.

**Comment by merbanan** [comment]
Something standalone not from me is much more likely.
