### ISSUE TITLE
See some packet short  and CRC fail

### ISSUE THREAD

**Issue by opabert** [merbanan/rtl_433#1940]
lacrosse_breezepro_decode: Wrong packet length: 236
lacrosse_wr1_decode: Packet too long: 237 bits
lacrosse_th_decode: packet length: 237
lacrosse_th_decode: Sync word not found
lacrosse_r1_decode: packet length: 237
lacrosse_r1_decode: Sync word not found
honeywell_cm921_decode: {1058} aa aa aa a8 ed 2d 4b 2d 33 4a ad 2d 4b 55 55 33 4d 4d 35 2b 35 35 33 55 55 54 d3 55 2d 35 2c b5 4b 33 33 35 54 d3 52 d2 d4 ab 52 d3 33 55 55 4a ca b3 4c b5 55 53 4c d3 54 ad 55 55 55 55 2a d4 ab 33 55 34 b5 2a b4 cb 55 55 4b 4a b4 ad 52 d3 4d 34 ab 55 54 b3 52 ad 53 34 aa ac ab 35 4b 4c d3 2d 32 aa cd 52 cc cb 52 b5 35 32 b3 4b 52 ca b2 d3 35 52 d3 53 32 aa cd 2d 54 cc b5 2d 4d 2c d3 32 b3 2c c0
preamble_start=1058 start=1088 len=-30
fineoffset_WH0290_callback: short package. Row length: 3. Header index: 27
bitbuffer:: Number of rows: 1
[00] { 3} e0        : 111
fineoffset_wh1080_callback: short package. Header index: 27
bitbuffer:: Number of rows: 1
[00] { 3} e0        : 111
fineoffset_WH0290_callback: short package. Row length: 1. Header index: 25
bitbuffer:: Number of rows: 1
[00] { 1} 80        : 1
fineoffset_wh1080_callback: short package. Header index: 25
bitbuffer:: Number of rows: 1
[00] { 1} 80        : 1
fineoffset_WH0290_callback: short package. Row length: 20. Header index: 44
bitbuffer:: Number of rows: 1
[00] {20} 20 00 d0  : 00100000 00000000 1101
M-Bus: CRC error: Calculated 0xFFFF, Read: 0x0
fineoffset_wh1080_callback: short package. Header index: 44
bitbuffer:: Number of rows: 1
[00] {20} 20 00 d0  : 00100000 00000000 1101
lacrosse_breezepro_decode: Wrong packet length: 2
lacrosse_wr1_decode: Packet too short: 6 bits
lacrosse_th_decode: Packet too short: 6 bits
lacrosse_r1_decode: Packet too short: 6 bits
honeywell_cm921_decode: {174} b0 00 00 78 20 46 44 00 01 20 70 01 0d 94 01 96 6a cc 50 bc 0e 20
preamble_start=174 start=204 len=-30
fineoffset_WH0290_callback: short package. Row length: 77. Header index: 101
bitbuffer:: Number of rows: 1
[00] {77} 80 e0 90 44 00 01 10 80 00 80
M-Bus: CRC error: Calculated 0xFFFF, Read: 0x0
fineoffset_wh1080_callback: short package. Header index: 101
bitbuffer:: Number of rows: 1
[00] {77} 80 e0 90 44 00 01 10 80 00 80
lacrosse_breezepro_decode: Wrong packet length: 22
lacrosse_wr1_decode: Packet too short: 26 bits
lacrosse_th_decode: Packet too short: 26 bits
lacrosse_r1_decode: Packet too short: 26 bits
honeywell_cm921_decode: {320} aa aa aa ab fe 00 b3 2a ab 2a 95 96 66 59 5a 66 a6 a9 6a 56 95 aa a9 52 cc ab 52 ca b2 ac b5 55 54 d3 4c ab 53 55 95 55
preamble_start=19 start=49 len=271
fineoffset_WH0290_callback: short package. Row length: 80. Header index: 104
bitbuffer:: Number of rows: 1
[00] {80} 7f ff ff ff ff ff ff ff ff ff
M-Bus: CRC error: Calculated 0xFFFF, Read: 0x0
fineoffset_wh1080_callback: short package. Header index: 104
bitbuffer:: Number of rows: 1
[00] {80} 7f ff ff ff ff ff ff ff ff ff
lacrosse_breezepro_decode: Wrong packet length: 45
lacrosse_wr1_decode: Packet too short: 46 bits
lacrosse_th_decode: Packet too short: 46 bits
lacrosse_r1_decode: Packet too short: 46 bits
honeywell_cm921_decode: {216} 39 1a 5f fe c9 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
preamble_start=216 start=246 len=-30
fineoffset_WH0290_callback: short package. Row length: 5. Header index: 29
bitbuffer:: Number of rows: 1
[00] { 5} 00        : 00000
fineoffset_wh1080_callback: short package. Header index: 29
bitbuffer:: Number of rows: 1
[00] { 5} 00        : 00000
fineoffset_WH0290_callback: short package. Row length: 17. Header index: 41
bitbuffer:: Number of rows: 1
[00] {17} ff ff 80  : 11111111 11111111 1
fineoffset_wh1080_callback: short package. Header index: 41
bitbuffer:: Number of rows: 1
[00] {17} ff ff 80  : 11111111 11111111 1
lacrosse_breezepro_decode: Wrong packet length: 9
lacrosse_wr1_decode: Packet too short: 9 bits
lacrosse_th_decode: Packet too short: 9 bits
lacrosse_r1_decode: Packet too short: 9 bits
fineoffset_WH0290_callback: short package. Row length: 3. Header index: 27
bitbuffer:: Number of rows: 1
[00] { 3} e0        : 111
fineoffset_wh1080_callback: short package. Header index: 27
bitbuffer:: Number of rows: 1
[00] { 3} e0        : 111
lacrosse_breezepro_decode: Wrong packet length: 2
lacrosse_wr1_decode: Packet too short: 2 bits
lacrosse_th_decode: Packet too short: 2 bits
lacrosse_r1_decode: Packet too short: 2 bits
fineoffset_WH0290_callback: short package. Row length: 4. Header index: 28
bitbuffer:: Number of rows: 1
[00] { 4} f0        : 1111
fineoffset_wh1080_callback: short package. Header index: 28
bitbuffer:: Number of rows: 1
[00] { 4} f0        : 1111
lacrosse_breezepro_decode: Wrong packet length: 1
lacrosse_wr1_decode: Packet too short: 1 bits
lacrosse_th_decode: Packet too short: 1 bits
lacrosse_r1_decode: Packet too short: 1 bits
fineoffset_WH0290_callback: short package. Row length: 1. Header index: 25
bitbuffer:: Number of rows: 1
[00] { 1} 80        : 1
fineoffset_wh1080_callback: short package. Header index: 25
bitbuffer:: Number of rows: 1
[00] { 1} 80        : 1

**Comment by merbanan** [comment]
This is normal operation from rtl_433. The output is from all decoders trying to process the bit stream.
