### ISSUE TITLE
Docs Issue For MQTT QoS 

### ISSUE THREAD

**Issue by ssmoss** [merbanan/rtl_433#1943]
I noticed this commit https://github.com/merbanan/rtl_433/commit/32c1f4a65fd238be70dee4af7ef8c58cec7af554 which seemed to remove details added about QoS for MQTT for an earlier issue I had opened up https://github.com/merbanan/rtl_433/issues/1769. I believe that 0 and 1 are supported but not 2.

**Comment by zuckschwerdt** [comment]
As pointed out: only use `qos=1` for debugging, it's not fully supported.
