### ISSUE TITLE
enable all protocols plus some disabled?

### ISSUE THREAD

**Issue by Gollam** [merbanan/rtl_433#1944]
Hi!
Sorry for the possibly dumb question, I cannot find an easy way to enable all default enabled protocols, plus a blacklisted one. I want to see the devices in my neighborhood, plus my disabled sensor's data. If I use -R, only the blacklisted one will be available, and -G will enable all of them, right? The only way I can think of is to write all numbers after -R, but that is not a very good method. So am I missing something?

**Comment by zuckschwerdt** [comment]
Using `-G` is never the right choice. You probably want a .conf file.
Otherwise just disable one protocol (negative number), that gives you all others, then add the one you want extra.

**Comment by Gollam** [comment]
Thanks!
