### ISSUE TITLE
868 MHz only receive Honeywell and Mbus

### ISSUE THREAD

**Issue by sdramateur** [merbanan/rtl_433#1945]
After several hours running
Using a high tower mast in a city area
- 868MHz
Only see honeywell no other devices shown 
No TPM  868
No KEYFOP 868
No weather stations 868

Do you know if Mbus are Smart meters?

![DEVICES_LIST_868_001_PNG](https://user-images.githubusercontent.com/79095872/150176497-b7570a70-ab4a-47ab-b735-6409a2d1f537.png)

**Comment by merbanan** [comment]
Mbus is used for meters. Electrica, water, gas.

**Comment by sdramateur** [comment]
Thank you.
I notice 868 MHz  is very, very busy,  is there a setting or way to find unknown devices or unknown protocol to shown?

**Comment by zuckschwerdt** [comment]
Maybe try with  `-Y autolevel -Y minmax -Y magest -M level -M noise -M time:usec -C si -F http` then open 127.0.0.1:8433 and switch Mode to raw.

**Comment by merbanan** [comment]
Closing.
