### ISSUE TITLE
SDRPlay and Windows 10

### ISSUE THREAD

**Issue by SuspectTheGoose** [merbanan/rtl_433#1974]
Hello,

I'm a bit confused on how to use RTL_433 on Windows 10 with an SDRPlay RSPdx. Can one use the premade SoapySDR libraries in the Pothos software package when compiling the RTL_433 source? Is there a command line switch required when compiling to enable use with SDRPlay receivers? Does a precompiled version of RTL_433 with SDRPlay support exist already?

Thank you.

**Comment by zuckschwerdt** [comment]
We have [releases](https://github.com/merbanan/rtl_433/releases) for Windows, which include versions with SoapySDR support. You need to supply the SoapySDR modules, e.g. install Pothos.

**Comment by gdt** [comment]
question was answered.
