### ISSUE TITLE
alarm() problem

### ISSUE THREAD

**Issue by gvanem** [merbanan/rtl_433#1977]
When using option `-vvvv`, I get a lot of Pulse-report output. 
So must that `rtl_433.exe` often exits with `Async read stalled, exiting`.

(tested n a DAB channel just for kicks).

But using `-vvvv 2> NUL` or a file, is okay.
This should perhaps be improved somehow.

**Comment by zuckschwerdt** [comment]
I suspected trouble there for some time. I had another (4th?) go at decoupling the SDR code the last weeks. This will solve this and many more problems. See #1978

**Comment by zuckschwerdt** [comment]
This should be fixed now, the watchdog is in the main loop and if that is busy (with output) no checks will be done.
