### ISSUE TITLE
Build on Debian

### ISSUE THREAD

**Issue by septs** [merbanan/rtl_433#1979]
```shell
git clone https://github.com/merbanan/rtl_433
cd rtl_433
apt-get install -y build-essential cmake librtlsdr-dev libsoapysdr-dev libssl-dev
./do_build.sh
```

**Comment by septs** [comment]
The issue only record build commands

**Comment by zuckschwerdt** [comment]
The `./do_build.sh` is special for the CI.

Always use
`mkdir build; cd build; cmake .. && make`
or better with Ninja:
`mkdir build; cd build; cmake -DFORCE_COLORED_BUILD:BOOL=ON -GNinja .. && cmake --build . -j 10`
