### ISSUE TITLE
Help decoding HS1527-based magnetic door sensor (SONOFF DW2-RF)

### ISSUE THREAD

**Issue by wipeout666** [merbanan/rtl_433#1982]
I'm having trouble understanding the signal coming from my magnetic door sensor SONOFF DW2-RF. Since it is HS1527-based, I am expecting a OOK_PWM modulation that RTL_433 would easily recognize, maybe with a flex decoder. However, upon a closer look with universal radio hacker, I myself cannot recognize anything coming out of that RF device.

Top signal is the capture signal from the SONOFF door sensor
Bottom signal is a signal from another device, something I recognize as ASK / OOK_PWM. I was expecting something similar to this signal.

![image](https://user-images.githubusercontent.com/71163149/154190800-dfd566df-f1ce-49f3-9073-479e01642ec8.png)

I did not include a .cu8 file because running RTL_433 with -A isn't picking up the signal from the door sensor. If it's helpful to record one anyway, let me know and I'll do it.

Can you help decoding this with RTL_433?

Thanks !

**Comment by zuckschwerdt** [comment]
Is that the waveform of the signals? If that's I/Q then you should offset the carrier from DC.
This is a single HS1527 packet and a zoom in (logic level, I, Q, amplitude):

![hs1527-a](https://user-images.githubusercontent.com/12833/154218719-6ebfdfa3-6879-433b-b546-da5ae9b4c13f.png)

![hs1527-b](https://user-images.githubusercontent.com/12833/154218727-59a03d1b-ff4f-4db2-8573-5a5960a11a16.png)

**Comment by wipeout666** [comment]
Yes this is the raw waveform, as capture when tuned to 433.92MHz.

Can you elaborate more on the DC offset? How is that applicable to RTL_433?

**Comment by zuckschwerdt** [comment]
It looks like the carrier is nearly at DC (0 Hz), you don't get a wave but only parts of slopes. You should offset this 10 kHz or more so you can better see the carrier (the green+yellow above).

**Comment by wipeout666** [comment]
Yup, that was part of the problem, good catch!. I've re-captured with a 20kHz offset:

![image](https://user-images.githubusercontent.com/71163149/154603346-34a326a3-6b71-402f-aa3a-d0c1d8b233d3.png)

![image](https://user-images.githubusercontent.com/71163149/154603363-0a73bc34-012a-44ae-bed3-66680cd09f02.png)

Capture: https://www.dropbox.com/s/v0ifbe7o2itkyys/RTL-SDR-20220217_205658-433_9MHz-1MSps-1MHz.zip?dl=1

I'm still not able to build a flex decoder in RTL_433. I think the following should work, but it does not: -R 0 -X "n=doorsensor,m=OOK_PWM,s=250,l=750,r=900,bits=25" -f 433.9M

The signal seems to slowly "die" at the end, loosing amplitude until zero. This seems to confuse RTL_433; how can I get around that?

**Comment by zuckschwerdt** [comment]
The fading at the end is expected for a HS 1527 encoder and won't be a problem.

**Comment by zuckschwerdt** [comment]
The sample isn't like anything we expect to encounter live (no noise floor, prominent DC). But it exposed a logic flaw in the pulse detector. We reset the detector on spurious short pulses, which we likely shouldn't (only noticeable if there is already pulse data from a previous buffer that had no marked frame end). I'll fix that shortly.

**Comment by wipeout666** [comment]
"_the sample isn't like anything we expect to encounter live_" - But this is exactly as I've captured. OK, the transmitter is close to the antenna, but I did not create a perfect environment. Just the environment it's going to work in.

"_We reset the detector on spurious short pulses_" - Where do you see that ?

Just curious; good if it can be fixed! Otherwise, what can I try, now?

**Comment by zuckschwerdt** [comment]
The capture isn't post-processed? What SDR did you capture with? Why is there no noise floor?

You can set [PD_MIN_PULSE_SAMPLES](https://github.com/merbanan/rtl_433/blob/master/include/pulse_detect.h#L21) to a lower value, like 1 and this will then work:
`rtl_433 -X 'n=name,m=OOK_PWM,s=125,l=380,g=500,r=1000'`

**Comment by wipeout666** [comment]
No, it is not post processed. It was captured with universal radio hacker, so unless the record tool is post processing without my knowledge...

The radio is RTL2832U. I'll try your suggestion in a few hours, when I get back home

**Comment by zuckschwerdt** [comment]
If that was an RTLSDR then the sample is heavily post-processed. Capture with `-S unknown` or perhaps something like `-w myfile.cu8 -T 30` and compare in https://triq.org/pdv/

**Comment by wipeout666** [comment]
The red arrows are the magnetic door sensor event's (each time two events each ~1s appart, then 3 quick ones, then two events ~1s appart). Using "-w", the signal, apparently, is clipping with auto gain:

![image](https://user-images.githubusercontent.com/71163149/154890566-d8d2eb04-fab9-4536-bdf6-23a21d3ad5d0.png)
Ref: clipping.cu8

I manually set the gain to 40dB, which yields:
![image](https://user-images.githubusercontent.com/71163149/154890600-8017ed19-8713-4b51-98a7-92ad349e7067.png)

https://www.dropbox.com/s/mjp4f0tkzl8w75n/DoorSensorCapture.zip?dl=1

Even with gain set at 40dB, I encouter the same struggles ... Any clues in this?

**Comment by wipeout666** [comment]
Setting PD_MIN_PULSE_SAMPLES to 1 does work with the following:

 rtl_433 -f 433.91M -R 0 -X "n=rfdoor,m=OOK_PWM,s=250,l=750,r=7850,g=760,repeats>=2,match={25}c9c47e8"

Is the change to PD_MIN_PULSE_SAMPLES going to adversely impact demodulation of my other stuff?

**Comment by zuckschwerdt** [comment]
> Is the change to PD_MIN_PULSE_SAMPLES going to adversely impact demodulation of my other stuff?

Yes, it will impact FSK very much.

**Comment by wipeout666** [comment]
Thanks for confirming; not an issue for me at the moment. Is there a mecanism to know when the "_logic flaw in the pulse detector_" will be fixed? An issue to track? I'll need to keep PD_MIN_PULSE_SAMPLES at 1 until then.

Thanks for your help, I couldn't have done it without your support!

**Comment by zuckschwerdt** [comment]
I'm working on a fix, but it's a critical piece which could cause big regressions, so hard to change.

**Comment by wipeout666** [comment]
Can PD_MIN_PULSE_SAMPLES be set in the .conf file instead of recompiling pulse_detect.h?

**Comment by zuckschwerdt** [comment]
No, sorry. It's not meant to be a configurable value but just a sanity check for the pulse detector.

**Comment by zuckschwerdt** [comment]
It should be fixed now, you will get bitbuffers for OOK even if the pulses end with a spurious short pulse.

**Comment by sheilbronn** [comment]
Hello, I have a Sonoff DW2-RF, too. However, it seems the signal is not being picked up in the my current version of rtl_433 (21.12-95-gddbc8420 branch master at 202204012124), but only in the Sonoff 433MhZ Bridge running in parallel. 
Could somebody **please confirm that the DW2 should be working in the current version**?! Thx!
Is there anything I could do to support debugging?

**Comment by wipeout666** [comment]
The fix was introduced in this commit:
![image](https://user-images.githubusercontent.com/71163149/168187218-ce9327a2-1463-416c-b2b4-757366b5d55f.png)

So my guess is that you do not have the fix in this version; you should upgrade.

Also note that you need to change the tuner's frequency to be a little offset from 433.92MHz, such as: -f 433.91M

Turns out my SONOFF device is exactly tuned at 433.92MHz, unlike my other 433MHz devices. Being tuned at exactly the carrier's frequency doesn't work, as everything is shifted to DC, which is not decodable.

Hope that helps
