### ISSUE TITLE
Installing rtl_433 on Windows 10

### ISSUE THREAD

**Issue by rowanbradley** [merbanan/rtl_433#1999]
I'm trying to install rtl-433 on Windows-10. I need to do this to read the data from my Apollo oil level sensor. I have run into several problems:

1. The instructions that I'm trying to follow say "install GNU Radio Live SDR Environment". When I go to the page https://wiki.gnuradio.org/index.php/GNU_Radio_Live_SDR_Environment, it says "Distribution of the GNU Radio Live SDR is currently retired. We are looking into creating new images based on newer releases.". Where do I get this software to install on my Windows PC (in a Ubuntu VM)?
2. In another part of the instructions, it tells me to run the command $ sudo add-apt-repository ppa:gnuradio-releases-3.9
on my Ubuntu VM. When I do this, I get "Cannot add PPA: 'ppa:~gnuradio-releases-3.9/ubuntu/ppa'.
ERROR: '~gnuradio-releases-3.9' user or team does not exist.". How do I overcome this problem?

I am a total noob with Unix type OS, so this may be some very simple finger trouble, but I need help to get through this. And get it working so I can read my data. Ideally this will be without rebuilding software, which will (I suspect) get me into much deeper water...

I _think_ I have got the Ubuntu VM installed properly, and working, but I can't be sure...

Thank you - Rowan

**Comment by zuckschwerdt** [comment]
Where did you read that? Those instructions seem rather off.
Just get the [Windows release](https://github.com/merbanan/rtl_433/releases).
If you want to use SoapySDR driver (any SDR other than RTL-SDR) then install [Pothos](https://downloads.myriadrf.org/builds/PothosSDR/).
