### ISSUE TITLE
1byOne (Quhwa) Wireless Doorbell Transmitter

### ISSUE THREAD

**Issue by luigough** [merbanan/rtl_433#20]
Dear Benjamin Larsson,

First of all, thanks for rtl_433. It has been quite useful in monitoring ASK/OOK signals, and I have thoroughly enjoyed using it.

I recently purchased several 1byOne branded (Quhwa manufactured) wireless doorbell transmitters. I have three of them, and I had dumped the analyze data on my blog posting about it at http://goughlui.com/?p=5395

The data looks very sensible, and patterns are visible (last 3 octets of all 3 transmitters are 0xbc0, 49 repetitions). I was wondering if you could add this as a protocol filter to the code as it seems very trivial to implement.

Many thanks,

Gough.

**Comment by merbanan** [comment]
This should be supported now.
