### ISSUE TITLE
Data specification inconsistent for "id"

### ISSUE THREAD

**Issue by xhci** [merbanan/rtl_433#2005]
[DATA_FORMAT.md](https://github.com/merbanan/rtl_433/blob/d123816efec570a2a79250405022431ffea2f5c7/docs/DATA_FORMAT.md) specifies `id` as an optional `string`, however it comes back as a json `number` in many cases (at least in my testing with Acurite 609TXC/Tower sensors).

I think it's worthwhile to either modify the spec and specifically point this out (easy), or comply with what is already there (probably harder).

While the second option is probably more difficult to identify and fix all the cases, it prevents custom unmarshalling logic in downstream systems.

Example of a received MQTT message:
`{"time":"2022-03-07 05:55:13","model":"Acurite-Tower","id":12084,"channel":"A","battery_ok":1,"temperature_C":-7.7,"humidity":13,"mic":"CHECKSUM"}`

`"id":12084` is the problematic part.

**Comment by zuckschwerdt** [comment]
A reader needs to be flexible with the values, most "id" values are integer, but might also be string (notably to give hex string from e.g. TPMS). Also "channel" is usually an integer, but there are two decoders that insist on a string (acurite.c, x10_rf.c).

I'll update the docs, thanks!
