### ISSUE TITLE
Log to two destinations

### ISSUE THREAD

**Issue by rowanbradley** [merbanan/rtl_433#2006]
Can rtl_433 handle multiple logging destinations? I.e. can I do something like this:
rtl_433.exe -F json -F json:'D:\XPS_8700 Extended Files\Users\RowanB\Documents\Energy\Oil\Apollo Oil Level\Readings\oil_level_$((Get-Date).ToString(\'yyMMdd\')).json

What I would hope thisw would do is to log data to stdout, but also log the same data to a file.

Is this possible?

Thanks - Rowan

**Comment by zuckschwerdt** [comment]
Yes, as many as you like, it's a common setup. https://triq.org/rtl_433/OPERATION.html#outputs
