### ISSUE TITLE
How to add support for WS80BN weather station

### ISSUE THREAD

**Issue by w1ll1am23** [merbanan/rtl_433#2011]
Picked up one of these https://ambientweather.com/build-your-own-personal-weather-station (the ws-5000)

Hoping it would just work with rtl_433. Unfortunately it does not. 

With -vvvv output I see pulses but not sure where to go from there in trying to get this thing supported. 

Any guidance on what I can collect to help? Or a guide on how to go about adding support myself? 

Thanks.

**Comment by zuckschwerdt** [comment]
There are some hints on https://triq.org/rtl_433/ANALYZE.html

**Comment by w1ll1am23** [comment]
Thanks, I'll take a look

**Comment by gdt** [comment]
Please feel free to ask for help if you dig in.
