### ISSUE TITLE
A locking problem

### ISSUE THREAD

**Issue by ryancaicse** [merbanan/rtl_433#2022]
Hi, it seems the lock `srv->lock` is not released before Line 246. Although the condition may not very possible to reach, would it be better to release the lock before returning?

https://github.com/merbanan/rtl_433/blob/517b972f99ed4fd53da95925e0afbb417dc3f588/src/output_rtltcp.c#L231-L246

**Comment by zuckschwerdt** [comment]
Thanks for looking through this! Valid point. The code around the slots mechanism was changed quite a lot in the end and I missed that.
On the other hand it's really an invariant and we are doomed should 2 users (writer + reader) lock more than 2 slots ;)

That code has been replaced already with a different strategy (the global ring buffer on shared memory, mentioned in line 91), we'll hopefully have that in a few months.
