### ISSUE TITLE
Force MQTT topic id

### ISSUE THREAD

**Issue by Ulrar** [merbanan/rtl_433#2026]
Hi,

I'm using this in docker and on each run, it comes up with a new id and home assistant has to be pointed to the new one.
Is there a way to keep the default behavior of publishing everything, but force the ID ? I see that you can do it per event type, but when you do that not everything gets published.

`-C si -M level -Fmqtt://172.22.0.1:1883,user=mqttuser,pass=mqttpass,retain=1`

```
Publishing device info to MQTT topic "rtl_433/9717d81a1fdf/devices[/type][/model][/subtype][/channel][/id]".
Publishing events info to MQTT topic "rtl_433/9717d81a1fdf/events".
Publishing states info to MQTT topic "rtl_433/9717d81a1fdf/states".
```

In the above `9717d81a1fdf` changes everytime the container restarts.

Thanks

**Comment by zuckschwerdt** [comment]
See https://triq.org/rtl_433/OPERATION.html#outputs
You want to add 
- `devices=rtl_433/no-host/devices[/type][/model][/subtype][/channel][/id]`
- `events=rtl_433/no-host/events`
- `states=rtl_433/no-host/states`
