### ISSUE TITLE
Add Support for Digitech XC-0430 Rain Gauge

### ISSUE THREAD

**Issue by PetarMilevski** [merbanan/rtl_433#2038]
Hi all, I would like some help to add support for the Digitech XC-0430 rain gauge. 

I want to build a rainfall pluviograph from this device. So exporting the temperature reading is not that important at the moment (but others may want this feature).

I want to collect the number of the bucket tips that occur each time the unit transmits data and then to save that data to a text file. 

The unit transmits data at 917MHz frequency every 12 seconds.

I have created a pull request here:

https://github.com/merbanan/rtl_433_tests/pull/423

If you need any other data please let me know.

Thanks in advance, great project!!

**Comment by zuckschwerdt** [comment]
Drop the files on https://triq.org/pdv/ -- you see it is FSK.
Run `rtl_433 -A` on some files. Too much noise, not detected as FSK. Someone needs to look for the problem.
Maybe try a clean recording to analyze the protocol, then solve the noise issue later.

> To get a clean signal remove the receiver antenna and place the device at 10cm to the receiver, that mostly isolates the transmissions.

**Comment by PetarMilevski** [comment]
Thanks for your response. Leave it with me, I'll do as you suggest and try to get a cleaner recording.

**Comment by PetarMilevski** [comment]
Hi i just push up some new data collected as per your recommendations. Please have a look and let me know if it's about good. If it's not, i really don't know what more i can do. Regards

**Comment by zuckschwerdt** [comment]
If you have Pulseview (from SigRok) installed, then you can take a look at the demod:

`rtl_433 -W 16tips_temp16_6DegC_917M_1000k.sr 16tips_temp16_6DegC_917M_1000k.cu8`
![XC-0430 Rain Gauge](https://user-images.githubusercontent.com/12833/161371169-78456e61-425d-4f27-bece-a6a6b4e9a4b0.png)

The FSK is there and plain to see, but for some strange reason the demod ignores it. Something wrong with the pulse_detect. This will take some time to debug.

For comparison, here is what a signal from e.g. Bresser-6in1 looks like in the demod:

![bresser-6in1](https://user-images.githubusercontent.com/12833/161371340-968b39ae-8472-45e5-b78e-f49182407c08.png)

**Comment by PetarMilevski** [comment]
Ok so the data i sent is "ok". I'm in no hurry, I'll leave it in your capable hands to debug. I have a La Crosse LTV-R1 coming in the mail next week which is supported by your software.I will try getting it to do what i need.

**Comment by gdt** [comment]
@PetarMilevski Are you still working on this?  Plans?

**Comment by gdt** [comment]
abandoned (>2y) and not enough useful info to justify remaining open
