### ISSUE TITLE
protocol 214

### ISSUE THREAD

**Issue by giros79** [merbanan/rtl_433#2056]
Hi,
i tried to install in a rasp pi zero w but i cachet see more than these.

Registered 145 out of 175 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 ]

i need 214

if dongle is connected to macbook everything is 👌🏻

thanks

**Comment by zuckschwerdt** [comment]
The version you installed (from Debian repo likely) is too old. You need to compile the latest version yourself:
https://triq.org/rtl_433/BUILDING.html#linux-mac-os-x

**Comment by giros79** [comment]
many thanks @zuckschwerdt
