### ISSUE TITLE
need help for my project

### ISSUE THREAD

**Issue by IFMradio** [merbanan/rtl_433#2059]
Good evening I am a student and I would like as part of my project, edit the source code to receive only the data that I need and sent them by a function that I will create. The command that interests me is the following: rtl_433 -M level -T 40 is what it is possible to help me reduce the source code or modify it so that when we launch the program the command is automatic. thanks in advance

**Comment by IFMradio** [comment]
> What data? And send it how and where?

Good evening thank you for this quick answer, the data are: the power "rssi", the model "model", the identifier "id", the time "time" and finally the snr. This data will be sent via a function that makes a POST request to send it to the server and then a GET request to receive it. Of course this data will then arrive in a MariaDB database

**Comment by zuckschwerdt** [comment]
- The easy way: use a script like https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_custom.py to receive the JSON data via syslog UDP, then post it from there. I don't see the need to change rtl_433 for that, just start it with `rtl_433 -M level -F syslog` (or use a .conf file, see https://github.com/merbanan/rtl_433/blob/master/conf/rtl_433.example.conf)

- The advanced way: look at https://github.com/merbanan/rtl_433/blob/master/src/http_server.c and pull the data from REST or WebSocket (instead of HTTP POST push). Again no reason to change anything, just `rtl_433 -M level -F http`

- The hard way: look at https://github.com/merbanan/rtl_433/blob/master/src/output_influx.c and duplicate that for a HTTP POST output.

**Comment by IFMradio** [comment]
Thanks again for the advice but my real problem is that I am limited in line of code and the only command that is really necessary for me is this one rtl_433 -M level -T 40 and sends data to the server. My question will be rather: is there no way to remove the other options? sorry for the inconvenience

**Comment by zuckschwerdt** [comment]
> am limited in line of code

You really mean actual lines of code? rtl_433 is about 80k lines.

> only command necessary is this one rtl_433 -M level -T 40

Sorry, that's not a *command* but an *option*. The command is `rtl_433` and can't be slimmed down without losing functionality.

Maybe look at https://github.com/osmocom/rtl-sdr/blob/master/src/rtl_power.c or the similar ones. Or perhaps use Python and SoapySDR to write your own RSSI meter.

**Comment by IFMradio** [comment]
> > je suis limité dans la ligne de code
> 
> Vous voulez vraiment dire des lignes de code réelles? rtl_433 est d’environ 80k lignes.
> 
> > la seule commande nécessaire est celle-ci rtl_433 -M niveau -T 40
> 
> Désolé, ce n’est pas une _commande_ mais une _option_. La commande est et ne peut pas être allégée sans perdre de fonctionnalité.`rtl_433`
> 
> Peut-être regarder https://github.com/osmocom/rtl-sdr/blob/master/src/rtl_power.c ou les similaires. Ou peut-être utiliser Python et SoapySDR pour écrire votre propre compteur RSSI.

what I meant was that I wanted to remove the other options and leave only this one. Like its when I launch the program rtl_433 I do not have to define the option I want to choose.
I don't know if I was clear enough.
thank you very much for your help

**Comment by zuckschwerdt** [comment]
Write a file `start_rtl433.sh`:
```
#!/bin/sh
rtl_433 -M level -T 40
```
then `chmod a+x start_rtl433.sh` and now it is automated with `start_rtl433.sh`

If you desperately want a custom version (which seems really wrong) then change this line:
https://github.com/merbanan/rtl_433/blob/master/src/rtl_433.c#L1386

**Comment by IFMradio** [comment]
> chmod a+x

I think used start.sh is the best solution thank you for your help I would have another question why the version with logging was not kept

**Comment by zuckschwerdt** [comment]
> why the version with logging was not kept

What is a "version with logging"? How did we "not kept"? Was something removed?

**Comment by IFMradio** [comment]
https://github.com/merbanan/rtl_433/tree/feat-logger  is it another version? maybe I'm wrong

**Comment by zuckschwerdt** [comment]
It is not a version. Ignore it.
