### ISSUE TITLE
collected pipe 

### ISSUE THREAD

**Issue by IFMradio** [merbanan/rtl_433#2070]
Hello I would like to collect the data send by rtl_433 with the rtl_433_collectd_pipe.py but I do not know how to make it work can you help me

**Comment by zuckschwerdt** [comment]
That's just an example to roll your own integration. You will need to change the script to fit your setup.
Then just start something like `rtl_433 SOME-OPTIONS-HERE | rtl_433_collectd_pipe.py`

**Comment by AutomGuy** [comment]
which OS you are you use ? is it a debian linux? and what will you do with the collected data?

**Comment by IFMradio** [comment]
> which OS you are you use ? is it a debian linux? and what will you do with the collected data?

Raspian lite  and the data I will send to my database through a function

**Comment by AutomGuy** [comment]
I would like to say -> take a look in that example "rtl_433_influxdb_relay.py ". This script is more or less a UDP server with DB connector in that case a influxdb. So you have to start  "rtl_433 -F json syslog:127.0.0.1:1433" (may be as service) afterwards you should start the python script above. First of all you have to modify the python script above with your database values.

**Comment by IFMradio** [comment]
> I would like to say -> take a look in that example "rtl_433_influxdb_relay.py ". This script is more or less a UDP server with DB connector in that case a influxdb. So you have to start "rtl_433 -F json syslog:127.0.0.1:1433" (may be as service) afterwards you should start the python script above. First of all you have to modify the python script above with your database values.

unfortunately I don't use influxdb I use a Mariadb

**Comment by AutomGuy** [comment]
that should be not a problem you have to exchange all influxdb stuff to mariadb stuff. i believe that python has also mariadb stuff @zuckschwerdt is'n it. @IFMradio Or you are not familar with python?

**Comment by IFMradio** [comment]
> that should be not a problem you have to exchange all influxdb stuff to mariadb stuff. i believe that python has also mariadb stuff @zuckschwerdt is'n it. @IFMradio Or you are not familar with python?

I know basic things on python , most of the time I code in C/C++  
In fact I wanted to go through a pipe because the information must be processed by the function created by my colleague I do not really need a connection with my database

**Comment by AutomGuy** [comment]
So ok IMHO the pipe script "rtl_433_collectd_pipe.py" work like this. The received record with the fields wich are defined inside the script will send  a payload at a specific time to a specific host and specific port. @zuckschwerdt right? Under this circumstances i think you need a piece of Software that receive this record -> pass it through your colleague's function and write it to the database.

**Comment by AutomGuy** [comment]
@zuckschwerdt  Christian the custom.py print the value only to the stdout is'n it?

**Comment by zuckschwerdt** [comment]
> the custom.py print the value only to the stdout is'n it?

Yes, you will always need to add some logic to handle values (e.g. send to DB)

> i prefer the udp things, because its nicer for debuging and distributing of values. :)

Yes, me too. Pipe can break and you can't control (restart...) the programs individually.

**Comment by IFMradio** [comment]
> So ok IMHO the pipe script "rtl_433_collectd_pipe.py" work like this. The received record with the fields wich are defined inside the script will send a payload at a specific time to a specific host and specific port. @zuckschwerdt right? Under this circumstances i think you need a piece of Software that receive this record -> pass it through your colleague's function and write it to the database.

I launched the script rtl_433_collectd_pipe.py with rtl_433 -F log:127.0.0.1:25826 but at the output nothing is displayed is it necessary to print to check that there is information. And why I need to use software. All I want is to have access to live rtl_433 data.

**Comment by IFMradio** [comment]
> I would recommend `rtl_433_custom.py` but yes, any of the scripts (pipe or UDP) will work. You can also read the JSON from a C program directly with `rtl_433 -F json | my_c_program`
I haven't tried yet but if you recommend it to me it's probably better for what I have to do :)  thanks for advice

**Comment by IFMradio** [comment]
![Capture_rtl](https://user-images.githubusercontent.com/104509792/168235692-f26ab1a1-c38d-4ea8-962a-86874c501283.PNG)
![image](https://user-images.githubusercontent.com/104509792/168235797-caf01fdc-3dab-4a14-845f-a11429989391.png)

**Comment by IFMradio** [comment]
well i put 127.0.0.1 but don't worry i change the ip adress

**Comment by zuckschwerdt** [comment]
https://github.com/merbanan/rtl_433/tree/master/examples
note which `-F` is used.

**Comment by IFMradio** [comment]
![image](https://user-images.githubusercontent.com/104509792/168244873-b92c9edf-4108-48a9-ad48-53664c8a3aab.png)
![image](https://user-images.githubusercontent.com/104509792/168245373-759175ff-b6f8-4391-b762-2047d98493d8.png)

**Comment by IFMradio** [comment]
I put syslog:the ip address of my pc:1433 but still no data

**Comment by zuckschwerdt** [comment]
You can add `-F kv` to see what is sent out.

**Comment by IFMradio** [comment]
like this: rtl_433 -F kv:the ip address of my pc:1433?

**Comment by IFMradio** [comment]
![image](https://user-images.githubusercontent.com/104509792/168247068-f6b818d0-b964-48bc-878d-911539e9115c.png)
I receive no data on my pc

**Comment by IFMradio** [comment]
sortie mean output

**Comment by zuckschwerdt** [comment]
No. Add each output on it's own:
`rtl_433 -F kv -F syslog:127.0.0.1:1433`

**Comment by IFMradio** [comment]
![image](https://user-images.githubusercontent.com/104509792/168251192-72cea8c5-4d9d-4002-9d95-65e53b595625.png)
I don't understand I still have nothing

**Comment by zuckschwerdt** [comment]
Ok, E4000 tuner? That might be the problem. Use `-Y autolevel -M level -M noise`

**Comment by IFMradio** [comment]
> Ok, E4000 tuner? That might be the problem. Use `-Y autolevel -M level -M noise`
![image](https://user-images.githubusercontent.com/104509792/168286486-8e0c7b6b-bc7f-4d0c-b875-805f25e249e1.png)

**Comment by zuckschwerdt** [comment]
Seems you are using an old version of rtl_433.
Install a new one (https://triq.org/rtl_433/BUILDING.html)
You should see:
```
baseband_demod_FM: low pass filter for 250000 Hz at cutoff 25000 Hz, 40.0 us
...
Estimated noise level is -17.4 dB, adjusting minimum detection level to -14.4 dB
...
Current noise level -21.6 dB, estimated noise -18.4 dB
```

**Comment by IFMradio** [comment]
Hello I tried to manage to solve the problem but unfortunately I have the same error at the output: The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by zuckschwerdt** [comment]
> The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Sorry, I don't know about Pylance (is it VSCode?). If the startup crashes, then perhaps the command or parameters are wrong?

**Comment by IFMradio** [comment]
> > The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

it's ok I solved with  the problem with the server it was enough to uninstall and reinstall the python extension and I managed to send the data to the function of my teammate thank you for your help and especially thank you for devoting your time to answer my questions.
