### ISSUE TITLE
Microchip-HCS200

### ISSUE THREAD

**Issue by rumicagit** [merbanan/rtl_433#2074]
Everyone noticed that decoding Microchip-HCS200 has changed in last version?
The old one has id, id_rev,, encrypted and encrypted reverse.
Now it has only id end encrypted. But the id is the old id_reversed with less than a character (7 instead on 8).
Can anyone one explain if this is a feature or a bug?
Don't we loose some info now?
Regards

**Comment by zuckschwerdt** [comment]
See #1752 and #1512
