### ISSUE TITLE
Support for ambient weather remote sensor WH2B

### ISSUE THREAD

**Issue by maxmib** [merbanan/rtl_433#2084]
Is wh2b supported by rtl433 ? Thanks .

Link from Amazon  
Ambient Weather WH2C Thermo-Hygrometer https://a.co/d/7Bw1Baw

It seems to be the same with WH2C.

**Comment by zuckschwerdt** [comment]
The code is in [fineoffset.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/fineoffset.c).
Currently we known about WH2 and WH2A. Post some samples and we'll add support for WH2B/C.
https://triq.org/rtl_433/ANALYZE.html

**Comment by zuckschwerdt** [comment]
Is the device that old? What's noted there should fit with the WH2 code :)

**Comment by maxmib** [comment]
I think wh2b is  at least eight years old according to comments on Amazon.I bought some at very cheap price . When I get them ,I will check if they can be recognized by rtl433.Thanks.

**Comment by maxmib** [comment]
WH2b is supported by rtl433 ,it fits with WH2 code .so issue closed.

**Comment by zuckschwerdt** [comment]
Thanks for the feedback!
