### ISSUE TITLE
ISM PLUGIN FOR AIRSPY R2

### ISSUE THREAD

**Issue by nj3h** [merbanan/rtl_433#2095]
Is there any chance that you can make your ISM plug in work with the Airspy R2?

When I try using it, I get an unhandled exception after a minute.

Using the latest plug in version, Win 10, SDR# vers. 1858.

Any help in this regard would be helpful.

Thanks,
George

**Comment by zuckschwerdt** [comment]
You are looking for another project, likely https://github.com/marco402/Rtl_433_dll-for-plugin-SdrSharp
They just copied our readme file, that might be the confusion :)
