### ISSUE TITLE
"time" field terminal color choice makes it hard to read

### ISSUE THREAD

**Issue by gvanem** [merbanan/rtl_433#2097]
My shell (4NT from [jpsoft.com](jpsoft.com)) uses a blue background. 
So when using the `-M time` parameter the console looks like:
![RTL_433_time](https://user-images.githubusercontent.com/945271/175774795-1db1c17b-8dd4-4f47-a64f-d01e782021f6.png)

invisible! So after this patch:
```diff
--- a/src/output_file.c 2022-05-16 12:21:09
+++ b/src/output_file.c 2022-06-25 15:01:07
@@ -155,7 +155,7 @@
     if (!key || !*key)
         return TERM_COLOR_RESET;
     if (!strcmp(key, "tag") || !strcmp(key, "time"))
-        return TERM_COLOR_BLUE;
+        return TERM_COLOR_BRIGHT_WHITE;
     if (!strcmp(key, "model") || !strcmp(key, "type") || !strcmp(key, "id"))
         return TERM_COLOR_RED;
     if (!strcmp(key, "mic"))
```

it looks OK for me:

![RTL_433_time-2](https://user-images.githubusercontent.com/945271/175774891-5ff43a2d-9aad-4d1b-81a8-5a68b6a3f498.png)

I think many people have other background shell colours than plain black. I have yet to see someone with bright-white.
So the above patch should be pleasing for most.

**Comment by zuckschwerdt** [comment]
Bright (9x codes) doesn't seem to work in my terminals. The default white isn't great on a bright background (we should consider bright and dark bg's, and also blue then).

![bright_term](https://user-images.githubusercontent.com/12833/175776876-678715f6-2858-4082-9abb-dd78805eb639.png)

Maybe we need to add the `bold` attribute for this?

**Comment by gvanem** [comment]
Or a reverse;`TERM_COLOR_BRIGHT_BLUE_ON_WHITE`. Possible?

**Comment by gdt** [comment]
I would expect there is prior art on how to deal with this (besides the curmudgeon approach of not using colors).   rtl_433 doesn't seem particularly special in doing this sort of thing.

**Comment by gdt** [comment]
I'm inclined to close this; it seems intractable and if someone wants to create a PR that adds some general approach that's fine.  This could be support for multiple palettes, or a config file for colors.     But I can't see us tweaking colors to fit particular people's setups, and this has been idle for a long time.

(I can also see an easy way to disable colorization.  This is proof that's needed, but that's for another issue.)
