### ISSUE TITLE
TFA 30.3243.02 is supported

### ISSUE THREAD

**Issue by unicilindro** [merbanan/rtl_433#2107]
Thanks for maintaning such a cool project!

It would be nice to mention in the docs that TFA 30.3243.02 works well, it's detected as "LaCrosse-TX141Bv3" and shows correct temperature/humidity.
https://www.tfa-dostmann.de/en/product/temperature-transmitter-30-3243/

**Comment by zuckschwerdt** [comment]
Thanks!
