### ISSUE TITLE
If MQTT output is enabled, publish online / LWT message

### ISSUE THREAD

**Issue by Elwell** [merbanan/rtl_433#2108]
Wishlist idea: if MQTT is one of the output formats used, when connected to a broker, publish 'Online' to say rtl_433/hostname/status, with a Last Will & Testament (LWT) to the same topic of 'Offline'

I suspect it'll need a change to the connection logic in src/output_mqtt.c, but that's about the limit of my knowledge

Spec of the will details is in https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901040

My use case for this is with RF sensors - if I stop seeing them updating on home assistant or wherever, I've no way of knowing if the battery is flat in the sensor, or that rtl_433 has died. knowing that the RF->network link is healthy means I can fault find easier.

Many thanks
Andrew

**Comment by zuckschwerdt** [comment]
There is a discussion in #1394 and a PR in #1547. TL;DR We can can't reliably set anything but "Online". It's really not clear what the states should be.
Basically we could set "Online" and "Offline" but you can't deduce anything from "Offline".
