### ISSUE TITLE
ecowitt wh40 output?

### ISSUE THREAD

**Issue by GHSTUDIO1** [merbanan/rtl_433#2111]
I am running RTL_433 to an MQTT server and reading the results with Node-Red to feed through Home Assistant.  I have a WH51 working perfectly, showing 

time: "2022-07-17 14:38:20"
model: "Fineoffset-WH51"
id: "0ce5b7"
battery_ok: 1
battery_mV: 1600
moisture: 38
boost: 0
ad_raw: 207
mic: "CRC"

I just tried a WH40 rain gauge and the only output I get is:

time: "2022-07-17 14:37:35"
model: "EcoWitt-WH40"
id: 5185
rain_mm: 0.6
data: "2040000000"
mic: "CRC"

Is it possible to see battery status and/or battery_mv?  Any idea what's in the data field?  The rain_mm field appears to be  cumulative (tested it manually) but cumulative in the last hour/day/until the battery is changed/????.   

If I want daily rainfall, do I need to code the cumulative rain at midnight each day and then record any increase in the cumulative rainfall before I restart the procedure the next midnight.

Just trying to figure out how to create some useful output for this device using RTL_433/MQTT/.....

**Comment by zuckschwerdt** [comment]
> Is it possible to see battery status and/or battery_mv? Any idea what's in the data field? The rain_mm field appears to be cumulative (tested it manually) but cumulative in the last hour/day/until the battery is changed/????.

WH40 has just the rain value. There might be a battery flag, you need to uncomment this https://github.com/merbanan/rtl_433/blob/master/src/devices/ambientweather_wh31e.c#L299-L300 and test. Let us know.
That "data" is likely just garbage.

> If I want daily rainfall, do I need to code the cumulative rain at midnight each day and then record any increase in the cumulative rainfall before I restart the procedure the next midnight.

However you like. I'd maybe get/reset the count at 6 or 8 o'clock to capture the full night of rainfall.
