### ISSUE TITLE
WN34L / WN34S

### ISSUE THREAD

**Issue by mfraser** [merbanan/rtl_433#2138]
Does the Ecowitt WN34 (S/L) use the same protocol as the WH31 transmitters?

**Comment by Mindavi** [comment]
If you have the device, you could try and maybe confirm if it works.

**Comment by alexfunk** [comment]
I can confirm that WN34L works fine with rtl_433 version 21.12-160-geee869e7 branch master at 202210252023 on arch Linux. With this call `rtl_433 -f 868.4M` I get temp reading all 87sec. Thanks to all.

**Comment by Mindavi** [comment]
Thanks for the confirmation! Closed by https://github.com/merbanan/rtl_433/pull/2122
