### ISSUE TITLE
Ewelink Smoke Detector

### ISSUE THREAD

**Issue by dshanske** [merbanan/rtl_433#2139]
https://ewelinkstore.com/product/smartwise-smoke-pro-rf-sensor/?v=fa868488740a

Has anyone ever tried to integrate this item into this project? It seems to be sold under multiple brands. Couldn't find anything, but thought I'd ask.

**Comment by zuckschwerdt** [comment]
Smoke Detectors are rather dumb, mostly using an EV1527-style (fixed 24 bit code). Mention of Sonoff-Gateway confirms this.
Should be simpel to receive, see
- https://triq.org/rtl_433/ANALYZE.html
- https://github.com/merbanan/rtl_433/blob/master/conf/EV1527-PIR-Sgooway.conf

**Comment by gdt** [comment]
answered question
