### ISSUE TITLE
Protocol Weather Station Bresser 6in1 - Confirmed to work with "Soil temperature and moisture meter" 7009972

### ISSUE THREAD

**Issue by matthias-bs** [merbanan/rtl_433#2146]
The existing code [src/devices/bresser_6in1.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/bresser_6in1.c) also works with the Bresser [Soil temperature and moisture meter](https://www.bresser.de/en/Weather-Time/Accessories-bresser-2/Sensors/BRESSER-soil-temperature-and-moisture-meter.html), product number 7009972.
Example ID: 0x83750871
Sensor Type: 4
(Addition to https://github.com/merbanan/rtl_433/issues/1214)

**Comment by zuckschwerdt** [comment]
Thanks! I'll add that note.

**Comment by matthias-bs** [comment]
Thank you very much!
