### ISSUE TITLE
How to decode data from RF awings?

### ISSUE THREAD

**Issue by folid-vw** [merbanan/rtl_433#2164]
I am having trouble getting the codes for some RF awnings. The remote control is very similar to the Dooya DC1602 but appears under a different brand. I can't see what kind of modulation it's using as it doesn't seem to be OOK. 

Here is an example of the analyzer's output:
```
user@debian:/tmp$ rtl_433 -A g001_433.92M_250k.cu8 
rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/user/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 145 out of 175 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 ]
Test mode active. Reading samples from file: g001_433.92M_250k.cu8
Detected OOK package    @0.088780s
Analyzing pulses...
Total count:    9,  width: 794.26 ms            (198564 S)
Pulse width distribution:
 [ 0] count:    1,  width: 137920 us [137920;137920]    (34480 S)
 [ 1] count:    8,  width: 6720 us [6720;6728]  (1680 S)
Gap width distribution:
 [ 0] count:    8,  width: 75316 us [75200;75928]       (18829 S)
Pulse period distribution:
 [ 0] count:    1,  width: 213848 us [213848;213848]    (53462 S)
 [ 1] count:    7,  width: 81952 us [81924;82016]       (20488 S)
Pulse timing distribution:
 [ 0] count:    1,  width: 137920 us [137920;137920]    (34480 S)
 [ 1] count:    8,  width: 6720 us [6720;6728]  (1680 S)
 [ 2] count:    8,  width: 75316 us [75200;75928]       (18829 S)
 [ 3] count:    1,  width: 100004 us [100004;100004]    (25001 S)
Level estimates [high, low]:   1249,      7
RSSI: -11.2 dB SNR: 22.5 dB Noise: -33.7 dB
Frequency offsets [F1, F2]:    -833,      0     (-3.2 kHz, +0.0 kHz)
Guessing modulation: Pulse Width Modulation with fixed gap
view at https://triq.org/pdv/#AAB1041AC01A40263486A482929292929292929355
Attempting demodulation... short_width: 6720, long_width: 137920, reset_limit: 75932, sync_width: 0
Use a flex decoder with -X 'n=name,m=OOK_PWM,s=6720,l=137920,r=75932,g=0,t=52480,y=0'
pulse_demod_pwm(): Analyzer Device
bitbuffer:: Number of rows: 1 
[00] { 9} 7f 80     : 01111111 1
```

Attached are the captured files from 3 different channels [g00X_433.92M_250k.zip](https://github.com/merbanan/rtl_433/files/9466071/g00X_433.92M_250k.zip)

Could any one guide me on what type of modulation is being used?

Thanks in advance

**Comment by zuckschwerdt** [comment]
It's FSK. But there a strong harmonics that disturb the signal. (Which is likely the senders fault; we see this in the cheapest senders.)
Perhaps offset the band with `-f 433.89M` and also make sure the sender isn't too close to the receiver or remove/replace the antenna.

![awings](https://user-images.githubusercontent.com/12833/187895622-41f2e5c1-e148-46f1-9810-e1955c1d1d5a.png)

**Comment by folid-vw** [comment]
Thank you for your advice. I have removed the antenna and now the signal seems to be better and I can see FSK form wave.
![image](https://user-images.githubusercontent.com/80062338/188007329-9caff41f-7892-4d92-bf2e-e650bd2a3ce8.png)

The analyzer continues detecting the same OOK modulation instead of FSK. I suppose I have to enter the correct parameters to decode the signal. [g00X_433.89M_250k.zip](https://github.com/merbanan/rtl_433/files/9473261/g00X_433.89M_250k.zip)


Thanks for your support.

**Comment by zuckschwerdt** [comment]
The signal still is full of harmonics and skewed, nothing we can do about that -- but the `minmax` demod can handle that mostly. Try
` rtl_433 -Y minmax -X 'n=name,m=FSK_PCM,s=24,l=24,r=300' g001_433.89M_250k.cu8`

Not sure how reliable that is, but there is at least a `2dd4` (twice) in there. That's a well known sync word. So we know coding, polarity, and alignment are right.
Here is [a BitBench with that data synced](https://triq.net/bitbench#c=%7B262%7Daaaaaaaaaaaaaa8b750b750484b04d0e95b8adb333298f94ea1cbc88c39fd96500&c=%7B262%7D5555555555555516ea16ea090960c62c5b0cfa945eea931ea11254bd6f04aa4e10&c=%7B261%7D5555555555555516ea16ea090960f7b0fd557552a29bcd69387fd057339b88b890&c=%7B260%7D5555555555555516ea16ea090960e99b3227adb79b142a04c2b37d14fb2aab4c9&c=%7B259%7D5555555555555516ea16ea090960a65c911b4711b2afa69657e58e215c590a818&c=%7B261%7Daaaaaaaaaaaaaa8b750b750484b05c31a8cc1648512923037d13f32c567c2e58c0&c=%7B260%7D5555555555555516ea16ea090960bd6b90326b427b266f7f109115e636bc2eee1&c=%7B260%7D5555555555555516ea16ea0909608a070c2fe1efe9206b69dcc82fb356420b960&f=8h8h%20&a=Sync&m=2dd4%202dd4&cw=4).

**Comment by gdt** [comment]
@folid-vw any progress?   It doesn't seem like there's enough info figured out in the issue to leave it open, so far.

**Comment by folid-vw** [comment]
You can close the issue. I couldn't improve the signal quality. I'll try to get the data with a logic analyzer that samples the SPI interface. Thank you so much!
