### ISSUE TITLE
malloc: nano zone abandoned due to inability to preallocate reserved vm space on macOS 12.5.1

### ISSUE THREAD

**Issue by deviantintegral** [merbanan/rtl_433#2165]
When running `rtl_433` from homebrew or compiled myself I get:

`rtl_433(43305,0x10f2f5600) malloc: nano zone abandoned due to inability to preallocate reserved vm space.`

Checking out a commit from a few months ago shows the same error. I think this may be due to a macOS update, and not an explicit change in rtl_433.

I'm not sure if this is the right way to solve this, but https://stackoverflow.com/questions/64126942/malloc-nano-zone-abandoned-due-to-inability-to-preallocate-reserved-vm-space has some comments on this.

**Comment by zuckschwerdt** [comment]
The answer to the linked SO question explains it well. We don't have any control over libmalloc and I don't think we can or should change anything.
