### ISSUE TITLE
rename conversion mode "customary units" to be more specific

### ISSUE THREAD

**Issue by knarrff** [merbanan/rtl_433#2167]
Hi,

although I am aware that in the US, the term "customary units" is set to mean "the system of units used in the US", the term "customary units" is misleading in other parts of the world, because the term itself means "the units customary used", which in most countries is not the US system. What are your thoughts about clarifying that by changing the name (option name)? Alternatives that would be less confusion could be

- USAcustomary
- USA-customary
- FPS (I like this most, as it is both short and not misleading)

Note that 'standard' (another common synonym in the US) would also be a bad alternative, as it is not the standard in most countries around the globe.

(The old string could/should still be usable for backwards compatibility.)

**Comment by merbanan** [comment]
I think we had a long long discussion regarding this when we originally named it. Look into that and see if your comments have anything to add to that. I am against to break command line api. Adding another string might be applicable.

**Comment by AutomGuy** [comment]
@knarrff I can't understand why this is in "Issues" but it's probably more for the "Discussions" section.

**Comment by knarrff** [comment]
You are right. I'm closing this here, look at the discussion and then think about what to do from there. Can you please point me to the mentioned discussions, did they happen in the 'discussions'-section (I can't find them there).

**Comment by zuckschwerdt** [comment]
IIRC "imperial" was the contender, but that's british. A bit harsh, but I take it people in the US known what "customary" means and for everybody else it's "si" (not just metric but really Système International)

**Comment by zuckschwerdt** [comment]
https://github.com/merbanan/rtl_433/pull/263

**Comment by knarrff** [comment]
Thanks. It is so nice to get helpful responses in essentially no time. (not meant sarcastically, but literally)

**Comment by gdt** [comment]
"Imperial" and "US Customary Units" are not the same thing.   While many units are the same the gallon is different.

I agree that when the choices are "si" and "customary" it's pretty obvious.    It might help for the help text to say that si is metric and customary is US Customary.

**Comment by knarrff** [comment]
"si is metric": this is correct, but not as in "same as", just as in "is a type of", as "metric is not si". For example, the cgs-System is metric, but different from the SI system.

**Comment by gdt** [comment]
Fair enough; as a fellow pedant I should have been more careful!
