### ISSUE TITLE
Is it possible to "listen" in both 433 and 868 frequencies at the same time ?

### ISSUE THREAD

**Issue by PAOK1926** [merbanan/rtl_433#2201]
i have rtl_433 working fine with a cheap dongle at 433 Mhz.
i recently purchased a weather station which broadcasts at 868 Mhz.
is it possible to monitor both, with the same dongle ?
i have "frequency   433.92M"     in my rtl_433.conf

**Comment by zuckschwerdt** [comment]
You can alternate (hop) between frequencies. Use `-H` on the command line or multiple `frequency` entries in the conf.

**Comment by PAOK1926** [comment]
i should write this in my conf file ?

frequency   868M
frequency   433.92M

**Comment by PAOK1926** [comment]
i added these lines to my rtl_433.conf
`frequency   868M
frequency   433.92M
hop_interval  11`

and it seems to work fine. Thank you all !
