### ISSUE TITLE
Bresser 5in1 MQTT problem

### ISSUE THREAD

**Issue by Lobuzeczek** [merbanan/rtl_433#2213]
I have 5 in 1 bresser stations. The problem is sending MQTT data. When temperature and humidity are sent out, rain is 0. When rain is sent after 12 seconds, temperature and humidity are 0.

![7c36728b26d55571667892aa59d6cce187be8177](https://user-images.githubusercontent.com/65848704/197418468-3594fe74-4ff3-4066-ba83-b36c76a0d947.png)

MQTT DATA AFTER 12 SECONDS
![d37f77ebcf40edfbb7d042d6c6d8e06825a52ca0](https://user-images.githubusercontent.com/65848704/197418525-1a2caab9-6fa8-40c6-bb6a-27d1d2b5f3e4.png)
AFTER 24 SECONDS
![260a9caf73badecd30f2884191ac7b5d19919ab8](https://user-images.githubusercontent.com/65848704/197418540-b54c94f0-80de-421c-8384-13acdea9833b.png)

**Comment by zuckschwerdt** [comment]
Yes the Bresser-6in1 sends:
- 24 seconds interval for temperature, hum, uv and rain (alternating messages)
- 12 seconds interval for wind data (every message)

But we never add "0" values. The MQTT topics either get a fresh value or are unset (unless you use `retain`).
I guess this is a processing error in your display software? What software is that?

**Comment by Lobuzeczek** [comment]
> Yes the Bresser-6in1 sends:
> 
> * 24 seconds interval for temperature, hum, uv and rain (alternating messages)
> * 12 seconds interval for wind data (every message)
> 
> But we never add "0" values. The MQTT topics either get a fresh value or are unset (unless you use `retain`). I guess this is a processing error in your display software? What software is that?

My software is Home Assistant

**Comment by gdt** [comment]
Please feel free to open a fresh issue with reproduction information with current git master.    Please include -F json direct from rtl_433.
