### ISSUE TITLE
Flex decoder where short, long, sync reset and tolerance values are not always the same

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [merbanan/rtl_433#2225]
I'm trying to make a flex decoder for my wireless remote, but most values change and aren't always the same. The only value that remains the same is match, but I can't make a decoder only with match parameter. Sometimes it's like this: `-X 'n=name,m=OOK_PWM,s=384,l=1184,r=1236,g=0,t=320,y=0,match={25}0xa345fe80'`, and sometimes like this: `-X 'n=name,m=OOK_PWM,s=380,l=1168,r=1252,g=0,t=315,y=0,match={25}0xa345fe80'`. Is there a way I can get around this and only check the match value?

**Comment by zuckschwerdt** [comment]
Those two are practically the same, but the reset could be too narrow. Use
`'n=my-remote,m=OOK_PWM,s=400,l=1200,r=1800,match=a345fe'`

**Comment by Andrei-Iosifescu123** [comment]
Thank you, this saved my time.

mie., 2 nov. 2022, 09:11 Christian W. Zuckschwerdt ***@***.***>
a scris:
