### ISSUE TITLE
Decoder "Abarth 124 Spider TPMS" gave invalid return value -6: notify maintainer

### ISSUE THREAD

**Issue by sm3ulc** [merbanan/rtl_433#2234]
Decoder "Abarth 124 Spider TPMS" gave invalid return value -6: notify maintainer

$rtl_433 -V
rtl_433 version 20.02-86-gd362397 branch master at 202007062107 inputs file rtl_tcp RTL-SDR

**Comment by zuckschwerdt** [comment]
Thanks. That version is old ;) Already fixed in 1bce1c9.
