### ISSUE TITLE
22.11 not statically compiled on Windows

### ISSUE THREAD

**Issue by neversphere** [merbanan/rtl_433#2251]
Out of the box it doesn't run due to a complaint about libwinpthread-1.dll being missing. On the same box version 21.12 runs fine.

**Comment by zuckschwerdt** [comment]
Thanks for the report! We don't actually use pthreads on win32, so something else must have broken.

**Comment by cizzop** [comment]
Same issue here. After putting libwinpthread-1.dll directly in the folder I then get "The application was unable to start correctly (0xc000007b)"

**Comment by zuckschwerdt** [comment]
Ah ok, we only use native threads with MSC (Visual Studio), but pthreads on WIN32 otherwise (GCC).
I changed that to always native threads in dc95819 now. Still need to do a new build though.

**Comment by zuckschwerdt** [comment]
If you want to test this right away here are the new binaries:
[rtl_433-win-x32.zip](https://github.com/merbanan/rtl_433/files/10198678/rtl_433-win-x32.zip)
[rtl_433-win-x64.zip](https://github.com/merbanan/rtl_433/files/10198679/rtl_433-win-x64.zip)

**Comment by gdt** [comment]
This seems likely fixed, and we're 9 months after binaries were provided for testing, with no reply.

**Comment by neversphere** [comment]
Sorry I didn't update. This fixed it. Thanks!

**Comment by gdt** [comment]
Thanks for confirming.
