### ISSUE TITLE
Toyota PMV-C11A

### ISSUE THREAD

**Issue by gamer765** [merbanan/rtl_433#2262]
It seems that sometime during the past 2 years, Toyota has rolled out a new TPMS sensor that supercedes the Pacific PMV-107J. The new part number is PMV-C11A and from a quick Google search it seems that these new sensors do not behave with third party tools. Has anyone purchased one of these new sensors and can verify if it still works as a PMV-107J?

**Comment by gdt** [comment]
Please feel free to open a discussion or ask on the list.    Apparently nobody who reads the issues knows...
