### ISSUE TITLE
Protocol Weather Station Bresser 6in1 - Confirmed to work with "Outdoor temperature/humidity sensor" 7009999

### ISSUE THREAD

**Issue by matthias-bs** [merbanan/rtl_433#2269]
The existing code [src/devices/bresser_6in1.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/bresser_6in1.c) also works with the Bresser [Thermo-/Hygro-Sensor 7 Channel 868 MHz](https://www.bresser.de/en/Weather-Time/Accessories-bresser-2/Sensors/BRESSER-Thermo-Hygro-Sensor-7-Channel-868-MHz.html), product number 7009999.

**Comment by zuckschwerdt** [comment]
Thanks! I'll add a note.

**Comment by matthias-bs** [comment]
The field s_type is "2".

**Comment by zuckschwerdt** [comment]
Thanks for the update. Yes, we suppose that's the default for "indoor"-type units.

**Comment by matthias-bs** [comment]
It is actually an outdoor unit with 150m nominal range.
