### ISSUE TITLE
Disable / deprioritise devices without CRC support

### ISSUE THREAD

**Issue by dwmw2** [merbanan/rtl_433#227]
Watching my oil monitors, I occasionally get spurious reports for invalid devices:

```
2015-12-10 14:51:16 Oil Watchman c7724c 60 19 0 0
2015-12-10 15:23:17 Oil Watchman 4ecc8c 80 20 0 58

Sensor        = Temperature event
Device        = 0
Battery?      = 00
Temp          = 0.000000
Model         = Generic temperature sensor 1
Received Data = 00 00 00
2015-12-10 15:26:20 Oil Watchman c7724c 80 20 0 0
2015-12-10 15:58:16 Oil Watchman 4ecc8c 80 20 0 58
2015-12-10 16:02:03 Oil Watchman c7724c 80 19 0 0
2015-12-10 16:33:15 Oil Watchman 4ecc8c 80 20 0 59
2015-12-10 16:37:46 Oil Watchman c7724c 80 19 0 0
Danfoss CFR Thermostat:
bitbuffer:: Number of rows: 1 
[00] {258} f8 3f f0 03 ff 07 c1 f0 7c 1f 00 3f f0 03 e0 f8 3e 0f 83 e0 f8 3f f0 7c 00 f8 3f f0 7c 1f 07 c1 c0 

2015-12-10 17:13:29 Oil Watchman c7724c 80 19 0 0

Sensor        = Temperature event
Device        = 0
Battery?      = 00
Temp          = 0.000000
Model         = Generic temperature sensor 1
Received Data = 00 00 00
2015-12-10 17:49:12 Oil Watchman c7724c 80 18 0 0
```

Unfortunately I didn't capture the input waveform so can't reproduce. But that definitely should have been one of the transmissions from unit 4ecc8c. It got eaten by the Danfoss driver which just dumps the bitbuffer without doing any checks. When the Danfoss callback returned '1' did that mean the pulses weren't even offered to the oil_watchman callback to be interpreted?

Should I have put oil_watchman earlier in the device list, as has a decent CRC and is _very_ unlikely to claim events that aren't really its own? And can we have a mode which disables _all_ device support that doesn't have reasonable confidence? Perhaps an estimate _in_ the `r_device` structure of the probability of false positives would be a good idea? And would also help to focus the submitters' minds on such things :)

**Comment by merbanan** [comment]
Hi, run with -t for a while. It will save all detected signals. That way we can debug later.

**Comment by dwmw2** [comment]
It doesn't seem to be. Running with `-t -a` saves signals. Is there a mode which will actually run the real device decoder as well as saving signals to separate files?

**Comment by dwmw2** [comment]
Running with this for now; we'll see what it catches:
```
--- a/src/rtl_433.c
+++ b/src/rtl_433.c
@@ -619,7 +619,7 @@ static void rtlsdr_callback(unsigned char *iq_buf, uint32_t len, void *ctx) {
 
        if (demod->analyze || (demod->out_file == stdout)) {    // We don't want to decode devices when outputting to stdout
                pwm_analyze(demod, demod->am_buf, len / 2);
-       } else {
+       } /* else */ {
                // Loop through all demodulators for all samples (CPU intensive!)
                for (i = 0; i < demod->r_dev_num; i++) {
                        switch (demod->r_devs[i]->modulation) {
```

**Comment by dwmw2** [comment]
Hm, this one doesn't get decoded at all. If I let rtl_433 do the FM decoding and feed it to my own original hack decoder, it does work.

**Comment by dwmw2** [comment]
Oh, that one does work with `-l 4716`.

**Comment by dwmw2** [comment]
Perhaps for FM decoding, a lower default detection level should apply than for AM? Isn't that half the point in using FM? If you look at the FM decode in this case, it's not as if it's at all ambiguous...
![gfile022-fm](https://cloud.githubusercontent.com/assets/911239/11731251/e1fc339e-9f91-11e5-8ea7-cc6f1552d209.png)

**Comment by merbanan** [comment]
If you find a better limit set that as default.

**Comment by merbanan** [comment]
And ideally there should be some kind of prioritization for packet decoding so signals with crc are tried before those without.

**Comment by merbanan** [comment]
Some signal formats are very simple. Those are hard to not get conflicts with.

**Comment by merbanan** [comment]
There has been significant rework of the code so bogus signals should be less common. It is also possible to disable decoders if the application only need to look for one device. And hopefully the signal recorder will get smarter so it is possible to run the regular decode process but still record signals for later analysis. Closing issue.
