### ISSUE TITLE
Expose timezone information to MQTT

### ISSUE THREAD

**Issue by 3v1n0** [merbanan/rtl_433#2293]
When using a Bresser 5-in1 station, I'm getting this error in HA when parsing the `time` value passed via MQTT:

```
ValueError: Invalid datetime: sensor.bresser_5_in_1_utc provides state '2022-12-31 05:33:33', which is missing timezone information
```

**Comment by zuckschwerdt** [comment]
Use e.g. `-M time:iso:usec:utc:tz` (`usec` is optional and `utc` depends on your setup)
