### ISSUE TITLE
usb_open error -3

### ISSUE THREAD

**Issue by Cvar1984** [merbanan/rtl_433#2297]
i got this error on windows system, dunno how to fix this on windows system
```
Found 1 device(s):
  0:  Failed to query data

Using device 0: Generic RTL2832U OEM
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
```

**Comment by zuckschwerdt** [comment]
Did you use Zadig to uninstall RTL-SDR DVB drivers?

**Comment by Cvar1984** [comment]
> Did you use Zadig to uninstall RTL-SDR DVB drivers?

no, should i uninstall the drivers?

**Comment by zuckschwerdt** [comment]
Standard RTL-SDR setup procedure on Windows systems. No SDR application can work if "original" television drivers claim the device.

"Zadig" and "RTL-SDR setup Windows" should give some search results if you need further instructions. Have fun!
