### ISSUE TITLE
Bresser 3ch checksum

### ISSUE THREAD

**Issue by Crsarmv7l** [merbanan/rtl_433#2307]
Hi I am seeking info on how the Bresser 3ch checksum is computed.

Using the test file here:
https://github.com/merbanan/rtl_433_tests/blob/master/tests/bresser_3ch/gfile001.cu8

and running that through rtl_433 with -vv I get the bitstring:
00010111 0010 0110 00001100 01000000 10001001

The rtl_433 results show the following:
ID: 23
Channel:2
Temp: 64.80
Humid: 64%

Breaking it down:
00010111 in decimal is 23, the ID
0010 in decimal is 2, the channel (last two bits)
011000001100 in decimal is 1548, when converted using the formula in src 1548/10 = 154.8- 90 = 64.8 the temp
01000000 in decimal is 64, the humidity

That leaves 10001001 as the checksum. Per the notes in Bresser 3ch, this should be the sum of the previous bytes, but that is not at all what I am getting.
![Screenshot 2023-01-10 4 46 48 PM](https://user-images.githubusercontent.com/85343771/211672562-365073d9-6c02-45f3-8ad1-cce648c70953.png)

I would appreciate any insight into how the checksum is calculated. Thank you

**Comment by merbanan** [comment]
b = bitbuffer->bb[r];
    b[0] = ~b[0];
    b[1] = ~b[1];
    b[2] = ~b[2];
    b[3] = ~b[3];
    b[4] = ~b[4];

    if (((b[0] + b[1] + b[2] + b[3] - b[4]) & 0xFF) != 0) {
        decoder_log(decoder, 1, __func__, "checksum error");
        return DECODE_FAIL_MIC;
    }

**Comment by merbanan** [comment]
That is the code for the checksum. Invert and then sum.
