### ISSUE TITLE
capturing and replaying Fan control

### ISSUE THREAD

**Issue by aram535** [merbanan/rtl_433#2311]
I'm trying to capture a Fan/Light control - controller is a no name brand.  

The FCC ID: Grantee Code: kuj Product Code: ce9103  

According to the FCC ID it should be @ 304.0 Mhz 

How do I capture this so I can replay it? 

-A did not capture anything.

**Comment by zuckschwerdt** [comment]
https://triq.org/rtl_433/ANALYZE.html
