### ISSUE TITLE
Automatic dongle reset

### ISSUE THREAD

**Issue by testuser7** [merbanan/rtl_433#2330]
Is there any chance to implement reset function (usbreset) in rtl_433 in case of `Async read stalled, exiting!`?
I have RTL2838 based dongle and it hangs very often. Usbreset application is able to properly reset dongle.

**Comment by zuckschwerdt** [comment]
Not likely. There are different failure modes and USB reset is not a good tool in most of them. Just run your usbreset after each rtl_433 exit with a e.g. shell script.

**Comment by zuckschwerdt** [comment]
rtl_433_with_reset.sh
```
#!/bin/sh
if rtl_433 "$@" ; then
  :
else
  echo Resetting USB
  usbreset
fi
```
