### ISSUE TITLE
Cotech 36-7959 / Ragova FT-0310 - Rain Not valid

### ISSUE THREAD

**Issue by manuel-held** [merbanan/rtl_433#2332]
Hello, 

my Ragova FT-0310 Base Station ist showing no Rain 
![IMG_20230120_212557](https://user-images.githubusercontent.com/373735/213799647-4cee4d8a-e3a3-41d4-8745-5e6ea420c888.jpg)

But rtl_433 does:

![Screenshot_2023-01-20-20-25-47-736_com android chrome](https://user-images.githubusercontent.com/373735/213799965-4a8a91b2-e83d-4758-86cd-cb578ec0922e.jpg)

I use the Version 22.11-40-g676a4042 branch master at 202301182158

Any hints?

**Comment by zuckschwerdt** [comment]
Common pitfall actually ;) The values from rtl_433 are "current total" -- you need to aggregate yourself (in some dashboard software maybe), e.g. hourly, daily, … i.e. save the "midnight" value, subtract from the next "midnight" value and you got "daily".

**Comment by manuel-held** [comment]
Ahh damn. Thank you :)
