### ISSUE TITLE
No luck with 3 sensors of protocol 52  # Bresser Thermo-/Hygro-Sensor 3CH

### ISSUE THREAD

**Issue by riegelbrau** [merbanan/rtl_433#2333]
Hello,
I bought a kit named BRESSER Temp Hygro Quadro, that contains 3 sensors named exactly like the protocol 52  "Bresser Thermo-/Hygro-Sensor 3CH" on the BRESSER website.  With protocol 52 activated there are no results, while the receiver displays the thermo and hygro information. I tested all 3 sensors with all channels and with my two SDR sticks I have. See some saved results using -A -S unknown attached.

Any help is appreciated.

Regards
Christoph
[g001_433.92M_250k.zip](https://github.com/merbanan/rtl_433/files/10470779/g001_433.92M_250k.zip)

**Comment by zuckschwerdt** [comment]
Only `g003_433.92M_250k.cu8` contains a complete signal. Drop on https://triq.org/pdv/
It's 10 repeats of a PPM code -- that's a Nexus, FreeTec NC-7345, NX-3980, Solight TE82S, TFA 30.3209 temperature/humidity sensor.
If that's not the one you wanted to capture: https://triq.org/rtl_433/ANALYZE.html
