### ISSUE TITLE
Error "Unknown keyword "pulse_detect""

### ISSUE THREAD

**Issue by rowanbradley** [merbanan/rtl_433#2338]
When I try to run the 2019-08-19 version in WIndows 10 with options -R 43 -F json I get the error message Unknown keyword "pulse_detect". Version 21.12 seems to run without error, although I have as yet failed to get it to read any data from my RF device (an Apollo oil level monitor).
What does Unknown keyword "pulse_detect" mean? Where has it found this keyword?

Thank you - Rowan

**Comment by zuckschwerdt** [comment]
The `pulse_detect` setting is a more modern switch to set demod parameters. It's not available in older versions.

You likely installed a newer version with those conf files, and then an older binary.
Check your .conf files and remove that option. See here:
https://github.com/merbanan/rtl_433/blob/e37fc5dd3854ca7e95099a9cf6410357701c3089/conf/rtl_433.example.conf#L83-L109
