### ISSUE TITLE
Running on Raspberry PI Zero W

### ISSUE THREAD

**Issue by algorni** [merbanan/rtl_433#2342]
Is such a device powerful enough to get this stuff running?

**Comment by merbanan** [comment]
Yes, at least the OOK demodulation.

**Comment by zuckschwerdt** [comment]
S.a. #1551 
Use `-Y autolevel -Y squelch` to skip frames below estimated noise level to reduce cpu load.

**Comment by algorni** [comment]
Super!!! with -Y auto magically make it running!
