### ISSUE TITLE
rtl_433 with MQTT on pi:  working,  then error

### ISSUE THREAD

**Issue by TGSnedecor** [merbanan/rtl_433#2365]
UPDATE:  problem found and fixed.
the problem was that I had started to be able to run from a rtl_433.conf file.  So, there existed an "in-progress" rtl_433.conf file with a mqtt statement in it.  When I started rtl_433 from the command line (which also had F MQTT:... in it), both were read and the instance was trying to log in to MQTT broker twice.  This is not allowed per MQTT rules, and the connection was dropped.  

I thought one or the other (command line or .conf entry) over-rode the other, but evidently not.

Mosquitto broker in HomeAssistant rejects connection from rtl_433 on pi.  Worked fine for several days, then ssh to pi was terminated due to windows restart.  Now when I try to run, using same command as before, mosquitto broker on home assistant (on separate VM) I get:  
2023-02-04 07:40:38: New client connected from 192.168.1.30:52862 as rtl_433-a90dffff (p2, c0, k60, u'mqttuser').
2023-02-04 07:40:38: New connection from 192.168.1.30:52864 on port 1883.
2023-02-04 07:40:38: Client rtl_433-a90dffff already connected, closing old connection.
It seems like my rtl_433 instance is trying to connect twice.  The windows restart did not stop Homeassistant VM, mosquito broker add-in, only the connection to my pi, running rtl_433

I have tried rebooting pi, stopping and restarting mosquitto broker, stopping and restarting HA, both HA and VM it's running on, changing pi IP, and restoring to yesterday's HomeAssistant backup.  Can someone direct me to some expertise?  

Are there instructions for totally removing rtl_433 from my pi and re-installing?

Thanks for your help!

**Comment by zuckschwerdt** [comment]
A `Client rtl_433-a90dffff already connected, closing old connection.` is just a warning. The old rtl_433 connection was not closed and did not timeout.
But if you are indeed running rtl_433 twice then that obviously won't work (you can share the RTL-SDR input).

If the old rtl_433 was already "dead" it should just work. If not you can forcibly remove that with `killall rtl_433`. A restart will only fix those problems if you don't autostart some rtl_433. `ps aux|grep rtl_433` to check.

This is a linux administration topic and not related to rtl_433.
