### ISSUE TITLE
Sainlogic Weather Station FT0300. No topics mqtt Light Intensity and UV Index

### ISSUE THREAD

**Issue by AVmillev** [merbanan/rtl_433#2370]
Lib Cotech 36-7959 Weatherstation, 433Mhz.
Device Sainlogic Weather Station FT0300
Not sending mqtt topics Light intensity and UV index
![image](https://user-images.githubusercontent.com/16835301/217217158-f55b7a05-a9b5-492b-8c55-68ef06ab2ed6.png)
![image](https://user-images.githubusercontent.com/16835301/217217488-c63a3c49-0795-4da5-bf7c-25123f44a468.png)

**Comment by zuckschwerdt** [comment]
Not the same packets, look at the timestamp. Grab a packet which shows this behaviour.
https://triq.org/rtl_433/ANALYZE.html#grab-a-sample
