### ISSUE TITLE
 Custom decoder not always detecting OOK_PWM signal ( possible interference? )

### ISSUE THREAD

**Issue by Daniel-dk** [merbanan/rtl_433#2380]
hihi, 
I've done a custom decoder for an outdoor motion sensor, but they are not always detected.
The SDR is mounted outside on the roof with a 5 dBi Omni antenna, connected to a [HABamp (SAW filter + 19 dB gain LNA )](https://store.uputronics.com/index.php?route=product/product&product_id=53) and then into the SDR.

I've captured a few signals with rtl_433 -s 250000 -f 433.92M -w <filename>.cu8 -T 10
The OOK_PWM signal in the screenshot is what I'm trying to decode. ( screnshot from triq.org/pdv/ File is 250k_433.92_3.cu8 )
will the ( what looks like a constant tone ) affect the decoders ?
![image](https://user-images.githubusercontent.com/582384/218839548-580708cd-504d-4f9b-89cb-f425db400dd9.png)

- AGC is left active, should I disable it or set it to a fixed value with the HABamp 
- Should I lower the  number of repeats to be more resiliant to some of them getting corrupted ?
- - The packet structure is <tune up> < 32x 0 bits > < 8 x 24 bit packet repeated >
- I can Climb up to the device and remove the HABamp later..

The decoder for this partiular signal is ( from recordings analysed on [URH ](https://github.com/jopohl/urh)and on TRIQ with Pulseview )
decoder {
        n=Outdoor_Motion,
        m=OOK_PWM,
        s=950,
        l=2200,
        g=3400,
        r=17000,
        bits=24,
        repeats>=7,
        get=@8:{16}:id,
        get=@0:{3}:value:,
        get=@0:{3}:type:[1:Signal_A 5:Signal_B 6:Signal_C],
        unique
}

[250k_433.92.zip](https://github.com/merbanan/rtl_433/files/10736206/250k_433.92.zip)

**Comment by zuckschwerdt** [comment]
The signal is visible but looks really instable and "dirty". The motion sensor is likely not using a frequency stable sender but just "clocking a pin". I have one of those too, it won't work reliable.
Since PIRs are affordable (this one looks cheap) I would just try to find a good one.

I would likely also remove the amp. Even the RTL-SDR (R820T2) has good sensitivity (given low noise background).
