### ISSUE TITLE
Just purchased a KERUI motion detector, decoded as SMOKE-GS558

### ISSUE THREAD

**Issue by A-Swafford** [merbanan/rtl_433#2385]
As title reads. I purchased a KERUI PIR motion sensor from amazon and it's being decoded as a smoke sensor. Here's the sensor that showed up in MQTT Explorer:

Smoke-GS558
13028
time = 2023-02-17 20:29:18
id = 13028
unit = 18
learn = 0
code = 965c92  

Am a noob at this, but happy to help get these cheap-ie sensors working again!

**Comment by zuckschwerdt** [comment]
Those x1527 type encoders all just send a fixed 24 bit number (plus 1 bit trailing sync).
Timings will differ though. https://triq.org/rtl_433/ANALYZE.html to get the timings, then use a flex decoder conf. https://github.com/merbanan/rtl_433/tree/master/conf

Closing as this is not something to change or fix in rtl_433, feel free to discuss further though.
