### ISSUE TITLE
Bresser 5in1 wrong 'rain' value

### ISSUE THREAD

**Issue by PopcornAWH** [merbanan/rtl_433#2398]
Hi, 
Been using rtl_433 for some years to capture and decode my Bresser 5in)1.

On a newly installed Pi4B (raspiOS bullseye) the installed rtl_433 version is:
rtl_433 version nightly-2-g371ccfd5 branch master at 202302201511 inputs file rtl_tcp RTL-SDR

This version shows the rain value wrong... 
time      : 2023-02-25 15:29:10
model     : Bresser/mczakk Weather Center 5-in-1   count     : 1             num_rows  : 1             rows      :
len       : 285          data      : 80555555555516ea720ebfebffed77cc7fd43bf47f8df1401400128833802bc40b800000
codes     : {285}80555555555516ea720ebfebffed77cc7fd43bf47f8df1401400128833802bc40b800000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-02-25 15:29:10
model     : Bresser-5in1 id        : 226
Battery   : 1            Temperature: 6.7 C        Humidity  : 57            Wind Gust : 4.0 m/s       Wind Speed: 2.5 m/s       Direction : 0.0           **_Rain      : 178.8 mm_**
Integrity : CHECKSUM

this one (other Pi4) is correct:
rtl_433 version unknown inputs file rtl_tcp RTL-SDR SoapySDR
"time": "2023-02-25 18:43:34",
    "model": "Bresser-5in1",
    "id": 226,
    "battery_ok": 1,
    "temperature_C": 3.300,
    "humidity": 59,
    "wind_max_m_s": 0.800,
    "wind_avg_m_s": 0.900,
    "wind_dir_deg": 0.000,
    **_"rain_mm": 78.800,_**
    "mic": "CHECKSUM"

Bresser 5in1 has a cycling rain value 0 to 100 (or maybe 99), in any case, it should never be greater than 100.

cu8 and ook files from both the right, and wrong decode:
https://www.dropbox.com/sh/slicjbnjygf2x4e/AADwc_tcWFnWucCsSHI2FYIqa?dl=0

Let me know if you need anything more from me, happy to provide it...

Paul

**Comment by matthias-bs** [comment]
Please see here for expanation:https://github.com/merbanan/rtl_433/pull/2312
-------- Ursprüngliche Nachricht --------Von: PopcornAWH ***@***.***> Datum: 25.02.23  15:43  (GMT+01:00) An: merbanan/rtl_433 ***@***.***> Cc: Subscribed ***@***.***> Betreff: [merbanan/rtl_433] Bresser 5in1 wrong 'rain' value (Issue #2398) 
Hi,
Been using rtl_433 for some years to capture and decode my Bresser 5in)1.
On a newly installed Pi4B (raspiOS bullseye) the installed rtl_433 version is:
rtl_433 version nightly-2-g371ccfd5 branch master at 202302201511 inputs file rtl_tcp RTL-SDR
This version shows the rain value wrong...
time      : 2023-02-25 15:29:10
model     : Bresser/mczakk Weather Center 5-in-1   count     : 1             num_rows  : 1             rows      :
len       : 285          data      : 80555555555516ea720ebfebffed77cc7fd43bf47f8df1401400128833802bc40b800000
codes     : {285}80555555555516ea720ebfebffed77cc7fd43bf47f8df1401400128833802bc40b800000

time      : 2023-02-25 15:29:10
model     : Bresser-5in1 id        : 226
Battery   : 1            Temperature: 6.7 C        Humidity  : 57            Wind Gust : 4.0 m/s       Wind Speed: 2.5 m/s       Direction : 0.0           Rain      : 178.8 mm
Integrity : CHECKSUM
Bresser 5in1 has a cycling rain value 0 to 100 (or maybe 99), in any case, it should never be greater than 100.
cu8 and ook file:
https://www.dropbox.com/sh/slicjbnjygf2x4e/AADwc_tcWFnWucCsSHI2FYIqa?dl=0
Let me know if you need anything more from me, happy to provide it...
Paul

**Comment by zuckschwerdt** [comment]
Thanks @matthias-bs
Closing as this seems to be a misunderstanding only, value goes to `999.9 mm` now, but please let us know if you see anything suspicious or wrong with the values.

**Comment by PopcornAWH** [comment]
I'll adapt my backend, will report if something looks wrong...
