### ISSUE TITLE
SW-ATT-RDW

### ISSUE THREAD

**Issue by royboo78** [merbanan/rtl_433#2406]
Would it be possible to get these sensors to work with rtl_433? I can see info using mqtt explorer but i have no idea how to make them work with home assistant. I am guessing rtl_433 doesn’t have the protocol info. I can supply any screen shots that would be needed if someone can help. These sensors are very nice as they are hidden and only cost like $5 on ebay.

**Comment by klohner** [comment]
I looked at a couple of these. Their internal PCBs are each labeled "HW:5048-01-B01 SWS5048-01-B02" and look similar to the one on the [FCCID site](https://fccid.io/QNP-433RDW). ([external photos](https://fccid.io/QNP-433RDW/External-Photos/External-Photos-1679452), [internal photos](https://fccid.io/QNP-433RDW/Internal-Photos/Internal-Photos-1679457)).

For each event, the signal repeats 8 times with some random internal between each repetition.  I didn't test a low battery event (my batteries are just over 3v), but I was able to capture 4 unique signals per device.  Besides the signals for opening (magnet removed), and closing (magnet near), there are unique signals when initially inserting the battery during an opened state, and one during a closed state.

Here are signals I captured: [SW-ATT-RDW.zip](https://github.com/merbanan/rtl_433/files/10947482/SW-ATT-RDW.zip)

```
{56}0d9e840000d247 [g001 Device 1, closed]
{56}0d9e8402005e44 [g002 Device 1, opened]
{56}0d9e84083a62d8 [g003 Device 1, powered up closed]
{56}0d9e840a3aeedb [g004 Device 1, powered up opened]

{56}10063e0000beee [g005 Device 2, closed]
{56}10063e020032ed [g006 Device 2, opened]
{56}10063e083a0e71 [g007 Device 2, powered up closed]
{56}10063e0a3a8272 [g008 Device 2, powered up opened]
```

rtl_433 can reliably recognize these signals with:

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=1200,invert,preamble=ffea"`

I had to use `-R 0` because there were some instances where the signal was misrecognized as "Interlogix-Security"

```
$ rtl_433 -r g005_433.92M_250k.cu8
time      : @0.154128s
Model     : Interlogix-Security                    Device Type: unknown      ID        : 022011
Battery   : 1            Switch1 State: CLOSED     Switch2 State: CLOSED     Switch3 State: CLOSED     Switch4 State: CLOSED     Switch5 State: CLOSED
Raw Message: 000308

```
Here's a flex spec that picks out some of the suspected data:

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=120000,invert,preamble=ffea,bits=72,get=ID:@0:{24},get=State:@30:{1}:[0:OPEN 1:CLOSED],get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],get=CRC16:@40:{16}"`

With this command, I get results like this:

```
time      : @2.264920s
model     : SW-ATT-RDW   count     : 1             num_rows  : 1             rows      :
len       : 56           data      : 10063e0000beee ID        : 1050174      State     : OPEN          Mode      : NORMAL        CRC16     : 48878
codes     : {56}10063e0000beee

```
Here's a [bitbench](https://triq.net/bitbench#c=%7B56%7D0d9e840000d247%20%5Bg001%20Device%201%2C%20closed%5D&c=%7B56%7D0d9e8402005e44%20%5Bg002%20Device%201%2C%20opened%5D&c=%7B56%7D0d9e84083a62d8%20%5Bg003%20Device%201%2C%20powered%20up%20closed%5D&c=%7B56%7D0d9e840a3aeedb%20%5Bg004%20Device%201%2C%20powered%20up%20opened%5D&c=&c=%7B56%7D10063e0000beee%20%5Bg005%20Device%202%2C%20closed%5D&c=%7B56%7D10063e020032ed%20%5Bg006%20Device%202%2C%20opened%5D&c=%7B56%7D10063e083a0e71%20%5Bg007%20Device%202%2C%20powered%20up%20closed%5D&c=%7B56%7D10063e0a3a8272%20%5Bg008%20Device%202%2C%20powered%20up%20opened%5D&c=&c=%5B%5D&f=ID%3Ahhhhhh%20FLAGS%3A%3F%3Fvv%20%3F%3Fvv%20INITIALIZED%3Abv%20OPEN%3Abv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20CRC%3Ahhhh&cw=4) of the data I collected.

Here's confirmation of the CRC-16:
```
$ reveng -w 16 -s 0d9e840000d247 0d9e8402005e44 0d9e84083a62d8 0d9e840a3aeedb 10063e0000beee 10063e020032ed 10063e083a0e71 10063e0a3a8272
width=16  poly=0x8005  init=0xa74c  refin=false  refout=false  xorout=0x0000  check=0xd072  residue=0x0000  name=(none)
```

@royboo78 - Would you please capture codes from your devices using the `rtl_433` command above?  For each device, please provide the unique code, labeled with each of the 4 states (if possible).  If you're able to capture a "low battery" event, please provide that as well.

**Comment by royboo78** [comment]
I will try my best but i am very new to this. Can you tell me what specific commands you would like?

**Comment by klohner** [comment]
I managed to get a low battery event and added it to the [bitbench](https://triq.net/bitbench#c=%7B56%7D0d9e840000d247%20%5Bg001%20Device%201%2C%20closed%5D&c=%7B56%7D0d9e8402005e44%20%5Bg002%20Device%201%2C%20opened%5D&c=%7B56%7D0d9e84083a62d8%20%5Bg003%20Device%201%2C%20powered%20up%20closed%5D&c=%7B56%7D0d9e840a3aeedb%20%5Bg004%20Device%201%2C%20powered%20up%20opened%5D&c=&c=%7B56%7D10063e0000beee%20%5Bg005%20Device%202%2C%20closed%5D&c=%7B56%7D10063e020032ed%20%5Bg006%20Device%202%2C%20opened%5D&c=%7B56%7D10063e083a0e71%20%5Bg007%20Device%202%2C%20powered%20up%20closed%5D&c=%7B56%7D10063e0a3a8272%20%5Bg008%20Device%202%2C%20powered%20up%20opened%5D&c=%7B56%7D10063e8200b2e4%20%5BDevice%202%2C%20low%20battery%20while%20open%5D&c=&c=%5B%5D&f=ID%3Ahhhhhh%20FLAGS%3ALOW-BATTERY%3Abv%20%3F%3Fvv%20INITIALIZED%3Abv%20OPEN%3Abv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20CRC%3Ahhhh&cw=4).

`{56}10063e8200b2e4 [Device 2, low battery while open]`

So, here's an update flex decoder:

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=120000,invert,preamble=ffea,bits=72,get=ID:@0:{24},get=State:@30:{1}:[0:OPEN 1:CLOSED],get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],get=Battery:@24:{1}:[0:OK 1:LOW],get=CRC16:@40:{16}"`

**Comment by klohner** [comment]
I'd think you could run:

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=1200,invert,preamble=ffea"`

If possible, do this with no antenna on the RTL-SDR device and hold each door sensor device near the RTL-SDR so it won't pick up any other device.

Then, for each device, try holding a magnet close to it, then pull it away.  If you can, you could also try inserting the battery while holding a magnet close it it, and insert a battery while a magnet is not close to it.  Copy/paste the unique code for each event and label it.

Go through all your devices.  Optimally, it'd be most useful to see your results in format like this:

```
{56}0d9e840000d247 [Device 1, closed]
{56}0d9e8402005e44 [Device 1, opened]
{56}0d9e84083a62d8 [Device 1, powered up closed]
{56}0d9e840a3aeedb [Device 1, powered up opened]

{56}10063e0000beee [Device 2, closed]
{56}10063e020032ed [Device 2, opened]
{56}10063e083a0e71 [Device 2, powered up closed]
{56}10063e0a3a8272 [Device 2, powered up opened]

...etc.
```

**Comment by royboo78** [comment]
![Capture1](https://user-images.githubusercontent.com/97014263/224842587-04977cee-5f2e-4e8b-8070-1ab0cc6b1ad0.JPG)
 Here is what i got so far. I think i did it right. It does seem to read the sensor opposite as when the magnet is close it reads open instead of closed. Let me know if you need any thing else and I will try my best to get you what you need to make these work home assistant.

**Comment by klohner** [comment]
Hmm, my mistake. It seems I had the opened/closed logic backwards in the previous flex spec. Here is the fixed version:

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=1200,invert,preamble=ffea,bits=72,get=ID:@0:{24},get=State:@30:{1}:[0:CLOSED 1:OPEN],get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],get=Battery:@24:{1}:[0:OK 1:LOW],get=CRC:@40:{16}:"`

Is that your only SW-ATT-RDW sensor, @royboo78?  If so, looks like we've got this all figured out.

I've added @royboo78's codes and other codes from another SW-ATT-RDW device I found to the [bitbench](https://triq.net/bitbench#c=%7B56%7D0d9e840000d247%20%5Bg001%20Device%200D9E84%2C%20closed%5D&c=%7B56%7D0d9e8402005e44%20%5Bg002%20Device%200D9E84%2C%20opened%5D&c=%7B56%7D0d9e84083a62d8%20%5Bg003%20Device%200D9E84%2C%20powered%20up%20closed%5D&c=%7B56%7D0d9e840a3aeedb%20%5Bg004%20Device%200D9E84%2C%20powered%20up%20opened%5D&c=&c=%7B56%7D10063e0000beee%20%5Bg005%20Device%2010063E%2C%20closed%5D&c=%7B56%7D10063e020032ed%20%5Bg006%20Device%2010063E%2C%20opened%5D&c=%7B56%7D10063e083a0e71%20%5Bg007%20Device%2010063E%2C%20powered%20up%20closed%5D&c=%7B56%7D10063e0a3a8272%20%5Bg008%20Device%2010063E%2C%20powered%20up%20opened%5D&c=%7B56%7D10063e8200b2e4%20%5BDevice%2010063E%2C%20low%20battery%20while%20open%5D&c=&c=%7B56%7D4310c2000093d0%20%5BDevice%204310C2%20closed%5D&c=%7B56%7D4310c202001fd3%20%5BDevice%204310C2%20opened%5D&c=%7B56%7D4310c2083a234f%20%5BDevice%204310C2%20powered%20up%20closed%5D&c=%7B56%7D4310c20a3aaf4c%20%5BDevice%204310C2%20powered%20up%20open%5D&c=&c=%7B56%7D1ac62a0000bcec%20%5BDevice%201AC62A%20closed%5D&c=%7B56%7D1ac62a020030ef%20%5BDevice%201AC62A%20opened%5D&c=%7B56%7D1ac62a083a0c73%20%5BDevice%201AC62A%20powered%20up%20closed%5D&c=%7B56%7D1ac62a0a3a8070%20%5BDevice%201AC62A%20powered%20up%20opened%5D&c=%7B56%7D1ac62a8a3a0079%20%5BDevice%201AC62A%20powered%20up%20opened%2C%20low%20battery%5D&c=%5B%5D&f=ID%3Ahhhhhh%20FLAGS%3ALOW-BATTERY%3Abv%20%3F%3Fvv%20INITIALIZED%3Abv%20OPEN%3Abv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20CRC%3Ahhhh&cw=4).

```
{56}4310c2000093d0 [Device 4310C2 closed]
{56}4310c202001fd3 [Device 4310C2 opened]
{56}4310c2083a234f [Device 4310C2 powered up closed]
{56}4310c20a3aaf4c [Device 4310C2 powered up open]

{56}1ac62a0000bcec [Device 1AC62A closed]
{56}1ac62a020030ef [Device 1AC62A opened]
{56}1ac62a083a0c73 [Device 1AC62A powered up closed]
{56}1ac62a0a3a8070 [Device 1AC62A powered up opened]
{56}1ac62a8a3a0079 [Device 1AC62A powered up opened, low battery]
```

All my devices have their hexadecimal "S/N" printed on their case, and these exactly match the ID identified in the bitbench.

If an external .conf file is more to one's liking, 

`$ rtl_433 -c SW-ATT-RDW.conf`

```
# SW-ATT-RDW.conf
# Decoder for the AT&T Digital Life SW-ATT-RDW Door Sensor:
# https://fccid.io/QNP-433RDW
#
# Operates on 433.920MHz.
# 

decoder {
    name=SW-ATT-RDW,
    modulation=OOK_MC_ZEROBIT,
    short=132,
    long=132,
    reset=1200,
    bits=72,
    preamble={16}ffea,
    invert,
    unique,
    get=ID:@0:{24},
    get=State:@30:{1}:[0:CLOSED 1:OPEN],
    get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],
    get=Battery:@24:{1}:[0:OK 1:LOW],
    get=CRC:@40:{16}:
}
```

**Comment by royboo78** [comment]
Ok here are 3 total, the first one over again using the the new command and 2 others. Do you happen to know how to get these to work in home assistant?

{56}4310c2000093d0 [Device 1, closed]
{56}4310c202001fd3 [Device 1, opened]
{56}4310c2083a234f [Device 1, powered up closed]
{56}4310c20a3aaf4c [Device 1, powered up opened]

{56}4307270000b212 [Device 2, closed]
{56}43072702003e11 [Device 2, opened]
{56}430727083a028d [Device 2, powered up closed]
{56}4307270a3a8e8e [Device 2, powered up opened]

{56}4310db00001227 [Device 3, closed]
{56}4310db02009e24 [Device 3, opened]
{56}4310db083aa2b8 [Device 3, powered up closed]
{56}4310db0a3a2ebb [Device 3, powered up opened]

**Comment by klohner** [comment]
Great.  I've added them to the [bitbench](https://triq.net/bitbench#c=%7B56%7D0d9e840000d247%20%5Bg001%20Device%200D9E84%2C%20closed%5D&c=%7B56%7D0d9e8402005e44%20%5Bg002%20Device%200D9E84%2C%20opened%5D&c=%7B56%7D0d9e84083a62d8%20%5Bg003%20Device%200D9E84%2C%20powered%20up%20closed%5D&c=%7B56%7D0d9e840a3aeedb%20%5Bg004%20Device%200D9E84%2C%20powered%20up%20opened%5D&c=&c=%7B56%7D10063e0000beee%20%5Bg005%20Device%2010063E%2C%20closed%5D&c=%7B56%7D10063e020032ed%20%5Bg006%20Device%2010063E%2C%20opened%5D&c=%7B56%7D10063e083a0e71%20%5Bg007%20Device%2010063E%2C%20powered%20up%20closed%5D&c=%7B56%7D10063e0a3a8272%20%5Bg008%20Device%2010063E%2C%20powered%20up%20opened%5D&c=%7B56%7D10063e8200b2e4%20%5BDevice%2010063E%2C%20low%20battery%20while%20open%5D&c=&c=%7B56%7D1ac62a0000bcec%20%5BDevice%201AC62A%20closed%5D&c=%7B56%7D1ac62a020030ef%20%5BDevice%201AC62A%20opened%5D&c=%7B56%7D1ac62a083a0c73%20%5BDevice%201AC62A%20powered%20up%20closed%5D&c=%7B56%7D1ac62a0a3a8070%20%5BDevice%201AC62A%20powered%20up%20opened%5D&c=%7B56%7D1ac62a8a3a0079%20%5BDevice%201AC62A%20powered%20up%20opened%2C%20low%20battery%5D&c=%7B56%7D1ac62a80003ce5%20%5BDevice%201AC62A%20closed%2C%20low%20battery%5D&c=%7B56%7D1ac62a8200b0e6%20%5BDevice%201AC62A%20opened%2C%20low%20battery%5D&c=&c=%7B56%7D4310c2000093d0%20%5BDevice%204310C2%20closed%5D&c=%7B56%7D4310c202001fd3%20%5BDevice%204310C2%20opened%5D&c=%7B56%7D4310c2083a234f%20%5BDevice%204310C2%20powered%20up%20closed%5D&c=%7B56%7D4310c20a3aaf4c%20%5BDevice%204310C2%20powered%20up%20open%5D&c=&c=%7B56%7D4307270000b212%20%5BDevice%20430727%2C%20closed%5D&c=%7B56%7D43072702003e11%20%5BDevice%20430727%2C%20opened%5D&c=%7B56%7D430727083a028d%20%5BDevice%20430727%2C%20powered%20up%20closed%5D&c=%7B56%7D4307270a3a8e8e%20%5BDevice%20430727%2C%20powered%20up%20opened%5D&c=&c=%7B56%7D4310db00001227%20%5BDevice%204310DB%2C%20closed%5D&c=%7B56%7D4310db02009e24%20%5BDevice%204310DB%2C%20opened%5D&c=%7B56%7D4310db083aa2b8%20%5BDevice%204310DB%2C%20powered%20up%20closed%5D&c=%7B56%7D4310db0a3a2ebb%20%5BDevice%204310DB%2C%20powered%20up%20opened%5D&c=%5B%5D&f=ID%3Ahhhhhh%20FLAGS%3A%20LOW-BATTERY%3Abv%20%3F%3Fvv%20INITIALIZED%3Abv%20OPEN%3Abv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20%3F%3Fvv%20CRC%3Ahhhh&cw=4).

Sorry, I can't help with the Home Assistant project. Maybe there's something that will help you if you search for rtl_433 on the [Home Assistant Community](https://community.home-assistant.io/) forum.

**Comment by gdt** [comment]
Has this reached conclusion?  What's next?

**Comment by royboo78** [comment]
They are working. I had to manually create them in home assistant.

**Comment by NPutting** [comment]
Bit late to the party but small change of formatting the ID as hex to keep it readable without conversion. 

```# SW-ATT-RDW.conf
# Decoder for the AT&T Digital Life SW-ATT-RDW Door Sensor:
# https://fccid.io/QNP-433RDW
#
# Operates on 433.920MHz.
# 

decoder {
    name=SW-ATT-RDW,
    modulation=OOK_MC_ZEROBIT,
    short=132,
    long=132,
    reset=1200,
    bits=72,
    preamble={16}ffea,
    invert,
    unique,
    get=ID:@0:{24},
    get=State:@30:{1}:[0:CLOSED 1:OPEN],
    get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],
    get=Battery:@24:{1}:[0:OK 1:LOW],
    get=CRC:@40:{16}:
}
```



Or 

`$ rtl_433 -R 0 -X "n=SW-ATT-RDW,m=OOK_MC_ZEROBIT,s=132,l=132,r=1200,invert,preamble=ffea,bits=72,get=ID:@0:{24}:%06X,get=State:@30:{1}:[0:CLOSED 1:OPEN],get=Mode:@28:{1}:[0:NORMAL 1:POWERED_UP],get=Battery:@24:{1}:[0:OK 1:LOW],get=CRC:@40:{16}:"`

**Comment by mcticer** [comment]
Just adding the config file from @NPutting works for SW-ATT-V2 Window / Door sensors (the non recessed version) also.   Thanks for the contribution!
