### ISSUE TITLE
Patch - ESA 1000 / 2000 Energy Cost Monitor

### ISSUE THREAD

**Issue by TylerDurden23** [merbanan/rtl_433#242]
[esa-monitor.diff.txt](https://github.com/merbanan/rtl_433/files/63420/esa-monitor.diff.txt)
![record-signal zip](https://cloud.githubusercontent.com/assets/16313812/11829093/4cb0babe-a39a-11e5-8e78-c003db099153.gif)

**Comment by merbanan** [comment]
Can you send a github pull request of this. Together with some samples for the rtl_433_tests repository ?

**Comment by TylerDurden23** [comment]
The recording is attached as part of the post (the record signal gif, github is not accepting raw file uploads).

**Comment by merbanan** [comment]
Well look at the rtl_433_tests repository and you will find out how to submit samples. I'm not sure what you did but it is not working for me.

**Comment by TylerDurden23** [comment]
Upgrade for compatibility with the latest version.

[esa.zip](https://github.com/merbanan/rtl_433/files/1431093/esa.zip)

**Comment by zuckschwerdt** [comment]
- Fork this repo (use the "Fork" button)
- Clone that to your computer (`git clone https://github.com/TylerDurden23/rtl_433.git`)
- Create a branch (`git checkout -b feat-esa`)
- Make changes to the source
- Commit (`git add ...`, `git commit`), Push (`git push`)
- Create a pull request (buttons on github)

**Comment by merbanan** [comment]
@TylerDurden23 the code has been committed in a modified form. If you have more samples please submit them. Closing issue.
