### ISSUE TITLE
Itron Cyble HRF 868Mhz V5.2

### ISSUE THREAD

**Issue by jonathanD91** [merbanan/rtl_433#2433]
Hello, I have an Itron Cyble brand water meter. the mbus protocol is C2 and I can't listen to it. Are there any specific parameters for this protocol?

**Comment by merbanan** [comment]
Hi, follow these instructions:

https://github.com/merbanan/rtl_433/blob/master/docs/ANALYZE.md

**Comment by merbanan** [comment]
And the wmbusmeters project might be able to help also.

**Comment by jonathanD91** [comment]
> Et le projet wmbusmeters pourrait également aider.

I opened an issue of wmbusmeters also to understand the configuration on C2 but I still have no answer. I will try while waiting for your solution.

**Comment by gdt** [comment]
Please feel free to re-engage if you make progress.  This issues doesn't have actual content and it's stale, so I'm closing it.

**Comment by Anas92230** [comment]
> Hello, I have an Itron Cyble brand water meter. the mbus protocol is C2 and I can't listen to it. Are there any specific parameters for this protocol?

Hello did you find a solution? I have the same water meter.
