### ISSUE TITLE
Oregon Scientific temp sensor being mis-reported as AcuRite Rain Gauge

### ISSUE THREAD

**Issue by simonhenry700** [merbanan/rtl_433#246]
Hi all

I'm new to this - apologies if this problem is of my own making...

...I am receiving data from an Oregon Scientific THN128, but rtl_433 reports it as an AcuRite Rain Gauge. Is there some configuration I can do to correct this behaviour?

Regards
Simon

**Comment by ygator** [comment]
That sensor would be version 1.0 which is not handled currently.  I've put a sample under test so hopefully someone will look into adding support.

If you don't want to receive the bogus data you can run rtl_433 with the -R option to select which protocols you want it to handle.

**Comment by simonhenry700** [comment]
That would explain it - thanks.
