### ISSUE TITLE
Freq not updating when using frequency hopping

### ISSUE THREAD

**Issue by williamstlr** [merbanan/rtl_433#2468]
Hey All,

Not sure if it's just me but I noticed some odd behavior occurring when I use frequency hopping. In my test I'm hopping between 433M and 915M. When watching the `Freq` field as messages are received, I see this:

* Messages received on the 433M hop have a Freq field of 433.x MHz
* Messages received on the 915 hop have a Freq field of 433.x MHz

What used to happen was this:
* Messages received on the 433M hop have a Freq field of 433.x MHz
* Messages received on the 915 hop have a Freq field of 915.x MHz

The last commit for me that works as expected is fa13eb69ce52cd47fff61dad0ddaf642362199d5. Not sure if anyone else is seeing this but I didn't see any other issues on this so I figured I'd open this up.

**Comment by zuckschwerdt** [comment]
The change #1978 might have a problem with the very first frame after a hop, but should work. We need to check that.

**Comment by zuckschwerdt** [comment]
It's a confirmed logic bug with passing the current SDR parameters around. I'll fix this in a few days. Thanks!

**Comment by sheilbronn** [comment]
I was the one who filed the previous issue #2036 ... I can confirm that I was still seeing this recently.
I will recompile with commit 24e6f88 and report back after a few days....

**Comment by sheilbronn** [comment]
> I was the one who filed the previous issue #2036 ... I can confirm that I was still seeing an effect like the one reported above a few weeks ago (not sure when exactly).Now, I will update and recompile including commit [24e6f88](https://github.com/merbanan/rtl_433/commit/24e6f8823377ff8cde5a6ad96878dae4efe710cb) and report back after a few days....

@zuckschwerdt ; After updating to the latest rtl_433 commit https://github.com/merbanan/rtl_433/commit/93f0f30c28cfb6b82b8cc3753415b01a85bee91d it seems to me that I cant get rtl_433 to do any frequency hopping at all, anymore :(
Using this command line I don't see any announcements for frequency hops any more:
`rtl_433 -M protocol -f 433.91M -f 868.3M -H 10 -M stats:1:30 -F json -v`
Could anybody check this, too, please.
Maybe I should open a separate issue?!

**Comment by sheilbronn** [comment]
> For the period of time I was running [24e6f88](https://github.com/merbanan/rtl_433/commit/24e6f8823377ff8cde5a6ad96878dae4efe710cb), the `Freq` field was populating as expected for me with frequency hopping. I started seeing what looked like is being reported here though #2426

Frequency hopping doesn't seem to work for me anymore... Would you mind trying the command line in issue #2475 and reporting any results there. Thank you!
