### ISSUE TITLE
Sonoff PIR3-RF detecting as Smoke-GS558

### ISSUE THREAD

**Issue by justinhunt1223** [merbanan/rtl_433#2471]
Reading through [google group](https://groups.google.com/g/rtl_433/c/uUoRvEDsuZA/m/jQvlg8l_BAAJ) I see that this is not an uncommon issue - seems its due to the encoder chip. Is there a way to get this to be detected as motion sensor?

**Comment by zuckschwerdt** [comment]
Like mentioned it is just a 24 bit (25 with sync at the end) code. There is no structure to it.

If it works well just "mentally" remap Smoke to PIR ;) Otherwise deactivate the GS558 (`-R -86`) and write a flex conf. See also examples in https://github.com/merbanan/rtl_433/tree/master/conf
