### ISSUE TITLE
Does Not Decode Pressure From HP1000/WH24 Station

### ISSUE THREAD

**Issue by IM-studios** [merbanan/rtl_433#2485]
I can receive data from an HP1000/WH24 station:  

time      : 2023-04-19 21:12:01
model     : Fineoffset-WH24                        ID        : 157
Battery   : 1            Temperature: 27.2 C       Humidity  : 68 %          Wind direction: 116       Wind speed: 6.6 m/s
Gust speed: 9.0 m/s      Rainfall  : 2831.1 mm     UV        : 2843          UVI       : 7             Light     : 94689.0 lux
Integrity : CRC

Pressure is not listed in the data.

**Comment by merbanan** [comment]
The barometer part is often not in the remove transmitter unit but in the local station. So there is no signal from it to decode.
