### ISSUE TITLE
Decoding multiple oil sensors

### ISSUE THREAD

**Issue by phiebs** [merbanan/rtl_433#2491]
Hello,
I've got a few existing Watchman oil sensors (protocol 43) working just fine. Have bought a couple of new ones and they are clearly different (protocol 234).

In order to get the new ones to be picked up at all, I have to use the "-Y minmax" flag and also set the gain manually, which in itself is not an issue - can read them reliably using this method, however it prevents the existing sensors from being picked up.

Any smart ideas how I could have both picked up short of getting another rtl dongle and running 2 instances of rtl_sdr?

Any help appreciated!

**Comment by zuckschwerdt** [comment]
Both protocols are quite similar (FSK PCM 1000 and FSK PCM 500). It should just work, chances are that `minmax` is not the problem.
Perhaps try to offset the frequency in 10k steps up or down. But really you need to capture samples of each sensor, compare, and determine a sweet spot for frequency and gain.

**Comment by phiebs** [comment]
Thanks, I'd not messed around with the frequency so will try that and report back. Failing that I'll try as you say and capture samples of each sensor. Appreciate the help and clarification on the protocol types.

**Comment by phiebs** [comment]
Well I've gone up and down in 10k steps (probably tried about 30 steps) and it seems that without the minmax option I can never receive on the new sensors. On this dongle the centre of one of the new sensors is around 433.950 and have validated the gain in SDR#, have tried just off of that freq too but get nothing. Is it possible I have an even newer model of sensor or something? If I could provide a sample (or samples) would it help diagnose the issue? Don't want to take up anyones time but if I can help the project somehow I'd gladly do that?

**Comment by merbanan** [comment]
Well how about running with 2 sets of parameters 30 minutes at the time ? You can hopp in frequency but not switch FSK demodulator without restarting.

**Comment by phiebs** [comment]
The frequency doesn't seem to help, within the [comments on the Watchman Advanced](https://github.com/merbanan/rtl_433/blob/master/src/devices/oil_watchman_advanced.c) it even states `Using -Y minmax should be sufficient to get it to work.`. If there's no way of switching the demod without restarting then perhaps I just run 2 USB dongles, one for each demod?

**Comment by phiebs** [comment]
I ended up using 2 dongles, works a charm now.
