### ISSUE TITLE
Windows static build: missing libwinpthread-1.dll

### ISSUE THREAD

**Issue by schweini** [merbanan/rtl_433#2495]
I'm trying to run the windows rtl_433-win-x64-22.11.zip relase, and both executables, including the static one, complain about a missing libwinpthread-1.dll

The nightly build works though.

**Comment by zuckschwerdt** [comment]
Thanks for the report. Seems like a dup of #2251
The nightly should work: https://github.com/merbanan/rtl_433/releases/tag/nightly
