### ISSUE TITLE
Include frequency in MQTT data

### ISSUE THREAD

**Issue by rsnodgrass** [merbanan/rtl_433#2501]
Is it possible to include which frequency a given event was received on and include this in the MQTT message? With multiple antennas, tuned to different frequencies, it is hard to know which antennas can be removed or upgraded to better support certain event notifications we are receiving. Thanks.

**Comment by zuckschwerdt** [comment]
Yes, use `-M level`
```
$ rtl_433 -M
		= Meta information option =
  [-M time[:<options>]|protocol|level|noise[:<secs>]|stats|bits] Add various metadata to every output line.
…
	Use "level" to add Modulation, Frequency, RSSI, SNR, and Noise meta data.
…
```
