### ISSUE TITLE
LIBUSB_ERROR_NOT_FOUND: Entity not found!

### ISSUE THREAD

**Issue by schmiernippel** [merbanan/rtl_433#2505]
When i use the hopping mode, i always get this error and program stops....: 

LIBUSB_ERROR_NOT_FOUND: Entity not found!

Any workaround for this?

PS: And "[R82XX] PLL not locked!" is always showing when i run the program, but it works!

**Comment by zuckschwerdt** [comment]
Are you sure this is related to hopping? Does it occour without hopping? Does it happen at startup, before the first hop or after a hop?

It rather sounds like you have another driver (the original DVB-T drivers) loaded?

**Comment by schmiernippel** [comment]
its sometimes without hopping, but always with hopping!

But i tried nightly release, and everything works!!! Great work !!! :-)
