### ISSUE TITLE
Id versus Id_reverse and Encrypted versus Encrypted_reverse (HCS200)

### ISSUE THREAD

**Issue by 8um1c4** [merbanan/rtl_433#2506]
Hi guys
In an old RTL_433 decoding HCS433 we had id, id_rev, encrypted and encrypted_id.
Now we have only id and encrypted.
Is there any formula to calculate id_rev and encrypted_rev from id and encrypted to generate a key?
Thanks

**Comment by zuckschwerdt** [comment]
That change is from #1752
Just reverse all bits. But all bits read backwards would then just be the wrong order.
