### ISSUE TITLE
-E quit option does not output to MQTT

### ISSUE THREAD

**Issue by bdf0506** [merbanan/rtl_433#2519]
When running the program with the `-E quit` option, it will listen for one event and then quit as expected. However, if configured to output to MQTT, it will NOT output to MQTT before it quits.

If you do the `-E hop` option, it posts to MQTT as expected.

**Comment by zuckschwerdt** [comment]
Yes, this is a known problem. The main program exit does not care about pending network events. We are on the way to fix that -- likely it is already fixed with current master? Which version did you test?

**Comment by gdt** [comment]
Needs retest with current master.   7-day timer because that was requested in June and hasn't happened, and the issue is believed fixed.

**Comment by gdt** [comment]
submitter has abandoned the issue.
