### ISSUE TITLE
M5stack

### ISSUE THREAD

**Issue by Koekebeest** [merbanan/rtl_433#2524]
Hello,

I wonder if this can be used on a M5stack core v2 with a 433mhz receiver/transmitter?

**Comment by zuckschwerdt** [comment]
A better fit could be some Flipper-Zero software. But the Arduino port of rtl_433 should support some simpler transceivers.

**Comment by Koekebeest** [comment]
Hm, interesting. Thank you for your time and information! :)

**Comment by Koekebeest** [comment]
> A better fit could be some Flipper-Zero software. But the Arduino port of rtl_433 should support some simpler transceivers.

Which software are you referring to if I may ask? Will that work on the m5core2?

**Comment by gdt** [comment]
This was a question and has run its course; closing to reduce issue clutter.  Please feel free to open a discussion or ask on the mailinglist.
