### ISSUE TITLE
More SCM+ Support

### ISSUE THREAD

**Issue by MiddleSiggy** [merbanan/rtl_433#2546]
Would you be able to add some additional SCM+ support.

I can use the rtlamr software and retrieve my water meter readings (and those around me)

Sample:
./rtlamr -msgtype=scm+
20:56:15.154621 decode.go:45: CenterFreq: 912600155
20:56:15.155415 decode.go:46: SampleRate: 2359296
20:56:15.155588 decode.go:47: DataRate: 32768
20:56:15.155718 decode.go:48: ChipLength: 72
20:56:15.155889 decode.go:49: PreambleSymbols: 16
20:56:15.156016 decode.go:50: PreambleLength: 2304
20:56:15.156140 decode.go:51: PacketSymbols: 128
20:56:15.156309 decode.go:52: PacketLength: 18432
20:56:15.156439 decode.go:59: Protocols: scm+
20:56:15.156610 decode.go:60: Preambles: 0001011010100011
20:56:15.156777 main.go:124: GainCount: 29
{Time:2023-06-26T20:56:17.829 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73227139 Consumption:     54239 Tamper:0x4900 PacketCRC:0xF9DB}}
{Time:2023-06-26T20:56:57.829 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73227139 Consumption:     54239 Tamper:0x4900 PacketCRC:0xF9DB}}
{Time:2023-06-26T20:57:12.780 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  72149111 Consumption:     57860 Tamper:0x4900 PacketCRC:0x1348}}
{Time:2023-06-26T20:57:13.943 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  75230233 Consumption:    122500 Tamper:0x2500 PacketCRC:0x6489}}
{Time:2023-06-26T20:57:18.720 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73738930 Consumption:    117555 Tamper:0x2500 PacketCRC:0x9D37}}
{Time:2023-06-26T20:57:23.941 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  75230233 Consumption:    122500 Tamper:0x2500 PacketCRC:0x6489}}
{Time:2023-06-26T20:57:38.446 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  71784101 Consumption:     49973 Tamper:0x2500 PacketCRC:0xEE1A}}
{Time:2023-06-26T20:57:47.827 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73227139 Consumption:     54239 Tamper:0x4900 PacketCRC:0xF9DB}}
{Time:2023-06-26T20:57:48.943 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  71784101 Consumption:     49973 Tamper:0x2500 PacketCRC:0xEE1A}}
{Time:2023-06-26T20:58:02.780 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  72149111 Consumption:     57860 Tamper:0x4900 PacketCRC:0x1348}}
{Time:2023-06-26T20:58:08.328 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73227139 Consumption:     54239 Tamper:0x4900 PacketCRC:0xF9DB}}
{Time:2023-06-26T20:58:09.221 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  73738930 Consumption:    117555 Tamper:0x2500 PacketCRC:0x9D37}}
{Time:2023-06-26T20:58:18.943 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  71784101 Consumption:     49973 Tamper:0x2500 PacketCRC:0xEE1A}}
{Time:2023-06-26T20:58:28.946 SCM+:{ProtocolID:0x1E EndpointType:0xAB EndpointID:  71784101 Consumption:     49973 Tamper:0x2500 PacketCRC:0xEE1A}}

I can confirm that my water meter is : EndpointID:  75230233

If I run "rtl_433 -M protocol -M level -M noise -M stats -f 915600155 -s 2359296 -g 0 -S unknown -R 154 -A" I get a bunch of SCM+ messages that are not decoded. 

I saved the unknown samples and added them to the zip file here.
[2023-06-26 - Samples.zip](https://github.com/merbanan/rtl_433/files/11876581/2023-06-26.-.Samples.zip)

Also this is the exact water meter transmitter documentation:
https://www.itron.com/-/media/feature/products/documents/spec-sheet/101320sp03-100w-watercommmodweb.pdf

Let me know if there is anything I can do for you. Thank you

**Comment by gdt** [comment]
Generally there is nobody here looking at issues and digging in for devices they don't have.   If rtlamr works, you should be able to submit a PR to enhance `devices/scm_plus.c`.
