### ISSUE TITLE
Home Assistant auto discovery broken due to bad topic subscription

### ISSUE THREAD

**Issue by mill1000** [merbanan/rtl_433#2554]
Looks like the Home Assistant auto discovery (rtl_433_mqtt_hass.py) is broken. Possibly introduced by #2289.

The topic subscriptions that are created for the sensors are missing the proper topic prefix so no values are received.
New subscription
![image](https://github.com/merbanan/rtl_433/assets/6924622/39d68e04-f99f-431b-a43d-d64f53bdfbd5)

Previous subscription
![image](https://github.com/merbanan/rtl_433/assets/6924622/1392f4a3-9bc6-401d-971d-ad2a926bcb90)

rtl_433 command
```
docker run --device /dev/bus/usb/001/007 hertzg/rtl_433:latest -C si -F "mqtt://10.100.1.6:1883,user=,pass=" -F log -F kv  -R 162 -M level
```

**Comment by mill1000** [comment]
Here's a working config using the current main.

```
> rtl_433_mqtt_hass.py -d -T rtl_433/devices[/type][/model][/subtype][/channel][/id]
```

rtl_433
```
> rtl_433 -C si -F "mqtt://10.100.1.6:1883,devices=rtl_433/devices[/type][/model][/subtype][/channel][/id],events=rtl_433/test/events,states=rtl_433/test/states" -F log -F kv -M level
```

Not ideal since I had to put an extra level in the events and states topics

**Comment by zuckschwerdt** [comment]
@unverbraucht can you check this please?

**Comment by unverbraucht** [comment]
Looking into it.

**Comment by unverbraucht** [comment]
I could reproduce the issue, looking into it now.
