### ISSUE TITLE
Home Assistant getting: Discovery Timeout in the future error from Bresser Weather 7-in-1 sensor

### ISSUE THREAD

**Issue by okainov** [merbanan/rtl_433#2575]
I'm just getting some initial setup for HA and want to read the data from by Bresser weather sensor.

When I installed Autodiscovery addon (https://github.com/pbkhrv/rtl_433-hass-addons/tree/main/rtl_433_mqtt_autodiscovery), I first was happy that it worked out-of-the box, detecting the sensor and reading data, but shortly after I noticed the data is not being updated really. Then I started digging into logs and found out it pushes only the initial data after start and all the other measurements are being skipped with "Discovery Timeout in the future".

Discovery interval was set to default 600. Unfortunately there was no really any hint/description, what does it actually do, so I searched across the code and found this. And it seemed to be the problem - if the interval is too big, it just skips the push. So I updated it to "5" and everything started working fine.

Any clues whether this can be improved somehow, either functionally or at least descriptions/documentation?

https://github.com/merbanan/rtl_433/blob/4968419bf748ac9b5fca5ebfc267b7cd9f31c0e6/examples/rtl_433_mqtt_hass.py#L726

**Comment by gdt** [comment]
This is not clearly a bug in rtl_433.    You are going to need to make sure you are running the latest rtl_433 code, both rtl_433 itself, and the mqtt scripts, and then to look at what is happening at the json level from rtl_433, and at the mqtt level.  Also check your clocks and timezones.    Please feel free to open  a discussion asking for help, or to use the mailinglist.

I'm closing this as not providing evidence that there is a bug in rtl_433, and not being a basis to try to fix anything.
