### ISSUE TITLE
Decoder "TFA 30.3151 Weather Station" gave invalid return value -12: notify maintainer

### ISSUE THREAD

**Issue by penfold42** [merbanan/rtl_433#2600]
I have two dongles and only one is reporting the error from a WHx080 (in a fridge!)
Works fine:
antenna is about 12m away and is a simple piece of 150cm wire indoors
running Linux kali2.home 4.18.0-477.15.1.el8_8.x86_64 

Fails intermittently - 
about 20m away, outside, "proper" 2m/70cm antenna
running Linux pi4 5.10.103-v7l+ 

I'm guessing the signal level is going to be lower on the failing item.

rtl_433 version nightly-20-ge7682f80 branch master at 202308132256

**Comment by zuckschwerdt** [comment]
Thanks, fixed.
