### ISSUE TITLE
Add "device database" that maps between drivers and devices, and also known frequencies

### ISSUE THREAD

**Issue by psa-jforestier** [merbanan/rtl_433#2611]
Is there any way to have the list of all devices compatible with existing drivers ?
For example, I bought a weather station Optex 990019, but I was not sure before trying that it works with rtl_433.
Hopefully, it is detected as a "Bresser-5-in-1" sensor (https://github.com/merbanan/rtl_433/blob/master/src/devices/bresser_5in1.c) .

How, and where, can I indicate that this sensor (Optex 990019, also known as Optex SM-019) is fully compatible with the Bresser driver ? I plan to modify the code of bresser_5in1.c to have such indication, but I was wondering if there is an other way to do it.
Something like a markdown / json / whatever file with info like :
```
decoder_number | name                          | driver         | compatibility
119            | Bresser Weather Center 5-in-1 | bresser_5in1.c | Optex 990019, Lacrosse XXYZZ, ...
```

**Comment by zuckschwerdt** [comment]
Yes we still need such a driver-support "database". Marking this in code is currently the only choice.

I have a half-finished support/experience (price, quality, …) page where users can contribute such infos -- I hope to finish it soon-ish.

**Comment by psa-jforestier** [comment]
Good news ! it should be a huge work to do such a database. Let us know when you want user contribution to enlarge this DB.

**Comment by ProfBoc75** [comment]
Salut @psa-jforestier : yes it's some kind of archeology , I did it with Emax w6 (device 215) . Optex is a french rebrand of chineese products , but all around the world you have lot of other subbrands doing the same. So it's very difficult to get compatibility except to wait and track feedback from users. This takes times, and sometime it's not fully compatible, same protocol but missing a sensor, like weather station with or without wind gust or the uv/lux... This adding another level of complexity. But good idea to get such compatibility matrix. The approach could be like rfxcom user guide where compatible devices are listed and link to a protocol, here is decoder.

**Comment by gdt** [comment]
This issue now includes which-frequency-is-used-by-device in addition to which-device-is-decoded-by-driver, enabling us to close #917
