### ISSUE TITLE
OOB read in Somfy io-homecontrol

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#2655]
Probably easy to fix, but I don't have time right now. Found using fuzzing.

Reproducer:

`rtl_433 -y "5}fx6x50B005050050500505005050055x" -R189`

Causes a segfault in somfy_iohc_decode, I think because the msg_len / data_length is not validated before using as an index.

**Comment by zuckschwerdt** [comment]
Thanks. Yes. Minimum msg length check is missing.
