### ISSUE TITLE
rtl_433 version -128-NOTFOUND after update

### ISSUE THREAD

**Issue by fankyy** [merbanan/rtl_433#2656]
After upgrade, rtl433 works but it says

`rtl_433 version -128-NOTFOUND branch master at -128-NOTFOUND inputs file rtl_tcp RTL-SDR`

Is this normal?

Could this happen if I mistaken git pull with git clone?

**Comment by zuckschwerdt** [comment]
Clear the build dir and rerun cmake. It should tell you what version info was scraped from git:
```
-- Found Git version: refs/heads/master commit 46afffc8bbbb4db1c3b0d4bb6fa0767db1c9bdab from 2023-10-03T13:32:00+0200
-- Using Git version tag: nightly-1-g46afffc8 on master at 202310031332
```
Which is somewhat useless these days as the `nightly` tag is always very recent.
