### ISSUE TITLE
Bresser 7in1 weather station reports rain even if there is none

### ISSUE THREAD

**Issue by rplc** [merbanan/rtl_433#2658]
Hello,

I've bought the bresser 7in1 weather station ([https://www.amazon.de/Bresser-ClimateConnect-Tuya-Alexa-Google/dp/B09HY2ZRS5](https://www.amazon.de/Bresser-ClimateConnect-Tuya-Alexa-Google/dp/B09HY2ZRS5), model number 7003600GYE000).

I've checked out the current master branch and build it. Everything seems fine until I noticed that the 173 protocol always parses a rain value of 23.6mm (even if there has been no single drop). The tuya display corresponding to the weather station displays no rain, it seems that there is a decoding problem/issue.

Examples are attached

```
time      : 2023-10-05 12:55:00+0200
model     : Bresser-7in1 id        : 43930
Temperature: 15.2 C      Humidity  : 69            Wind Gust : 0.8 m/s       Wind Speed: 0.8 m/s       Direction : 280           Rain      : 23.6 mm       Light     : 30.025 klx    Light     : 30025.000 lux UV Index  : 2.1           Battery   : 1
Integrity : CRC
```
[g005_868.3M_250k.cu8.txt](https://github.com/merbanan/rtl_433/files/12817533/g005_868.3M_250k.cu8.txt)
```
time      : 2023-10-05 13:00:12+0200
model     : Bresser-7in1 id        : 43930
Temperature: 14.9 C      Humidity  : 68            Wind Gust : 1.3 m/s       Wind Speed: 1.3 m/s       Direction : 288           Rain      : 23.6 mm       Light     : 33.809 klx    Light     : 33809.000 lux UV Index  : 2.7           Battery   : 1
Integrity : CRC
```
[g016_868.3M_250k.cu8.txt](https://github.com/merbanan/rtl_433/files/12817570/g016_868.3M_250k.cu8.txt)

Greetings Alex

**Comment by zuckschwerdt** [comment]
That value is the accumulated total rain. You have to derive values for hourly, daily, etc. intervals yourself.
