### ISSUE TITLE
Wrong channel with Oregon Scientific sensors (R=12)

### ISSUE THREAD

**Issue by Quasaro** [merbanan/rtl_433#2665]
Hi,
I've noticed that the latest nightly introduced an issue that was not present in the latests tag 22.11.
Basically, the sensor with channel=3 is wrongly reported as ch=4. That didn't happen in the previous stable release.
Here's a screenshot of the HTTP interface:
![image](https://github.com/merbanan/rtl_433/assets/45846933/00e0e07e-2d18-49ed-94c6-1578c09c68c7)

Is there any specific test you want me to do to help troubleshooting this issue?

Thanks

**Comment by zuckschwerdt** [comment]
In #2033 we decided to not fudge with received data to match a specific hardware bug. Channel 3 is actually channel 4 but mislabeled. The hack to make it seem like channel 3 broke another device where there is actually a CH 3 and 4.
To all users, sorry for the inconvenience -- we hope it's just a slight update in your UI tools.

There is a summary of the current  most important changes at https://github.com/merbanan/rtl_433/releases

**Comment by zuckschwerdt** [comment]
Lacking documentation we assumed the bug was in THN132N, but you show it's also in THGR122N and THGR810 -- this is interesting. Thanks!

**Comment by Quasaro** [comment]
Thanks for your quick reply. I'll use some different info from the 2 sensor (in place of channel) to tell which one is which. Hope these details are sent to MQTT.
Cheers
