### ISSUE TITLE
Not able to install last version on Pi 3 64 bits

### ISSUE THREAD

**Issue by 8um1c4** [merbanan/rtl_433#2700]
Hi guys,

I was trying to update rtl_433 with new and last changes, but it hangs on 7% compilation after 2 major errors.
I'm using a Raspberry 3 with 64 bits OS, completely updated.
Log below.
Can you advise?

Regards.

-------------------------------

pi@Pi64:~ $ git clone https://github.com/merbanan/rtl_433.git
cd rtl_433/  
mkdir build
cd build
Cloning into 'rtl_433'...
remote: Enumerating objects: 22767, done.
remote: Counting objects: 100% (4913/4913), done.
remote: Compressing objects: 100% (637/637), done.
remote: Total 22767 (delta 4421), reused 4395 (delta 4270), pack-reused 17854
Receiving objects: 100% (22767/22767), 8.47 MiB | 3.05 MiB/s, done.
Resolving deltas: 100% (17891/17891), done.
pi@Pi64:~/rtl_433/build $ cmake ../
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found Git version: refs/heads/master commit 8535ba24f675afc498dc75ca84e00625aceac06f from 2023-10-27T12:26:51+0200
-- Using Git version tag: 22.11-238-g8535ba24 on master at 202310271226
-- Using GCC Static analysis
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- IPv6 support enabled.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Threads support will be compiled.
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1w")  
-- OpenSSL TLS support will be compiled. Found version 1.1.1w
-- Found LibRTLSDR: /usr/lib/aarch64-linux-gnu/librtlsdr.so (found version "0.6.0")
-- Found LibUSB: /usr/lib/aarch64-linux-gnu/[libusb-1.0.so](http://libusb-1.0.so/) (found version "1.0.24")
-- RTL-SDR device input will be compiled. Found version 0.6.0
-- libusb-1.0 error messages are available. Found version 1.0.24
-- SoapySDR device input will be compiled. Found version 0.8.1-gd2496c50
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen missing components: dot
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/rtl_433/build
pi@Pi64:~/rtl_433/build $ make
Scanning dependencies of target data
[  0%] Building C object src/CMakeFiles/data.dir/data.c.o
[  1%] Building C object src/CMakeFiles/data.dir/abuf.c.o
[  1%] Linking C static library libdata.a
[  1%] Built target data
Scanning dependencies of target r_433
[  2%] Building C object src/CMakeFiles/r_433.dir/abuf.c.o
[  2%] Building C object src/CMakeFiles/r_433.dir/am_analyze.c.o
[  3%] Building C object src/CMakeFiles/r_433.dir/baseband.c.o
[  3%] Building C object src/CMakeFiles/r_433.dir/bitbuffer.c.o
[  3%] Building C object src/CMakeFiles/r_433.dir/compat_paths.c.o
[  4%] Building C object src/CMakeFiles/r_433.dir/compat_time.c.o
[  4%] Building C object src/CMakeFiles/r_433.dir/confparse.c.o
[  4%] Building C object src/CMakeFiles/r_433.dir/data.c.o
[  5%] Building C object src/CMakeFiles/r_433.dir/data_tag.c.o
[  5%] Building C object src/CMakeFiles/r_433.dir/decoder_util.c.o
/home/pi/rtl_433/src/decoder_util.c: In function ‘decoder_log_bitrow.part.0’:
/home/pi/rtl_433/src/decoder_util.c:221:9: warning: double-‘free’ of ‘row_bits’ [CWE-415] [-Wanalyzer-double-free]
  221 |         free(row_bits);
      |         ^~~~~~~~~~~~~~
  ‘decoder_log_bitrow’: events 1-2
    |
    |  191 | void decoder_log_bitrow(r_device *decoder, int level, char const *func, uint8_t const *bitrow, unsigned bit_len, char const *msg)
    |      |      ^~~~~~~~~~~~~~~~~~
    |      |      |
    |      |      (1) entry to ‘decoder_log_bitrow’
    |  192 | {
    |  193 |     if (decoder->verbose >= level) {
    |      |        ~
    |      |        |
    |      |        (2) following ‘true’ branch...
    |
  ‘decoder_log_bitrow’: event 3
    |
    |cc1:
    | (3): ...to here
    |
  ‘decoder_log_bitrow’: event 4
    |
    |cc1:
    | (4): calling ‘decoder_log_bitrow.part.0’ from ‘decoder_log_bitrow’
    |
    +--> ‘decoder_log_bitrow.part.0’: events 5-6
           |
           |
           +--> ‘bitrow_asprint_code’: events 7-12
                  |
                  |   46 | static char *bitrow_asprint_code(uint8_t const *bitrow, unsigned bit_len)
                  |      |              ^~~~~~~~~~~~~~~~~~~
                  |      |              |
                  |      |              (7) entry to ‘bitrow_asprint_code’
                  |......
                  |   53 |     for (unsigned col = 0; col < (unsigned)(bit_len + 7) / 8; ++col) {
                  |      |     ~~~      
                  |      |     |
                  |      |     (8) following ‘false’ branch...
                  |......
                  |   57 |     row_bytes[2 * (bit_len + 3) / 8] = '\0';
                  |      |                   ~~~~~~~~~~~~~
                  |      |                            |
                  |      |                            (9) ...to here
                  |......
                  |   60 |     if (bit_len == 0) {
                  |      |        ~      
                  |      |        |
                  |      |        (10) following ‘false’ branch (when ‘bit_len != 0’)...
                  |......
                  |   65 |     row_code = malloc(8 + bit_len / 4 + 1); // "{nnnn}..\0"
                  |      |                           ~~~~~~~~~~~
                  |      |                                   |
                  |      |                                   (11) ...to here
                  |   66 |     if (!row_code) {
                  |      |        ~      
                  |      |        |
                  |      |        (12) following ‘true’ branch (when ‘row_code’ is NULL)...
                  |
                ‘bitrow_asprint_code’: event 13
                  |
                  |cc1:
                  | (13): ...to here
                  |
           <------+
           |
         ‘decoder_log_bitrow.part.0’: events 14-17
           |
           |  200 |         row_code = bitrow_asprint_code(bitrow, bit_len);
           |      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           |      |                    |
           |      |                    (14) returning to ‘decoder_log_bitrow.part.0’ from ‘bitrow_asprint_code’
           |......
           |  211 |         if (decoder->verbose_bits) {
           |      |            ~        
           |      |            |
           |      |            (15) following ‘true’ branch...
           |  212 |             row_bits = bitrow_asprint_bits(bitrow, bit_len);
           |      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           |      |                        |
           |      |                        (16) ...to here
           |      |                        (17) calling ‘bitrow_asprint_bits’ from ‘decoder_log_bitrow.part.0’
           |
           +--> ‘bitrow_asprint_bits’: events 18-19
                  |
                  |   75 | static char *bitrow_asprint_bits(uint8_t const *bitrow, unsigned bit_len)
                  |      |              ^~~~~~~~~~~~~~~~~~~
                  |      |              |
                  |      |              (18) entry to ‘bitrow_asprint_bits’
                  |......
                  |   80 |     if (!row_bits) {
                  |      |        ~      
                  |      |        |
                  |      |        (19) following ‘true’ branch (when ‘row_bits’ is NULL)...
                  |
                ‘bitrow_asprint_bits’: event 20
                  |
                  |cc1:
                  | (20): ...to here
                  |
                ‘bitrow_asprint_bits’: event 21
                  |
                  |cc1:
                  | (21): ‘<return-value>’ is NULL
                  |
           <------+
           |
         ‘decoder_log_bitrow.part.0’: events 22-24
           |
           |   36 |     decoder->log_fn(decoder, level, data);
           |      |     ~~~~~~~~~~~~~~~    
           |      |            |
           |      |            (23) first ‘free’ here
           |......
           |  212 |             row_bits = bitrow_asprint_bits(bitrow, bit_len);
           |      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           |      |                        |
           |      |                        (22) returning to ‘decoder_log_bitrow.part.0’ from ‘bitrow_asprint_bits’
           |......
           |  221 |         free(row_bits);
           |      |         ~~~~~~~~~~~~~~  
           |      |         |
           |      |         (24) second ‘free’ here; first ‘free’ was at (23)
           |
[  5%] Building C object src/CMakeFiles/r_433.dir/fileformat.c.o
[  6%] Building C object src/CMakeFiles/r_433.dir/http_server.c.o
In function ‘ring_list_new’:
/home/pi/rtl_433/src/http_server.c:158:16: warning: leak of ‘<unknown>’ [CWE-401] [-Wanalyzer-malloc-leak]
  158 |     ring->tail = ring->data;
      |     ~~~~~~~~~~~^~~~~~~~~~~~
  ‘data_output_http_create’: events 1-4
    |
    | 1246 | struct data_output *data_output_http_create(struct mg_mgr *mgr, char const *host, char const *port, r_cfg_t *cfg)
    |      |                     ^~~~~~~~~~~~~~~~~~~~~~~
    |      |                     |
    |      |                     (1) entry to ‘data_output_http_create’
    |......
    | 1249 |     if (!http) {
    |      |        ~            
    |      |        |
    |      |        (2) following ‘false’ branch (when ‘http’ is non-NULL)...
    |......
    | 1254 |     http->output.log_level    = LOG_TRACE; // sensible default, not parsed from args
    |      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                               |
    |      |                               (3) ...to here
    |......
    | 1258 |     http->server = http_server_start(mgr, host, port, cfg, &http->output);
    |      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                    |
    |      |                    (4) calling ‘http_server_start’ from ‘data_output_http_create’
    |
    +--> ‘http_server_start’: events 5-8
           |
           | 1107 | static struct http_server_context *http_server_start(struct mg_mgr *mgr, char const *host, char const *port, r_cfg_t *cfg, struct data_output *output)
           |      |                                    ^~~~~~~~~~~~~~~~~
           |      |                                    |
           |      |                                    (5) entry to ‘http_server_start’
           |......
           | 1114 |     if (!ctx) {
           |      |        ~                            
           |      |        |
           |      |        (6) following ‘false’ branch (when ‘ctx’ is non-NULL)...
           |......
           | 1119 |     ctx->cfg     = cfg;
           |      |     ~~~~~~~~~~~~~~~~~~              
           |      |                  |
           |      |                  (7) ...to here
           | 1120 |     ctx->output  = output;
           | 1121 |     ctx->history = ring_list_new(DEFAULT_HISTORY_SIZE);
           |      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           |      |                    |
           |      |                    (8) calling ‘ring_list_new’ from ‘http_server_start’
           |
           +--> ‘ring_list_new’: events 9-16
                  |
                  |  142 | static ring_list_t *ring_list_new(unsigned size)
                  |      |                     ^~~~~~~~~~~~~
                  |      |                     |
                  |      |                     (9) entry to ‘ring_list_new’
                  |......
                  |  145 |     if (!ring) {
                  |      |        ~            
                  |      |        |
                  |      |        (10) following ‘false’ branch (when ‘ring’ is non-NULL)...
                  |......
                  |  150 |     ring->data = calloc(size, sizeof(void *));
                  |      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  |      |                  |
                  |      |                  (11) ...to here
                  |      |                  (12) allocated here
                  |  151 |     if (!ring->data) {
                  |      |        ~            
                  |      |        |
                  |      |        (13) assuming ‘<unknown>’ is non-NULL
                  |      |        (14) following ‘false’ branch...
                  |......
                  |  157 |     ring->size = size;
                  |      |     ~~~~~~~~~~~~~~~~~
                  |      |                |
                  |      |                (15) ...to here
                  |  158 |     ring->tail = ring->data;
                  |      |     ~~~~~~~~~~~~~~~~~~~~~~~
                  |      |                |
                  |      |                (16) ‘<unknown>’ leaks here; was allocated at (12)
                  |
[  6%] Building C object src/CMakeFiles/r_433.dir/jsmn.c.o
[  6%] Building C object src/CMakeFiles/r_433.dir/list.c.o
[  7%] Building C object src/CMakeFiles/r_433.dir/logger.c.o
[  7%] Building C object src/CMakeFiles/r_433.dir/mongoose.c.o

**Comment by zuckschwerdt** [comment]
It seems GCC 10.2.1 is handling the static analysis well. Just remove this block: https://github.com/merbanan/rtl_433/blob/8535ba24f675afc498dc75ca84e00625aceac06f/CMakeLists.txt#L103-L107

**Comment by zuckschwerdt** [comment]
If restricted Static analysis to GCC 13.2+ now, the tested versions 10.2.1, 12.2.1 are too buggy/strict.

**Comment by 8um1c4** [comment]
Procedure follow with success.

**Comment by 8um1c4** [comment]
Procedure followed with success. Instalation finished and rtl_433 running. Many thanks.
