### ISSUE TITLE
Bresser Weather Center 6-in-1 and 2 Tuner

### ISSUE THREAD

**Issue by djmalin** [merbanan/rtl_433#2735]
Hello, I have two dvb-t 820t2@ sdr tuners, one I want to set to read wmbusmeters and the apator162 overlay, and the other one wants to read outdoor weather stations Bresser Weather Center 6-in-1 using rtl_433, my tuners have the following access paths
1. DEVNAME: /dev/bus/usb/001/020
2. DEVNAME: /dev/bus/usb/001/006

my config rtl_433:

`

> output mqtt://192.168.x.xx:1883,user=xxx,pass=xxxx,retain=retain
>report_meta time:iso:usec:tz
>device serial /dev/bus/usb/001/020
>#device auto
>frequency 868.30M
>#frequency 169.00M
>#frequency 433.92M
>hop_interval 5
>#protocol 217
>#protocol 214
>#protocol 52
>#protocol 119
>protocol 172
>protocol 173
`

config wmbusmeters:

`
>device=auto
>donotprobe=/dev/bus/usb/001/006
>format=json
>logfile=/dev/stdout
>loglevel=normal
>logtelegrams=false
>shell=/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
`

log rtl_433:

`
>s6-rc: info: service s6rc-oneshot-runner: starting
>s6-rc: info: service s6rc-oneshot-runner successfully started
>s6-rc: info: service fix-attrs: starting
>s6-rc: info: service fix-attrs successfully started
>s6-rc: info: service legacy-cont-init: starting
>s6-rc: info: service legacy-cont-init successfully started
>s6-rc: info: service legacy-services: starting
>s6-rc: info: service legacy-services successfully started
>Starting rtl_433 with rtl_433.conf...
>[rtl_433] rtl_433 version 22.11 branch  at 202211191645 inputs file rtl_tcp RTL-SDR
>[rtl_433] Use -h for usage help and see https://triq.org/ for documentation.
>[rtl_433] Publishing MQTT data to 192.168.xx.xx port 1883
>[rtl_433] Publishing device info to MQTT topic "rtl_433/local-rtl433/devices[/type][/model][/subtype][/channel][/id]".
>[rtl_433] Publishing events info to MQTT topic "rtl_433/local-rtl433/events".
>[rtl_433] Publishing states info to MQTT topic "rtl_433/local-rtl433/states".
>[rtl_433] 
>[rtl_433] New defaults active, use "-Y classic -s 250k" for the old defaults!
>[rtl_433] 
>[rtl_433] Registered 2 out of 223 device decoding protocols [ 172-173 ]
>[rtl_433] No input driver for SoapySDR compiled in.
>s6-rc: info: service legacy-services: stopping
>s6-rc: info: service legacy-services successfully stopped
>s6-rc: info: service legacy-cont-init: stopping
>s6-rc: info: service legacy-cont-init successfully stopped
>s6-rc: info: service fix-attrs: stopping
>s6-rc: info: service fix-attrs successfully stopped
>s6-rc: info: service s6rc-oneshot-runner: stopping
>s6-rc: info: service s6rc-oneshot-runner successfully stopped
`

**Comment by zuckschwerdt** [comment]
Set names on the dongles with `rtl_eeprom` then use `device :NAME`, from the help:
```
  [-d :<RTL-SDR USB device serial (can be set with rtl_eeprom -s)>]
```
