### ISSUE TITLE
Identifying lora singals

### ISSUE THREAD

**Issue by PovilasID** [merbanan/rtl_433#2745]
Hey,

A lot of meters were updated and most of them have Lora enabled and I heard that at least on of them should not be encrypted, so I ran `rtl_433 -S unknown -f 868.1M ` with various other settings and combos, to capture some signals. And capture I did... a lot of signals. Most of them noise but some look like they could be signals.
However, I am not sure how Lora signal should really look like... so here are a few samples I captured that then plugged into https://triq.org/pdv/ return some bits.
[plausible.zip](https://github.com/merbanan/rtl_433/files/13523673/plausible.zip)
Are those Lora signals or something else? They look to be too large lora one seams to have almost 12 kilobytes.
And if they are how do I get that packet into a hex format that I can then use?  Here is sample of what I am looking for `0ea0355d10ae7718002935000054c0345db2731800e7290000b800b900b800b800b800b900b800b800b800b800`

P.S. I got my SDR USB stick yesterday, so I may be missing... a lot. However, the fact I was able to stumble, so far forward is truly a testament to awesome tools here.

**Comment by zuckschwerdt** [comment]
Yes, those up- or down sweeps are typical LoRa. S.a. https://www.sigidwiki.com/wiki/LoRa

**Comment by zuckschwerdt** [comment]
Perhaps some LoRa tools can also read a file instead of live input. The rtl_433 demod can't decipher LoRa (to hex) though (we expect some form of pulses, not these sweeps/chirps).

**Comment by gdt** [comment]
It seems like this was a discussion not an issue, and that some suggestions have been given and it's run it's course.  I don't see a reason that keeping it open is helpful.  If I'm wrong please explain and we can reopen.
