### ISSUE TITLE
Decoder for Mueller Hot Rod V1 Water Meter Transmitter

### ISSUE THREAD

**Issue by dolai1** [merbanan/rtl_433#2752]
This software is awesome; I appreciate the work of the devs.

Could support be added for this water meter?

Someone has already been able to get the consumption data out of it:
https://github.com/sycophantic/muellerhotrod/

And, some more information:
https://www.oaklodgewaterservices.org/files/7babb4e56/meters+installed.pdf

Is this sufficient information to create the decoder?

Thank you.

**Comment by zuckschwerdt** [comment]
A very nice teardown/description there. Seems easy to add. Can you grab some (20 to 100 maybe?) raw codes (e.g. `{92}feb10014376017005053000`) and post here so we can take a swing at the checksum?

**Comment by zuckschwerdt** [comment]
> I'd be happy to, but, forgive me, is there a way to do this with my current setup?

Yes, the `-X` line from the linked repo

**Comment by zuckschwerdt** [comment]
Try to use a UI with a waterfall display first. Locate the signal and then pick a center frequency close but not directly on the signal (10 to 50 kHz offset should work best).

**Comment by zuckschwerdt** [comment]
In no particular order: Gqrx, CubicSDR, SDRangel, SigDigger.

Bandwidth is equal to sample rate, default is 250k for lower freqs like 433.92M and 1024k for higher like 868M.

**Comment by zuckschwerdt** [comment]
The last byte could be a CRC (CRC-8/ITU, poly 0x07 init 0). But for that the code needs to be 72 bits (or more).
The only 3 good codes (your three truncation examples above) work.
The 10 "filtered for uniques" you posted also work (up to the truncation -- they are all too short).
E.g. truncate codes to 64 bits (like this `1259651402670905`) and observe the crc value of `c3` in https://crccalc.com/

**Comment by zuckschwerdt** [comment]
> I don't see it working by the same method with the "filtered for uniques" list,

E.g.  `{70}125964390531330538` using `1259643905313305` matches the CRC of `3A` if we ignore the missing bits at the end. Similar for all others.

> Can this now be turned into a decoder, or would that be premature?

Yes, it has a checksum and most fields are known. Do you want to code a PR or should I just add a decoder?

**Comment by ProfBoc75** [comment]
> I meant to ask, will the decoder be part of the next release? Thank you.

@zuckschwerdt : I can help on this issue, let me know. Sounds to be a simple decoder here: we have samples, bitbench, preamble/sync word, crc, another issue is opened on the same protocol, I guess we have enough information, just the unit to be confirmed gallon or liter or just a counter without unit ?

**Comment by zuckschwerdt** [comment]
@ProfBoc75 that would be great! I currently don't have much time for this :/

**Comment by ProfBoc75** [comment]
Hi @dolai1:

I started to write the decoder, I would like some more codes / more samples.

Notice that from the cu8 files I analyzed, the pulse is more around 26 µs than 20.
Can you try this:

    rtl_433 -f 909M -R 0 -X 'n=hotrod,m=FSK_PCM,s=26,l=26,r=2500,preamble={24}feb100,bits>=72'

I would like to confirm the data layout at the volume level, with 5, 6 or 7 nibbles after the ID.

Possible [bitbenchs](https://triq.net/bitbench#c=%7B73%7D1259651402670905c30&c=%7B74%7D1259651402670905c30&c=%7B75%7D1259651402670905c30&c=%7B73%7D1259651402671905940&c=%7B74%7D1259651402671905940&c=%7B75%7D1259651402671905940&c=%7B75%7D1259651402672105c50&f=ID%2032h%20VOLUME_GAL%2020h%20FLAGONE%3A4h%20FLAGTWO%3A8h%20CRC%3A8h%208x%0AID%2032h%20VOLUME_GAL%2024h%20_________FLAGTWO%3A8h%20CRC%3A8h%208x%0AID%2032h%20VOLUME_GAL%2028h%20________FLAGTWO%3A%204h%20CRC%3A8h%208x%0A----------------------------------------------------------%0A&z=1&cl=56&cw=4)

Let me know.

I will pull a request soon, starting with volume based on 5 nibbles / 20 bit.

**Comment by ProfBoc75** [comment]
@dolai1 : Thanks for your feedback.

So, yes, for me the increase is by 10 gallons, but we can use the 7 nibbles, the unit will stay 0.
Then you have a flag always at 5 then the CRC.

My [bitbench](https://triq.net/bitbench#c=aaaafeb1001259651402670905c3&c=aaaafeb100125965140267190594&c=aaaafeb1001259651402672105c5&c=aaaafeb10012596514027331059b&c=aaaafeb1001259651402733205a4&c=aaaafeb10014376017005053000e&c=aaaafeb1001442661604978900fc&c=aaaafeb100144266160497950057&c=aaaafeb100144266160512080082&c=aaaafeb100144266160512228027&f=ID%2032h%20GALLONS%2028h%20FLAG%204h%20CRC%208h&z=1&a=Preamble&m=feb100&cw=4)
