### ISSUE TITLE
Emontx off by one access

### ISSUE THREAD

**Issue by zuckschwerdt** [merbanan/rtl_433#277]
@dwmw2 et al.
in `rtl_433/src/devices/emontx.c:104`:
the array index 13 is past the end of the array (which contains 13 elements)
```
                if (crc != words[13])
```
the array 'words' is declared in `rtl_433/src/devices/emontx.c:56`:
```
                uint16_t words[13];
```

**Comment by dwmw2** [comment]
Oops. Sorry about that; thanks for catching it.
