### ISSUE TITLE
Eva-Dry Safe sensor compatibility

### ISSUE THREAD

**Issue by bkenobi** [merbanan/rtl_433#2774]
I have a thermohygrometer that I inherited in a box of miscellaneous stuff.  I was thinking it was probably junk (battery corrosion was my suspicion) so I opened it up and it looks very clean.  The device runs on 433.92 based on the crystal.  I looked for an FCCID but did not see one on the product and it does not appear to be on the mfg web site.  The boards have what appears to be a date stamped on them "20130725" so this is around a 10 year old design.

![product-95166-1681826973-e-ss50](https://github.com/merbanan/rtl_433/assets/6903751/3ef6cef4-3606-44ab-87c4-32b63bd7b201)

I have not tried to capture anything yet.  I was hoping to find out if this is an already included product.  I did not see it in the list so assume not.  I can capture data but I'm not sure how to convert it.  Without the FCC filing, I'm assuming it's probably not something that can be accomplished?  It seems to use standard off the shelf daughter boards for the RX/TX so I was hoping it might be straight forward but I can't even locate those in the FCC database.

**Comment by zuckschwerdt** [comment]
The easiest way is too capture a sample and look at that. See https://triq.org/rtl_433/ANALYZE.html

**Comment by bkenobi** [comment]
Looks like a very well put together doc!  I already have a lot of devices transmitting so I'm not sure how easy it will be to isolate a signal. I may have to build an image on an old RPi and take it to a clean location unless there is an easy way to make a Faraday cage around the sdr and device.

**Comment by zuckschwerdt** [comment]
Isolating mostly seems to work well when unplugging any antenna an placing the sensor at maybe 30 cm to the receiver.

**Comment by bkenobi** [comment]
Ok worth a try. Also a lot easier than making a new image or constructing a faraday cage  for a simple test.

**Comment by bkenobi** [comment]
Some internal images for reference:

![20240102_160355](https://github.com/merbanan/rtl_433/assets/6903751/60345b6b-d29e-42bd-860f-f13c166c99d2)
![20240102_160303](https://github.com/merbanan/rtl_433/assets/6903751/33ee7c93-0a1f-43e2-ad7b-96da0aa1d21d)
![20240102_160325](https://github.com/merbanan/rtl_433/assets/6903751/feea1fab-0316-4504-bbba-925317f6c58d)

**Comment by bkenobi** [comment]
Manual
[Eva-Dry Sensor1.pdf](https://github.com/merbanan/rtl_433/files/13821901/Eva-Dry.Sensor1.pdf)

**Comment by gdt** [comment]
This seems like a request for a decoder with no actionable info.  I'll therefore close it in 7 days, unless there's restatement/progress or telling me I'm confused.

**Comment by bkenobi** [comment]
That's correct. I collected the info I had about hardware etc but didn't get a chance to collect any data. This can be closed. If I get a chance to post data at some point I will update.

**Comment by gdt** [comment]
Thanks for responding.   We can easily reopen this issue if you return with data someday.
