### ISSUE TITLE
Use fabsf() instead of abs() for floats or cast.

### ISSUE THREAD

**Issue by zuckschwerdt** [merbanan/rtl_433#278]
The recent switch from ints to floats is a problem with the use of `abs()` in rtl_433/src/pulse_demod.c.
Include the header <math.h> and use `fabsf()` or explicitly cast to ints.
I'd cast (truncate) to ints, there is no benefit in using a float here.

**Comment by merbanan** [comment]
Can you submit a patch for fabsf() ?

**Comment by zuckschwerdt** [comment]
Here you go: https://github.com/merbanan/rtl_433/pull/280
I'm not sure on the use of floats here, though. All the comparisons are to ints anyway.

**Comment by merbanan** [comment]
Ok Ill take a closer look later.

**Comment by merbanan** [comment]
Well I don't remember if I took a look or not. But 3ish years later I'd say that the patch was ok.
