### ISSUE TITLE
Build Instruction Using CMAKE, Appears to be Missing Sudo Cmd

### ISSUE THREAD

**Issue by rmschaller** [merbanan/rtl_433#2781]
On Line 82 of the build instructions page for rtl_433 project, the command as is, creates a permissions error and was fixed using "sudo make install" the existing line 82 is "make install"  Unless this issue is specific to my system, you might want to revisit line 82.

**Comment by gdt** [comment]
Strictly, you don't need elevated privs if installing to some prefix you own, and installing to system needing elevated privs is normal, but I agree a hint might be nice.

**Comment by zuckschwerdt** [comment]
We don't consider rtl_433 beginner friendly but a note has now been added.

**Comment by rmschaller** [comment]
Thanks!  I was able to get pass the issue I had rather quickly.  The note may be of help to others.
