### ISSUE TITLE
Bresser 6in1 does not deliver barometer values like hPa

### ISSUE THREAD

**Issue by hacp00** [merbanan/rtl_433#2794]
Hi,
according to the documentation of the Bresser 6in1 also a barometer (atmospheric air pressure) value should be there.
https://www.bresser.de/out/media/f667ed14a228a377c515422d80a8d81e.pdf
Please can you check this, I guess it might be the unknown one in the data map in the code maybe?
Thank you.

**Comment by zuckschwerdt** [comment]
S. e.g. #2485
Note that ambient pressure is always measured at the base station /head unit, it's by principle not an "outdoor" value.
