### ISSUE TITLE
Weird problem with rtl_433

### ISSUE THREAD

**Issue by carefulcomputer** [merbanan/rtl_433#2807]
I am using a Fitipower FC0012 tuner and trying to capture traffic from honeywell door sensors (protocol 70)
Here is my conf file
```
output kv:/rtlData/rtl_433.log
frequency     395M
convert     si
protocol 70
report_meta time:iso:usec:tz
report_meta level
report_meta noise
report_meta stats
report_meta protocol
pulse_detect autolevel
```

for weird reasons i see any data only when I add verbose mode ( -vvvv). Otherwise there is no output at all. What could I be doing wrong ?

on command line when I run this

`rtl_433 -vvvv -f345M -R70`

I see following data

`rtl_433 version 23.11 (2023-11-28) inputs file rtl_tcp RTL-SDR with TLS
[Protocols] Registered 1 out of 250 device decoding protocols
[Input] The internals of input handling changed, read about and report problems on PR #1978
Registering protocol [70] "Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater"
[SDR] Found 1 device(s)
[SDR] trying device 0: Realtek, RTL2838UHIDIR, SN: 00000001
Detached kernel driver
Found Fitipower FC0012 tuner
Exact sample rate is: 250000.000414 Hz
[SDR] Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
[SDR] Sample rate set to 250000 S/s.
[Input] Bit detection level set to 0.0 (Auto).
[SDR] Tuner gain set to Auto.
[Input] Reading samples in async mode...
[SDR] rtlsdr_set_center_freq 345000000 = 0
[SDR] Tuned to 345.000MHz.
[acquire_thread] acquire_thread enter...
Allocating 15 zero-copy buffers
Pulse data: 1 pulses
[  0] Pulse: 5377, Gap: 25001, Period: 30378
Pulse data: 1 pulses
[  0] Pulse: 5375, Gap: 25001, Period: 30376
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5375, Gap: 25001, Period: 30376
Pulse data: 1 pulses
[  0] Pulse: 5375, Gap: 25001, Period: 30376
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5340, Gap: 25001, Period: 30341
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
Pulse data: 1 pulses
[  0] Pulse: 5375, Gap: 25001, Period: 30376
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5375, Gap: 25001, Period: 30376
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5372, Gap: 25001, Period: 30373
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 11 pulses
[  0] Pulse: 5372, Gap: 23127, Period: 28499
[  1] Pulse: 5372, Gap: 23126, Period: 28498
[  2] Pulse: 5372, Gap: 23127, Period: 28499
[  3] Pulse: 5370, Gap: 23128, Period: 28498
[  4] Pulse: 5370, Gap: 16172, Period: 21542
[  5] Pulse: 5339, Gap: 23127, Period: 28466
[  6] Pulse: 5373, Gap: 23125, Period: 28498
[  7] Pulse: 5372, Gap: 23122, Period: 28494
[  8] Pulse: 5373, Gap: 23126, Period: 28499
[  9] Pulse: 5372, Gap: 23124, Period: 28496
[ 10] Pulse: 5371, Gap: 25001, Period: 30372
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5376, Gap: 25001, Period: 30377
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5374, Gap: 25001, Period: 30375
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5372, Gap: 25001, Period: 30373
Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit]Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
 Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5371, Gap: 25001, Period: 30372
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5372, Gap: 25001, Period: 30373
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5373, Gap: 25001, Period: 30374
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5371, Gap: 25001, Period: 30372
Pulse data: 1 pulses
[  0] Pulse: 5371, Gap: 25001, Period: 30372
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5343, Gap: 25001, Period: 30344`

with -A flag

`Detected OOK package	2024-01-29 05:42:33
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4
Pulse data: 1 pulses
[  0] Pulse: 5368, Gap: 25001, Period: 30369
Analyzing pulses...
Total count:    1,  width: 21.47 ms		( 5368 S)
Pulse width distribution:
 [ 0] count:    1,  width: 21472 us [21472;21472]	(5368 S)
Gap width distribution:
Pulse period distribution:
Pulse timing distribution:
 [ 0] count:    1,  width: 21472 us [21472;21472]	(5368 S)
 [ 1] count:    1,  width: 100004 us [100004;100004]	(25001 S)
Level estimates [high, low]:  15889,   1261
RSSI: -0.1 dB SNR: 11.0 dB Noise: -11.1 dB
Frequency offsets [F1, F2]:   14675,      0	(+56.0 kHz, +0.0 kHz)
Guessing modulation: Single pulse detected. Probably Frequency Shift Keying or just noise...
view at https://triq.org/pdv/#AAB10253E0FFFF8155

Detected OOK package	2024-01-29 05:42:34
Pulse data: 1 pulses
[  0] Pulse: 5370, Gap: 25001, Period: 30371
Analyzing pulses...
Total count:    1,  width: 21.48 ms		( 5370 S)
Pulse width distribution:
 [ 0] count:    1,  width: 21480 us [21480;21480]	(5370 S)
Gap width distribution:
Pulse period distribution:
Pulse timing distribution:
 [ 0] count:    1,  width: 21480 us [21480;21480]	(5370 S)
 [ 1] count:    1,  width: 100004 us [100004;100004]	(25001 S)
Level estimates [high, low]:  15914,   1235
RSSI: -0.1 dB SNR: 11.1 dB Noise: -11.2 dB
Frequency offsets [F1, F2]:   15029,      0	(+57.3 kHz, +0.0 kHz)
Guessing modulation: Single pulse detected. Probably Frequency Shift Keying or just noise...
view at https://triq.org/pdv/#AAB10253E8FFFF8155

[pulse_slicer_manchester_zerobit] Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater
codes     : {2}4`

**Comment by carefulcomputer** [comment]
closing this. found the issue. I had to set the sampling rate to 1024k. after that it worked fine.

**Comment by zuckschwerdt** [comment]
Interesting. We'd expect 250k to work (this protocol is OOK). Maybe try offsetting the center frequency a little, e.g. `-f 345.1M` or `-f 344.9M`

**Comment by carefulcomputer** [comment]
Here is full config which finally worked for me. will try offsetting the center frequency and report back (with default sample rate)

```
convert     si
sample_rate 1024k
frequency 345M
decoder n=honeywell_door_sensor2gig,m=OOK_MC_ZEROBIT,s=156,r=292
report_meta time:iso:usec:tz
report_meta protocol
pulse_detect autolevel
pulse_detect squelch
```

**Comment by carefulcomputer** [comment]
here is where the things are.  i don't see any decoded values on command line, however when i add -vvvv it seems to print all the packets but I don't see any decoded values.
here is my command line

`rtl_433  -F kv -Y auto -C si -vvvv`

and here is output (i know it is not 345mhz, this is just for testing). it doesn't show any nicely printed decoded output. when i remove -vvvv then it just sits with no values after initial startup messages. do i need some specific additional parameters to decode all the data it is seeing ? My assumption was if i don't specify any -R parameter, it will decode all values. 

```
pulse_slicer_pwm] EMOS E6016 rain gauge
codes     : {1}8
[pulse_slicer_pwm] Rubicson Pool Thermometer 48942
codes     : {1}8
[tpms_tyreguard400_callback] Bad message in row 0 need 88 bits got 1
codes     : {1}0
[tpms_tyreguard400_callback] Bad transmission
[pulse_slicer_manchester_zerobit] TyreGuard 400 TPMS
codes     : {1}0
[pulse_slicer_pcm] Neptune R900 flow meters
codes     : {12}800
[pulse_slicer_pwm] Govee Water Leak Detector H5054
codes     : {1}8
[pulse_slicer_pwm] Revolt NC-5642 Energy Meter
codes     : {1}0
[tpms_eezrv_decode] Preamble not found
[pulse_slicer_manchester_zerobit] EezTire E618, Carchet TPMS
codes     : {1}8

and so on..
```

**Comment by zuckschwerdt** [comment]
Yes, `rtl_433` without any options will run all decoders. It seems you have interference or problems with the RTL-SDR stick.
Capture the band an visually check it. https://triq.org/rtl_433/ANALYZE.html#verify-a-transmission
