### ISSUE TITLE
rtlsdr_read_reg failed with -7 after Ctrl+C in previous session

### ISSUE THREAD

**Issue by messageexplorer** [merbanan/rtl_433#2820]
I faced next issue. After pressing Ctrl+C in rtl_433 or rtl_tpc device stops working until I disconect it and connect again:

![image](https://github.com/merbanan/rtl_433/assets/84482830/e2613e4a-18cb-4097-9654-788cd0ca082b)

**Comment by merbanan** [comment]
Most likely there is an issue with the rtl-sdr libraries and the FC0012 tuner. This is then unrelated to rtl_433 and nothing we can do about.

**Comment by messageexplorer** [comment]
Ok, will try to disconnect tuner and reconnect back in this case. Thank you
