### ISSUE TITLE
[R82XX] PLL not locked!

### ISSUE THREAD

**Issue by evlo** [merbanan/rtl_433#2822]
I have bought some random rtl.sdr from ali, i tried sdrsharp and it found FM on it, now I wanted to try the thing I bought it for - reading data at 433, but I only get this error.

I tried quick searching on bing and google and found nothing that would help me.
I tried restarting PC I use for these test

I only tried on windows so far.

![image](https://github.com/merbanan/rtl_433/assets/8813196/ce7e883b-d273-458d-bf99-096c6182d910)

When I press the button I use for testing I get no data reading.

Can someone more experienced with SDR please help me? This is the first time I'm trying to use it.

SDRsharp does see some traffic on 433 and around - i think these might be data i'm interested in
![image](https://github.com/merbanan/rtl_433/assets/8813196/35c5b1fb-cc86-43bf-a1be-8906006a8ee7)

Again, total noob at this, maybe there is a way to at least see the digital/data traffic in other tools then rtl_433 to at least verify if I can read what I want :)

verbose does have some more output after `[R82XX] PLL not locked!`
![image](https://github.com/merbanan/rtl_433/assets/8813196/fba84507-b48b-49dd-988a-ba2a73775838)

Maybe this is expected behavior if no traffic is decoded (which i find currious)

Update: I added additional protocols and now on button press I do get detection so I guess my device is just not supported and probably dedicated esp32 with 433 antenna might be better
![image](https://github.com/merbanan/rtl_433/assets/8813196/28a6e351-3b20-45af-9e8c-7d93c8ec668d)

each pulse_slicer_pcm message is one button press

**Comment by zuckschwerdt** [comment]
Try using `-A` to view the raw contents of messages. The look at the `-X` suggestion to find parameters to read your device.
