### ISSUE TITLE
Terminal output ignores terminal capabilities (termcap).

### ISSUE THREAD

**Issue by dreirund** [merbanan/rtl_433#2824]
When I run `TERM=dump rtl_443 --help`, there should be no colouring at all, since dump terminals do not support this.

But there still is coloured output, see screenshot below.

Please consider making coloured output according to the terminal capabilities, preferably using the termcap library.

Regards!

---

![rtl_433--help_colouroutput](https://github.com/merbanan/rtl_433/assets/1590519/115dba9a-1536-426d-86f9-ce2f9b5b69a0)

---

**Comment by zuckschwerdt** [comment]
We won't link to external libs like e.g. termcap. If there is another way to cheaply accomplish this please advice. For now this is not a todo for us.

**Comment by dreirund** [comment]
> We won't link to external libs like e.g. termcap. If there is another
> way to cheaply accomplish this please advice. For now this is not a
> todo for us.

OK. But then this would break in some cases, e.g. also some serial
terminals.

Maybe you then add a command line option like `-nc | --no-colour`?

Regards!

**Comment by zuckschwerdt** [comment]
This should be addressed by 0443488 now. `RTL433_COLOR=always/never/auto`
Can you check if it works for you?
