### ISSUE TITLE
How to configure MQTT?

### ISSUE THREAD

**Issue by OZ1SEJ** [merbanan/rtl_433#2837]
According to the documentation, rtl_433 can publish data to MQTT,
"Assuming rtl_433 is started with
```rtl_433` -C si -M time:unix:usec:utc -F mqtt"```
However, is doesn't say anywhere how to configure MQTT server, username, password, topic, etc. How/where is this done?

**Comment by zuckschwerdt** [comment]
See `rtl_433 -F`
