### ISSUE TITLE
Input device start failed, exiting!

### ISSUE THREAD

**Issue by proyleg** [merbanan/rtl_433#2839]
Hi,

I have setup the addon on my Home assistant running under VmaWare workstation on Windows. When I assign the RTL2838UHIDIR device to the VM and start the addon, everything works perfectly fine. If I simply restart the addon, I always get this error:

Found Rafael Micro R820T/2 tuner
Exact sample rate is: 250000.000414 Hz
[SDR] Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
SDR: Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
Allocating 15 zero-copy buffers
Failed to allocate zero-copy buffer for transfer 1
Falling back to buffers in userspace
Allocating 15 (non-zero-copy) user-space buffers
[Input] Input device start failed, exiting!

The only way to make it work again, is to unplug/replug the device or reboot HA and the addon works.
Would it be a problem how the device is released? And cannot re-initialize it? 

I hope you can help

**Comment by merbanan** [comment]
This is a librtl-sdr issue. What might work is to do a usb reset. Try the rtl-sdr-reset tool.
