### ISSUE TITLE
Quhwa-Doorbell dosnt decode anymore

### ISSUE THREAD

**Issue by jab42** [merbanan/rtl_433#2868]
hi, i have some 1byone sensors that decoded fine until about mid 2023.
now there is no response anymore.
as topic it had rtl_433/9b13b3f4-rtl433/devices/Quhwa-Doorbell/56863/time
what can i do?

**Comment by gdt** [comment]
This is a question that lacks information that could be used to help.  You haven't said anything about software version, hardware, what evidence you have that the device works at all, what you've done already to debug this, or really anything else.   So it is unsurprising that there have been no comments.  (Plus, I personally think questions belong in discussions, and thus tend to avoid answering them in issues; others don't feel that way.)

I'll close >= 7 days absent useful information.
