### ISSUE TITLE
Triq

### ISSUE THREAD

**Issue by Pascal66** [merbanan/rtl_433#2875]
Is triq.org / triq.net down ?
Was very usefull

**Comment by zuckschwerdt** [comment]
It's not down but strictly filtered against abuse. There might be some overblocking.
Let me know your address prefix (IP with last number replaced by zero) or ASN (e.g. https://scamalytics.com/ to look up), by private e-mail if you like. I'll check that it's removed from the blocking.

In the long run we should perhaps move the content to some free CDN.

**Comment by zuckschwerdt** [comment]
There is/was no blocking on that range ever. Has to be something else then.
Does DNS resolve (`dig triq.org. a`)? Where is the route disrupted (`mtr triq.org`)?

**Comment by zuckschwerdt** [comment]
Thanks for following up. There was some blocking after all. It should be fixed now.
