### ISSUE TITLE
Identifying the correct usb rtl device

### ISSUE THREAD

**Issue by FosterSM** [merbanan/rtl_433#2878]
On my system I use two rtl usb devices one is used with another application one I use with rtl_433. The rtl_433 is embeded in a Qt application and my problem is that on boot up I do not know which device is which sometimes I need to start the rtl_433 with "-d 0" other times it requires "-d 1" the help info infers another way to identify the device but I do not understand how to make it work. I can collect device information via libusb but I don't know which (if any) of the information I could use. 

Any help would be appreciated.

**Comment by zuckschwerdt** [comment]
Use `rtl_eeprom` to give them unique serials, then use `rtl_433 -d :MYSERIAL`
