### ISSUE TITLE
Help in interpreting the signal from OBH Oven Thermometer

### ISSUE THREAD

**Issue by OleStauning** [merbanan/rtl_433#29]
I am trying to figure out how to read the temperature sent by my OBH oven thermometer (see http://www.obhnordica.se/Files/Filer/Userguides/4775.pdf). 

Could you please help me in interpreting the output (http://pastie.org/9098436) that I get when running the command "./rtl_433 -f 433892400 -a -l 3000"? -  the receiver says the temperature is constant; 24 degrees celcius. 

Your feedback is greatly appreciated.

**Comment by merbanan** [comment]
Long time no answer, can some one of you send the resulting files when running with rtl_433 -a -t ?

**Comment by merbanan** [comment]
Without any sample signals and matching temperatures nothing more can be done. Closing issue,
