### ISSUE TITLE
Dewenwils BH-V series AC outlet switches

### ISSUE THREAD

**Issue by waltje** [merbanan/rtl_433#2924]
Hello:

Looks like the BH-V series transmitters (I have 5-channel units, but they also exist in 1, 2 and 3-channel models)
are not supported yet.

These use a standard PT2260-series encoder, but with a twist: their oscillator is set to a very short period (4.7M ohm
reistors, I believe that ends up being 168usec or so?)

Debug output available.

**Comment by zuckschwerdt** [comment]
Can you grab a sample file and upload here as zip? https://triq.org/rtl_433/ANALYZE.html

**Comment by zuckschwerdt** [comment]
Looks good. The `rtl_433 -A` suggestions will work, e.g. use a flex decoder with
`-X 'n=name,m=OOK_PWM,s=150,l=500,g=800,r=6000,t=50,bits=25'`
for an output of `{25}eaaacc8` and `{25}eaaac38`

Write a documented conf file like these https://github.com/merbanan/rtl_433/tree/master/conf and PR if you like.

**Comment by waltje** [comment]
I will.
I also obtained a remote with a different code (mine is 0301, new one has 0304) just to verify my decoder.  I will PR it once that remote is in, and has been verified.
Fred

    On Friday, May 10, 2024 at 01:57:34 PM GMT-5, Christian W. Zuckschwerdt ***@***.***> wrote:  
 
 


Looks good. The rtl_433 -A suggestions will work, e.g. use a flex decoder with
-X 'n=name,m=OOK_PWM,s=150,l=500,g=800,r=6000,t=50,bits=25'
for an output of {25}eaaacc8 and {25}eaaac38

Write a documented conf file like these https://github.com/merbanan/rtl_433/tree/master/conf and PR if you like.

**Comment by waltje** [comment]
PR opened.
