### ISSUE TITLE
Document Support for Ambient Weather's TX-3110B Sensor

### ISSUE THREAD

**Issue by ewsandor** [merbanan/rtl_433#2927]
First of all, thank you for supporting this amazing project.

I would like to document support for Ambient Weather's TX-3110B sensor as it looks like this sensor is supported under the 'Bresser-6in1' protocol.

**Background:**
This sensor is sold as a replacement for Ambient Weather's Falcon WS-8480 weather station which looks to be the same as the Bresser 6-in-1 weather station but with different branding for the United States.  Documenting this support may help others discover and participate with this project.

**Behavior:**
Specifically, this sensor is detected as 'Sensor Type 2' and the temperature, humidity, channel values look correct (I have not yet performed any detailed comparison with another temperature/humidity sensor to see if any calibration is needed, but ballpark values look good).  The ID and CRC also look consistent.

**Other Notes:**
Briefly reviewing the rtl_433 implementation of the Bressor-6in1 sensor, I see reference a soil sensor and pool/spa sensor.  My base station (Ambient Weather's WS-8482)  is compatible with Ambient Weather's TX-3102 soil sensor and TX-3107 pool/spa sensor.  Assuming this is truly the same protocol, these two sensors are likely also supported, but I do not have access to either of these sensors to confirm.

**Screenshot of rtl_433 receiving my sensor:**
_For reference
CH 1 is indoors,
CH 2 is outdoors (Illinois evening in May),
CH 3 is in the refrigerator,
CH 4 is in the freezer,
CH 5 is in the basement_
![image](https://github.com/merbanan/rtl_433/assets/1273949/ace81e3c-c897-485e-a597-c7c65d99b3ec)

**Comment by zuckschwerdt** [comment]
We need to transfer a summary of this report to https://github.com/merbanan/rtl_433/blob/master/src/devices/bresser_6in1.c#L26
