### ISSUE TITLE
Suggest to add protocol number to output

### ISSUE THREAD

**Issue by OZ1SEJ** [merbanan/rtl_433#2974]
It's great that you can specify which protocols to allow or deny, but for some reason it isn't possible to see the protocol used for decoded messages. I would suggest that this info could be output, perhaps when using the `-vv` option.

**Comment by zuckschwerdt** [comment]
You might be looking for `-M protocol`

**Comment by OZ1SEJ** [comment]
:facepalm: Sorry. Thank you.
