### ISSUE TITLE
Support for Thermoworks RFX Meat Thermometers

### ISSUE THREAD

**Issue by victorhooi** [merbanan/rtl_433#3041]
Hi,

What do you guys think of this?

https://www.thermoworks.com/rfx-starter-kit/

Thermoworks - US company that specialises in cooking/BBQ thermometers, and other things (although I think they resell some UK company) - they have a new RFX range:

![image](https://github.com/user-attachments/assets/806e1e73-f2d0-4721-98af-cbdcebf5bdd0)

From the picture on their product page - seems to be 433 Mhz - would it be conceivable that something like this could be supported in rtl_433?

I could pickup some units to test.

Is it helpful to have both the probes and the gateway? Or would just the probe suffice?

**Comment by zuckschwerdt** [comment]
Yes, they say 433 MHz, should not be too hard to decode that signal. If you take a good range of readings then working out the fields in a transmission is likely to succeed even without a precise reference from a receiver/gateway.

E.g. grab a sample, work out the timings and coding. Then grab a range of codes while slowly heating or cooling -- the temperature field(s) should stand out. The range of -50 to 300°C suggest an offset of 50 with likely 12 bit (at 0.1 C resolution). Also a checksum should be visible with a range of codes of 0.1 C changes.
Then run down the battery and look for that field (or just a battery-low bit).
