### ISSUE TITLE
Eeztire / Continental TPMS not decoding with test repo file

### ISSUE THREAD

**Issue by Crsarmv7l** [merbanan/rtl_433#3054]
I wanted to look into Continental TPMS a bit and noticed it wasn't listed in the devices, a little further digging took me to this issue https://github.com/merbanan/rtl_433/issues/2920 which clued me in that it is Eeztire.

I grabbed this file from the test repo: https://github.com/merbanan/rtl_433_tests/blob/master/tests/continental_tpms/01/g001_433.92M_250k.cu8 

Ran it through rtl_433 ( with rtl_433 g001_433.92M_250k.cu8 )and...nothing:
![image](https://github.com/user-attachments/assets/44d65a15-6101-48b7-9963-903297ba5fc7)

I realize my build is a bit outdated (but built after initial support for the decoder was added Feb 2023), so I built and installed a new version just now. Still nothing.
![image](https://github.com/user-attachments/assets/95f1a78c-0471-4261-800c-c94e5ec85adf)

I thought maybe the decoder was disabled by default, but it isn't. 

Just to verify the issue is with that decoder, I ran another tpms file from the test repo through and it decode fine:
![image](https://github.com/user-attachments/assets/98d01781-67d9-431e-9f0f-2faf86506837)

**Comment by zuckschwerdt** [comment]
You need to force the `-Y minmax` discriminator. It's a default for 868M and above and recommended for FSK.

**Comment by Crsarmv7l** [comment]
> You need to force the `-Y minmax` discriminator. It's a default for 868M and above and recommended for FSK.

Ah thanks. Seems to work. Interesting that Continental is BMW?

![image](https://github.com/user-attachments/assets/583a64cc-ce92-4c65-93a9-2b1daf2cb321)

**Comment by ProfBoc75** [comment]
@Crsarmv7l : Yes, depends on the brand id:

- 0x00 = Audi Pressure Alert,
- 0x03 = HUF Gen 5/Beru, 
- 0x23 = 35 = Schrader/Sensata, 
- 0x80 = 128 = Continental, 
- 0x88 = 136 = Audi

**Comment by Crsarmv7l** [comment]
> @Crsarmv7l : Yes, depends on the brand id:
> 
> * 0x00 = Audi Pressure Alert,
> * 0x03 = HUF Gen 5/Beru,
> * 0x23 = 35 = Schrader/Sensata,
> * 0x80 = 128 = Continental,
> * 0x88 = 136 = Audi

Gotcha. Is the short/long width really 25? That seems really fast for TPMS, most of the others I have played with and created synthetics for are 9600 baud -  ~20400 (elantra 2012 with short/long width 49 and before now the fastest I have seen)
