### ISSUE TITLE
How to install SoapyDriver for HackRF?

### ISSUE THREAD

**Issue by nico0481** [merbanan/rtl_433#3070]
I try to use rtl_433 with hackRF but i get a error:

rtl_433 -d ""
rtl_433 version 23.11-163-ge25cfc0f branch master at 202409200913 inputs file rtl_tcp RTL-SDR with TLS
[sdr_open] No input driver for SoapySDR compiled in.

Although Hack RF well detected with SoapySDRUtil --find

how to add soapy driver to already installed package?

**Comment by zuckschwerdt** [comment]
You need to compile and install rtl_433 again. Use at least `-DENABLE_SOAPYSDR=ON`, see https://triq.org/rtl_433/BUILDING.html
If all went well then the "rtl_433 version" line will list SoapySDR.

**Comment by nico0481** [comment]
I saw https://triq.org/rtl_433/BUILDING.html, but rtl_433 is part of Kali, I didn't install it myself, neither build. I don't find where it was compiled.

**Comment by zuckschwerdt** [comment]
You might be able to just use one of our binary releases. https://github.com/merbanan/rtl_433/releases
Try if either OpenSSL 1.1 or 3 works.
