### ISSUE TITLE
Memory not freed?

### ISSUE THREAD

**Issue by ygator** [merbanan/rtl_433#309]
I might be missing something, but shouldn't data.c: data_free also do a free(data->format)?
Also in rtl_433.c shouldn't a free(d->key) be done before the new assignment of d->key with a strdup?

**Comment by zuckschwerdt** [comment]
I'd say you are spot on. `data_make` always assigns `key` and `format` with strdup.

**Comment by ygator** [comment]
Okay, I'll fix it and issue a pull request.

**Comment by merbanan** [comment]
Confirmed, and patch merged.
