### ISSUE TITLE
RTL_433 no loger work since new Homeassistant-Core "core_2024.10.4"

### ISSUE THREAD

**Issue by zillawilli** [merbanan/rtl_433#3094]
Hello everyone
I also have the problem with my weather station as described in [#3090](https://github.com/merbanan/rtl_433/issues/3090).
With Homeassistant-Core "core_2024.9.0" the add-ons "rtl_433 Home Assistant Add-on 0.5.2" and "rtl_433 MQTT Auto Discovery Home Assistant Add-on 0.8.2" still work perfectly.
Only after an update to HA-Core "core_2024.10.4" or "core_2024.11.0" does rtl_433 unfortunately no longer work.

The following messages appear in the LOG file:
![rtl_433 Bild 01](https://github.com/user-attachments/assets/a58f1db4-91a5-4420-9634-5bc243dd59f7)
![rtl_433 Bild 02](https://github.com/user-attachments/assets/a55ff92a-9146-4a53-8de7-b7e50b63b9db)

Could you please take a look at this?
I believe that several more people have this problem

Thank you very much

**Comment by zuckschwerdt** [comment]
At least for the second error you just need an rtl_433 config of `-M time:iso:tz` or if you like -M 'time:iso:utc:tz'
For the first one you might need to discard old autoconfigs in HA.
