### ISSUE TITLE
Error 5 password with special characters

### ISSUE THREAD

**Issue by ArtCodesArt** [merbanan/rtl_433#3108]
When I try to connect to MQTT I get the following error

`rtl_433 -C si -F "mqtt://192.168.1.2:1883,user=mqtt,pass=complex$%^&!@" ` < example of complex passphrase.
```
...
MQTT Connected...
MQTT Connection error: 5
MQTT Connection failed...
```

I think it's related to my password having special characters such as @ # ! $ Without re-doing the password to only use a-Z and 0-9 is there way to pass a complex password to

**Comment by zuckschwerdt** [comment]
The parser will interpret some special characters, e.g. comma, but you can pass arbitrary passwords with the `MQTT_PASSWORD` environment var (and also `MQTT_USERNAME`).
