### ISSUE TITLE
Tag head for release please?

### ISSUE THREAD

**Issue by labeneator** [merbanan/rtl_433#324]
I am writing a recipe for OSX homebrew. The project requires a tagged release for acceptance. Can you please tag 922a76a81820c68e2e5c55a428e5d22135a8be9a for release?  

Please see https://github.com/Homebrew/homebrew/pull/49793

**Comment by labeneator** [comment]
bump

**Comment by merbanan** [comment]
tag 0.01 pushed

**Comment by labeneator** [comment]
Thank you!
