### ISSUE TITLE
Need help to decode 868.4MHz nRF905 transmitter 

### ISSUE THREAD

**Issue by fritzmeier** [merbanan/rtl_433#33]
Hi,
I'm trying to decode frames of the above transmitter by recording about 15 seconds frames of 2 transmitters near by the rtl-dongle via rtl_fm. Every frame is Manchester encoded and has 10 bit preamble(unknown), 24 bit address, 192 bit payload and 16 bit CRC. How i have to create a new protocol, or what i have to to do to get this frames decoded. When i run rtl_433 (see below) i get some results and the final result of 38 detected packets is looking good.
Please have a look to the results of rtl_433.
Thanks for all
Fritz

BBb:root@~/rtl_433/build/src# ./rtl_433  -a -t  -m 0 -r 2xflarm 
output:
Registering protocol[01] Rubicson Temperature Sensor
Registering protocol[02] Prologue Temperature Sensor
Registering protocol[03] Silvercrest Remote Control
Registering protocol[04] ELV EM 1000
Registering protocol[05] ELV WS 2000
Registering protocol[06] Waveman Switch Transmitter
Registering protocol[07] Steffen Switch Transmitter
No supported devices found.
Found 0 device(s):

Using device 0: 
Failed to open rtlsdr device #0.
WARNING: Failed to set sample rate.
Sample rate decimation set to 0. 250000->250000
Bit detection level set to 10000.
WARNING: Failed to enable automatic gain.
Test mode active. Reading samples from file: 2xflarm
**\* signal_start = 25270, signal_end = 104342
signal_len = 79072,  pulses = 35
Iteration 1. t: 28    min: 12 (19)    max: 44 (16)    delta 277
Iteration 2. t: 28    min: 12 (19)    max: 44 (16)    delta 0
Pulse coding: Short pulse length 12 - Long pulse length 44

Short distance: 190, long distance: 21319, packet distance: 30703

p_limit: 28

[00] {9} 30 00 : 00110000 00000000 
[01] {26} b8 5b e3 00 : 10111000 01011011 11100011 00000000 

signal_bszie = 262144  -      sg_index = 393216
start_pos    = -53462  -   buffer_size = 3145728
restart_pos = 3092266
**\* Saving signal to file gfile001.data
**\* Writing data from 3092266, len 53462
**\* Writing data from 0, len 208682
**\* signal_start = 150757, signal_end = 227118
signal_len = 76361,  pulses = 29
Iteration 1. t: 30    min: 12 (6)    max: 48 (23)    delta 325
Iteration 2. t: 30    min: 12 (6)    max: 48 (23)    delta 0
Pulse coding: Short pulse length 12 - Long pulse length 48

Short distance: 38, long distance: 14392, packet distance: 25445

p_limit: 30

[00] {21} fe fe 38 : 11111110 11111110 00111000 
[01] {8} 77 00 : 01110111 00000000 

signal_bszie = 262144  -      sg_index = 655360
start_pos    = 192090  -   buffer_size = 3145728
**\* Saving signal to file gfile002.data
**\* Writing data from 192090, len 262144
**\* signal_start = 264904, signal_end = 316123
signal_len = 51219,  pulses = 28
Iteration 1. t: 29    min: 13 (9)    max: 45 (19)    delta 317
Iteration 2. t: 29    min: 13 (9)    max: 45 (19)    delta 0
Pulse coding: Short pulse length 13 - Long pulse length 45

Short distance: 46, long distance: 3156, packet distance: 22799

p_limit: 29

[00] {14} 1f fc : 00011111 11111100 
[01] {14} e6 e0 : 11100110 11100000 

signal_bszie = 131072  -      sg_index = 786432
start_pos    = 501172  -   buffer_size = 3145728
**\* Saving signal to file gfile003.data
**\* Writing data from 501172, len 131072
**\* signal_start = 378257, signal_end = 450554
signal_len = 72297,  pulses = 28
Iteration 1. t: 28    min: 10 (3)    max: 47 (25)    delta 218
Iteration 2. t: 28    min: 10 (3)    max: 47 (25)    delta 0
Pulse coding: Short pulse length 10 - Long pulse length 47

Short distance: 99, long distance: 11141, packet distance: 37554

p_limit: 28

[00] {13} 7f f8 : 01111111 11111000 
[01] {15} fb f6 : 11111011 11110110 

signal_bszie = 262144  -      sg_index = 1048576
start_pos    = 638962  -   buffer_size = 3145728
**\* Saving signal to file gfile004.data
**\* Writing data from 638962, len 262144
**\* signal_start = 490492, signal_end = 900535
signal_len = 410043,  pulses = 107
Iteration 1. t: 31    min: 15 (25)    max: 48 (82)    delta 394
Iteration 2. t: 31    min: 15 (24)    max: 48 (83)    delta 0
Pulse coding: Short pulse length 15 - Long pulse length 48

Short distance: 146, long distance: 20876, packet distance: 45209

p_limit: 31

[00] {27} 3b fc ef 00 : 00111011 11111100 11101111 00000000 
[01] {13} ef 98 : 11101111 10011000 
[02] {14} b3 74 : 10110011 01110100 
[03] {27} ff d8 3f e0 : 11111111 11011000 00111111 11100000 
[04] {12} ff f0 : 11111111 11110000 
[05] {14} fb fc : 11111011 11111100 

signal_bszie = 917504  -      sg_index = 1966080
start_pos    = 883564  -   buffer_size = 3145728
**\* Saving signal to file gfile005.data
**\* Writing data from 883564, len 917504
**\* signal_start = 940261, signal_end = 1099902
signal_len = 159641,  pulses = 52
Iteration 1. t: 32    min: 17 (10)    max: 47 (42)    delta 452
Iteration 2. t: 32    min: 17 (10)    max: 47 (42)    delta 0
Pulse coding: Short pulse length 17 - Long pulse length 47

Short distance: 246, long distance: 19864, packet distance: 47140

p_limit: 32

[00] {27} 37 f5 fe e0 : 00110111 11110101 11111110 11100000 
[01] {25} e6 ff fd 80 : 11100110 11111111 11111101 10000000 

signal_bszie = 393216  -      sg_index = 2359296
start_pos    = 1806586  -   buffer_size = 3145728
**\* Saving signal to file gfile006.data
**\* Writing data from 1806586, len 393216
**\* signal_start = 1179598, signal_end = 1448913
signal_len = 269315,  pulses = 87
Iteration 1. t: 29    min: 11 (18)    max: 48 (69)    delta 353
Iteration 2. t: 29    min: 11 (18)    max: 48 (69)    delta 0
Pulse coding: Short pulse length 11 - Long pulse length 48

Short distance: 194, long distance: 16665, packet distance: 36169

p_limit: 29

[00] {14} 77 38 : 01110111 00111000 
[01] {16} ef db 00 : 11101111 11011011 00000000 
[02] {15} 3b fc : 00111011 11111100 
[03] {14} fd f4 : 11111101 11110100 
[04] {15} f7 7a : 11110111 01111010 
[05] {13} f7 f8 : 11110111 11111000 

signal_bszie = 655360  -      sg_index = 3014656
start_pos    = 2242464  -   buffer_size = 3145728
**\* Saving signal to file gfile007.data
**\* Writing data from 2242464, len 655360
**\* signal_start = 1499288, signal_end = 1547814
signal_len = 48526,  pulses = 26
Iteration 1. t: 32    min: 19 (7)    max: 46 (19)    delta 452
Iteration 2. t: 32    min: 19 (7)    max: 46 (19)    delta 0
Pulse coding: Short pulse length 19 - Long pulse length 46

Short distance: 70, long distance: 7297, packet distance: 18581

p_limit: 32

[00] {13} 36 f0 : 00110110 11110000 
[01] {13} ff c8 : 11111111 11001000 

signal_bszie = 131072  -      sg_index = 131072
start_pos    = -181174  -   buffer_size = 3145728
restart_pos = 2964554
**\* Saving signal to file gfile008.data
**\* Writing data from 2964554, len 131072
**\* signal_start = 1613040, signal_end = 1794649
signal_len = 181609,  pulses = 52
Iteration 1. t: 30    min: 13 (11)    max: 48 (41)    delta 317
Iteration 2. t: 29    min: 11 (10)    max: 47 (42)    delta 5
Iteration 3. t: 26    min: 7 (8)    max: 46 (44)    delta 17
Iteration 4. t: 26    min: 7 (8)    max: 46 (44)    delta 0
Pulse coding: Short pulse length 7 - Long pulse length 46

Short distance: 277, long distance: 20108, packet distance: 43198

p_limit: 26

[00] {14} fe 5c : 11111110 01011100 
[01] {13} f1 f8 : 11110001 11111000 
[02] {25} fa ff ff 80 : 11111010 11111111 11111111 10000000 

signal_bszie = 393216  -      sg_index = 524288
start_pos    = 50352  -   buffer_size = 3145728
**\* Saving signal to file gfile009.data
**\* Writing data from 50352, len 393216
**\* signal_start = 1852528, signal_end = 1917329
signal_len = 64801,  pulses = 28
Iteration 1. t: 29    min: 11 (7)    max: 48 (21)    delta 146
Iteration 2. t: 29    min: 11 (7)    max: 48 (21)    delta 0
Pulse coding: Short pulse length 11 - Long pulse length 48

Short distance: 40, long distance: 2500, packet distance: 37743

p_limit: 29

[00] {13} f7 f8 : 11110111 11111000 
[01] {15} 23 be : 00100011 10111110 

signal_bszie = 131072  -      sg_index = 786432
start_pos    = 557856  -   buffer_size = 3145728
**\* Saving signal to file gfile010.data
**\* Writing data from 557856, len 131072
Iteration 1. t: 31    min: 14 (32)    max: 48 (110)    delta 377
Iteration 2. t: 30    min: 14 (31)    max: 47 (111)    delta 1
Iteration 3. t: 30    min: 13 (30)    max: 47 (112)    delta 1
Iteration 4. t: 30    min: 13 (30)    max: 47 (112)    delta 0
Pulse coding: Short pulse length 13 - Long pulse length 47

Short distance: 174, long distance: 24823, packet distance: 40667

p_limit: 30

[00] {32} 7e b8 ff d7 00 : 01111110 10111000 11111111 11010111 00000000 
[01] {27} f3 3f 7e e0 : 11110011 00111111 01111110 11100000 
[02] {6} fc : 11111100 
[03] {19} ff ef e0 : 11111111 11101111 11100000 
[04] {30} b6 7d 37 fc : 10110110 01111101 00110111 11111100 
[05] {15} e7 be : 11100111 10111110 
[06] {13} 2f e8 : 00101111 11101000 

Test mode file issued 38 packets
Filter coeffs used:
a: 32768 31754
b: 506 506
BBb:root@~/rtl_433/build/src#

**Comment by mcauser** [comment]
You can attach any files, if you .zip them

**Comment by merbanan** [comment]
Without any sample signals there is nothing we can do further.

**Comment by eelcohn** [comment]
I realize that this is a very old topic, but I've figured out a way to decode nRF905 signals, and I'd like to report this here as a reference for others:
```
./rtl_433 -f 868400000 -g 50 -X n=nrf905,m=FSK_MC_ZEROBIT,s=10,r=100,preamble={10}fd4,invert
```
