### ISSUE TITLE
AlectoV1 protocol not working anymore

### ISSUE THREAD

**Issue by xes** [merbanan/rtl_433#344]
After a few months i have tried to build an updated version of rtl_433 but it seems that recent versions can't decode anymore the Alecto v1 samples from:
https://github.com/merbanan/rtl_433_tests/tree/master/tests/alectov1

and the Auriol H13726A samples (use -l 2000) from:  
https://github.com/merbanan/rtl_433_tests/tree/master/tests/auriol/04

The last build that seems to be working right is "ab4bfd15e230291a845c85cac1bbf6b3297c03ab" of 20151124  

Tests:
./rtl_433.20151124 -R 16 -r ./alecto_gfile001.data
---> 2016-03-24 16:50:22 AlectoV1 Wind Sensor 44: Wind speed 5 units = 1.00 m/s: Wind gust 8 units = 1.60 m/s: Direction 135 degrees: Battery OK

./rtl_433.20151124 -l 2000 -R 16 -r ./gfile001_H13726A_Silvercrest_Weather_2008-Auriol_2011-Wind-event_0.2S_0.6G_315DEG.data 
---> 2016-03-24 16:47:37 AlectoV1 Wind Sensor 106: Wind speed 1 units = 0.20 m/s: Wind gust 3 units = 0.60 m/s: Direction 315 degrees: Battery OK

./rtl_433.20151124 -l 2000 -R 16 -r ./gfile002_H13726A_Silvercrest_Weather_2008-Auriol_2011-Temp-event_33.2C_44H.data 
---> 2016-03-24 16:49:28 AlectoV1 Sensor 106 Channel 1: Temperature 33.2 C: Humidity 44 %: Battery OK

**Comment by merbanan** [comment]
It works for me.

rtl_433 -r ../../rtl_433_tests/tests/alectov1/gfile001.data

Test mode active. Reading samples from file: ../../rtl_433_tests/tests/alectov1/gfile001.data
Input format: uint8
@1.572864s :	AlectoV1 Wind Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Wind speed:	 1.00 m/s
	Wind gust:	 1.60 m/s
	Direction:	 135
Test mode file issued 4 packets


src/rtl_433 -l 0 -r ../../rtl_433_tests/tests/auriol/04/gfile001_H13726A_Silvercrest_Weather_2008-Auriol_2011-Wind-event_0.2S_0.6G_315DEG.data

Test mode active. Reading samples from file: ../../rtl_433_tests/tests/auriol/04/gfile001_H13726A_Silvercrest_Weather_2008-Auriol_2011-Wind-event_0.2S_0.6G_315DEG.data
Input format: uint8
@1.572864s :	Prologue sensor 	:	5 	:	102
	Channel:	 1
	Battery:	 OK
	Button:	 0
	Temperature:	 0.80 C
	Humidity:	 14 %
@1.572864s :	AlectoV1 Wind Sensor
	House Code:	 106
	Channel:	 1
	Battery:	 OK
	Wind speed:	 0.20 m/s
	Wind gust:	 0.60 m/s
	Direction:	 315
Test mode file issued 4 packets


src/rtl_433 -l 0 -r ../../rtl_433_tests/tests/auriol/04/gfile002_H13726A_Silvercrest_Weather_2008-Auriol_2011-Temp-event_33.2C_44H.data

Test mode active. Reading samples from file: ../../rtl_433_tests/tests/auriol/04/gfile002_H13726A_Silvercrest_Weather_2008-Auriol_2011-Temp-event_33.2C_44H.data
Input format: uint8
@1.572864s :	Prologue sensor 	:	5 	:	100
	Channel:	 4
	Battery:	 LOW
	Button:	 0
	Temperature:	 64.20 C
	Humidity:	 34 %
@1.572864s :	AlectoV1 Temperature Sensor
	House Code:	 106
	Channel:	 1
	Battery:	 OK
	Temperature:	 33.20 C
	Humidity:	 44 %
Test mode file issued 4 packets
