### ISSUE TITLE
Add support for Auriol

### ISSUE THREAD

**Issue by marki555** [merbanan/rtl_433#35]
Hello,
Can you please add support for Auriol weather station? Or guide me how to do it? Here is the protocol spec: http://www.tfd.hu/tfdhu/files/wsprotocol/auriol_protocol_v20.pdf
And here is output of rtl_433 -a -D: http://pastebin.com/DRJs3mFV

**Comment by merbanan** [comment]
The referenced gfile015.data gave this with current code.

@0.524288s :	AlectoV1 Rain Sensor
	House Code:	 132
	Channel:	 0
	Battery:	 OK
	Total Rain:	 0.25 mm
	Integrity:	 CHECKSUM

**Comment by merbanan** [comment]
And the linked gfile001-002 does also work. It seems this is implemented. Closing issue.
