### ISSUE TITLE
Mistake in company name "Brennstuhl"

### ISSUE THREAD

**Issue by Atalanttore** [merbanan/rtl_433#369]
Hi,

there are several mistakes in the protocol decoder library '[brennstuhl_rcs_2044.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/brennstuhl_rcs_2044.c)' concerning variable names, strings and comments.

The correct name of the company is _Brenn**en**stuhl_ and not Brennstuhl. See [webpage for Remote Control Set RCS 2044 N Comfort](http://www.brennenstuhl.de/en-DE/multi-way-extensions-und-plug-in-appliances/remote-control-set/remote-control-set-rcs-2044-n-comfort-1.html).

Regards,
Ettore

**Comment by merbanan** [comment]
Patch welcome.

**Comment by ludwich66** [comment]
it is closed
