### ISSUE TITLE
What do do with "OOK_PWM_D"? 

### ISSUE THREAD

**Issue by khkremer** [merbanan/rtl_433#377]
I have old code that was able to receive data from an Acurite 00606TX temperature sensor. However, my code uses the OOK_PWM_D demodulator. How can I port this to the current version of rt._433? Is there a comparable demodulator that I can just swap in, or do I have to go back to square one to figure out what the data is like? I used to use this device configuration: 

```
r_device acurite606TX = {
    /* .id             = */ 10,
    /* .name           = */ "Acurite 606TX",
    /* .modulation     = */ OOK_PWM_D,
    /* .short_limit    = */ 875,
    /* .long_limit     = */ 1750,
    /* .reset_limit    = */ 3750,
    /* .json_callback  = */ &acurite_606TX_callback,
    /* .json_callback  = */ // &debug_callback,
    /* .disabled       = */ 0,
};
```

Thanks.

**Comment by merbanan** [comment]
Answer on mailing list.
