### ISSUE TITLE
Group bit not used for Proove

### ISSUE THREAD

**Issue by gnbl** [merbanan/rtl_433#388]
I tested a "Telecontrol Plus" remote by "REV Ritter GmbH" (Germany) , model number "008341C-1". It has 4x2 buttons, columns labelled "1,2,3,G", rows labelled  "on/off". It looks identical to the ones depicted on http://tech.jolowe.se/home-automation-rf-protocol-update/ , where they are called "Proove from 'Kjell & Company', Anslut from 'Jula',". The device sends 6 packets. The G button transmits the same as the 1 button but has the group bit set. This is not output by rtl_433, although the bits are identified in the decoder header
  https://github.com/merbanan/rtl_433/blob/master/src/devices/proove.c#L11
and are also extracted
  https://github.com/merbanan/rtl_433/blob/master/src/devices/proove.c#L54

I guess it just needs to make it into data
https://github.com/merbanan/rtl_433/blob/master/src/devices/proove.c#L62
and *output_fields[]
https://github.com/merbanan/rtl_433/blob/master/src/devices/proove.c#L75

I forked but setting up toolchain and dependencies is too involved for me right now.
Here's a start: 
[proove.zip](https://github.com/merbanan/rtl_433/files/299268/proove.zip)

I used the 64 bit build from 
http://cognito.me.uk/computers/rtl_433-windows-binary-32-bit/
http://cognito.me.uk/uploads/rtl433/rtl433_win64_13042016.zip

Thanks for your efforts!

PS:
The above-mentioned page on jolowe.se also mentions a remote called "Nexa" with identical protocol (button/device and channel bits inverted) which sends 5 packets. This seems identical to my "Intertechno ITLS-16" (OEM model # "ITAPT-821") which I use with "Intertechno ITDM-250" dimmer module which is an "ARC Technology" product with model # "WMR-250" (product page: http://www.arctech.com.tw/index.php/product/detail/155).
Maybe this information can be added as aliases to the "Proove" device name..

**Comment by merbanan** [comment]
Changes added to the code. Untested but looked trivial.

**Comment by gnbl** [comment]
I'm not sure that I even have these anymore. If I should find them, I shall remember this and test... :-)
