### ISSUE TITLE
Rubicson/Auriol protocol decoder - invalid decoding of Auriol 2013 temp/humidity sensor

### ISSUE THREAD

**Issue by pm-cz** [merbanan/rtl_433#39]
Hello, 
I am trying to make Auriol sensor (temperature & humidity, revision 2013, probably similar to proposed Nexus protocol) work and I have encountered a problem with Rubicson/Auriol protocol decoder which provides invalid outputs.

In newer Auriol sensors, the first packet (packet 0) is empty. Because of that, the decoder provides invalid temperature data, e.g.

Sensor temperature event:
protocol       = Rubicson/Auriol
rid            = 0
temp           = 0.0
51 00 00 00 00

If I use a patched version when taking data from the 1st packet instead, the result is correct, but this could break compatibility with the original sensor (which I don't have and can't test):

Sensor temperature event:
protocol = Rubicson/Auriol
rid = **51**
temp = **30.5**
51 **01 31 f3 40**

I have decoded the frame format so I plan to write a separate decoder anyway (or extend the Nexus One), but to prevent the invalid detections, maybe you could include following line in the Rubicson/Auriol detection condition:

``` c
       (bb[0][1] != 0 || bb[0][2] != 0 || bb[0][3] != 0 || bb[0][4] != 0) &&
```

**Comment by merbanan** [comment]
Retry with the new code and see if it works better. If not sample signals are needed to be able to debug the issue.
