### ISSUE TITLE
Honeywell Door Chime

### ISSUE THREAD

**Issue by kuroyi** [merbanan/rtl_433#40]
Hi,

I recently bought a Honeywell RCWL300A1006 and hope to receive the signal and play a custom chime from my computer speakers when the button is pressed. I discovered that it uses 916.8Mhz and was able to capture the signal using rtl_433 but it was not able to decode anything. I suspect that maybe the device is using FSK to encode the signal...
http://yourhome.honeywell.com/home/Products/Door+Chimes/Wireless+Doorbell+Push+Buttons/RPWL300A.htm

**\* signal_start = 1421354, signal_end = 1743672
signal_len = 322318,  pulses = 1
Distance coding: Pulse length 302317

Short distance: 1000000, long distance: 0, packet distance: 0

p_limit: 302317

[00] {0} 00 : 00000000 

signal_bszie = 655360  -      sg_index = 524288
start_pos    = -313746  -   buffer_size = 3145728
restart_pos = 2831982

**Comment by klohner** [comment]
I'm able to detect the signal from my [Honeywell RPWL400W2000/a Series 3, 5, 9 Wireless Doorbell Push Button with Halo Light](https://amzn.com/B01LXKH0ED) (which also operates on 916.8MHz) using this command:

`rtl_433 -f 916800000 -q -X "Honeywell Doorbell:FSK_PCM:160:160:340,bits=149,match={4}0xe"`

I suspect it uses the same encoding as the doorbell you have.

See this thread on rtl-sdr.com for more info:  [Help identifying wireless doorbell signal](https://www.rtl-sdr.com/forum/viewtopic.php?f=8&t=1138&p=6010)

--Karl.

**Comment by merbanan** [comment]
@zuckschwerdt Can you figure out a flex definition for this? I can't get it to work with the current tree.

**Comment by zuckschwerdt** [comment]
Looks like FSK PWM, mostly. But the signal is somewhat distorted. Would be best to record this again with `-s 1024k`.

**Comment by klohner** [comment]
I've done some further work to reverse this signal.  Please see my notes at https://github.com/klohner/honeywell-wireless-doorbell

**Comment by merbanan** [comment]
@klohner can you submit a set of signals sampled at 1024k (-s 1024k) to the tests repository? This device might need its own decoder.

**Comment by merbanan** [comment]
#898 adds support for this and issue #652 also is about the Honeywell device. Closing this issue.

**Comment by merbanan** [comment]
The sample signal in this ticket overloads the receiver.

**Comment by peteakalad** [comment]
For UK version of this door bell works on 868Mhz based frequency.  For mine rtl_433 is succesfully working on freq 868221000
