### ISSUE TITLE
Honda Remote info

### ISSUE THREAD

**Issue by planetclegg** [merbanan/rtl_433#413]
Just noticed "Honda Remote" was added, any info on which Honda models/remotes work?     my 1999 honda remote doesn't appear to be recognized (although I can see what looks like raw data in -a mode)

**Comment by merbanan** [comment]
Ask the author on the mailing list. I have no further info. You could add your own remote if you send sample signals.

**Comment by ukshady** [comment]
It's for a 2004 Honda Accord, but if you record some samples and upload to rtl_433_tests I could see if could be modified.
On 10 Aug 2016 5:09 p.m., planetclegg <notifications@github.com> wrote:Just noticed "Honda Remote" was added, any info on which Honda models/remotes work?     my 1999 honda remote doesn't appear to be recognized (although I can see what looks like raw data in -a mode)

**Comment by planetclegg** [comment]
I'll look into it, if I figure out how recording works, I may give a try at decoding it myself.   I already have a small pull request for a different sensor, we'll see how it goes.   It occurs to me the format may change every few model years, may get tricky to lump all of them into one 'device'
