### ISSUE TITLE
esperanza_ews add support for variant. 

### ISSUE THREAD

**Issue by mpmc** [merbanan/rtl_433#415]
I have a variant of the Esperanza sensor but the code for it gives incorrect values, there is a fix on the google groups here: https://groups.google.com/d/msg/rtl_433/fiHwkXP-uEE/ukjuAA_IEgAJ that gives the correct values, but it no longer works as there has been some major changes to the code.

Could this be implemented please? I did try myself but I'm no C coder :p

Thanks.

**Comment by merbanan** [comment]
Sample signals are missing to test an eventual implementation. Closing issue.
