### ISSUE TITLE
CRC

### ISSUE THREAD

**Issue by merbanan** [merbanan/rtl_433#416]
Add CRC = OK for decoders that support crc.

**Comment by enavarro222** [comment]
Did you mean as a "CRC" output field or within device configuration struct ?

**Comment by merbanan** [comment]
In the json output. Consumers should be able to trust crc enabled devices more then devices without crc.

**Comment by rct** [comment]
If devices drop messages that don't have a valid CRC, what purpose would this serve?

**Comment by merbanan** [comment]
Data consumers can add trust to the messages. For example a temperature sensor that transmits a crc has equal trust as one without crc if we don't add a crc tag. The idea is to extract as much useful information as possible from the message.

**Comment by merbanan** [comment]
This is pretty much implemented. We have the mic field.
