### ISSUE TITLE
autoreconf fails - "possibly undefined macro: AC_PROG_LIBTOOL"

### ISSUE THREAD

**Issue by bigpresh** [merbanan/rtl_433#417]
Following the install instructions fails:

```
[davidp@supernova:~/rtl_433]$ autoreconf --install
configure.ac:16: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

My checkout is at 0fb4dec498

Following is some version information in case it helps.  Am I missing something obvious?

```
[davidp@supernova:~/rtl_433]$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[davidp@supernova:~/rtl_433]$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie
[davidp@supernova:~/rtl_433]$ aptitude show rtl-sdr | egrep '^(State|Version)'
State: installed
Version: 0.5.3-3
```

**Comment by bigpresh** [comment]
Ah - I did not have libtool installed; installing that first made that unclear error go away.

Now, instead, I get as far as being able to run `./configure`, and getting:

```
./configure: line 11822: syntax error near unexpected token `LIBRTLSDR,'
./configure: line 11822: `PKG_CHECK_MODULES(LIBRTLSDR, librtlsdr)'
```

Installing librtlsdr-dev and re-running (from autoreconf onwards) made no apparent difference.

```
[davidp@supernova:~/rtl_433]$ aptitude search librtlsdr
i   librtlsdr-dev                                                                 - Software defined radio receiver for Realtek RTL2832U (development files)                
i A librtlsdr0                                                                    - Software defined radio receiver for Realtek RTL2832U (library)
```

I'm probably missing something obvious here.

**Comment by panarom** [comment]
@bigpresh : I think I ran into this error at one point, and I believe this was the solution I found:
apt-get install pkg-config
make sure autoreconf -i is run (again) after installing package
HTH

**Comment by bigpresh** [comment]
Ah - yes, after installing pkg-config, autoreconf --install works much better - still emits warnings, but they look harmless:

I was then able to run ./configure, which was happy, but `make` then bailed because libusb-1.0-0-dev wasn't installed - for anyone Googling the error, I got:

```
...
  CCLD     rtl_433
/usr/bin/ld: cannot find -lusb-1.0
collect2: error: ld returned 1 exit status
Makefile:602: recipe for target 'rtl_433' failed
make[2]: *** [rtl_433] Error 1
...
```

I installed `libusb-1.0-0-dev` (via apt-get) and was then able to compile and run rtl_433 - excellent stuff.

Thanks for the assistance, @panarom.

I think it would be nice if the build process was a bit more user-friendly and robust at detecting and reporting missing dependencies, etc (or, at least, if the dependencies were better documented in the install instructions) personally.  That's coming as a relatively experienced *nix user and developer, not a clueless newbie, too.

**Comment by panarom** [comment]
The user-friendliest thing to do would probably be to package this up for the different distros. If I get really ambitious, I'll try to create a PPA one of these days.
@bigpresh : if you're satisfied with the resolution, can you close the issue? or @merbanan , if @bigpresh can't close it, I think you can; either way, I think it can be marked resolved.

**Comment by bigpresh** [comment]
Sure thing, I'll close it, as it's working well for me now.  If I get a moment, I'd be happy to try to write up some more detailed install instructions along with a list of required packages etc.

**Comment by KimYar** [comment]
Hi everyone,
I am getting the below error msg after running buildozer -v android debug and I couldn't find a solution. Could you please help me with this?

`
`kivy is already unpacked, skipping
[INFO]:    <- directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for hostpython3[armeabi-v7a]
[INFO]:    hostpython3 already patched, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    libffi already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python3[armeabi-v7a]
[INFO]:    python3 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding setuptools for armeabi-v7a
[INFO]:    setuptools has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/android-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    hostpython3 said it is already built, skipping
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    libffi said it is already built, skipping
[INFO]:    -> running cp /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build...(and 219 more)
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    openssl said it is already built, skipping
[INFO]:    -> running cp /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build...(and 391 more)
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sqlite3 for armeabi-v7a
[INFO]:    sqlite3 said it is already built, skipping
[INFO]:    Building python3 for armeabi-v7a
[INFO]:    python3 said it is already built, skipping
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2/jni
[INFO]:    -> running ndk-build V=1 NDK_DEBUG=1
[INFO]:    <- directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android       
[INFO]:    Building setuptools for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    setuptools said it is already built, skipping
[INFO]:    Building six for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    six said it is already built, skipping
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    jnius apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in pyjnius
[INFO]:    -> directory context /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius
[INFO]:    -> running python3 -c import sys; print(sys.path)
[INFO]:    Trying first build of pyjnius to get cython files: this is expected to fail                                          
[INFO]:    -> running python3 setup.py build_ext -v
Exception in thread background thread for pid 63092:                                                                            
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports javac.
Please visit http://www.java.com for information on installing Java.

Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    compile_native_invocation_handler(*get_possible_homes(PLATFORM))
  File "setup.py", line 85, in compile_native_invocation_handler
    subprocess.check_call([
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Lib/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/javac', '-target', '1.7', '-source', '1.7', 'jnius/src/org/jnius/NativeInvocationHandler.java']' returned non-zero exit status 1.


  STDERR:


[INFO]:    pyjnius first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize jnius/jnius.pyx
[INFO]:    -> running python3 -cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exi...(and 39 more)

Exception in thread background thread for pid 63098:                                                                            
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/appleapple/Desktop/CalendarIA/venv/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./jnius/jnius.pyx

  STDOUT:
/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius/jnius/jnius.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
import sys
import traceback

include "jnius_compat.pxi"
include "jni.pxi"
include "config.pxi"
^
------------------------------------------------------------

jnius/jnius.pyx:100:0: 'config.pxi' not found

Error compiling Cython file:
------------------------------------------------------------
...

include "jnius_compat.pxi"
include "jni.pxi"
include "config.pxi"

IF JNIUS_PLATFORM == "android":
  ^
------------------------------------------------------------

jnius/jnius.pyx:102:3: Compile-time name 'JNIUS_PLATFORM' not defined

Error compiling Cython file:
------------------------------------------------------------
...
include "jni.pxi"
include "config.pxi"

IF JNIUS_PLATFORM == "android":
    include "jnius_jvm_android.pxi"
ELIF JNIUS_PLATFORM == "win32":
    ^
------------------------------------------------------------

jnius/jnius.pyx:104:5: Compile-time name 'JNIUS_PLATFORM' not defined

Error compiling Cython file:
------------------------------------------------------------
...
include "config.pxi"
^
------------------------------------------------------------

jnius/jnius_jvm_dlopen.pxi:1:0: 'config.pxi' not found

Error compiling Cython file:
------------------------------------------------------------
...
    JAVA_HOME = os.getenv('JAVA_HOME') or find_java_home()
    if JAVA_HOME is None or JAVA_HOME == '':
        raise SystemError("JAVA_HOME is not set, and unable to guess JAVA_HOME")
    cdef str JNIUS_LIB_SUFFIX = get_jnius_lib_location(JNIUS_PLATFORM)

    IF JNIUS_PYTHON3:
      ^
------------------------------------------------------------

jnius/jnius_jvm_dlopen.pxi:89:7: Compile-time name 'JNIUS_PYTHON3' not defined

Error compiling Cython file:
------------------------------------------------------------
...

include "jnius_env.pxi"
include "jnius_utils.pxi"
include "jnius_conversion.pxi"
include "jnius_localref.pxi"
IF JNIUS_PYTHON3:
  ^
------------------------------------------------------------

jnius/jnius.pyx:113:3: Compile-time name 'JNIUS_PYTHON3' not defined



  STDERR:


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1276, in <module>
    main()
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 215, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1059, in build_arch
    self.build_cython_components(arch)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1084, in build_cython_components
    self.cythonize_build(env=env)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1132, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1123, in cythonize_file
    filename, *self.cython_args, _env=cyenv)
  File "/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 953, in next
    self.wait()
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/appleapple/Desktop/CalendarIA/venv/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./jnius/jnius.pyx

  STDOUT:
/Users/appleapple/Desktop/CalendarIA/venv/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius/jnius/jnius.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
import sys
import traceback

include "jnius_compat.pxi"
include "jni.pxi"
include "config.pxi"
^
------------------------------------------------------------

jnius/jnius.pyx:100:0: 'config.pxi' not found

Error compiling Cython file:
------------------------------------------------------------
...

include "jnius_compat.pxi"
include "jni.pxi"
include "config.pxi"

IF JNIUS_PLATFORM == "android":
  ^
------------------------------------------------------------

jnius/jnius.pyx:102:3: Compile-time name 'JNIUS_PLATFORM' not defined

Error compiling Cython file:
------------------------------------------------------------
...
include "jni.pxi"
include "config.pxi"

IF JNIUS_PLATFORM == "android":
    include "jnius_jvm_android.pxi"
ELIF JNIUS_PLATFORM == "win32":
    ^
------------------------------------------------------------

jnius/jnius.pyx:104:5: Compile-time name 'JNIUS_PLATFORM' not defined

Error compiling Cython file:
------------------------------------------------------------
...
include "config.pxi"
^
------------------------------------------------------------

jnius/jnius_jvm_dlopen.pxi:1:0: 'config.pxi' not found

Error compiling Cython file:
------------------------------------------------------------
...
    JAVA_HOME = os.getenv('JAVA_HOME') or find_java_home()
    if JAVA_HOME is None or JAVA_HOME == '':
        raise SystemError("JAVA_HOME is not set, and unable to guess JAVA_HOME")
    cdef str JNIUS_LIB_SUFFIX = get_jnius_lib_location(JNIUS_PLATFORM)

    IF JNIUS_PYTHON3:
      ^
------------------------------------------------------------

jnius/jnius_jvm_dlopen.pxi:89:7: Compile-time name 'JNIUS_PYTHON3' not defined

Error compiling Cython file:
------------------------------------------------------------
...

include "jnius_env.pxi"
include "jnius_utils.pxi"
include "jnius_conversion.pxi"
include "jnius_localref.pxi"
IF JNIUS_PYTHON3:
  ^
------------------------------------------------------------

jnius/jnius.pyx:113:3: Compile-time name 'JNIUS_PYTHON3' not defined



  STDERR:

# Command failed: /Users/appleapple/Desktop/CalendarIA/venv/bin/python -m pythonforandroid.toolchain create --dist_name=kvcalc --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/appleapple/Desktop/CalendarIA/CAI/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     TMPDIR = '/var/folders/38/s153lprs32d5n6sn_c19w8240000gn/T/'
#     CONDA_SHLVL = '0'
#     USER = 'appleapple'
#     COMMAND_MODE = 'unix2003'
#     CONDA_EXE = '/Users/appleapple/anaconda3/bin/conda'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.PpqkPympBV/Listeners'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x52'
#     VIRTUAL_ENV = '/Users/appleapple/Desktop/CalendarIA/venv'
#     _CE_CONDA = ''
#     PATH = '/Users/appleapple/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/appleapple/Desktop/CalendarIA/venv/bin:/Users/appleapple/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/appleapple/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     __CFBundleIdentifier = 'com.jetbrains.pycharm'
#     PWD = '/Users/appleapple/Desktop/CalendarIA/CAI'
#     XPC_FLAGS = '0x0'
#     PS1 = '(venv) \\h:\\W \\u\\$ '
#     _CE_M = ''
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/appleapple'
#     CONDA_PYTHON_EXE = '/Users/appleapple/anaconda3/bin/python'
#     LOGNAME = 'appleapple'
#     LC_CTYPE = 'en_CA.UTF-8'
#     DISPLAY = '/private/tmp/com.apple.launchd.JG7odCqoLs/org.macosforge.xquartz:0'
#     _ = '/Users/appleapple/Desktop/CalendarIA/venv/bin/buildozer'
#     OLDPWD = '/Users/appleapple/Desktop/CalendarIA'
#     __PYVENV_LAUNCHER__ = '/Users/appleapple/Desktop/CalendarIA/venv/bin/python'
#     PACKAGES_PATH = '/Users/appleapple/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/appleapple/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/appleapple/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
``
