### ISSUE TITLE
can't use -m mode switch

### ISSUE THREAD

**Issue by iddq** [merbanan/rtl_433#455]
It says input format uint8 and this is maybe wrong and decoding doesn't work in this case

        [-m <mode>] Data file mode for input / output file (default: 0)
                 0 = Raw I/Q samples (uint8, 2 channel)
                 1 = AM demodulated samples (int16 pcm, 1 channel)
                 2 = FM demodulated samples (int16) (experimental)
                 3 = Raw I/Q samples (cf32, 2 channel)
                 Note: If output file is specified, input will always be I/Q

./src/rtl_433 -m 1 -r /tmp/test.wav
Test mode active. Reading samples from file: /tmp/test.wav
Input format: uint8
Test mode file issued 12 packets

[test.zip](https://github.com/merbanan/rtl_433/files/638593/test.zip)

**Comment by merbanan** [comment]
Wav input is not supported. That and wav out might be added in the future. Closing issue.
