### ISSUE TITLE
Man page/Release

### ISSUE THREAD

**Issue by martijnvanbrummelen** [merbanan/rtl_433#465]
Would it be possible to create a man-page for rtl_433 and please rename release "push" to 0.1 or higher so it can be  packaged for Debian.
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851309
Thanks!

**Comment by merbanan** [comment]
Sure, can you point me in the correct direction for debian man page requirements and I will look into it?

I will also tag up a proper release point when the debian requirements are committed.

**Comment by martijnvanbrummelen** [comment]
I can also create it and send a pull request?

**Comment by merbanan** [comment]
Works for me.

**Comment by martijnvanbrummelen** [comment]
Do you have a emailadres/alias I can put in the files?
If you don't want it on github send a mail to mvb@debian.org

**Comment by merbanan** [comment]
banan at ludd dot ltu dot se

**Comment by merbanan** [comment]
Maybe time for a 18.12 version. Anyway issue solved, closing.
