### ISSUE TITLE
Any caveats with using decimation rate in rtl_433

### ISSUE THREAD

**Issue by magellannh** [merbanan/rtl_433#47]
Hello,

I've been using rtl_433 in an application that gathers and reports Oregon Scientific weather sensor data.  The app runs on a Raspberry Pi and on a Netgear R7000 router running dd-wrt.  So far so good.

Now I'd like to add support for an Efergy current sensor to my app.  I have the decoding for the new sensor working, but it uses FSK encoding and requires rtl_fm instead of rtl_433.  

My plan is to merge the code for rtl_433 and rtl_fm and send raw rtl-sdr samples to both decoders for processing.  Separately, the rtl_fm code uses about 20% cpu on the Rasperry Pi, and the rtl_433 code uses about 12%.

My problem is that the rtl_fm decoder runs at 1,200,000 samples per second and I can't get it working at rates much below that.  I've been running rtl_433 at 250,000 samples per second.  

To have a shot at merging the code, I need to get both decoders running at the same frequency and sample rate and consuming a reasonable amount of cpu. rtl_433 does fine decoding messages from my OS sensors at 1,200,000 samples per second, but the problem is it uses 60% of the Raspberry pi's cpu to do it.

So I thought maybe I could sample at 1,200,000 s/sec and set decimation using -c 2 so rtl_433 didn't have to work so hard.  If I understand how it works, this would get the effective sample rate that rtl_433 has to process to about 300,000, which is close to the default of 250000.  Sure enough, when I use "rtl_433 -s 1.2e6 -c 2", the cpu load drops to 20% or less as I had hoped.

The problem is that decoding doesn't work with decimation set to anything other than the default 0.  I manually adjusted the short, long, and reset limits in rtl_433 to account for the effective sample rate difference from using -c 2 by dividing the values by 4.  I also tried -c 1 with dividing the values by 2.  (I also tried these settings with the original values just in case there was some magic adjustment in the code that I didn't see).

Do I understand how this works or am I missing something big?  I would have guessed that using decimation would have been fine, since the new sample rate was so much higher than the old one.  Are there any other caveats to using the decimation feature to reduce processing load?

Any thoughts on this would be greatly appreciated!

Thanks!

**Comment by robho** [comment]
Close this one?

* Decimation support has been removed from rtl_433 (db9b44a)
* rtl_433 has native support for efergy power meter (at least efergy e2 classic)

**Comment by merbanan** [comment]
Sure.
