### ISSUE TITLE
bugs found by cppcheck

### ISSUE THREAD

**Issue by bertrik** [merbanan/rtl_433#476]
If you run cppcheck on the source code, it find some peculiarities:

src/data.c line 207: what is this about?
char* format = false;

src/devices/honeywell.c, line 47/49/52, a 2-digit hex-value is printed to a buffer, but the buffer is too small, it doesn't take into account the trailing zero:
  char hex[2];

also, the same problem in src/devices/maverick_et73x.c

**Comment by zuckschwerdt** [comment]
The honeywell decoder uses sprintf for bitmasking? That really needs to get fixed.

**Comment by merbanan** [comment]
Both decoders look fine now. Closing issue.
