### ISSUE TITLE
Add support for LaCrosse TX29 and TX35 (this post include .data and protocol spec)

### ISSUE THREAD

**Issue by psa-jforestier** [merbanan/rtl_433#477]
Hello, and thanks for all this work. I have two different sensors from LaCrosse Europe (868,2 MHz), and a clone from Conrad.
The current version of RTL_433 can't decode it, but the protocol is documented, and in -a mode I can see the bytes, and I saved a valid .data file. I dont know how to contribute to this project. Do I have to create a fork of the rtl_433_tests project, add all necessary information, and create a Pull Request ?

data files :
[gfile.zip](https://github.com/merbanan/rtl_433/files/729991/gfile.zip)

TX29-IT & TX35
--------------
Captured signals for LaCrosse compatible TX29-IT, made by Conrad 868 Mhz temperature. The TX9U-IT version is 915MHz, dont know if it use the same protocol.

This should also work for LaCrosse TX35 and  which use the same protocol, with humidty.

Device Info
-----------
* Buy it online : http://www.conrad.fr/ce/fr/product/646282/
* Owner's Manual : FR : http://www.lacrossetechnology.fr/donnees/documents/produits/TX29IT+/PDF-fr-TX29IT+.pdf
* EAN: 4016138439489

Device Notes
------------

* Random Device ID - When the device is powered up (batteries are
  changed) it will generate a random ID byte that it will send with
  all transmissions.
* Messages are sent once.
* There is temperature and humidty in the same message. If (humidity & 0x7F == 0x6A) it meens there is no humidity sensor.

Protocol Documentation
----------------------
A nice page documenting how to decode the protocol is available here http://fredboboss.free.fr/articles/tx29.php/

Basically : 

* carrier frequency : 868.3 MHz
* modulation OOK
* baudate 17.24 kpbs
* 64-bit messages (8 bytes, including preamble and crc)
* CRC is a CRC-8 with the polynom x8 + x5 + x4 + 1 (poly=0x31, int=0, final xor=0) of bytes 4 to 7

```
Nibble num :
---1 ---2 ---3 ---4 ---5 ---6 ---7 ---8 ---9 --10 --11 --12 --13 --14 --15 --16
Example Data bytes(gfile-tx29.data) : 
   a    a    2    d    d    4    9    2    8    4    4    8    6    a    e    c
Example Data bits (gfile-tx29.data) : 
1010 1010 0010 1101 1101 0100 1001 0010 1000 0100 0100 1000 0110 1010 1110 1100
Bytes num :
----1---- ----2---- ----3---- ----4---- ----5---- ----6---- ----7---- ----8----
~~~~~~~~~ preamble, always "0xaa"
          ~~~~~~~~~~~~~~~~~~~ brand identifier, always 0x2dd4
                              ~~~~ datalength (always 9) in nibble, including this field and crc
                                   ~~~~ ~~ Random device id (6 bits)
                                          ~ new battery indicator
                                           ~ unkown, unused
                                             ~~~~ ~~~~ ~~~~ temperature, in bcd *10 +40
                                                            ~ weak battery
                                                             ~~~ ~~~~ humidity, in%. If == 0x6a : no humidity sensor
                                                                      ~~~~ ~~~~ crc8 of bytes
```

CRC computing :
See http://www.sunshine2k.de/coding/javascript/crc/crc_js.html with custom with
Polynomial = 0x31
init = 0x00
final xor value = 0x00
or
http://crccalc.com/?crc=0x92+0x84+0x48+0x6a&method=crc8&datatype=hex
(see result on line MAXIM)
On the previous example, CRC is calculated with bytes 4 to 7 (0x92 0x84 0x48 0x6a). Result is 0xec and must be equal to byte 8.

Files
-----
[gfile.zip](https://github.com/merbanan/rtl_433/files/729991/gfile.zip)
gfile gfile-tx29.data
Data : aa 2d d4 92 84 48 6a ec
Sensor : LaCrosse TX29 or TX35
Temperature : 4.8°C
Humidity : N/A (0x6a)
Newbatt : 0
Weakbatt : 0
CRC computed : 0xec
CRC received : 0xec

gfile gfile002-TX35DTH-IT.data
data : aa 2d d4 96 a6 41 22 50
Sensor : LaCrosse TX29 or TX35
Temperature : 24.1°C
Humidity : 34 
Newbatt : 1
Weakbatt : 0
CRC computed : 0x50
CRC received : 0x50

**Comment by psa-jforestier** [comment]
I created a pull request on the _test repository : https://github.com/merbanan/rtl_433_tests/pull/141
I'm going to try to modify the rtl_433 code to add support to this sensors.

**Comment by psa-jforestier** [comment]
Here is an analysis (rtl_433 -r gfile-tx29.data -A)
```
Test mode active. Reading samples from file: gfile-tx29.data
Input format: uint8
Detected FSK package
Analyzing pulses...
Total count:   21,  width:   901                ( 3.6 ms)
Pulse width distribution:
 [ 0] count:   16,  width:    14 [13;15]        (  56 us)
 [ 1] count:    3,  width:    29 [29;29]        ( 116 us)
 [ 2] count:    2,  width:    43 [43;44]        ( 172 us)
Gap width distribution:
 [ 0] count:   12,  width:    14 [14;16]        (  56 us)
 [ 1] count:    2,  width:    43 [43;44]        ( 172 us)
 [ 2] count:    4,  width:    29 [29;29]        ( 116 us)
 [ 3] count:    2,  width:    58 [58;58]        ( 232 us)
Pulse period distribution:
 [ 0] count:    8,  width:    29 [29;31]        ( 116 us)
 [ 1] count:    6,  width:    62 [58;72]        ( 248 us)
 [ 2] count:    6,  width:    43 [43;44]        ( 172 us)
Level estimates [high, low]:  15983,     39
Frequency offsets [F1, F2]:   14811, -13392     (+56.5 kHz, -51.1 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 14, long_limit: 14, reset_limit: 14336, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {65} aa 2d d4 92 84 48 6a ec 00

Test mode file issued 1 packets

```

What is the best suitable decoder ?

**Comment by psa-jforestier** [comment]
PR in progress : https://github.com/merbanan/rtl_433/pull/479

**Comment by psa-jforestier** [comment]
Fixed in commit https://github.com/merbanan/rtl_433/commit/a9a574fe4f93b63caef52d0fcecb23afa0a01fc2

**Comment by thomasvjohansen** [comment]
I cant make install it....

when doing "make" this error appears:

`[  2%] Building C object src/CMakeFiles/rtl_433.dir/devices/lacrosse_tx35.c.o
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c: In function ‘lacrossetx29_callback’:
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c:57:40: error: expected ‘)’ before ‘;’ token
 #define LACROSSE_TX29_MODEL          29; // Model number
                                        ^
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c:159:32: note: in expansion of macro ‘LACROSSE_TX29_MODEL’
  return lacrosse_it(bitbuffer, LACROSSE_TX29_MODEL);
                                ^
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c: In function ‘lacrossetx35_callback’:
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c:58:40: error: expected ‘)’ before ‘;’ token
 #define LACROSSE_TX35_MODEL          35;
                                        ^
/home/thomas/Skrivebord/rtl_433/src/devices/lacrosse_tx35.c:166:32: note: in expansion of macro ‘LACROSSE_TX35_MODEL’
  return lacrosse_it(bitbuffer, LACROSSE_TX35_MODEL);
                                ^
make[2]: *** [src/CMakeFiles/rtl_433.dir/devices/lacrosse_tx35.c.o] Fejl 1
make[1]: *** [src/CMakeFiles/rtl_433.dir/all] Fejl 2
make: *** [all] Fejl 2
`

**Comment by psa-jforestier** [comment]
Fixed in https://github.com/merbanan/rtl_433/pull/484
