### ISSUE TITLE
Oil Watchman - temperature incorrect

### ISSUE THREAD

**Issue by prae5** [merbanan/rtl_433#482]
I've got an Watchman Sonic and I'm struggling to get it to report the temperature.

Its been fixed at 10.000c regardless of outside temperature. 
`
{"time" : "2017-01-30 23:34:46", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
{"time" : "2017-01-30 23:52:13", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
{"time" : "2017-01-31 00:09:39", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
{"time" : "2017-01-31 00:27:05", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
{"time" : "2017-01-31 00:44:31", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
{"time" : "2017-01-31 01:01:58", "model" : "Oil Watchman", "id" : 139548083, "flags" : 128, "maybetemp" : 23, "temperature_C" : 10.000, "binding_countdown" : 0, "depth" : 47}
`

I've put it into pairing mode to confirm i was looking at the correct device.
`2017-01-31 13:35:37 :   Oil Watchman    :       85155b3         :       60      :       23      :       10.000  :       0       :       48`

I would say the depth measure is about right, so it seems to be decoding correctly.

Can you give me some pointers on what i should be investigating?

**Comment by merbanan** [comment]
There are no real signal specification for this device. Try contacting the author of the decoding module.  maybetemp might be the value you are asking for. Closing issue.
