### ISSUE TITLE
Better protocol detection adding packet length (bits) in addition to timing parameters

### ISSUE THREAD

**Issue by jcarduino** [merbanan/rtl_433#49]
It would be nice if we could use packet length further narrow down protocol detection to prevent false positives. I tried to implement it within the callback but I think I cannot access parameters to work things out.

Any hints about implementing this into rtl_433??

**Comment by Batilan** [comment]
Please also see my issue #78 I think if we can get the  plugin infra implemented also for the PWM decoders we can more easily develop and test this without having to change all plugins. Like @rct mentions bigger changes are probably required to further improve validation of devices and make the software more scalable.

**Comment by merbanan** [comment]
The new analyzer -A and demodulator configuration makes this better.
