### ISSUE TITLE
BYRON BY34 Wireless Bell Push

### ISSUE THREAD

**Issue by jonathanmbradshaw** [merbanan/rtl_433#509]
Checking in to see if anyone has done any work on the Byron BY34 Bell Push, protocol detail follows;

*** signal_start = 835061, signal_end = 1272780
signal_len = 437719,  pulses = 1050
Iteration 1. t: 186    min: 124 (572)    max: 249 (428)    delta 8
Iteration 2. t: 186    min: 124 (572)    max: 249 (428)    delta 0
Pulse coding: Short pulse length 124 - Long pulse length 249

Short distance: 125, long distance: 250, packet distance: 751

p_limit: 186
bitbuffer:: Number of rows: 25 
[00] {21} 35 21 a8 : 00110101 00100001 10101
[01] {21} 35 21 a8 : 00110101 00100001 10101

Detected OOK package	@ 2017-04-01 11:06:48
Analyzing pulses...
Total count: 1050,  width: 417717		(1670.9 ms)
Pulse width distribution:
 [ 0] count:  600,  width:   125 [124;130]	( 500 us)
 [ 1] count:  450,  width:   250 [249;253]	(1000 us)
Gap width distribution:
 [ 0] count:  550,  width:   248 [247;251]	( 992 us)
 [ 1] count:  450,  width:   124 [122;126]	( 496 us)
 [ 2] count:   49,  width:   750 [749;752]	(3000 us)
Pulse period distribution:
 [ 0] count:  350,  width:   374 [373;378]	(1496 us)
 [ 1] count:  350,  width:   249 [248;251]	( 996 us)
 [ 2] count:  300,  width:   499 [499;501]	(1996 us)
 [ 3] count:   49,  width:  1001 [1000;1003]	(4004 us)
Level estimates [high, low]:  15841,      3
Frequency offsets [F1, F2]:    8712,      0	(+33.2 kHz, +0.0 kHz)
Guessing modulation: No clue...

**Comment by zuckschwerdt** [comment]
see #682
