### ISSUE TITLE
Fix for battery status on Acurite 606TX

### ISSUE THREAD

**Issue by skiphansen** [merbanan/rtl_433#510]
Please find attached a patch that fixes the Acurite 606TX battery status decode which was being reported incorrectly as "Low" when it was in fact "Ok".

Thanks for the code!
Skip

[0001-Fix-battery-status-on-Acurite-606TX.patch.txt](https://github.com/merbanan/rtl_433/files/888682/0001-Fix-battery-status-on-Acurite-606TX.patch.txt)

**Comment by merbanan** [comment]
Send a PR and I will merge it.

**Comment by skiphansen** [comment]
Sorry, the current HEAD didn't build using ./configure;make so I had pulled an earlier version.  My fix is already in the HEAD.  BTW: cmake does build the current HEAD.   I was on autopiliot and didn't notice cmake.
