### ISSUE TITLE
MAX_PROTOCOLS Error

### ISSUE THREAD

**Issue by ludwich66** [merbanan/rtl_433#519]
Hi, there is an actual Error with  MAX_PROTOCOLS.
Who can fix  it?
 The File was fresh compiled - 18-04-2017 19:30
-------
LAST PROTOKOLL
Registering protocol [78] "Fine Offset Electronics, WH0530 Temperature/Rain Sensor"

ERROR
Max number of protocols reached 77
Increase MAX_PROTOCOLS and recompile
----------

ludwich

**Comment by hoenes** [comment]
this error is back, counted up to 79 protocols
