### ISSUE TITLE
Better message validation

### ISSUE THREAD

**Issue by maxx23** [merbanan/rtl_433#55]
Since lots of sensors seem to repeat themselves a lot in one burst i'd like to propose a solution for reconstructing the most plausible sequence.
It works by creating a sum for 1s or 0s in a row (for all the bits). 0s decrease the counter, 1s increase. The final data is then reconstructed by checking if the sum for the bit in this row is positive (so it's a 1) or negative (so it's 0). If the sum is just zero no decision can be made since the propability for it being a 1 or 0 is exactly 50%.

``` C
// this tries to get the most plausible bit sequence from sensors
// repeating their data a few times
//  result - where the sequence is stored (usually the size of cols)
//  input   - usually this is bits_buffer
//  rows    - number of repetitions to concider
//  cols    - how many bytes to concider in a repetition
//  offset  - offset for bit buffer (e.g. input[0] usually is a preamble)
//  returns the number of discrepancies (kind of like bit errors)
static int bit_validate(
        uint8_t *result,
        uint8_t input[BITBUF_ROWS][BITBUF_COLS],
        int rows,
        int cols,
        int offset)
{
    int8_t counters[cols * 8];      // one bytes for every bit in a row
                                    // 0s count negative, 1s positive
    int errs = 0;                   // error counter
    int row, col, bit;

    // reset arrays
    memset(counters, 0x0, sizeof(int8_t) * (cols * 8));
    memset(result, 0x0, sizeof(uint8_t) * cols);

    // count number of 1s and 0s per row per bit
    for(row = offset; row < rows + offset; row++)
    {   
        for(col = 0; col < cols; col++)
        {   
            for(bit = 0; bit < 8; bit++)
            {   
                uint8_t val = (input[row][col] >> bit) & 0x1;
                counters[col * 8 + bit] += (val << 1) - 1;
            }
        }
    }

    // use the gathered sums to reconstruct most plausible bit sequence
    for(col = 0; col < cols; col++)
    {   
        for(bit = 0; bit < 8; bit++)
        {   
            int8_t c = counters[col * 8 + bit];
            uint8_t val;

            // actual decision
            // if sum is 0: 1s and 0s are equally distributed so no
            // decision can be made
            if(c > 0)
                val = 1;
            else if(c < 0)
                val = 0;
            else
                return -1;

            // construct resulting byte
            result[col] |= val << bit;
            // and count the errors
            errs += rows - abs(c);
        }
    }

    errs >>= 1;

    return errs;
}
```

To use it you need to know how many repetitions the sensor is sending, how many bytes are in one "packet" (or repetition) and the first repetition containing useful data to get the offset. Afterwards simply use the result from bit_validate since this is the error-corrected data.

Usage might look like this:

``` C
static int unknown0_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS]) {
    uint8_t res[5];
    int errs;

    // sensor repeats itself 11 times
    // there are 5 bytes in one repetition
    // useful data starts at the second row, so offset is 1
    errs = bit_validate(res, bb, 11, 5, 1);

    if (res[0] == 0xb2 && res[1] == 0x00) {
        int temp = res[2];
        int pressure = (res[3] << 4) | (res[4] >> 4);
        ...
```
- Jan R.

**Comment by merbanan** [comment]
Hi, great idea. But I think this should not be in the decoder context. Ideally the decoder should be sent a "processed" row that the decoder should parse. This row should be the data your code outputs.

**Comment by merbanan** [comment]
While this idea is good but it only works for a subset of signals, that is signals that repeat rows and don't have a checksum, we also have the bitbuffer_find_repeated_row() function now. What could be done is if no decoder triggers on a bit buffer one could validate it like described here and then try to decode it again. The issue with this is that I don't really see a clear improvement and it will be hard to test the feature. So anyone is free to develop this but the code will also need a good test set of sample signals that are fixed by that code. Closing issue.

**Comment by zuckschwerdt** [comment]
As a suggestion if someone picks this up: a first step should be to classify (and maybe align) matching rows. Only if very few bits differ there should be a reconciliation/quorum.
