### ISSUE TITLE
trouble running in -a -t mode

### ISSUE THREAD

**Issue by bjlester** [merbanan/rtl_433#622]
When I run 

`rtl_433 -f 314970000 -a -t`

nothing happens. No output files are created.

The end goal is to be able to upload data about a remote controlled outlet I have. I have manually decoded the transmission, but I don't understand how to write the driver. I can try to upload the sdr recording and the decoding.

**Comment by panarom** [comment]
@bjlester what happens if you run w/o the `-t` parameter? do you get data on stdout?  can you paste the decoding here in this issue?

**Comment by bjlester** [comment]
Nothing is printed to the console when running with -a. If I use -A, I get a binary representation of the signal, but it is incorrect.

attached is a log when running with -A

[log.txt](https://github.com/merbanan/rtl_433/files/1457449/log.txt)

The binary output is incorrect. 
The correct signal for on is  `\x8E\xE8\xE8\x88\x88\xE8\x88\x88`
The correct signal for off is  `\x8E\xE8\xE8\x88\x88\x8E\x88\x88`

Note that the only difference is the reversal in the 6th octet. On is E8, off is 8E. There is no preamble. also attached is an image of the wav file I created from the waveforms. 

![off](https://user-images.githubusercontent.com/6900208/32603948-aadf3618-c519-11e7-9882-91d959fd1c9c.png)
![on](https://user-images.githubusercontent.com/6900208/32603949-aaea4e5e-c519-11e7-9810-605c5d263cc2.png)

**Comment by zuckschwerdt** [comment]
I guess you are confusing a fixed clock sampling with OOK here. Your 0x8 is high,low,low,low in one fixed clock period (or four, however you view this), and your 0xE is high,high,high,low. Those correspond to a single `0` or `1` bit in rtl_433. I.e. the signal pictured above is 01101011111101111.

**Comment by bjlester** [comment]
rtl_433 decodes the signal with -A as d0 40 repeating. But, this is not the primary issue at hand. Running rtl_433 with the -a option does absolutely nothing.

One of my neighbors has a weather station. I can receive those messages when I run it without -a, but running with -a, no output is generated in the console.

**Comment by merbanan** [comment]
Lots of things have been reworked. Try again with current code and report again if it still doesn't work as expected. Closing issue.
