### ISSUE TITLE
Issues decoding DSC WS4945 security contact

### ISSUE THREAD

**Issue by patrickgalbraith** [merbanan/rtl_433#645]
I'm getting nothing when decoding some DSC security contacts I have. 

I'm using ` rtl_433 -R 23 -r pathtofile.data` to decode the files. It works if I set it like this (which is strange):

```
    .short_limit   = 550,     
    .long_limit    = 1100,  
    .reset_limit   = 15000, 
```

See samples here https://github.com/patrickgalbraith/rtl_433_tests/tree/master/tests/dsc/02

**Comment by zuckschwerdt** [comment]
Preamble 433 samples (1732µs) low, 1330 samples (5320µs) high .
134 samples (536µs) per bit pulse.
The whole packet seems to be around 13268 samples (99 clocks).
There are 86 clocks after the preamble.
The pattern (gfile001.data) is
```
___----------
_-_-_-_-_-___-_________-_-_____-___________-_-_-___-_______-_-_-_______-_-_____-_-____
```
Which sliced for low-high=1, low-low=0 is
```
111110100001100100000111010001110001100110
```
Or sliced for high-low=1, low-low=0 is
```
111110100001100100000111010001110001100110
```
Either dropping the leading low or the trainling low pulse. Doesn't matter.

**Comment by zuckschwerdt** [comment]
Using Pulse Code Modulation works as expected with
```
    .modulation = OOK_PULSE_PCM_RZ,
    .short_limit = 536,     // Nominal width of pulse [us]
    .long_limit = 1072,     // Nominal width of bit period [us]
    .reset_limit = 6000,   // Maximum gap size before End Of Message [us].
```
giving
```
Test mode active. Reading samples from file: gfile001.data
[00] {46} fa 19 07 47 19 80 : 11111010 00011001 00000111 01000111 00011001 100000
[00] {46} fa 19 07 47 19 80 : 11111010 00011001 00000111 01000111 00011001 100000
```

**Comment by patrickgalbraith** [comment]
Awesome thanks for that. It works if I recompile it with those values in `devices/dsc.c`. But any reason why `rtl_433 -R 23 -z 536 -x 1072 -r gfile001.data` doesn't work?

**Comment by merbanan** [comment]
Those parameters are only used in the -a analyzer.

**Comment by patrickgalbraith** [comment]
Ok no worries makes sense now. Thanks guys.

Strange that the sensors I have require slightly different configuration but I guess it isn't a big deal.

Working on decoding the meaning of the status byte returned from the DSC decoder. What I have worked out so far:

```
0x01 = Tamper
0x02 = Open/Closed/Alarm triggered
0x04 = Heartbeat
```

**Comment by zuckschwerdt** [comment]
I'm working on a general purpose decoder where you'd just use e.g.
`-X MyDSC:OOK_PULSE_PCM_RZ:536:1072:6000:46`
to quickly check/debug/analyze your signal. It's not available right now though ;)

**Comment by zuckschwerdt** [comment]
The DSC notes mention a sync pulse every 8 bits. For a 0x00 byte you'd be seeing 1072*8µs silence. Best to put the reset_limit at 9000 then.

**Comment by rct** [comment]
FWIW, The sync pulse is needed since a byte could be all zero bits, meaning no actual signal is sent for the duration of the byte transmission.

@patrickgalbraith I'm curious about the differences with your recordings.  I'll take a look at them over the weekend and compare them to my own.  I've got ~25 of those contacts at varying distances that are working fairly reliably for two years or more.

The one issue I have is I don't know if certain sensors, namely the wireless smoke detectors only send 1 heartbeat message or I'm missing the repeat one due to timing or other demod issue.  The other sensors all send the heartbeat message twice.    It's a little hard to isolate that heartbeat since I've got on the order of 30-35 devices on 433 mhz.

**Comment by rct** [comment]
@patrickgalbraith - What sample rates were your recordings done at?    The limits you need to make it work are double what the current code is currently using.  A spot check shows your recordings are double the size of my recordings in the test repo  (256k vs 128k)

**Comment by patrickgalbraith** [comment]
@rct I just used the defaults when recording using `rtl_433 -a -t` so I guess `250000 Hz` which might explain the issue. I'll experiment a bit later.

You mentioned somewhere else that you managed to decode the low battery bit. Any chance you could share what that is.

**Comment by patrickgalbraith** [comment]
@rct just saw your post at http://rctnotes.blogspot.com.au/2015/08/rtl433-now-decodes-dsc-433-mhz-securty.html with the decoded status info. Thanks so much for this!!

**Comment by rct** [comment]
@patrickgalbraith - see PR #739 for the DSC status bits.  There is a more verbose description of the bits here https://rctnotes.blogspot.com/2018/05/rtl433-dsc-sensor-bit-decoding.html

**Comment by patrickgalbraith** [comment]
@rct Thanks for this amazing work!
