### ISSUE TITLE
Tags and New Description

### ISSUE THREAD

**Issue by DL4APT** [merbanan/rtl_433#654]
Please update the short description of the project because at the moment I think it's don't match the scale of the project anymore. Something along the lines of the example below should be more appropriate.

- Program to decode traffic from Devices that are broadcasting on 433.9 MHz like temperature sensors 

Also I would suggest using the flowing Tags to better find this amazing project:

- rtl-sdr
- sdr 

and maybe: 

- signal-processing 
- hacking

**Comment by merbanan** [comment]
Fixed. Close if it is ok.
