### ISSUE TITLE
branch feat-soapysdr is missing convenience.c and convenience.h

### ISSUE THREAD

**Issue by zvpunry** [merbanan/rtl_433#656]
I just discovered this branch and wanted to try it, but it didn't build because of these missing files ;)

**Comment by zuckschwerdt** [comment]
oops. fixed (force push, may need reset before pull).
The SoapySDR support basically works, tested with SoapyRTLSDR and SoapyRemote.
But the FSK decoding should be broken, I didn't fix the stream format.
Work in progress though, any comments very welcome.
