### ISSUE TITLE
Prologue Sensors not working with latest git-source

### ISSUE THREAD

**Issue by storole** [merbanan/rtl_433#657]
Hello! I built rtl_433 from the latest source (2017-12-19) and I noticed that there where a number of new sensors listed on the page. I found that none of my Prologue based sensors worked anymore.  All my Oregon S. sensors worked fine. Went back to a clone I did 2017-10-16, and all Prologue sensors showed up again.

**Comment by merbanan** [comment]
Can you do a git bisect or send a signal sample ?

**Comment by storole** [comment]
OK! I will send signal sample generated with latest git source.

**Comment by zuckschwerdt** [comment]
I just check, `rtl_433_tests/tests/prologue/02/` has json files and works, `rtl_433_tests/tests/prologue/01/` doesn't and does not work. Will be interesting to compare samples.

**Comment by zuckschwerdt** [comment]
I found the bug and I'll fix it tomorrow. Thanks for reporting and the new sample data.

**Comment by zuckschwerdt** [comment]
It's fixed now. The false positive reduction vs alecto/auriol was too harsh.

**Comment by storole** [comment]
Thanks! Just tested it and it works perfectly!
