### ISSUE TITLE
Template device declared two times...

### ISSUE THREAD

**Issue by enavarro222** [merbanan/rtl_433#659]
I just realized that "template" device is declared twice in 
- https://github.com/merbanan/rtl_433/blob/master/include/rtl_433_devices.h#L15
- https://github.com/merbanan/rtl_433/blob/master/include/rtl_433_devices.h#L71

Is it a reason for that or just a bug ?

**Comment by merbanan** [comment]
IIRC the reason was to keep the order the same when a decoder was removed.

**Comment by enavarro222** [comment]
Ok great so if I propose a new device I can use the second one as an "empty slot" ?

**Comment by merbanan** [comment]
No just add it at the end of the list.
