### ISSUE TITLE
Recorded files: Call back may not occur if reset_limit is too long

### ISSUE THREAD

**Issue by rct** [merbanan/rtl_433#66]
When using '-r' to play back record files, the call back function will not get called if the reset_limit is higher than the number of quiet samples at the end of the test file.

In my case, I had set a high reset_limit (20,000 samples), but the recorded file had approximately 10,000 quiet samples after the signal at the end.

I suggest that during development with recorded files, set the reset_limit below 10,000.

**Comment by zuckschwerdt** [comment]
This might still be an issue, I'll need to check this.

**Comment by zuckschwerdt** [comment]
ok, this is already solved as we always add an empty buffer last when using file input
