### ISSUE TITLE
pwm_p_decode (OOK_PWM_P) bug on first bit and pulse_width decoding notes

### ISSUE THREAD

**Issue by rct** [merbanan/rtl_433#67]
For Pulse Width Decoding (OOK_PWM_P) there is a bug that affects the processing of first bit as well as some differences in the way Pulse Width Decoding is currently handled vs. distance or analyze (-a).  

This leads to some unexpected results where analyze (-a) is giving different results than what the call back receives.

Things to be aware of when using OOK_PWM_P
1.  For OOK_PWM_P short pulses = 1, long pulses = 0.  This is inverted from what pwm_analyze (-a) or distance OOK_PWM_D uses (short pulse = 0, long pulse = 1).
2.  OOK_PWM_P considers the first pulse to be a start bit and silently discards it without setting a bit.  The call back will be missing the first bit when compared to analyze (-a) even after inverting.
3.  There is a bug processing the start bit that causes the first real bit (2nd pulse) to be misinterpreted unless the long_limit is higher than the long pulse period (long pulse width + space width * 2).   The sample_counter isn't reset after processing the start bit, which makes it look like the long_limit was reached when it shouldn't have been.   Note: Setting the long_limit high enough will work around this bug.

I will submit a patch (pull request) for the bug. 

This affects the Acurite processing and the LaCrosse TX (temperature/humidity) processing.  See acurite_detect().  

The other devices that use pwm_p_decode are silvercrest and waveman.  Presumably one or both of these depends on the behavior of discarding the start pulse and inverting the bits.  I might submit an alternate pulse width decoder that doesn't have those properties to benefit LaCrosse and Acurite, though I don't currently have any Acurite sensors to test with.

For No. 3, the bug, the fix:
```
        if (!p->real_bits && p->start_bit && (buf[i] < demod->level_limit)) {
            /* end of startbit */
            p->real_bits = 1;
           //  fprintf(stderr, "start bit pulse end detected [@ %d]\n", p->sample_counter);
+            p->sample_counter = 0;   // <<--- i think this was forgotten.
        } 
```

For  reference: No. 1 from pwm_p_decode:
```
if (p->pulse_length <= p->short_limit) {
  demod_add_bit(p, 1);
} else if (p->pulse_length > p->short_limit) {
  demod_add_bit(p, 0);
}
```
vs. pwm_d_decode:
```
if (p->sample_counter < p->short_limit) {
    demod_add_bit(p, 0);
} else if (p->sample_counter < p->long_limit) {
    demod_add_bit(p, 1);
} else {
```

**Comment by rct** [comment]
This got closed as merged, but the fix didn't seem to be in the new master.   I need to do a bit of tracing to see if it got lost or if @helgew deleted it intentionally.   This causes the LaCrosse code not to work.

(I don't see how to re-open this on github,   Do I have to create another issue?)

**Comment by helgew** [comment]
Which pull request included the changes mentioned in the first post on this issue? I only see issues referenced here and the only commit does not seem to have those changes.

**Comment by rct** [comment]
The pull request was PR #69    See: https://github.com/rct/rtl_433/commit/3291c4bf7412139954eab6b516466cdc2ee2e01f

Looks like I may not have cleanly separated the changes because this commit seems to also have the changes that register the LaCrosse callback in it.   See the two changes inside pwm_p_decode:  The actual fix is p->sample_counter = 0,   There was also a change for a commented out debugging fprintf that was printing the wrong value.

Thanks.

**Comment by rct** [comment]
If it helps here's the diff against the current merbanan/master:

```
diff --git a/src/rtl_433.c b/src/rtl_433.c
index 815a6dd..7271401 100644
--- a/src/rtl_433.c
+++ b/src/rtl_433.c
@@ -691,6 +691,7 @@ static void pwm_p_decode(struct dm_state *demod, struct protocol_state* p, int16
         if (!p->real_bits && p->start_bit && (buf[i] < demod->level_limit)) {
             /* end of startbit */
             p->real_bits = 1;
+           p->sample_counter = 0;
             //            fprintf(stderr, "start bit pulse end detected\n");
         }
         if (p->start_c) p->sample_counter++;
@@ -708,7 +709,7 @@ static void pwm_p_decode(struct dm_state *demod, struct protocol_state* p, int16

             p->pulse_length = p->sample_counter - p->pulse_start;
             //           fprintf(stderr, "real bit pulse end detected %d\n", p->pulse_length);
-            //           fprintf(stderr, "space duration %d\n", p->sample_counter);
+            //           fprintf(stderr, "space duration %d\n", p->sample_counter - p->pulse_length);

             if (p->pulse_length <= p->short_limit) {
                 demod_add_bit(p, 1);
```

**Comment by helgew** [comment]
ugh... I am not sure how I failed to see that. I was looking at the code and thought that change was there. My bad!

I updated my pull request, which addresses this.

**Comment by helgew** [comment]
@rct could you maybe submit some Lacrosse sensor data to the test repository? I was banging my head against the reason for the discarded bit in the acurite code and, although I have learned now quite a bit about the PWM decoding, I am not sure that it is generalizable.

The Acurite 5n1, for example, will use "fixed width signals" (I am still lacking all the terminology, so bear with me) where signal pulse and pause added together are always the same (610 us). It first sends a preamble of 4 high and 4 low pulses where highs and lows are 610 us each. Afterwards, it sends signals encoded such that long high and short low (400 us and 210 us respectively) encode a 1 and a short high and long low (210 us/400 us) encode a 0. There is no sync pulse like the pwm_p_decode routine assumes.

The current code will parse this OK since pwm_p_decode has another bug that sets the highest bit in the preceding and following bytes which can be used to set the highest bit of the "real data". However, I am not sure this will work with a different channel setting (the channel is encoded in the first two bits of the data and channel C would require a 0 highest bit.
