### ISSUE TITLE
make recipe failed: undefined reference to flex_create_device

### ISSUE THREAD

**Issue by myself248** [merbanan/rtl_433#673]
Following these instructions:
https://giammaiot.blogspot.it/2017/09/smart-install-rtl433-receiver-on.html

I also had to apt install autoconf, which wasn't listed in their steps. 

everything looked fine through ./configure 
and then make looked fine until here: 

```
  CC       devices/x10_sec.o
  CCLD     rtl_433
rtl_433.o: In function `main':
/home/nate/rtl_433/src/rtl_433.c:1124: undefined reference to `flex_create_device'
collect2: error: ld returned 1 exit status
Makefile:716: recipe for target 'rtl_433' failed
make[2]: *** [rtl_433] Error 1
make[2]: Leaving directory '/home/nate/rtl_433/src'
Makefile:494: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nate/rtl_433'
Makefile:380: recipe for target 'all' failed
make: *** [all] Error 2
```

I fetched the .zip this afternoon, and am running on ubuntu 16.04 LTS

**Comment by zuckschwerdt** [comment]
Those instructions are for windows. You should be fine with (in the top-level rtl_433 dir):
```
mkdir build ; cd build ; cmake .. && make
```
Anyway, thanks for the report! The Makefile bug is now fixed.
