### ISSUE TITLE
Analyze results inaccurate when there is a start/sync pulse of a different length.

### ISSUE THREAD

**Issue by rct** [merbanan/rtl_433#68]
Analyze mode (-a) does a very good job of analyzing many signal types.  However it produces inaccurate results when there is an initial start or sync pulse with different timings than the actual signal.    

Some signals, especially those that are similar to Infrared (IR) signals sent over RF have long initial start/wakeup pulses.  This causes the signals to look pulse width modulated whether they are or not.  

For example the X10 signal uses a NEC style IR signal,   After the long initial pulse, and long space, the signal is distance based.  The initial pulse is approximately 2,250 samples (9,000 uS). Real data pulses are 140 samples (500 uS).

An indication that this is occurring, the number of long pulses will be very small (< 10), such as one for each repeat.   Example for the X10 signal, there were nearly 200 short pulses both only 6 long pulses.  The signal is repeated 6 times.

Primarily I'm opening this issue to provide information for others trying to climb the learning curve. 

```
*** signal_start = 1003048, signal_end = 1175581
signal_len = 172533,  pulses = 204
Iteration 1. t: 1204    min: 144 (198)    max: 2264 (6)    delta 58
Iteration 2. t: 1204    min: 144 (198)    max: 2264 (6)    delta 0
Pulse coding: Short pulse length 144 - Long pulse length 2264

Short distance: 138, long distance: 458, packet distance: 10060

p_limit: 1204

[00] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000
[01] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000
[02] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000
[03] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000
[04] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000
[05] {34} 80 00 00 00 00 : 10000000 00000000 00000000 00000000 00000000

```

The first sync pulse in each message is interpreted as a 1, everything else winds up being interpreted as a 0.

Use debug mode (-D) and look at the pulse_distance lines,  to see the differences.

**Comment by merbanan** [comment]
I think we need to model how common signals look like and use that to help the analyze mode to decode the signals.

**Comment by rct** [comment]
While the old analyzer (-a) doesn't handle start/sync bits of different widths, @vestom's newer ulse analyzer (-A) does provide information on the widths.

**Comment by ygator** [comment]
I guess this is why I am not getting anything to work with on the OS V1.0 Protocol.
How would I got about skipping this sync to get to the real data?

Test mode active. Reading samples from file: 0198821b.data
*** signal_start = 13212, signal_end = 131073
signal_len = 117861,  pulses = 80
Iteration 1. t: 958    min: 479 (78)    max: 1437 (2)    delta 2509
Iteration 2. t: 958    min: 479 (78)    max: 1437 (2)    delta 0
Pulse coding: Short pulse length 479 - Long pulse length 1437

Short distance: 300, long distance: 795, packet distance: 26271

p_limit: 958
bitbuffer:: Number of rows: 2
[00] {40} 00 08 00 00 00 : 00000000 00001000 00000000 00000000 00000000
[01] {40} 00 08 00 00 00 : 00000000 00001000 00000000 00000000 00000000
Test mode file issued 2 packets

**Comment by merbanan** [comment]
The new analyzer -A does a good job with sync signals. Closing issue.
