### ISSUE TITLE
WH25A Version .../13 or .../14 different

### ISSUE THREAD

**Issue by pejonp** [merbanan/rtl_433#693]
Beim WH25A gibt es verschieden Versionen  .../13 oder .../14. 
Die Bits für die Temperatur sind anders. Die CRC-Summe stimmt dann auch nicht.

The WH25A has different versions ... / 13 or ... / 14.
The bits for the temperature are different. The CRC sum is then wrong.

file: fineoffset.c
line 180...

uint8_t tempkorr = 0;
    bitsum = (bitsum << 4) | (bitsum >> 4);     // Swap nibbles
    if (checksum != buffer[9]) {
       if (debug_output) {
            fprintf(stderr, "Fineoffset_WH25: Checksum error2: %02x %02x %02x %02x\n", checksum, buffer[9], bitsum, buffer[10]);
            bitbuffer_print(bitbuffer);
       }
       tempkorr = 0; 
       return 0;
    }
    if (checksum != buffer[9] || bitsum != buffer[10]) {
       if (debug_output) {
            fprintf(stderr, "Fineoffset_WH25: Checksum error1: %02x %02x %02x %02x\n", checksum, buffer[9], bitsum, buffer[10]);
            bitbuffer_print(bitbuffer);
       }
       tempkorr = 0; 
        //return 0;
    } else {
       tempkorr = 1;    
    } 
       if (debug_output) {
            fprintf(stderr, "Fineoffset_WH25: Checksum: %02x %02x %02x %02x %01x\n", checksum, buffer[9], bitsum, buffer[10], tempkorr);
            bitbuffer_print(bitbuffer);
       }
    // Decode data
    uint8_t id = (buffer[3] << 4) | (buffer[4] >> 4);
    float temperature = (float)((uint16_t)(buffer[4] & 0xF) << 8 | buffer[5]) / 10.0 - 40.0;
      if (tempkorr == 1)
    {
       temperature = (float)((uint16_t)(buffer[4] & 0x2) << 8 | buffer[5]) / 10.0 - 40.0; // WH25A ab Releas 20/14 andere Temp-Darstellung
    }

**Comment by merbanan** [comment]
Sample signals are missing. Closing issue.
