### ISSUE TITLE
New device: Wind Sensor Oregon Scientific WGR800 

### ISSUE THREAD

**Issue by andresol** [merbanan/rtl_433#695]
(2018-03-12 19:52:29,WGR800,101,0,OK,,,,,,,OS,,,0.000,0.000,225.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
)

**Comment by merbanan** [comment]
Reopen with more info.
