### ISSUE TITLE
Acurite 3 in 1 support

### ISSUE THREAD

**Issue by christislord** [merbanan/rtl_433#696]
I would like support for the Acurite 3 in 1 weather station.  There is already support for the 5 in 1, and it looks like you wanted test files for the 3 in 1.  Here are some test files. https://www.dropbox.com/s/yhp7cu24tgxc1qq/Acurite3In1.zip?dl=0

**Comment by zuckschwerdt** [comment]
thanks, see #720 for a basic decoder. Needs testing/comparison to wall unit values.
