### ISSUE TITLE
Decode all protocols, save files and view in real time? (rtl_433 -G -t)

### ISSUE THREAD

**Issue by 0ut0fb0unds** [merbanan/rtl_433#697]
Is it possible to decode all protocols (-G) while viewing the results on stdout and saving to individual files (-t)?

It seems to me that` rtl_433 -G -a -t `saves files, and appears to register all 100 decoders, but the -a means I don't see the decoded messages on stdout.

I tried `rtl_433 -G -t` and it showed decoded messages on stdout, but did not appear to save any files.

**Comment by merbanan** [comment]
Hopefully the refactoring work will allow this feature.

**Comment by merbanan** [comment]
The new signal recording feature will support this scenario.
