### ISSUE TITLE
ThermoPro TP-65  == Prologue

### ISSUE THREAD

**Issue by epruesse** [merbanan/rtl_433#699]
It appears the ThermoPro TP-65 sensor uses the same chip/protocol as the Prologue sensor. Channel, Button, Temperature and Humidity match what I see on the base station. Battery I haven't verified yet.

**Comment by zuckschwerdt** [comment]
Do you have some samples to add to the tests repo?

**Comment by merbanan** [comment]
No response for a while closing issue.
