### ISSUE TITLE
Failed to open rtlsdr device error

### ISSUE THREAD

**Issue by sergray** [merbanan/rtl_433#740]
I got this error, which is clearly a permission issue:
```
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Failed to open rtlsdr device #0.
```

Found a solution following http://www.instructables.com/id/rtl-sdr-on-Ubuntu/, but it would be nice to   describe how to create rtl-sdr.rules within the project and provide example file.

**Comment by merbanan** [comment]
Can you create a PR ? If not we'll leave this issue open for tracking.

**Comment by zuckschwerdt** [comment]
The first two lines of that error message (the instructive part…) are from [librtlsdr](https://github.com/osmocom/rtl-sdr/blob/master/src/librtlsdr.c#L1493). An enhancement of that message would best be placed there.

**Comment by sergray** [comment]
@zuckschwerdt thanks for the hint! There's available even an example of the rules https://github.com/osmocom/rtl-sdr/blob/master/rtl-sdr.rules

I'm going to try to see how to resolve it in the best possible way.

**Comment by zuckschwerdt** [comment]
Great! This issue and your link will likely also help out if people search for the message here :)

**Comment by lnee94** [comment]
Note if you run in to this problem, check if the user you are using is in the `plugdev` group

**Comment by typpos** [comment]
FWIW this error also occurs when another application uses the device, making he error message quite misleading.

* RTL2832
* Windows 10 Pro
* Airspy SDR# v1.0.0.1910
* rtl_433 v22.11-23-g4c495fd3
