### ISSUE TITLE
Feature: output protocol numbers at startup

### ISSUE THREAD

**Issue by zuckschwerdt** [merbanan/rtl_433#743]
The `Registering protocol [x]` output at startup should list the protocol numbers as with `-h`, not just an index. See https://groups.google.com/forum/#!topic/rtl_433/OXOC_5qoBKc

**Comment by merbanan** [comment]
The index is kinda useless in this case. Better replace it with the real id.

**Comment by zuckschwerdt** [comment]
Yes, I'm pretty sure I once made the mistake of using that index with -R myself :) I'll look into it next week.

**Comment by gdt** [comment]
Related: having -h output the driver list makes help output way too long.   So I suggest having a command to list the drivers, and to remove the driver list from -h.    I find the list of registering all drivers to be very voluminous on regular startup, so I also suggest omitting the driver list unless specific drivers were requested.  In the default case, a "registered 80 drivers" would suffice.

**Comment by merbanan** [comment]
Is this issue completed?
