### ISSUE TITLE
Add metadata to decodes

### ISSUE THREAD

**Issue by gdt** [merbanan/rtl_433#745]
Currently, the decoded output (json in particular) does not have metadata about the decoded packet.  This information is interesting, and seems good to add.  Specifically, I'd like to see:
 - frequency
 - signal to noise ratio (somehow)
 - probably any other decoder parameters that were estimated and used

**Comment by zuckschwerdt** [comment]
Understandably. I'm working on some of these, at low priority though.

**Comment by merbanan** [comment]
modulation
repeats
bits in message/total
ms length of ones and zeros

I think that if it would be possible to synthesize a signal based on the message and the metadata then that should cover almost all possible use of this

**Comment by zuckschwerdt** [comment]
Some meta data stats will be implemented with  #733

**Comment by frief** [comment]
having RSSI as metadata would be great. Could e.g. be used to assess antenna polarization of a sender.
