### ISSUE TITLE
2Gig DW10 Support

### ISSUE THREAD

**Issue by iautom8things** [merbanan/rtl_433#746]
Hi there!  Thank you for a great open source project!

I'm a bit outside my wheelhouse, although I have a technical background.  I'm pretty lost when it comes to radios.

I was trying to follow along [this guide for Home Assistant](https://community.home-assistant.io/t/honeywell-5800-series-345mhz-door-and-window-sensor-integration-with-ha/18970) which involves using this tool.  Unfortunately, it appears that [my door contacts](https://www.2gig.com/products/sensors/thin-doorwindow-contact/) are not supported.  From what I can tell, the sensors are not being picked up by my rtl-sdr.  [Here is what I see](https://gist.github.com/mazubieta/669f6d2573c837a00709d592a53ecb5f) when I execute `rtl_433 -f 344975000`.

If it'd be helpful, I'd gladly send a sensor out to you.

Thanks!

**Comment by mazubieta** [comment]
Ugh ... So good news, I tried reading through some other issues and I found the `-A` `-a` and `-t` flags that seem to be what people send y'all.  I was able to get some sample output from the 2gig DW10 and another device I was hoping to use, the [Resolution Products RE208](http://resolutionproducts.com/sdm_downloads/re208-hardwire-to-honeywell-translator/).

I've uploaded those `.cu8` files to this repo:

https://github.com/mazubieta/rtl-sdr-captures

Please let me know if there's anything else I can do to help.  Or if there's guidance on what the next steps would be to figure out the messages.

Thanks!

**Comment by zuckschwerdt** [comment]
Looks like Manchester encoded with a half-bit period of ~150µs. This will work:
```
rtl_433 -q -F json -R 0 -X '2gigdw10-re208:OOK_MC_ZEROBIT:150:150:300' -r g011_344.975M_250k.cu8
```

**Comment by mazubieta** [comment]
Thank you for such a quick response!

So yes, that command worked for ready the capture files.  I see lines like this:

```json
{"time" : "@0.000000s", "model" : "2gigdw10-re208", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 63, "data" : "0002fa635dbe7dba"}], "codes" : ["{63}0002fa635dbe7dba"]}
```

Trying to explore what you gave me and apply it for my uses, I tried dropping the `-r` flag in an attempt to see a live capture:

`rtl_433 -f 344975000 -F json -R 0 -X '2gigdw10-re208:OOK_MC_ZEROBIT:150:150:300'`

And I do see the events, now! Thank you!!
```json
{"time" : "2018-06-09 11:25:55", "model" : "2gigdw10-re208", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 64, "data" : "00015edf297f363f"}], "codes" : ["{64}00015edf297f363f"]}
{"time" : "2018-06-09 11:25:55", "model" : "2gigdw10-re208", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 64, "data" : "00015edf297f363f"}], "codes" : ["{64}00015edf297f363f"]}
{"time" : "2018-06-09 11:25:56", "model" : "2gigdw10-re208", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 64, "data" : "00015edf297f363f"}], "codes" : ["{64}00015edf297f363f"]}
{"time" : "2018-06-09 11:25:56", "model" : "2gigdw10-re208", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 64, "data" : "00015edf297f363f"}], "codes" : ["{64}00015edf297f363f"]}
```

So it seems the next step is to decipher the data that is included: `00015edf297f363f`.  Would this be considered outside the scope of `rtl_433`?  If so, if I'm on my own, would you please be able to point in the right direction for tackling that?

**Comment by merbanan** [comment]
If they keep state and can be configured for an id then it might be complex enough to warrant a dedicated decoder. If it just send this only signal then not.

**Comment by mazubieta** [comment]
They send more than just this one signal.  But I'm uncertain about the ability to configure them.  I'll try to test with multiple sensors to see if the data changes between them.

I can tell you feature-wise they support identifying different sensors, so they _should_ have an `ID` packed somewhere in there.  And then at the very least they send some type of `open`, `closed`, `tamper`, and `low battery` signals to the head unit.

**Comment by mazubieta** [comment]
Here is a small sample of the codes I've seen, just in the past few minutes:

```
00015edf295fba0f
00015edf297f363f
0002fa634fbe11ba
0002fa6351be55ba
0002fa6353bf59bc
0002fa6355bf4dbc
0002fa6357be41ba
0002fa6359fe643a
0002fa635bff683c
0002fa635dff7c3c
0002fa635fef705c
```

Unfortunately, I have about a dozen of these sensors in use (plus the RE208 which watches 8 hardwired sensors on its own).

I can see how this will be difficult without a specification from the manufacturers.  I had come across someone suggesting that you might be able to find information on what is sent by looking up the FCC filing?  Is this _a thing_?

**Comment by mazubieta** [comment]
I should note, I had come across this repo ([fusterjj/HoneywellSecurityMQTT](https://github.com/fusterjj/HoneywellSecurityMQTT/blob/master/src/digitalDecoder.cpp)) that claims to be able to work with the 2gig sensors, but had no luck getting it to work.  But maybe it can provide some insight on what the codes means?

**Comment by zuckschwerdt** [comment]
That code has a payload definition and a CRC. We can make a decoder for that protocol. Expect something in a few days.

**Comment by mazubieta** [comment]
Awesome!  Thank you!

Would it be safe to assume that the 2gig DW10 and the RE-208 have similar payloads?  Could this be used for both, or should I continue to search for answers on the RE-208 separately?

**Comment by zuckschwerdt** [comment]
They look the same. Do you get similar codes?

**Comment by mazubieta** [comment]
I _just_ noticed that the 2gig sensors report a 64 bit payload whereas the re-208 reports a 63 bit payload.  Here are some manual tests I just did:

# 2gig 
## sensor 1
open: 00015edf295fba0f
close: 00015edf297f363f
tamper open: 00015edf291f223f
tamper closed: 00015edf295fba0f

## sensor 2
open: 00015213685f0f2f
close: 00015213687f831f
tamper open: 00015213681f971f
tamper closed: 00015213685f0f2f


# re-208
## sensor 1
open: 0002fa635dbe7dba
close: 0002fa635dff7c3c

## sensor 2
open: 0002fa635bbe69ba
close: 0002fa635bff683c

## sensor 3
open: 0002fa6359bf65bc
close: 0002fa6359fe643a

## tamper
open: 0002fa635f6e735a
close: 0002fa635fef705c

And these two were seen but did not correlate with an intentional action. So I'm not sure if they might be some kind of _heartbeat_ signal?  These were all 64bit, so I'm assuming from some of my 2gig sensors.

0001d8bab5ff993f
00015b62c65fa9af
000147bf88fb2daf
00015213685b8e9f

**Comment by zuckschwerdt** [comment]
The bits here are inverted and the sync preamble should be 0xfffe. Allowing for a few missing bits at the start (you noticed packets shorter than 64 bits) this gives you the aligned and correct payload:
```
rtl_433 -q -F json -R 0 -X '2gigdw10-re208:OOK_MC_ZEROBIT:150:150:300,invert,preamble=ffe' -r g001_344.975M_250k.cu8
```
The 2GIG start with `a`, the RE208 with `8`. Proper decoder to follow soon.

**Comment by merbanan** [comment]
We need sample signals. Can you record some ?

**Comment by zuckschwerdt** [comment]
Actually I realize, it's just a minor tweak to fix the somewhat picky `Honeywell Door/Window Sensor` device.

**Comment by zuckschwerdt** [comment]
@merbanan I'll add the signals from @mazubieta 's repo to the honeywell folder.

**Comment by mazubieta** [comment]
I can record more if it'll help?  I have about several 2gig sensors and 4 lines hooked up to the RE208.

**Comment by mazubieta** [comment]
I just added another tar file with mixed events from both the 2gig and re208

**Comment by zuckschwerdt** [comment]
#747 should work for 2Gig and RE208

**Comment by merbanan** [comment]
Can this be closed? I tried the decoder with the mentioned samples and they seemed to work fine.

**Comment by merbanan** [comment]
@zuckschwerdt ping
