### ISSUE TITLE
rtl_433.h:48:30: error: unknown type name ‘uint8_t’

### ISSUE THREAD

**Issue by 0xFACE** [merbanan/rtl_433#76]
Can't build rtl_433 now:
/rtl_433.h:48:30: error: unknown type name ‘uint8_t’

I added #include<stdint.h> to workaround.

**Comment by helgew** [comment]
It compiles fine for me... what platform are you compiling on and what is the include you added?

**Comment by 0xFACE** [comment]
Linux raspberrypi 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014 armv6l GNU/Linux
I included "stdint.h".

**Comment by helgew** [comment]
I'll submit a patch... stdint.h is included via rtl-sdr.h, which is included in rtl_433.c. This works for my setup, but apparently, different compilers handle that differently.

**Comment by 0xFACE** [comment]
Ok, works now.
