### ISSUE TITLE
Wrong content in output csv and json file.

### ISSUE THREAD

**Issue by davidwowa** [merbanan/rtl_433#763]
Hi, 
I used two commands:

`rtl_433 -F csv /home/pi/.433Mhz_data.csv` and `rtl_433 -F json /home/pi/.433Mhz_data.json` in both cases the output file is not readable. 

The content of file shows so `H???XxñR?T?l????y?a??1??"?b?t?ޔ?¿?.?u:lI?+?Yϗq?v?g?c?SsAe?=?c׃?؅?P?;?rwoB?9؋???˃?4?R?LPy?hπ?p????m?R?8ft ?J?:?t??B?R??<Glq?<?iƃ?ֈ?¡?"?9Sk4s9?^?vl?o?Y?...`

Where is the problem?

Thx for help.

**Comment by zuckschwerdt** [comment]
Thats not how the output works, you dumped a raw sample stream.
```
	[-F] kv|json|csv|syslog Produce decoded output in given format. Not yet supported by all drivers.
		 append output to file with :<filename> (e.g. -F csv:log.csv), defaults to stdout.
		 specify host/port for syslog with e.g. -F syslog:127.0.0.1:1514
```
and
```
	[<filename>] Save data stream to output file (a '-' dumps samples to stdout)
```
