### ISSUE TITLE
see what protocol is being used

### ISSUE THREAD

**Issue by ghost** [merbanan/rtl_433#767]
is there a way to see what protocol is being used when data is being displayed or is the only way to enable  one at a time?

**Comment by zuckschwerdt** [comment]
Interesting point. You'd have to compare the "model" key in the output with the listing of `rtl_433 -h`. But the listing will be more verbose than the model-key and there might be multiple possible model's per decoder.
We should perhaps include the protocol number with the data output.

**Comment by merbanan** [comment]
@zuckschwerdt maybe this should be added to the -M option ?

**Comment by merbanan** [comment]
@zuckschwerdt I sort of need this for my next steps. Is this a quick fix for you are should I do this?

**Comment by zuckschwerdt** [comment]
This needs #905 to go in first, but the win32 implementation is untested. I guess I'll merge anyway and win32 needs to be fixed later ;)

**Comment by zuckschwerdt** [comment]
I snuck this in with 0e99cb2 now.
