### ISSUE TITLE
Noob question - sorry in advance

### ISSUE THREAD

**Issue by mlava** [merbanan/rtl_433#792]
Hi there.
IT seems this library will be perfect for replacing my old NinjaBlock, but having some trouble. I apologise in advance for noob questions and will be grateful for responses.

1. I assume I can run this on RPi without the SDR radio but using a 433Mhz receiver?
2. If so, how do I tell the software which GPIO to listen to? At present, I get 'No supported devices found' with any command.

Thanks again.

**Comment by merbanan** [comment]
There is no support for this type of hardware currently. Patches are welcome.
