### ISSUE TITLE
rtl_433 -q -F json throws a usb_claim_interface error -6

### ISSUE THREAD

**Issue by juergenschubert** [merbanan/rtl_433#795]
rtl_433 -q -F json on my raspberry PI is telling me:
usb_claim_interface error -6

**Comment by zuckschwerdt** [comment]
try `sudo rtl_433 -q -F json`. It's not an error originating with rtl_433.

**Comment by panarom** [comment]
@juergenschubert make sure the raspberryPi user is in the appropriate group to access USB, if you don't want to run it as root

**Comment by ms-jdow** [comment]
Nonetheless that is an rtlsdr.dll error not one in the program itself. Do you have the dongle opened by another program as well as the rtl433 program? What does rtl_test.exe tell you?

Break the diagnosis process into pieces. First determine that other programs can access the dongle. When rtl_test works then look to other places the error might happen.

Within rtlsdr.dll the program flow is roughly:
Initialize libusb to get a working context.
Get a list of devices and see if the device requested is listed.
Open the device. (This only means libusb associates the program with the dongle.) We get a device handle.
Query if the device is already active. If it is make an attempt to change that status or print an error.
Finally it tries to claim the interface "libusb_claim_interface".
The error -6 is LIBUSB_ERROR_BUSY. The device is already busy. There should be an attempt to detach it from drivers such as the mouse driver which may have claimed it. But you may have to get down and dirty with Linux to tell it to leave the dongle alone so you can work with it.
{^_^}

**Comment by merbanan** [comment]
Not a rtl_433 problem, closing issue.

**Comment by ab1jx** [comment]
It seems to be a librtlsdr issue.  I have a program I wrote a year ago that works, then I tried to reuse some of the same subroutines in a new program and I get this error.  Same computer, same librtlsdr, same dongle.  The old program still works, not the new one.  The problem seems to go dormant and come back.  Maybe it's a libusb issue.

**Comment by zuckschwerdt** [comment]
Unlikely to be a software problem. Might be drivers in a very specific setup, but I'd guess boot-up power consumption is too much to properly initialize the RTL-SDR. Try a better supply or a powered hub maybe.

**Comment by zuckschwerdt** [comment]
More likely something about the USB initialization on the Pi 4 then? You could try a powered hub or otherwise try with nothing else connected to USB.

**Perhaps other users of the Pi 4 can add their findings on this?**
