### ISSUE TITLE
"Always classify a signal at the end of the file" <-- I don't think this works as desired

### ISSUE THREAD

**Issue by winterrace** [merbanan/rtl_433#808]
Within the main() function the

`if (in_filename) {`
branch ends with:

```
        //Always classify a signal at the end of the file
        classify_signal();
        if (!quiet_mode) {
            fprintf(stderr, "Test mode file issued %d packets\n", n_blocks);
        }
        free(test_mode_buf);
        free(test_mode_float_buf);
        exit(0);
    }
```
The classify_signal() funktion works on data in the global array signal_pulse_data.
This array is filled by the pwm_analyze function, which is invoked during each call of the rtlsdr_callback function (which is also used by the above mentioned code region to process the data from the input file).

**BUT:**
pwm_analyze is only called by rtlsdr_callback under certain conditions:

```
    if (demod->analyze || (demod->out_file == stdout)) {    // We don't want to decode devices when outputting to stdout
        pwm_analyze(demod, demod->am_buf, n_samples);
    }
```

**This means:**
The above-mentioned call of classify_signal will only work on meaningful data if rtl_433 was either called with "-a" (--> demod->analyze == 1) or an output file specified (along with the input file name specified by -r)

**Comment by merbanan** [comment]
All this is old stuff that never got cleaned out. -a mode should be deprecated but it is needed for the signal grabbing functionality -a -t. The amount of cases where the -A analyzer can't decode what the -a mode can is fairly small so as long as -t works the -a mode could be removed.

**Comment by merbanan** [comment]
All this is in need of some rework. I the beginning I just wanted something functional quickly. Maybe do a release and then start cleaning out the old unmaintainable stuff.

**Comment by pdo-smith** [comment]
_The amount of cases where the -A analyzer can't decode what the -a mode can is fairly small so as long as -t works the -a mode could be removed._

I find the -a mode incredibly useful and have built my code around this feature. I would hate to see this removed. The -a mode is a real strength of rtl_433.

**Comment by zuckschwerdt** [comment]
@pdo-smith thanks for the feedback. You really shouldn't build on the output of either analyzer though, it's purely diagnostic output and may be changed from time to time.

**Comment by zuckschwerdt** [comment]
This has been refactored and there will be more changes. Basically I want to have all analyzers decoupled and as possible option if you want the output. Then there could also be more analyzers and perhaps raw data outputs (similar to the dumpers).
Closing as this will be addressed soon.
