### ISSUE TITLE
There are 3(!) instances of "Template decoder" in the protocol list

### ISSUE THREAD

**Issue by winterrace** [merbanan/rtl_433#848]
[08]  LaCrosse TX Temperature / Humidity Sensor
**[09]\* Template decoder**
[10]* Acurite 896 Rain Gauge
(...)
[64]  Honda Car Key
**[65]\* Template decoder
[66]\* Template decoder**
[67]  Radiohead ASK

Also new_template.c states...
> This device is disabled by default. Enable it with **-R 61** on the commandline

...which is outdated.

**Comment by zuckschwerdt** [comment]
Those are protocol keys were removed at some point. Possibly they shouldn't be listed at all.
I'll take a look.

**Comment by zuckschwerdt** [comment]
Fixed with 2ceb535
