### ISSUE TITLE
Question re appropriate use of rtl_433

### ISSUE THREAD

**Issue by pdo-smith** [merbanan/rtl_433#853]
The background
I have a bunch of motion sensors, push buttons and panic alarms from various sources. I want to create an integrated system that will take these various inputs and then take appropriate actions.

The broad solution.
I want to use rtl_433 to receive these many different signals. I will write the C programs that will sound alarms, lock doors, take video images, send alerts, manage testing and setup. This program will become an extension of rtl_w33. My first approach was to call my functions from within the device decoders. This seemed neat, clean and easily extensible.

The problem.
It became very difficult to recognise all the devices. For example the Quhhwa motion sensors and buttons could not be reliably recognised. And this was true of other devices. I have a motley collection. But then I realised, from a lot of testing, that the -a option, which calls classify_signal and does bitbuffer_print, always reliably gives the right results. b[0], b[1] and [b3] are unique for each device and tell me all I want to know. It seemed that this would solve all my problems.

The proposed solution.
Always invoke rtl_433 with the -a option but suppress printing in classify_signal. Instead I will call my own function which will examine b[0], b[1] and b[2], using this to identify the device and then call further functions to take appropriate action.

My question.
Have I overlooked something? Is there a reason why this may be a bad approach.

So far.
It works and my motley collection of devices are easily recognisable, allowing me to take the appropriate action.

The drawbacks?
There will be no clean separation between my code and that of rtl_433, making further updates problematic. I will mitigate this by confining my changes as much as possible to one place, calling my functions much in the manner that the device decoders are called.

Advice, guidance, opinions and warnings are all welcome.

**Comment by merbanan** [comment]
Well a solution would be to create reliable decoders. That way you can build a solution that uses existing supported api's. To get there I suggest you open bug reports against the protocol decoders that you need. Use the facility to record the signals to reproduce the issue. If the -a analyzer can decode the signals properly then a protocol decoder can do that also. So when those issues are fixed you can continue to create your program.

**Comment by zuckschwerdt** [comment]
For integration look at e.g. http://triq.net/articles/rtl-433-networking -- use a well defined interface and not the messages from stdout.
Write a bridge/relay/handler in the most appropriate language for you/the task. There are some examples in python -- weapon of choice for script like filtering and triggering of actions.
If your network is well integrated you might also want to use MQTT. rtl_433 will support MQTT natively someday.

For the decoder look at the flex device (`-X`) -- if `-a` / `-A` can receive it, then flex can receive it reliably. Filtering, data extraction and JSON is also available with flex.
Try https://github.com/merbanan/rtl_433/pull/790 esp. for hints look at https://github.com/zuckschwerdt/rtl_433/blob/feat-conf/rtl_433.example.conf#L262

You may open issues to get help with analyzing a protocol. But please don't go to the trouble of writing decoders for simple security / doorbell / clicker devices. Flex is the solution there, PR with a conf file welcome!

**Comment by pdo-smith** [comment]
Thanks. The flex approach looks interesting and I will try it out.

**Comment by zuckschwerdt** [comment]
I'll try to add `-X spec` hints to the analyze output tomorrow :)

**Comment by pdo-smith** [comment]
I like your json approach. That is the route I will go. I will create a json server to accept the messages, manage the integration of the devices and take required actions. This will result in nice, clean separation of functions. As it happens I have just been working on a json server.
