### ISSUE TITLE
Sdr# intergration

### ISSUE THREAD

**Issue by kevtheskin** [merbanan/rtl_433#869]
Hi all, Will anybody in the near future be making a Sdr# pluggin for 433 decoding?

Cheers Kev

**Comment by zuckschwerdt** [comment]
A few more months and the rtl_433 project is ready to be used from plugins for GUIs. I don't know of any plans to make a SDR# plugin though.

**Comment by merbanan** [comment]
@kevtheskin with the current stdin support and the upcoming rtl-tcp support it should be straight forward to implement a plugin. Just send raw iq to rtl_433 and present the output in some way. Doing the actual plugin will not be part of the rtl_433 project, someone else will have to do that. Closing issue.

**Comment by kevtheskin** [comment]
Hello there , Any new updates for plugins?

Cheers Kev

**Comment by zuckschwerdt** [comment]
Basic API should be there in 1-2 months. Building rtl_433 into some kind of plugin can start from that point.
