### ISSUE TITLE
make: *** [all] Error 2 on CentOS 7

### ISSUE THREAD

**Issue by pclov3r** [merbanan/rtl_433#87]
I'm unable to compile this on CentOS 7

The <stdint.h> patch doesn't fix the problem as it did for others it appears. This is in my rtl_433.h file.

[root@CentOS build]# cmake ../
-- The C compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- checking for module 'libusb-1.0'
--   found libusb-1.0, version 1.0.15
-- Found libusb-1.0: /usr/include/libusb-1.0, /usr/lib64/libusb-1.0.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Udev rules not being installed, install them with -DINSTALL_UDEV_RULES=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/rtl_433/build
[root@CentOS build]# make
Scanning dependencies of target rtlsdr_shared
[  3%] Building C object src/CMakeFiles/rtlsdr_shared.dir/librtlsdr.c.o
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘e4000_exit’:
/usr/local/src/rtl_433/src/librtlsdr.c:104:22: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int e4000_exit(void *dev) { return 0; }
                      ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc0012_exit’:
/usr/local/src/rtl_433/src/librtlsdr.c:148:23: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc0012_exit(void *dev) { return 0; }
                       ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc0012_set_bw’:
/usr/local/src/rtl_433/src/librtlsdr.c:154:25: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc0012_set_bw(void *dev, int bw) { return 0; }
                         ^
/usr/local/src/rtl_433/src/librtlsdr.c:154:34: warning: unused parameter ‘bw’ [-Wunused-parameter]
 int fc0012_set_bw(void *dev, int bw) { return 0; }
                                  ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc0012_set_gain_mode’:
/usr/local/src/rtl_433/src/librtlsdr.c:156:32: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc0012_set_gain_mode(void *dev, int manual) { return 0; }
                                ^
/usr/local/src/rtl_433/src/librtlsdr.c:156:41: warning: unused parameter ‘manual’ [-Wunused-parameter]
 int fc0012_set_gain_mode(void *dev, int manual) { return 0; }
                                         ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc0013_exit’:
/usr/local/src/rtl_433/src/librtlsdr.c:159:23: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc0013_exit(void *dev) { return 0; }
                       ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc0013_set_bw’:
/usr/local/src/rtl_433/src/librtlsdr.c:163:25: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc0013_set_bw(void *dev, int bw) { return 0; }
                         ^
/usr/local/src/rtl_433/src/librtlsdr.c:163:34: warning: unused parameter ‘bw’ [-Wunused-parameter]
 int fc0013_set_bw(void *dev, int bw) { return 0; }
                                  ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc2580_exit’:
/usr/local/src/rtl_433/src/librtlsdr.c:167:23: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc2580_exit(void *dev) { return 0; }
                       ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc2580_set_bw’:
/usr/local/src/rtl_433/src/librtlsdr.c:171:34: warning: unused parameter ‘bw’ [-Wunused-parameter]
 int fc2580_set_bw(void *dev, int bw) { return fc2580_SetBandwidthMode(dev, 1); }
                                  ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc2580_set_gain’:
/usr/local/src/rtl_433/src/librtlsdr.c:172:27: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc2580_set_gain(void *dev, int gain) { return 0; }
                           ^
/usr/local/src/rtl_433/src/librtlsdr.c:172:36: warning: unused parameter ‘gain’ [-Wunused-parameter]
 int fc2580_set_gain(void *dev, int gain) { return 0; }
                                    ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘fc2580_set_gain_mode’:
/usr/local/src/rtl_433/src/librtlsdr.c:173:32: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int fc2580_set_gain_mode(void *dev, int manual) { return 0; }
                                ^
/usr/local/src/rtl_433/src/librtlsdr.c:173:41: warning: unused parameter ‘manual’ [-Wunused-parameter]
 int fc2580_set_gain_mode(void *dev, int manual) { return 0; }
                                         ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘r820t_exit’:
/usr/local/src/rtl_433/src/librtlsdr.c:180:22: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int r820t_exit(void *dev) { return 0; }
                      ^
/usr/local/src/rtl_433/src/librtlsdr.c: In function ‘r820t_set_bw’:
/usr/local/src/rtl_433/src/librtlsdr.c:182:24: warning: unused parameter ‘dev’ [-Wunused-parameter]
 int r820t_set_bw(void *dev, int bw) { return 0; }
                        ^
/usr/local/src/rtl_433/src/librtlsdr.c:182:33: warning: unused parameter ‘bw’ [-Wunused-parameter]
 int r820t_set_bw(void *dev, int bw) { return 0; }
                                 ^
[  6%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_e4k.c.o
[  9%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0012.c.o
[ 12%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0013.c.o
[ 15%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc2580.c.o
/usr/local/src/rtl_433/src/tuner_fc2580.c: In function ‘fc2580_wait_msec’:
/usr/local/src/rtl_433/src/tuner_fc2580.c:124:29: warning: unused parameter ‘pTuner’ [-Wunused-parameter]
 void fc2580_wait_msec(void *pTuner, int a)
                             ^
/usr/local/src/rtl_433/src/tuner_fc2580.c:124:41: warning: unused parameter ‘a’ [-Wunused-parameter]
 void fc2580_wait_msec(void *pTuner, int a)
                                         ^
[ 18%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_r820t.c.o
/usr/local/src/rtl_433/src/tuner_r820t.c: In function ‘R828_Delay_MS’:
/usr/local/src/rtl_433/src/tuner_r820t.c:207:8: warning: unused parameter ‘pTuner’ [-Wunused-parameter]
  void *pTuner,
        ^
/usr/local/src/rtl_433/src/tuner_r820t.c:208:16: warning: unused parameter ‘WaitTimeMs’ [-Wunused-parameter]
  unsigned long WaitTimeMs
                ^
/usr/local/src/rtl_433/src/tuner_r820t.c: In function ‘R828_Filt_Cal’:
/usr/local/src/rtl_433/src/tuner_r820t.c:2484:66: warning: unused parameter ‘R828_BW’ [-Wunused-parameter]
 R828_ErrCode R828_Filt_Cal(void *pTuner, UINT32 Cal_Freq,BW_Type R828_BW)
                                                                  ^
Linking C shared library librtlsdr.so
[ 18%] Built target rtlsdr_shared
Scanning dependencies of target rtl_433
[ 21%] Building C object src/CMakeFiles/rtl_433.dir/rtl_433.c.o
/usr/local/src/rtl_433/src/rtl_433.c: In function ‘debug_callback’:
/usr/local/src/rtl_433/src/rtl_433.c:40:66: warning: unused parameter ‘bits_per_row’ [-Wunused-parameter]
 int debug_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                  ^
/usr/local/src/rtl_433/src/rtl_433.c: In function ‘sighandler’:
/usr/local/src/rtl_433/src/rtl_433.c:189:28: warning: unused parameter ‘signum’ [-Wunused-parameter]
 static void sighandler(int signum) {
                            ^
[ 25%] Building C object src/CMakeFiles/rtl_433.dir/devices/silvercrest.c.o
[ 28%] Building C object src/CMakeFiles/rtl_433.dir/devices/rubicson.c.o
[ 31%] Building C object src/CMakeFiles/rtl_433.dir/devices/prologue.c.o
/usr/local/src/rtl_433/src/devices/prologue.c: In function ‘prologue_callback’:
/usr/local/src/rtl_433/src/devices/prologue.c:32:32: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
         (bb[1][3] == bb[2][3]) && (bb[1][4] == bb[2][4])) {
                                ^
[ 34%] Building C object src/CMakeFiles/rtl_433.dir/devices/waveman.c.o
[ 37%] Building C object src/CMakeFiles/rtl_433.dir/devices/steffen.c.o
[ 40%] Building C object src/CMakeFiles/rtl_433.dir/devices/elv.c.o
[ 43%] Building C object src/CMakeFiles/rtl_433.dir/devices/lacrosse.c.o
[ 46%] Building C object src/CMakeFiles/rtl_433.dir/devices/acurite.c.o
/usr/local/src/rtl_433/src/devices/acurite.c: In function ‘acurite_rain_gauge_callback’:
/usr/local/src/rtl_433/src/devices/acurite.c:135:86: warning: unused parameter ‘bits_per_row’ [-Wunused-parameter]
 static int acurite_rain_gauge_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                                      ^
/usr/local/src/rtl_433/src/devices/acurite.c: In function ‘acurite_th_callback’:
/usr/local/src/rtl_433/src/devices/acurite.c:157:78: warning: unused parameter ‘bits_per_row’ [-Wunused-parameter]
 static int acurite_th_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                              ^
[ 50%] Building C object src/CMakeFiles/rtl_433.dir/devices/oregon_scientific.c.o
/usr/local/src/rtl_433/src/devices/oregon_scientific.c: In function ‘get_os_temperature’:
/usr/local/src/rtl_433/src/devices/oregon_scientific.c:3:63: warning: unused parameter ‘sensor_id’ [-Wunused-parameter]
 float get_os_temperature(unsigned char *message, unsigned int sensor_id) {
                                                               ^
/usr/local/src/rtl_433/src/devices/oregon_scientific.c: In function ‘get_os_humidity’:
/usr/local/src/rtl_433/src/devices/oregon_scientific.c:11:67: warning: unused parameter ‘sensor_id’ [-Wunused-parameter]
 unsigned int get_os_humidity(unsigned char *message, unsigned int sensor_id) {
                                                                   ^
/usr/local/src/rtl_433/src/devices/oregon_scientific.c: In function ‘oregon_scientific_v2_1_parser’:
/usr/local/src/rtl_433/src/devices/oregon_scientific.c:55:88: warning: unused parameter ‘bits_per_row’ [-Wunused-parameter]
 static int oregon_scientific_v2_1_parser(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                                        ^
/usr/local/src/rtl_433/src/devices/oregon_scientific.c: In function ‘oregon_scientific_v3_parser’:
/usr/local/src/rtl_433/src/devices/oregon_scientific.c:251:2: error: expected ‘}’ before ‘else’
  else if ((msg[0] == 0x19) && (msg[1] == 0x84)) {
  ^
/usr/local/src/rtl_433/src/devices/oregon_scientific.c:192:86: warning: unused parameter ‘bits_per_row’ [-Wunused-parameter]
 static int oregon_scientific_v3_parser(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                                      ^
make[2]: *** [src/CMakeFiles/rtl_433.dir/devices/oregon_scientific.c.o] Error 1
make[1]: *** [src/CMakeFiles/rtl_433.dir/all] Error 2
make: *** [all] Error 2

**Comment by pclov3r** [comment]
Fails to build on Fedora 21 as well with the same error output.

**Comment by pclov3r** [comment]
changed line 251 of /src/devices/oregon_scientific.c to  
} else if ((msg[0] == 0x19) && (msg[1] == 0x84)) { 

And it compiled without a problem.

**Comment by rct** [comment]
Same here, I don't think the OS matters, no compiler should accept that.

Are people submitting pull requests without making sure they even compile?

**Comment by pclov3r** [comment]
I would hope not. Guess it happens tho or was overlooked.
