### ISSUE TITLE
Help text for flex.c mentions example modulation that doesn't exist

### ISSUE THREAD

**Issue by marked23** [merbanan/rtl_433#870]
"E.g. -X \"doorbell:OOK_PWM_RAW:400:800:7000,match={24}0xa9878c,repeats>=3\"\n\n");
I think that should be OOK_PIWM_RAW.  
Also same thing in pulse_detect.c

**Comment by zuckschwerdt** [comment]
Thanks! fixed with df9daea.
We moving away from the _RAW demodulators, the short/long syntax of the _PRECISE should easier.
OOK_PWM is OOK_PWM_PRECISE.
