### ISSUE TITLE
MinGW compilation fails

### ISSUE THREAD

**Issue by Fra298** [merbanan/rtl_433#877]
Can't compile last release under MinGW64, got this error :

`confparse.c:39:19: error: storage size of 'st' isn't known
     struct __stat st;
                   ^~`

**Comment by zuckschwerdt** [comment]
Thanks for the report. If you delete one underscore on `__stat` (in src/confparse.c line 39) does that help?
@winterrace might have more insight.

**Comment by Fra298** [comment]
Compile fine with your trick 👍
