### ISSUE TITLE
HIDEKI Rain & Wind sensors

### ISSUE THREAD

**Issue by 10der** [merbanan/rtl_433#890]
Hi!
rain sensor always show me 202.3 mm
```
2018-12-01 19:15:23 :   HIDEKI Rain sensor
        Rolling Code:    0
        Channel:         4
        Battery:         OK
        Rain:    202.3 mm
```
Wind sensor show me strange values 
```
/raw/rtl_433 : msg.payload : Object
object
time: "2018-12-02 03:36:36"
model: "HIDEKI Wind sensor"
rc: 0
channel: 4
battery: "LOW"
temperature_C: -110.5
windstrength: 1.77
winddirection: 135
```
(IMHO misarrange)

Thank you!

**Comment by 10der** [comment]
I am sorry, but here is proof what this device was working properly.
pls scroll down to the last message.
[https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/z-wave-homeseer/107064-adding-qubino-z-wave-weather-station](url)

**Comment by 10der** [comment]
I have simulated rain

```
Detected OOK package    @ 2018-12-02 19:54:41
2018-12-02 19:54:41 :   HIDEKI Rain sensor
        Rolling Code:    0
        Channel:         4
        Battery:         OK
        Rain:    205.1 mm
Analyzing pulses...
Total count:   65,  width: 79.18 ms             (19796 S)
Pulse width distribution:
 [ 0] count:   17,  width:  936 us [932;964]    ( 234 S)
 [ 1] count:   47,  width:  444 us [440;456]    ( 111 S)
 [ 2] count:    1,  width:   56 us [56;56]      (  14 S)
Gap width distribution:
 [ 0] count:   17,  width: 1016 us [1012;1024]  ( 254 S)
 [ 1] count:   47,  width:  528 us [524;536]    ( 132 S)
Pulse period distribution:
 [ 0] count:   11,  width: 1956 us [1948;1976]  ( 489 S)
 [ 1] count:   12,  width: 1464 us [1460;1472]  ( 366 S)
 [ 2] count:   41,  width:  976 us [968;984]    ( 244 S)
Level estimates [high, low]:   3749,      3
RSSI: -6.4 dB SNR: 29.7 dB Noise: -37.4 dB
Frequency offsets [F1, F2]:   -5819,      0     (-22.2 kHz, +0.0 kHz)
Guessing modulation: Pulse Width Modulation with sync/delimiter
Attempting demodulation... short_width: 444, long_width: 936, reset_limit: 1028, sync_width: 56
Use a flex decoder with -X 'n=name,m=OOK_PWM,s=444,l=936,r=1028,g=0,t=0,y=56'
pulse_demod_pwm(): Analyzer Device
bitbuffer:: Number of rows: 2
[00] {64} 1f fb 6c ce df ed fe f5
[01] { 0}                         :
```

**Comment by 10der** [comment]
FIBARO HC2
![upb6vnobxm 1](https://user-images.githubusercontent.com/7056498/49343573-a7673c00-f674-11e8-8450-d9619ce02403.png)

**Comment by 10der** [comment]
Hmm. from help
```
rtl_433 -a -t | Will run in analyze mode and save a test file per detected signal (g###_###M_###k.cu8). Format is uint8, 2 channels.
```
but no .cu8 files here. ¯\_(ツ)_/¯

**Comment by 10der** [comment]
btw, the rain sensor still sends me. Rain:    205.1 mm
maybe it's "accumulated" value from the day when the sensor was stared? but look like crazy

**Comment by zuckschwerdt** [comment]
Run only `rtl_433 -a -t`
It will output
```
*** Saving signal to file g001_433.92M_250k.cu8
```

**Comment by 10der** [comment]
![utzlgyqf6g 1](https://user-images.githubusercontent.com/7056498/49344111-02e8f800-f67c-11e8-9625-409003789796.png)

![ugcfzughaz 1](https://user-images.githubusercontent.com/7056498/49344122-1c8a3f80-f67c-11e8-99f3-029f0ce0f114.png)

so. what I did wrong?

**Comment by 10der** [comment]
no 
*** Saving signal to file g001_433.92M_250k.cu8
msg

**Comment by zuckschwerdt** [comment]
Oh, I get it now. The signal is too weak for `-a`. Use `rtl_433 -l 3000 -a -t`
(I need to upgrade that `-a -t` thing someday soon :) )
If 3000 does not work try 2800 or 2500 or so.

**Comment by 10der** [comment]
got it. on itThank you!

**Comment by 10der** [comment]
yay!

*** Saving signal to file g001_433.92M_250k.cu8
*** Writing data from 1503592, len 262144


but where is?

**Comment by zuckschwerdt** [comment]
Your `pwd` shows `/home/pi`. It should be there ;)

**Comment by 10der** [comment]
yep, Sir!

**Comment by 10der** [comment]
[Qubino Weather Station.zip](https://github.com/merbanan/rtl_433/files/2637336/Qubino.Weather.Station.zip)

**Comment by zuckschwerdt** [comment]
Great samples! I'll work through this tomorrow.

**Comment by 10der** [comment]
thank you so much!

**Comment by zuckschwerdt** [comment]
(Use http://triq.net/iqs if you like to "see" the samples, looks very clear.)

**Comment by 10der** [comment]
wow!

**Comment by zuckschwerdt** [comment]
The rain value is accumulated. The reading is correct. (0x125 = 203 ; 203 * 0.7 = 205.1)
I have added CRC checksum to the sensor now.

**Comment by odenisenko** [comment]
cool. 
if not clear what is 203 but Ok.

**Comment by zuckschwerdt** [comment]
see also #891 -- the values and keys for wind and rain will change soon!

**Comment by zuckschwerdt** [comment]
`203` is the raw data from the sensor. Each `1` from the sensor is 0.7mm rain.

**Comment by odenisenko** [comment]
thank you co much!

**Comment by eugen66** [comment]
Hi,
Im using this rain sensor but I wonder if it can be something I can do to calibrate, the sensor shows that it have rained over 45 cm today. I use it with Weewx and are checking the "raw" values from sensor via rtl_433, it has increased from 841,1 mm to over 880.....
