### ISSUE TITLE
demote list of registered drivers to an option

### ISSUE THREAD

**Issue by gdt** [merbanan/rtl_433#915]
At startup, many lines are output about which drivers are registered.  This is mostly uninteresting, particularly when all enabled drivers are registered, compared to things like frequency and which device.

Therefore, I suggest having an option to list the drivers and which are default, and to omit the list of registered drivers on normal startup.

**Comment by zuckschwerdt** [comment]
You can use `-q` for that. It should really be the default.

Let's discuss if "quiet mode" should be the default!

**Comment by zuckschwerdt** [comment]
#918 will adress this.
