### ISSUE TITLE
WH65B incorrectly identified as WH24

### ISSUE THREAD

**Issue by cfarquhar** [merbanan/rtl_433#931]
#844 recently added support for the WH65B sensor array.  Unfortunately, my array is being incorrectly identified as WH24.  I'm opening this issue and a [PR](https://github.com/merbanan/rtl_433_tests/pull/250) with some collected samples with the hope that we can improve differentiation between the two models.

SDR is very new to me, so if there's any possibility that having something misconfigured could contribute to the incorrect model identification please let me know.

**Comment by rudders** [comment]
I have this issue I believe - can I fix it myself somehow?

**Comment by merbanan** [comment]
Should be fixed. But if more heuristics are needed then I think the model number should just be changed to wh24/wh65b.

**Comment by rudders** [comment]
I'll give it a try and report back.
