### ISSUE TITLE
Wrong example in README.md for MQTT

### ISSUE THREAD

**Issue by Hungry-Caterpillar** [merbanan/rtl_433#937]
README.md states the following

rtl_433 -F json -U \| mosquitto_pub -t home/rtl_433 -l | Will pipe the output to network as JSON formatted MQTT messages. A test MQTT client can be found in tests/mqtt_rtl_433_test.py.

-U is depreciated and the command will just hang in limbo which for newbees its not clear whether its just a warning and not working or is dead. Works great with the -M utc option !

linaro@linaro-alip:~/git/rtl_433/build$ rtl_433 -d 1 -F json -U | mosquitto_pub -t home/rtl_433 -l
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/linaro/.rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433.conf"...
Trying conf file at "/etc/rtl_433.conf"...
UTC mode option (-U) is deprecated. Please use "-M utc".

**Comment by zuckschwerdt** [comment]
Thanks! Fixed with 0fa3aba.
