### ISSUE TITLE
Intertechno ITT-1500 as Nexa/Proove detected

### ISSUE THREAD

**Issue by tnick61** [merbanan/rtl_433#939]
My Intertechno ITT-1500 remote control is being as Nexa/Proove switch detected. Activating only the Intertechno decoder shows no response.

**Comment by zuckschwerdt** [comment]
Simple remote controls, doorbells, PIR sensors, are likely to be interpreted wrongly. The Nexa and Proove protocol are somewhat better but I guess there are still quiet some similar devices.

Best idea here is to try a flex decoder (look at the timings and suggestion with `-A`). Use a `match=` in the flex spec to reliably detect your remote.

**Comment by zuckschwerdt** [comment]
Reopen or comment if you have an example flex decoder for our library or details on the timing and buttons.
