### ISSUE TITLE
Support for W132 ELV Sensors

### ISSUE THREAD

**Issue by stoffl6781** [merbanan/rtl_433#945]
Hi, is it popssible to add some more Sensors? 
http://www.tfd.hu/tfdhu/files/wsprotocol/auriol_protocol_v20.pdf
i have found this doc

Thank you 
Christoph

**Comment by zuckschwerdt** [comment]
We already have that Auriol protocl as "AlectoV1 Weather Sensor protocol". Please reopen with more info and captured sample data if that doesn't work.
