### ISSUE TITLE
Is decoded kv format a key/value pair?

### ISSUE THREAD

**Issue by dzach** [merbanan/rtl_433#958]
In the ```--help``` output of ``rtl_433`` I see:
```
        [-F kv|json|csv|syslog|null] Produce decoded output in given format.
 ```
I am assuming that the ```-F kv``` option relates to a [key/value pair](https://en.wikipedia.org/wiki/Attribute%E2%80%93value_pair) format. However, the actual output I see when using this option includes characters that break the ```key/value``` pair structure. Here is an random example of output from a sensor in the wild:
```
$ rtl_433 -F kv
rtl_433 version -128-NOTFOUND branch master at 201901110925 inputs file rtl_tcp RTL-SDR
...
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2019-01-15 09:43:43
model     : Acurite 606TX Sensor                   id        : 58
Battery   : OK           Temperature: 5.7 C
```
In this piece of output one can find:
- 100 "_" chars forming a separator of output messages
- ":" chars between keys and values, separated by a variable number of spaces
- values consisting of many words, without some kind of string delimiter.
- multiple ```key/value``` pairs on the **same** line, confusing where a value ends and where the next key starts

Although this output may be easily decoded by a human, it may present a problem to an automatic process recording OOK messages in the wild.

Is this output actually intended to be in ```key/value``` pair format?

If it is, I think it could be easily converted to a complying ```value/pair``` format, without sacrificing readability,  by:
- moving the ":" characters to the end of the key, if they need to exist at all
- limiting ```value/key``` pairs to one per line
- replacing the train of "_" characters delimiting messages with one empty line

Example of the same output, in the proposed format, including the ":" characters at the end of the keys:
```
time:        2019-01-15 09:43:43
model:       Acurite 606TX Sensor
id:          58
Battery:     OK
Temperature: 5.7 C

time:        2019-01-15 09:44:13
model:       Acurite 606TX Sensor
id:          58
Battery:     OK
Temperature: 5.7 C
```

**Comment by zuckschwerdt** [comment]
Thorough analysis. "kv" is something almost, but not quite entirely unlike key-value. The goal is best human readable output (color, separators, aligned columns, …).
IRC nobody ever needed machine-readable kv so far. I guess if there is a need for proper key-value output something else in the processing chain isn't designed well -- you should use CSV, JSON or network.

**Comment by zuckschwerdt** [comment]
I'd say we are open to add an output if there is a good case for it. The name "kv" is historical, it started as key-value, then got muddled when there was no need for machine-readable. Then it was recently tuned for easy human consumption. Important for readability here is a condensed format, so it can be glanced quickly and doesn't scroll off to fast. The named is now a bit misleading.
I'm not sure if a key-value output would have any advantage over JSON. JSON at least is ubiquitous. I'm parsing JSON on an Arduino in a few lines of code. MQTT and the whole of IoT seem to use it.
Do you have a use case for the key-value format in mind or it rather about the "kv" label?

**Comment by dzach** [comment]
Yes, I mostly use key/value pairs, even on MQTT. JSON is indeed ubiquitous, due to the proliferation of javascript in the web, but is not the most efficient data representation. I use JSON only to push data to websocket clients. But these represent only a fraction of the traffic through the MQTT server here.

Almost all sensors that I use are ultra low power devices, waking up, reporting and going to sleep again, using RFM12 or RFM69 radios, super-capacitors (no batteries) and tiny solar cells. Packet lengths are kept as short as possible, even byte sizes are reduced to 6 bits and packed, where possible (e.g. for battery levels), to save energy during transmission. So a  key/value pair is the most cost effective data representation,: no quotes, no brackets, no commas, no spaces (when data is byte packed), easy encryption. As little clock cycles as possible to do a sensor reading, and back to sleep.

A few days ago I had a look in the OOK frequencies with an RTLSDR I had bought a long time ago, using rtl_433, and, to my surprise, I discovered a wealth of data floating in the air.

So, had rtl_433 had a true key/value pair output format, I'd have just plugged in the received key/value pairs string, which fortunately seem to include ids too, and mostly deal with the presentation of the foreign sensors. Now, I have to revisit the decoding routines and add JSON capability, which is of course easily doable, but in principle not optimal.

The back end uses SQLite and is programmed in TCL, where key/value pairs (called dictionaries) are directly assignable and easily interchangeable between arrays, lists, math expressions, and procedure/function arguments.

That's my use case, in operation.

**Comment by dzach** [comment]
Of course JSON **is** a key/value data structure. What I mean above, is that the string that conveys a JSON packet is not optimally efficient.

**Comment by merbanan** [comment]
@dzach Just write you own output routine that fulfill your requirement. The data is structured internally and the design is there for your use-case. We just chose to normalize around json to have some common ground.
