### ISSUE TITLE
Reattaching kernel driver failed!

### ISSUE THREAD

**Issue by ich008** [merbanan/rtl_433#962]
> sudo rtl_433 -a -A

 ends with

> ^CSignal caught, exiting!
> r82xx_write: i2c wr failed=-9 reg=06 len=1
> Reattaching kernel driver failed!
> 

afterwars 

> sudo rtl_433
> rtl_433 version unknown inputs file rtl_tcp RTL-SDR
> Trying conf file at "rtl_433.conf"...
> Trying conf file at "/root/.rtl_433/rtl_433.conf"...
> Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
> Trying conf file at "/etc/rtl_433/rtl_433.conf"...
> Registered 96 out of 120 device decoding protocols [ 1-4 8 11-12 15-21 23 25-26 29-36 38-60 62-64 67-71 73-100 102-103 108-116 119 ]
> **No supported tuner found**
> Enabled direct sampling mode, input 1
> Exact sample rate is: 250000.000414 Hz
> Sample rate set to 250000 S/s.
> Tuner gain set to Auto.
> Tuned to 433.920MHz.
> ^CSignal caught, exiting!

before

> sudo rtl_433
> rtl_433 version unknown inputs file rtl_tcp RTL-SDR
> Trying conf file at "rtl_433.conf"...
> Trying conf file at "/root/.rtl_433/rtl_433.conf"...
> Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
> Trying conf file at "/etc/rtl_433/rtl_433.conf"...
> Registered 96 out of 120 device decoding protocols [ 1-4 8 11-12 15-21 23 25-26 29-36 38-60 62-64 67-71 73-100 102-103 108-116 119 ]
> Detached kernel driver
> Found Rafael Micro R820T tuner
> Exact sample rate is: 250000.000414 Hz
> [R82XX] PLL not locked!
> Sample rate set to 250000 S/s.
> Tuner gain set to Auto.
> Tuned to 433.920MHz.
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> time      : 2019-01-24 01:36:14
> model     : Prologue sensor                        id        : 5
> ...

 "-a -A" Brakes it and i cant fix it even when restarting and blacklisting drivers..

**Comment by zuckschwerdt** [comment]
`-a` or `-A` don't do anything special, just output. There is likely a module loaded which blocks RTL-SDR (the attach-business). Nothing we can do.

**Comment by merbanan** [comment]
r82xx_write: i2c wr failed=-9 reg=06 len=1, that is an indication that communication between the usb bridge and the tuner chip is not well. My guess is a bad usb port/cable or insufficient power. Could be a flaky rtl-sdr device also. Most likely the probe to reattach the kernel driver also fails because the tuner is missing during init. So rtl_433 is not causing this, try swapping usb ports or a powered usb hub.

**Comment by ich008** [comment]
After much testing it was a Hardware fault of the Tuner Chip only. Sorry, but it really seemed like "-a  -A" was causing the problem because it broke the exact time afterward on two different devices and never began working afterwards. (After re flowing (soldering) the R802T Chip it works again... I should invest in a better quality one)
