### ISSUE TITLE
Disable color output?

### ISSUE THREAD

**Issue by pclov3r** [merbanan/rtl_433#963]
Is there a option to disable the color output? 

I figure this may already exist as an option but i don't see it listed.

**Comment by zuckschwerdt** [comment]
Just make sure your output is not a TTY. E.g. use `| cat -`. We might add some environment var for that someday.
Is something wrong with the color or do you dislike it for aesthetic reasons only?

**Comment by pclov3r** [comment]
Mostly aesthetic reasons. Would be nice if there was command flag to disable it. 

I am using it on windows.

**Comment by gdt** [comment]
Seems like this can be closed; 4 years of not implementing a feature is evidence that the useful/effort ratio is too low, and no one has submitted a PR.
