### ISSUE TITLE
Specify file encoding when reading stdin

### ISSUE THREAD

**Issue by fmoessbauer** [merbanan/rtl_433#964]
With PR #815 the ability to explicitly specify the file encoding was removed. This is problematic when reading from stdin, as '-' does not have any suffix.

Is there any option (@zuckschwerdt ) to specify it? I'm currently working on a fix in ShinySDR to adapt the [rtl_433 integration](https://github.com/kpreid/shinysdr/blob/9e7ad0e95504aeecc865192fb756b36bdf17bc70/shinysdr/plugins/rtl_433.py#L97) to the new rtl_433 API. In my case, the stream is cf32 encoded.

**Comment by zuckschwerdt** [comment]
`CF32:-` should work. Perhaps the help at `rtl_433 -r` needs to explain that better. Where did you expect to find the info and what was missing?

**Comment by fmoessbauer** [comment]
That works, Thx! IMO this should be documented in the readme and in the cli help along with the -r parameter. Additionally, a breaking change notice in the changelog would have been great.

A more general thing is that I do not expect ABI / API changes on minor versions. However, according to the version numbers used here, rlt_433 just uses `<year>.<month>` which should be documented as well.

**Comment by merbanan** [comment]
Documented version numbering, documented pipe reading options and added it to the rtl_433 -r output.
