### ISSUE TITLE
Invalid JSON output.

### ISSUE THREAD

**Issue by Mihara** [merbanan/rtl_433#966]
Looking into my logs today, I found this:
```
2019-01-27 16:28:44,696 JSON decode error: b'{"model" : "Kerui-PIR-01", "count" : 1, "num_rows" : 1, "rows" : [{"len" : 25, "data" : "99180a0", "state" : 627072, "event" : "
pir"}], "codes" : ["{25}99180a0"], "mod" : "ASK", "freq" : 434.085, "rssi" : -2.372, "snr" : 39.772, "noise" : -inf}\n'
```

This is output from my Python-based rtl_433 handler, so this is the line exactly as it was received from rtl_433. Notice the malformed noise field: `"noise": -inf`

While the obvious workaround is not to ask for the metadata containing these values when using json output, I am pretty sure this is a bug.

**Comment by zuckschwerdt** [comment]
Noise level of raw 0. Quite quiet 😴 
I've added (6ab7b46) a raw 1 now to turn that -inf into 42.144.
