### ISSUE TITLE
Protocol selection seemingly messed up

### ISSUE THREAD

**Issue by winterrace** [merbanan/rtl_433#969]
With the current version, I notice some unexpected behavior:

rtl_433 -G
Current behavior: Registered 0 out of 120 device decoding protocols [ ]
Expected behavior: all default and non-default protocols should be listed

rtl_433 -R 5
Current behavior: Registered 1 out of 120 device decoding protocols [ 5 ]
Expected behavior: Rejection with "Remote device number specified is invalid"

rtl_433 -R 4
Current Behavior: Rejection with "Remote device number specified is invalid"
Expected behavior: Registered 1 out of 120 device decoding protocols [ 4 ]

I did not have the time to spend a closer look. But it seems related to the latest changes introduced for the parametric decoder functionality.

**Comment by zuckschwerdt** [comment]
Fixed with 640fc57

**Comment by winterrace** [comment]
Thanks!
