### ISSUE TITLE
Feature Request: Disable and enable specific devices.

### ISSUE THREAD

**Issue by pclov3r** [merbanan/rtl_433#97]
Not sure how this would be to implement but it would be nice if you could disable or enable specific devices. 

Basically for example if i only wanted to see LaCrosse sensors i could just enable that one device.

**Comment by helgew** [comment]
Addressed in #98 :smile:

**Comment by merbanan** [comment]
Merged.

**Comment by pclov3r** [comment]
How do I use this new feature with the -R? What do input for the device name?

**Comment by helgew** [comment]
When you run rtl_433 with the -h option, it will tell you what devices are supported and each will have a number associated with it. Use -R and one of those numbers to enable just that device. You can use the -R option multiple times to enable additional devices.

**Comment by pclov3r** [comment]
Attempting to use this feature right now results in a segfault for me on
linux and doesn't work on Windows

[root@localhost ~]# rtl_433 -R [08] LaCrosse TX Temperature / Humidity
Sensor
Segmentation fault (core dumped)
[root@localhost ~]# rtl_433 -R [08]
Segmentation fault (core dumped)
[root@localhost ~]# rtl_433 -R 08
Segmentation fault (core dumped)
[root@localhost ~]# rtl_433 -R 8
Segmentation fault (core dumped)
[root@localhost ~]#

Am i doing something wrong?
