### ISSUE TITLE
domoticz

### ISSUE THREAD

**Issue by ph1nt** [merbanan/rtl_433#974]
Because domoticz add '-I 2' I suggest ignoring this param, not exit.
--- a/src/rtl_433.c
+++ b/src/rtl_433.c
@@ -1183,8 +1183,8 @@ static void parse_conf_option(r_cfg_t *cfg, int opt, char *arg)
         cfg->demod->analyze_pulses = atobv(arg, 1);
         break;
     case 'I':
-        fprintf(stderr, "include_only (-I) is deprecated. Use -S none|all|unknown|known\n");
-        exit(1);
+        fprintf(stderr, "include_only (-I) is deprecated. Ignoring -I %s param.  Use -S none|all|unknown|known\n", arg);
+        //exit(1);
         break;
     case 'r':
         if (!arg)

**Comment by zuckschwerdt** [comment]
There should never have been a reason to use `-I` with Domoticz. As you see it's a debug tool to record sample data to disk.
I suggest changing Domoticz, sorry.
