### ISSUE TITLE
rtl_433.conf device syntax for SoapySDR

### ISSUE THREAD

**Issue by phinnay** [merbanan/rtl_433#976]
I can not figure out how to specify the device string inside the .conf file. Every permutation I've entered results in the error: 
**Remote device number specified is invalid**

on the command line, I specify " rtl_433 -d driver=rtlsdr" and everything works as it should. The identical string "driver=rtlsdr" when used in the conf file results in an error. 

Additionally, how would you specify SoapyRemote? I can not find anything in the documentation.

**Comment by zuckschwerdt** [comment]
Just
```
device        driver=remote
```
works. The string there is the usual SoapySDR device string. And SoapyRemote is the driver "remote". Maybe you put quotes there? There are no quotes in the config file.
