### ISSUE TITLE
Any possibility to add R900 and SCM meters from RTLAMR project?

### ISSUE THREAD

**Issue by TechnoSwiss** [merbanan/rtl_433#977]
I noticed there are some additions to the project in the 900MHz ISM band, is there any chance some of the SCM and R900 decoders from the bemasher/rtlamr project could get added in?

**Comment by merbanan** [comment]
The answer to this can mostly be answer by the question if you can supply sample signals and decoding descriptions? If yes then yes, if no then most likely no.

**Comment by TechnoSwiss** [comment]
I was trying to get sample signals earlier today, but even though I'm able to capture and decode packets with rtlamr I wasn't getting anything with rtl_433. Looking over the R900 decoder in the rtlamr project though it looks like maybe the issue was I had the frequency wrong. 

I think all the decoding descriptions are already in the github project for rtlamr.

**Comment by merbanan** [comment]
The decoding descriptions must be in there some where but every bit of research is time I or some one else can spend on implementation rather on digging through code.

**Comment by TechnoSwiss** [comment]
I'll see if I can dig those out then and check if the sample issue was just getting the freq. wrong. Thanks.

**Comment by merbanan** [comment]
https://en.wikipedia.org/wiki/Encoder_receiver_transmitter gave the basics beside the bit rate.

**Comment by dadler** [comment]
The rtlamr wiki has this page on their [Signal Processing](https://github.com/bemasher/rtlamr/wiki/Signal-Processing).  

Having rtl_433 support this would be great since then I could (presumably) have rtl_433 read alternately from 433 Mhz temperature sensors and a 900 Mhz water meter using the same dongle, without hacks like periodically stopping rtl_433 to run rtl_tcp and rtlamr.  Thanks.

**Comment by merbanan** [comment]
@dadler, have you been able to record some samples? I suggest you use rtlcap (github.com/bemasher/rtlcap) to create proper signal samples. Then we can look into what is needed to maybe add support for rtlamr supported protocols.

**Comment by TechnoSwiss** [comment]
I think I have actually gotten this working on my system, I need to verify, then figure out how to create a merge request I guess.

**Comment by merbanan** [comment]
@TechnoSwiss have you been able to get some signal samples?

**Comment by dadler** [comment]
Sorry, my water meter seems to have stopped transmitting so I can’t capture
data now.

**Comment by TechnoSwiss** [comment]
@merbanan Yes I was able to get samples I have them checked into my fork of the test repo https://github.com/TechnoSwiss/rtl_433_tests/tree/master/tests/scm/01 I have partial working decoder for this meter I believe, but then my time got preempted by other tasks before I finished going through the documentation on how to get this decoder finished and checked back into the main project line.

decoder {
    name=SCM,
    modulation=OOK_MC_ZEROBIT,
    short=30,
    long=0,
    reset=64,
    bits=96,
    get=@32:{24}:consumption,
    get=@56:{24}:ID
}

**Comment by dabeckham** [comment]
@merbanan Did you delete rtlcap?  

I too am trying to use rtl_433 for an R900 water meter. I would like to hop between frequencies to monitor everything with only one SDR dongle. Thanks for all your work making this available for everyone!!

**Comment by merbanan** [comment]
@TechnoSwiss do you have the code for the decoder somewhere?

**Comment by TechnoSwiss** [comment]
@merbanan I believe I'm just using one of the built-in decoders? I'll have to check when I get home. I believe I had rtl_433 spitting out decoded information, so I'll look and see how I got there.

**Comment by merbanan** [comment]
@TechnoSwiss ok I see, you used a config file.

**Comment by merbanan** [comment]
Implemented SCM support, send samples for other protocols.
