### ISSUE TITLE
Conrad KW9010 identical to TFA-Twin-Plus-30.3049

### ISSUE THREAD

**Issue by devZer0** [merbanan/rtl_433#981]
can someone with write access to this repo (Readme.md) add information that Conrad KW9010 is identical to TFA-Twin-Plus-30.3049 and works without problems ? the case looks similar to TFA model , but it's black one. i have seen it quite some times , iirc even under different branding (tchibo?) - and maybe it's an older variant of the TFA one.

i'd like to have this added as people may search how to receive data from KW9010 and then will be able to find this project

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-09 19:42:09
model     : TFA-Twin-Plus-30.3049                  Id        : 18
Channel   : 2            Battery   : OK            Temperature: 22.7 C       Humidity  : 36 %
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by zuckschwerdt** [comment]
Thanks for the research! Note added with #dd842fc

**Comment by devZer0** [comment]
thanks
