### ISSUE TITLE
More unified looks

### ISSUE THREAD

**Issue by gvanem** [merbanan/rtl_433#998]
Currently different sensors could display the `Temperature: xx.x C` at different positions
on the screen. Example screen-output:
![rtl_433_screen-2](https://user-images.githubusercontent.com/945271/53548821-c91c7600-3b32-11e9-8e24-23ffd5876eb8.jpg)

I do not understand how it could be different.  
But could the data in the `output_fields[]` be unified somehow?

PS. I used no config-file (`-c NUL` ) above. So nothing in `rtl_433.conf` could be the guilty part.

**Comment by zuckschwerdt** [comment]
There is no sorting, it's just fields as the decoder adds them. We should perhaps rewrite decoders to have some fixed order of well known keys:
- model (ok)
- id (ok, not sure where that rid fits)
- channel (ok, but might be missing)
- temperature (move this up)
- humidity (move this up)
- button, battery, … (move down)

But there is rather much diversity, there are probes with two temperature values, the temperature might not be the important part (TPMS), … Hard to say if there could be some consensus.

**Comment by gvanem** [comment]
> * temperature (move this up)

Maybe if the `.name` contains `Temperature`, that should determine what that **main-value** is?

**Comment by zuckschwerdt** [comment]
Todo: Key order (for Prologue here) should generally be
(type), model, (subtype), id, channel, battery_ok, temperature_x, humidity, …, and mic last. At least that seems to be the most used order in decoders.

**Comment by zuckschwerdt** [comment]
Most of this is done with 5e4c7dc now.
